/** 劇本心得九宮格的介面文字 */
import type { ImageRatio, ViewMode } from './model';

export const S = {
  /* 版面 */
  sectionLayout: '排列',
  view: '排列方式',
  views: { grid: '九宮格', list: '清單' } satisfies Record<ViewMode, string>,
  viewHint: {
    grid: '一列 3 格：圖片、規則、劇本名稱、作者與心得標籤。',
    list: '一列 2 格，不畫圖片，改畫感想。',
  } satisfies Record<ViewMode, string>,
  ratio: '圖片比例',
  ratios: { square: '正方形', original: '依原圖' } satisfies Record<ImageRatio, string>,
  ratioHint: '「依原圖」時圖片照原本的長寬比，同一列的格子高度會不同。',
  ratioListHint: '清單不畫圖片，圖片比例只在九宮格有作用。',

  /* 個人資料 */
  sectionProfile: '個人資料',
  profileHint: '畫在最上面；頭像、暱稱、帳號都空著時不畫這一列。',
  avatar: '頭像',
  avatarDrop: '頭像圖片',
  name: '暱稱',
  namePlaceholder: '例如 阿草',
  handle: '帳號或一句話',
  handlePlaceholder: '例如 @kusa_trpg',

  /* 圖片欄 */
  chooseImage: '選擇圖片',
  dropImage: '把圖片拖到這裡',
  changeImage: '換一張圖片',
  removeImage: '拿掉圖片',
  imageMissing: '圖片讀不到了（可能已從這個瀏覽器清除），請重新選擇。',

  /* 格子清單 */
  sectionCells: '劇本格子',
  cellsHint: '點一列（或預覽上的格子）編輯那一格；拖曳把手調整順序。',
  cellsCount: (n: number) => `${n} 格`,
  cellsLabel: '格子清單',
  cellNumber: (n: number) => `第 ${n} 格`,
  untitled: '（沒有劇本名稱）',
  addCell: '加一格',
  removeCellNamed: (label: string) => `刪除${label}`,
  lastCell: '至少要留一格。',
  cellLimit: (n: number) => `最多 ${n} 格。`,
  batchLabel: '一次放入多張圖片',
  batchDrop: '把好幾張圖片拖到這裡',
  batchHint: '依序放進還沒有圖片的格子，不夠時在最後加格子。拖到預覽上的某一格時從那一格開始放。',
  batchAria: '一次放入多張圖片',

  /* 這一格 */
  sectionCell: (n: number) => `第 ${n} 格`,
  cellImage: '圖片',
  cellImageDrop: '這一格的圖片',
  cellImageHint: '也可以把圖片拖到預覽上的格子，或滑鼠指著格子按 Ctrl＋V 貼上。',
  rule: '規則',
  rulePlaceholder: '例如 CoC 7版',
  title: '劇本名稱',
  titlePlaceholder: '例如 雨夜的訪客',
  writer: '作者',
  writerPlaceholder: '劇本作者',
  tags: '心得標籤',
  tagsCount: (n: number, max: number) => `已選 ${n}／${max}`,
  tagsHint: (max: number) => `最多選 ${max} 個，依選的順序排列；再按一次取消。`,
  tagsFull: (max: number) => `每一格最多 ${max} 個心得標籤，先取消一個再選。`,
  tagsAria: '心得標籤（可以複選）',
  offList: '（不在標籤清單裡）',
  quickTag: '自己寫一個標籤',
  quickTagPlaceholder: '加進清單並選取',
  quickTagAdd: '加入',
  comment: '感想',
  commentPlaceholder: '想說的話都可以寫在這裡',
  commentHintList: '感想畫在清單裡（九宮格不畫）。',
  commentHintGrid: '感想只畫在「清單」排列裡；九宮格不畫。',

  /* 心得標籤清單 */
  sectionTags: '心得標籤清單',
  tagsListHint:
    '每一格的心得標籤從這裡選。改了字，用到它的格子跟著改；刪掉時，用到它的格子一起拿掉。',
  tagsListLabel: '心得標籤清單',
  tagsListCount: (n: number) => `${n} 個`,
  tagText: (t: string) => `標籤「${t}」的文字`,
  tagUsed: (n: number) => (n ? `${n} 格` : ''),
  tagRemove: (t: string) => `刪除標籤「${t}」`,
  newTag: '新的標籤',
  newTagPlaceholder: '例如 KP 帶得超好',
  addTag: '加入標籤',
  tagCount: (n: number, max: number) => `${n}／${max}`,
  tagEmpty: '請輸入標籤的文字。',
  tagDuplicate: '清單裡已經有這個標籤。',
  tagListFull: (n: number) => `標籤最多 ${n} 個。`,
  tagRemoveTitle: (t: string) => `刪除標籤「${t}」？`,
  tagRemoveDesc: (n: number) => `有 ${n} 格選了這個標籤，會一起拿掉（可以復原）。`,
  tagRemoveConfirm: '刪除',
  resetTags: '回到預設的標籤',
  resetTagsTitle: '標籤清單回到預設？',
  resetTagsDesc: '清單換回預設的 20 個標籤；格子裡已經選的標籤留著（可以復原）。',
  resetTagsConfirm: '回到預設',

  /* 比較 */
  sectionCompare: '比較多人的心得',
  compareHint:
    '每個人各自存成專案檔（「專案」→「存成專案檔」）後收集起來，一次選 2 個以上，就能把同一個劇本的心得排在一起比較。原作存的資料備份（.json）也可以。',
  compareDrop: '把大家的專案檔拖到這裡',
  compareChoose: '選擇檔案',
  compareAria: '比較多人的心得：選擇檔案',
  compareReading: '讀取中…',
  compareNeedTwo: '請選 2 個以上的檔案（每個檔案是一個人）。',
  compareFailed: (names: string) =>
    `無法讀取「${names}」（不是這個工具的專案檔，也不是原作的資料備份）。`,
  compareNotProject: (names: string) => `「${names}」不是專案檔（.zip、.json），沒有列入比較。`,
  compareSkipped: '有檔案沒有列入比較。',
  compareNotEnough: '能讀的檔案不到 2 個，無法比較。',
  compareNoTitle: '這些檔案裡沒有填了劇本名稱的格子，無法比較。',
  compareTitle: '比較圖',
  compareSummary: (people: number, groups: number) => `${people} 人、${groups} 個劇本`,
  compareImageTitle: '劇本心得比較',
  comparePeople: (n: number) => `${n} 人的心得`,
  anonymous: '匿名',
  comparePreviewAlt: '比較圖的預覽',
  compareDownload: '下載 PNG',
  compareClose: '關閉',
  compareFile: '劇本心得比較',
  compareRenderFailed: '無法產生比較圖。',

  /* 預覽與匯出 */
  previewLabel: '心得卡片預覽',
  regionProfile: '個人資料',
  regionCell: (n: number, title: string) => `第 ${n} 格${title ? `：${title}` : ''}`,
  hint: '點預覽上的格子編輯那一格；把圖片拖到格子上，或滑鼠指著格子按 Ctrl＋V，就放進那一格。',
  imagesMissing: '有圖片讀不到了（可能已從這個瀏覽器清除），請重新選擇那幾格的圖片。',
  exportTitle: '匯出',
  downloadPng: '下載 PNG',
  scale: '大小',
  scaleAria: (n: number) => `${n} 倍`,
  exportSize: (w: number, h: number) => `${w} × ${h} px`,
  exportNote: '2 倍（寬 1800 px）適合貼到社群；預覽上的選取框不會畫進圖裡。',
  fileGrid: '劇本心得九宮格',
  fileList: '劇本心得清單',
  downloadDone: (name: string) => `已下載 ${name}`,
  downloadFailed: '無法產生圖片。',
  scaleReduced: (scale: string) => `圖太大，已自動降到 ${scale} 倍。`,

  /* 圖片的通知 */
  notImage: (names: string) => `「${names}」不是圖片檔。`,
  decodeError: (names: string) => `無法讀取「${names}」，檔案可能已損壞。`,
  imageNotSaved: '瀏覽器空間不足或無法存檔：圖片這次可以用，但重新整理之後就不見了。',
  imagesPlaced: (n: number) => (n === 1 ? '已放進圖片。' : `已放進 ${n} 格。`),
  imagesDropped: (n: number) => `格子已達上限，有 ${n} 張沒放進去。`,
  avatarSet: '已換上頭像。',
  windowDrop: '放開即可放進格子',
  windowDropHint: '放在預覽上的某一格就從那一格開始放；放在頭像上就換頭像',

  /* 專案檔 */
  openConfirmTitle: '開啟專案檔？',
  openConfirmDesc: '目前的內容會被檔案的內容取代（可以復原）。原作存的資料備份（.json）也可以開。',
  openConfirmLabel: '選擇檔案',
  projectOpened: '已開啟專案檔',
  projectBad: '專案檔的內容無法使用。',
  projectMissingImage: '專案檔裡少了圖片，無法開啟。',
  resetTitle: '全部重設？',
  resetDesc: '個人資料、格子與標籤清單都回到剛打開的樣子（可以復原）。',
  saveFailed: '自動儲存失敗（瀏覽器空間不足或被封鎖）',
  legacyDone: (n: number) => `已讀入原作的資料備份：${n} 格。`,
  legacyFailedImages: (n: number) => `有 ${n} 張圖片讀不了。`,
  legacyDropped: (n: number) => `超過 30 格，後面 ${n} 格沒有讀。`,

  /* 頁首 */
  undo: '復原',
  redo: '重做',
  groupEdit: '編輯',
  shortcutPaste: '貼上圖片到滑鼠指著的格子（沒有時是選取的格子）',
  usage: [
    '在左邊填個人資料；「劇本格子」選一格，填規則、劇本名稱、作者，選最多 3 個心得標籤。',
    '圖片：在「這一格」選擇圖片，或把圖片拖到預覽上的格子，或滑鼠指著格子按 Ctrl＋V 貼上；一次放好幾張可以用「一次放入多張圖片」。',
    '「排列」可以換成清單（不畫圖片，改畫感想）；九宮格的圖片可以選正方形或依原圖比例。',
    '心得標籤可以自己改：在「心得標籤清單」新增、改字、刪除、排序。',
    '預覽上方「下載 PNG」存成圖片；「專案」選單可以存成專案檔，之後再開啟繼續編輯。',
    '想和團員比較：大家各自存成專案檔後，在「比較多人的心得」一次選 2 個以上，就能產生同一個劇本的心得比較圖。',
  ],
} as const;
