/** 角色介紹圖產生器的介面文字（只有繁中） */

export const S = {
  /* ---------- 一覽與版型資訊 ---------- */
  galleryTitle: '選一個版型',
  galleryIntro:
    '點版型進入編輯：在畫布上點要改的地方，左邊（窄畫面在預覽下方）會切到那一項。編輯內容依版型分別自動保存在瀏覽器裡。',
  galleryAria: '版型一覽',
  notFound: (id: string) => `找不到「${id}」這個版型，請從一覽重新選擇。`,
  backToGallery: '版型一覽',
  switchTemplate: '換版型',
  templateNow: '目前版型',
  restored: '已載入最近一次的編輯。',
  restoreFailed: '無法還原自動保存的內容，已改用版型的初始內容。',
  saveFailed: '自動保存失敗了（瀏覽器空間可能不足）。請存成專案檔備份。',

  /* ---------- 編輯面板 ---------- */
  sidesAria: '編輯對象',
  groupsAria: '輸入項目',
  stickers: '貼紙',
  fontSample: '字型預覽',
  citeLabel: '出處',
  citePlaceholder: '有出處嗎？',
  chooseImage: '選擇圖片',
  clearImage: '清空圖片',
  imageHint: 'PNG、JPG、WebP，15 MB 以下',
  freeCropTitle: '裁切圖片（不限比例）',
  cropTitle: '裁切圖片',
  imageType: '請選擇 PNG、JPG 或 WebP 檔。',
  imageTooBig: '圖片請選 15 MB 以下的。',
  imageTooManyPixels: '圖片解析度太大了，請縮到 4,000 萬像素以下。',
  imageUnreadable: '讀不到這張圖片。',
  imageNotSaved: '圖片無法保存在瀏覽器裡（空間可能不足），重新整理後就會不見。',
  slotPreview: (label: string) => `${label}的圖片`,
  emptySlot: '還沒有圖片',

  /* ---------- 貼紙 ---------- */
  addSticker: '加入貼紙',
  stickerAdded: '已加入貼紙。可以在畫布上移動、縮放與旋轉。',
  stickerLimit: (n: number) => `貼紙最多只能加到 ${n} 張。`,
  stickerList: '貼紙清單（上面＝前面）',
  stickerEmpty: '還沒有貼紙。按「加入貼紙」選一張圖片。',
  stickerName: (name: string) => `貼紙：${name}`,
  stickerShadow: '陰影',
  stickerOutline: '外框線',
  stickerCite: '出處',
  stickerFront: '移到前面',
  stickerBack: '移到後面',
  stickerDelete: '刪除貼紙',
  stickerSelect: (name: string) => `選取「${name}」`,
  stickerPage: (n: number) => `第 ${n} 頁`,
  stickerHint:
    '選取的貼紙：拖曳移動、四角縮放、上方的控點旋轉（Shift 每 15°）；方向鍵微調、Delete 刪除、Esc 取消選取。',
  stickerDefaultName: '貼紙',

  /* ---------- 預覽與輸出 ---------- */
  previewAria: '介紹圖預覽',
  canvasAria: '畫布上的元素（點一下編輯）',
  pickHint: '在畫布上點一個顏色',
  downloadPng: '下載 PNG',
  downloadPdf: '下載 PDF',
  exportTitle: '下載',
  exportSize: (w: number, h: number) => `${w} × ${h} px`,
  exportNote: 'PNG 是畫布的原尺寸，含貼紙，不含選取框等編輯標示。',
  pngDone: (name: string) => `已下載 ${name}`,
  pngFailed: '產生 PNG 失敗了。',
  pdfNote: 'PDF 會存下所有頁面，文字可以選取、複製。',
  pdfProgress: (n: number, total: number) => `正在製作 PDF… 第 ${n}／${total} 頁`,
  pdfFonts: '正在準備 PDF 用的字型…',
  pdfDone: (n: number) => `已儲存 ${n} 頁的 PDF。`,
  pdfFailed: 'PDF 儲存失敗了。',
  pdfCancel: '取消',
  pdfCanceled: '已取消 PDF。',
  solo: '只看這一張',
  overview: '看全部',

  /* ---------- 多人資料框 ---------- */
  addMember: '新增角色',
  memberLimit: '最多 30 人。',
  memberCount: (n: number, max: number) => `${n} / ${max} 人`,
  rosterNavAria: '多人資料卡的角色',
  deleteMember: '刪除這個角色',
  deleteMemberTitle: '刪除這個角色？',
  deleteMemberDesc: '這個角色與它的輸入內容都會刪除，其餘角色往前遞補。',
  memberLeft: '往左移',
  memberRight: '往右移',

  /* ---------- 文字記錄 ---------- */
  prevPage: '上一頁',
  nextPage: '下一頁',
  pageCounter: (i: number, n: number) => `${i} / ${n}`,
  addPage: '新增頁面',
  deletePage: '刪除這一頁',
  deletePageTitle: '刪除這一頁？',
  deletePageDesc: '這一頁的文字與貼紙都會刪除。',
  pageLimit: '頁面最多只能加到 30 頁。',
  pagesCapped: '已經到達頁數上限。放不下的文字還保留在本文欄裡。',
  viewAll: '看全部',
  viewSingle: '單獨看',
  pageTab: (i: number) => `${i}p`,
  pageNavAria: '文字記錄的頁面',
  gotoPage: (i: number) => `切換到第 ${i} 頁`,

  /* ---------- 存檔槽 ---------- */
  slots: '存檔槽…',
  slotsTitle: '存檔槽',
  slotsNote: '存在這台裝置的瀏覽器裡。清除瀏覽器資料的話就會不見，重要的作品請另外存成專案檔。',
  slotNew: '建立新的存檔槽',
  slotCreated: '已存到新的存檔槽。',
  slotEmpty: '這個版型還沒有存檔槽。',
  slotName: '存檔槽名稱',
  slotDefaultName: '存檔槽',
  slotOverwrite: '覆蓋',
  slotOverwriteTitle: '覆蓋這個存檔槽？',
  slotOverwriteDesc: '存檔槽原本的內容會換成目前的編輯內容。',
  slotOverwritten: '已存到存檔槽。',
  slotLoad: '讀取',
  slotLoadTitle: '讀取這個存檔槽？',
  slotLoadDesc: '目前的編輯內容會被取代（可以用「復原」回來）。',
  slotLoaded: '已讀取存檔槽。',
  slotDelete: '刪除',
  slotDeleteTitle: '刪除這個存檔槽？',
  slotDeleteDesc: '刪掉之後無法復原。',
  slotDeleted: '已刪除存檔槽。',
  slotPreviewAlt: '存檔槽的預覽',
  slotFailed: '這個瀏覽器無法使用存檔槽（儲存空間不能用）。請改用專案檔。',
  slotBroken: '這個存檔槽的內容無法讀取：',

  /* ---------- 專案檔 ---------- */
  projectOpened: '已開啟專案檔。',
  openConfirmTitle: '開啟專案檔？',
  openConfirmDesc: '目前的編輯內容會被專案檔取代（可以用「復原」回來）。',
  openConfirmLabel: '開啟',
  archiveTooBig: '請選擇 80 MB 以下的專案檔。',
  archiveTooManyFiles: '解壓縮後的檔案太大或數量太多了。',
  archiveOtherTemplate: (name: string) => `這是「${name}」的專案檔，請先切換到那個版型再開啟。`,
  archiveUnknownTemplate: '這不是本工具的版型專案檔。',
  archiveMissingImage: 'ZIP 裡少了需要的圖片。',
  archiveDrop: '放開即可開啟專案檔（ZIP）',
  resetTitle: '重設這個版型？',
  resetDesc: '會清空目前的內容，回到版型的初始狀態（可以用「復原」回來）。',
  resetDone: '已重設成版型的初始內容。',
  undo: '復原',
  redo: '重做',

  /* ---------- 說明 ---------- */
  usage: [
    '在一覽選一個版型。編輯畫面的畫布上，點名字、圖片格、顏色塊、說明框或背景，設定欄就會切到那一項。',
    '圖片格：選檔後在裁切視窗把圖放進框裡（可以縮放、整張放入、旋轉），套用後存成格子的大小。下面的「出處」有填時，會在圖的下緣印「ⓒ 出處」。',
    '色彩欄的調色盤有「從畫布取色」：游標移到畫布上會出現放大鏡，點一下就取那一點的顏色。',
    '貼紙：在「貼紙」分頁加入圖片，在畫布上拖曳移動、拉四個角縮放、拖上方的控點旋轉；可以加陰影、白色外框線與出處，調整前後順序。',
    '文字記錄：本文放不下時，停手約 0.2 秒或離開本文欄後，多出來的字會接到下一頁同一欄的開頭（需要時自動加頁，最多 30 頁）。',
    '保存：內容會依版型自動保存在瀏覽器；「專案」選單可以存成專案檔（ZIP，含圖片）、開啟專案檔、打開存檔槽或重設。',
  ],
} as const;

/* ---------- 版型的文字 ---------- */

export const T = {
  left: '左邊的角色',
  right: '右邊的角色',
  leftShort: '左',
  rightShort: '右',
  common: '共用',

  /* 雙人資料卡 */
  duoSheet: {
    name: '雙人資料卡',
    tip: '兩個角色左右對照的資料整理。',
    profile: '頭像',
    nameGroup: '名字與標語',
    full: '全身圖',
    chibi: 'Q 版圖',
    looks: '外觀說明',
    colors: '髮色與瞳色',
    extra: (i: number) => `追加圖片 ${i}`,
    line: '一句話說明',
    bg: '背景',
    bgColor: '背景色',
    charName: '名字',
    charNameColor: '名字顏色',
    motto: '標語',
    mottoColor: '標語顏色',
    mottoFont: '標語字型',
    small: '更小的文字',
    outfit: '平常服裝',
    features: '外觀特徵',
    height: '身高（cm）',
    moe: '萌化',
    moeSuffix: ' 萌化',
    hair: '髮色',
    eyeL: '左眼',
    eyeR: '右眼',
    lineText: '一句話說明',
    lineBg: '背景顏色',
    lineColor: '文字顏色',
    sampleName: '角色名字',
    sampleMotto: 'Character',
    sampleText: '在這裡寫點什麼。',
    hairCaption: 'HAIR',
    eyesCaption: 'EYES',
  },

  /* 雙人配對・主題背景 */
  duoTheme: {
    name: '雙人配對・主題背景',
    tip: '背景可以換成亮色、暗色主題或自己的圖片。',
    backdrop: '後方背景',
    main: '主要圖片',
    mainInfo: '配對名稱',
    keyword: '關鍵字',
    ref: (i: number) => `參考圖 ${i}`,
    profile: '頭像',
    moe: '外觀與萌化',
    notes: '其他說明',
    mode: '選擇背景',
    light: '亮色主題',
    dark: '暗色主題',
    image: '自己的圖片',
    bgCheck: '加上背景色',
    bgColor: '背景色',
    blur: '背景模糊',
    pairName: '配對名稱',
    boxBg: '底色',
    boxColor: '文字色',
    refTitle: '標題',
    refText: '詳細內容',
    height: '身高',
    animalBg: '動物化底色',
    animalColor: '動物化文字色',
    animal: '動物化',
    hair: '髮色',
    eyeL: '左眼',
    eyeR: '右眼',
    notesText: '其他事項',
    sampleTitle: '標題',
    sampleText: '寫下詳細內容。',
    sampleNotes: '寫下外觀或個性。',
    notesCaption: '其他事項',
    hairCaption: 'Hair',
    eyesCaption: 'Eyes',
    heightSuffix: ' cm',
  },

  /* 花紋橫幅 */
  banner: {
    name: '花紋橫幅',
    tip: '1500 × 500 的橫幅：重複的花紋＋可以鋪滿的圖片。',
    main: '主要',
    pattern: '花紋',
    image: '圖片',
    kind: '花紋種類',
    check: '格紋',
    tartan: '蘇格蘭格紋',
    solid: '單色',
    checkBase: '格紋底色',
    checkLine: '格紋線色',
    thick: '粗線',
    thin: '細線',
    scale: '花紋大小',
    rotate: '花紋旋轉',
    opacity: '花紋不透明度',
    blur: '花紋模糊',
    back: '後方背景色',
    repeat: '重複鋪滿',
    imgScale: '圖片大小',
    imgX: '水平位置',
    imgY: '垂直位置',
    imgRotate: '圖片旋轉',
    imgOpacity: '圖片不透明度',
    imgBlur: '圖片模糊',
  },

  /* 多人資料卡 */
  roster: {
    name: '多人資料卡（1～30 人）',
    tip: '每人一張卡，最多 30 人，一列 3 張。',
    member: (n: number) => `角色 ${n}`,
    main: '主要圖片',
    sub: '參考圖片',
    info: '資訊',
    mainBg: '主要圖片背景',
    subBg: '參考圖片背景',
    mainBgColor: '主要圖片背景色',
    subBgColor: '參考圖片背景色',
    tab: '分頁名稱',
    extra: '追加資訊',
    extraPh: '年齡、A&B 之類的定位',
    charName: '名字',
    nameColor: '名字顏色',
    nameBg: '名字底色',
    height: '身高（cm）',
    heightPh: '只寫數字',
    hair: '髮色',
    eyeL: '左眼',
    eyeR: '右眼',
    notes: '其他事項',
    sampleExtra: '身高',
    sampleName: '名字',
    sampleNotes: '寫下追加的特徵。',
    notesCaption: '其他事項',
    hairCaption: 'Hair',
    eyesCaption: 'Eyes',
  },

  /* 置頂貼文 */
  post: {
    name: '置頂貼文',
    tip: '自我介紹用的置頂圖：名字、標語與兩段介紹。',
    side: '置頂貼文',
    back: '背景',
    image: '圖片',
    info: '資訊',
    charText: '角色性向',
    ownerText: '主人性向',
    mode: '背景',
    light: '亮色主題',
    dark: '暗色主題',
    solid: '單色',
    bgColor: '背景色',
    charName: '名字',
    age: '年齡',
    nameColor: '名字顏色',
    subName: '第二名字（英文／漢字）',
    subFont: '第二名字字型',
    subColor: '第二名字顏色',
    motto: '標語',
    mottoFont: '標語字型',
    mottoColor: '標語顏色',
    keyword: '關鍵字',
    keywordColor: '關鍵字顏色',
    sampleName: '名字',
    sampleAge: '年齡',
    sampleSub: 'NAME',
    sampleMotto: '一句標語',
    sampleKeyword: '#關鍵字 #關鍵字 #關鍵字',
    sampleChar: '－ 寫下角色的性向與設定。',
    sampleOwner: '－ 寫下自己的喜好與交流方式。',
    charHeading: 'Character',
    ownerHeading: 'Owner',
  },

  /* 文字記錄 */
  log: {
    plain: '文字記錄・素面',
    band: '文字記錄・頂部色帶',
    side: '文字記錄・側邊色帶',
    duo: '文字記錄・雙欄配對',
    tipPlain: '放不下的本文會自動接到下一頁。',
    tipBand: '頁首一塊往下淡出的裝飾區；放不下的本文會接到下一頁。',
    tipSide: '左邊一塊往右淡出的裝飾區；放不下的本文會接到下一頁。',
    tipDuo: '左右兩欄各自的標題與本文；放不下的會接到下一頁同一欄。',
    options: '選項與背景',
    layout: '版面',
    decor: '裝飾區',
    decorN: (i: number) => `裝飾區 ${i}`,
    title: '標題與副標題',
    titleLane: (lane: number) => (lane === 0 ? '左欄標題' : '右欄標題'),
    body: '本文',
    bodyLane: (lane: number) => (lane === 0 ? '左欄本文' : '右欄本文'),
    font: '字型',
    serif: '明體',
    sans: '黑體',
    bgMode: '背景',
    decorMode: '裝飾區內容',
    solid: '單色',
    image: '圖片',
    bgColor: '背景色',
    decorColor: '裝飾色',
    blur: '圖片模糊',
    opacity: '圖片不透明度',
    titleText: '標題',
    subText: '副標題',
    follow: (gap: number) => `標題跟著本文（保持 ${gap} px 間距）`,
    bodyText: '本文',
    align: '對齊',
    top: '靠上',
    middle: '置中',
    bottom: '靠下',
    indent: '首行縮排',
    titleNote: '先選取文字，再套用粗體或顏色。（建議 20 字左右）',
    subNote: '先選取文字，再套用粗體或顏色。（建議 30 字左右）',
    bodyNote: '輸入完成後，放不下的本文會接到下一頁的同一欄。（最多 50,000 字）',
    pageN: (i: number) => `第 ${i} 頁`,
    sampleTitle: '雨後的茶館',
    sampleSub: '一段沒有特別意義的範例文字。',
  },
} as const;

/** 文字記錄的範例本文（新版自寫） */
export const LOG_SAMPLE = {
  long: [
    '傍晚的雨停了，茶館的門口還滴著水。掌櫃把濕透的招牌翻過來晾著，說今天大概不會再有客人。角落那桌的旅人卻一直沒走，杯子裡的茶早就涼了。',
    '──  有些故事，要等雨停了才說得出口。',
    '她從背包裡拿出一張摺得很小的地圖，攤在桌上，用茶杯壓住四個角。上面畫的不是路，而是一圈一圈的星星。掌櫃看了一眼，默默把燈調亮了一點。',
    '「這是要去哪裡？」他問。旅人沒有回答，只是指了指窗外。雲正在散開，第一顆星星剛好出現在地圖上那個圈起來的位置。',
    '後來掌櫃常常想起那個晚上。他不記得旅人的名字，卻記得那張地圖、那杯涼掉的茶，還有門外滴答的水聲，像是在替誰數著時間。',
  ].join('\n\n'),
  short: [
    '傍晚的雨停了，茶館的門口還滴著水。掌櫃把濕透的招牌翻過來晾著，說今天大概不會再有客人。角落那桌的旅人卻一直沒走。',
    '──  有些故事，要等雨停了才說得出口。',
    '她從背包裡拿出一張摺得很小的地圖，攤在桌上，用茶杯壓住四個角。上面畫的不是路，而是一圈一圈的星星。',
  ].join('\n\n'),
};
