/**
 * 劇本排版台的介面文字（台灣繁體中文；用詞照 DESIGN.md 第 5 節）。
 */

export const S = {
  toolbar: {
    library: '作品',
    save: '儲存',
    open: '開啟',
    undo: '復原',
    redo: '重做',
    print: '列印 / PDF',
    exportHtml: '匯出',
    overview: '頁面一覽',
    zoomOut: '縮小',
    zoomIn: '放大',
    zoomFit: '配合寬度',
    side: '設定欄',
    copyText: '複製文字',
  },
  panes: {
    source: '書寫',
    paper: '紙面',
    side: '設定',
    overview: '頁面一覽',
  },
  side: {
    block: '段落',
    pages: '頁面',
    doc: '文件',
  },
  status: {
    saved: '已自動儲存',
    savedUnsaved: '已自動儲存（有尚未存成檔案的變更）',
    saveFailed: '無法寫進瀏覽器的存放處。請先「儲存」成檔案，以免內容遺失。',
    retry: '重試',
    tooBig: '內容太大（圖片、字型），這個瀏覽器無法自動儲存，請記得「儲存」成檔案。',
    fileSaved: (name: string) => `已儲存「${name}」`,
    opened: (title: string) => `已開啟「${title}」`,
    openedNew: (title: string) => `已把檔案加成新的作品「${title}」並開啟`,
    notDoc: '這不是劇本排版台的原稿（JSON）檔案。',
    readFail: '讀不到這個檔案。',
    typeChanged: (n: number, name: string) => `已把 ${n} 個段落改成「${name}」`,
    added: (name: string) => `已新增「${name}」`,
    addedToCell: (r: number, c: number, name: string) => `已在第 ${r} 列第 ${c} 欄加入「${name}」`,
    noCellType: '換頁、換欄、目錄、封面、版權頁不能放進表格的儲存格。',
    noPopType: '換頁、換欄、目錄、封面、版權頁不能放進彈出視窗。',
    pickCellFirst: '請先點一下要放進去的儲存格。',
    moved: (n: number) => `已移動 ${n} 個段落`,
    mergeNeed: '請在同一個串列裡選取兩個以上的段落。',
    mergeBad: 'NPC 卡、目錄、換頁、換欄不能合併。',
    merged: (n: number) => `已合併 ${n} 個段落`,
    duplicated: (n: number) => `已複製 ${n} 個段落`,
    deleted: (n: number) => `已刪除 ${n} 個段落`,
    lastBlock: '本文最後一個段落不能刪除。',
    textCopied: (n: number) => `已複製 ${n} 個段落的文字`,
    allCopied: '已複製全文',
    copyFailed: '無法寫進剪貼簿。',
    blocksCopied: (n: number) => `已記下 ${n} 個段落（按「貼上」放到選取的段落之後）`,
    pasted: (n: number) => `已貼上 ${n} 個段落`,
    nothingToPaste: '還沒有記下的段落。',
    noSelection: '請先選取段落。',
    colsSet: (pages: string, cols: number) => `已把 ${pages} 設成${cols === 2 ? '雙欄' : '單欄'}`,
    rubyNoField: '請先在文字欄裡點一下（或選取要加注音的文字）。',
    spanOnly: 'NPC 卡與流程圖只能全寬。',
    cmtNoRange: '請先在文字欄裡選取要加上註解的文字。',
    cmtNameField: '表格名稱不能加註解。',
    cmtAdded: '已加上註解',
    cmtNone: '選取的段落沒有註解。',
    cmtDeleted: (n: number) => `已刪除 ${n} 則註解`,
    colorNameField: '表格名稱不能上色。',
    colorSet: '已改變文字顏色',
    clrOnlyImage: '「解除文繞圖」是給圖片以外的段落用的，請選取要從圖片下方開始的段落。',
    indent: (lv: number) => `縮排：第 ${lv} 層`,
    popCreated: (names: string) => `已建立彈出視窗「${names}」（不放在紙面）`,
    popSelf: '彈出視窗不能搬進自己裡面。',
    coverExists: '已經有封面了。',
    coverMade: '已在最前面建立封面頁',
    colophonExists: '已經有版權頁了。',
    colophonMade: '已在最後建立版權頁',
    tocMade: '已建立目錄',
    pagesDeleted: (n: number) => `已刪除 ${n} 頁上的段落`,
    pickPage: '請先在「頁面」分頁勾選頁面。',
    noBlocksOnPage: '勾選的頁面上沒有段落。',
    bgApplied: (n: number) => `已把背景套用到 ${n} 頁`,
    bgRemoved: (n: number) => `已移除 ${n} 頁的背景`,
    tplSaved: (n: string) => `已把目前的外觀存成樣板「${n}」`,
    tplRemoved: (n: string) => `已刪除樣板「${n}」`,
    outCopied: '已複製輸出',
    outEmpty: '輸出是空的。',
    ccfCopied: '已複製 CCFOLIA 棋子，到 CCFOLIA 的房間裡貼上即可。',
    imageNoAr: '這張圖片讀不出尺寸，無法縮小，照原檔放入。',
    fontAdded: (n: string) => `已新增字型「${n}」`,
    fontRemoved: (n: string) => `已刪除字型「${n}」`,
    pdfDone: (n: string) => `已下載「${n}」`,
    htmlDone: (n: string) => `已匯出「${n}」`,
    reset: '已全部清除，重新開始（清除前的內容留在「過去的版本」，也可以復原）',
    openElsewhere: '這個作品也在別的分頁開著。兩邊同時修改會互相覆蓋，請只在一個分頁編輯。',
    restoredJournal: '已放回上次關閉前還沒存好的內容（之前的內容留在「過去的版本」）。',
    noIdb: '這個瀏覽器無法使用 IndexedDB，只能保存一個作品（存在 localStorage）。',
    flowOpen: '請在流程圖編輯視窗裡操作。',
    npcHint: 'NPC 卡請在設定欄或「開啟角色卡」裡修改。',
    tocHint: '目錄的設定在設定欄。',
    breakHint: '換頁在紙面上看不到；之後的段落從新的一頁開始。',
    lockedOther: '這個作品正在別的分頁編輯，不能在這裡開啟。',
    legacyImported: (n: number) => `已接收舊版保存的 ${n} 個作品`,
  },
  confirm: {
    deleteBlocks: (n: number) => `刪除 ${n} 個段落？`,
    deleteBlocksHint: '刪除後可以按「復原」恢復。',
    tocAgain: '已經有目錄了，還要再建立一個嗎？',
    deletePages: (pages: string, n: number) => `刪除 ${pages} 上的 ${n} 個段落？`,
    reset: '全部清除，重新開始？',
    resetHint:
      '目前作品的內容會換成範例原稿（清除前的內容留成「過去的版本」，也可以復原）。其他作品不受影響。',
    bigBg: '這張圖片超過 2.5 MB，原稿會變大、自動儲存變慢。還要使用嗎？',
    deleteWork: (t: string) => `把「${t}」移到垃圾桶？`,
    deleteWorkHint: '垃圾桶裡的作品 30 天內可以還原。',
    removeArt: '移除立繪？',
    deleteTab: (t: string) => `刪除分頁「${t}」？`,
    overwriteTpl: (n: string) => `已經有名為「${n}」的樣板，要覆寫嗎？`,
    deleteTpl: (n: string) => `刪除樣板「${n}」？`,
    deleteFont: (n: string) => `刪除字型「${n}」？`,
    deleteFontHint: '用到它的內文、標題會改回預設的字型。',
    ok: '確定',
    del: '刪除',
  },
  hints: {
    emptyText: '（在這裡輸入）',
    emptyCell: '（空白）',
    emptyPopup: '（還沒有放入任何段落：按上方的書式按鈕新增）',
    noSelection: '沒有選取段落：按書式按鈕會在最後新增一個段落。',
  },
} as const;

/** 頁碼清單：P.1、P.3 */
export const pagesText = (idx: readonly number[]): string =>
  idx.map((i) => `P.${i + 1}`).join('、');
