/** CCFOLIA & 圖片調色工作室的介面文字（只有台灣繁體中文；用詞照 DESIGN.md 第 5 節） */
import type { BlendMode, CurveChannel, CurvePreset } from './adjust';
import type { GlobalLoopMode } from './naming';
import type { Mode, SortKey } from './store';

const n = (v: number) => v.toLocaleString('zh-TW');

export const S = {
  /* ---------- 載入（F01～F12） ---------- */
  pickFiles: '選擇檔案',
  pickFolder: '選擇資料夾',
  loadLabel: '加入檔案',
  loadHint: 'CCFOLIA 房間 ZIP、PSD、圖片（PNG、APNG、JPG、WebP、GIF）',
  emptyTitle: '還沒有載入任何素材',
  emptyBody:
    '把 CCFOLIA 匯出的房間 ZIP、Photoshop 的 PSD，或一批圖片（也可以整個資料夾）拖進來，或用下面的按鈕選擇。',
  dropOverlay: '放開就加入',
  dropOverlayHint: '房間 ZIP、PSD 一次一個；圖片可以多張',
  clearWork: '清除作業',
  clearWorkHint: '清掉目前的素材並刪除瀏覽器裡的自動存檔（整體調色與自訂組合會保留）',
  clearConfirmTitle: '清除目前的作業？',
  clearConfirmBody:
    '載入的素材與它們的個別調色會一起清掉，自動存檔也會刪除。整體調色與自訂組合不受影響。',
  clearConfirmOk: '清除',
  cleared: '已清除作業',
  unsupported: '沒有可以處理的檔案',
  unsupportedHint: '支援 CCFOLIA 房間 ZIP、PSD，以及 PNG、APNG、JPG、WebP、GIF 圖片。',
  imagesAdded: (count: number) => `加入了 ${n(count)} 張圖片`,
  someFailed: (count: number) => `有 ${n(count)} 個檔案讀不到，已略過`,
  failedList: (names: string[]) => `讀不到：${names.join('、')}`,
  zipFailed: 'ZIP 讀不了',
  zipFailedHint: (reason: string) => `${reason}（原本的內容沒有變動）`,
  zipNoImages: '這個 ZIP 裡沒有可用的圖片',
  psdFailed: 'PSD 讀不了',
  psdNoLayers: 'PSD 裡沒有可以用的圖層',
  psdNoLayersHint: '看得見、而且有像素的圖層才會載入（原本的內容沒有變動）。',
  roomLoaded: (count: number) => `已載入房間：${n(count)} 張圖片`,
  zipImagesLoaded: (count: number) => `ZIP 裡沒有房間資料，以圖片模式載入 ${n(count)} 張`,
  psdLoaded: (count: number) => `已載入 PSD：${n(count)} 個圖層`,

  /* 處理中畫面（F12） */
  busyReading: '讀取中…',
  busyReadingSub: '正在讀檔案',
  busyImages: (i: number, total: number) => `讀取圖片 ${n(i)} / ${n(total)}`,
  busyZip: '讀取 ZIP…',
  busyZipImages: (i: number, total: number) => `讀取 ZIP 裡的圖片 ${n(i)} / ${n(total)}`,
  busyPsd: '讀取 PSD…',
  busyPsdSub: '第一次讀 PSD 時會先下載讀取程式',
  busyPsdLayers: (i: number, total: number) => `整理圖層 ${n(i)} / ${n(total)}`,
  busyExport: '匯出中…',
  busyExportPsd: '匯出分割圖層…',
  busyAsset: (i: number, total: number) => `處理素材 ${n(i)} / ${n(total)}`,
  busyFrame: (i: number, total: number) => `APNG 第 ${n(i)} 格／共 ${n(total)} 格`,
  busyTry: (scale: number, colors: number | null) =>
    colors === null ? `試無損（尺寸 ${scale}%）` : `試尺寸 ${scale}%、${colors} 色`,
  busySkip: '正在計算跳格',
  busyPack: '打包 ZIP 中…',
  busyResize: '改畫布尺寸…',
  busyResizeAll: '補到 24 的倍數…',
  busyRestore: '還原上次的作業…',
  busyRestoreSub: (count: number) => `正在還原 ${n(count)} 個素材`,
  busyRestoreItem: (i: number, total: number) => `還原素材 ${n(i)} / ${n(total)}`,
  busySingle: '處理這一張…',
  cancel: '取消',
  canceled: '已取消',

  /* ---------- 預覽區（F13～F35） ---------- */
  modeLabel: '模式',
  modes: { idle: '等待', image: '圖片', psd: 'PSD', room: '房間' } satisfies Record<Mode, string>,
  stats: (count: number, mode: Mode) =>
    `${n(count)} 個素材・${mode === 'psd' ? 'PSD 圖層' : mode === 'room' ? '房間備份' : '圖片'}`,
  tabLayout: { room: 'CCFOLIA 房間', psd: '圖層配置', other: '配置檢視' },
  tabList: '圖片清單',
  viewTabsLabel: '檢視方式',
  layoutDisabled: '圖片模式沒有配置檢視',
  /* 圖片清單 */
  search: '搜尋',
  searchPlaceholder: '檔名、資料夾或圖層名',
  sort: '排序',
  sortOptions: {
    order: '載入順序',
    name: '名稱',
    type: '類型',
    role: '在房間中的角色',
  } satisfies Record<SortKey, string>,
  padAll: '全部補到 24 倍數',
  padAllHint: 'CCFOLIA 一格是 24 px。把每張圖的四周補透明邊，讓寬高剛好是 24 的倍數（內容置中）。',
  listLabel: '素材清單',
  listEmptySearch: '沒有符合搜尋的素材',
  badgeApng: 'APNG',
  badgePsd: 'PSD',
  badgeHidden: '隱藏',
  badgeAdjusted: '個別調整',
  kindFrames: (count: number) => `${n(count)} 格`,
  kindLayer: '圖層',
  kindStatic: '靜態',
  tileOpen: (name: string) => `開啟「${name}」的檢視器`,
  /* 配置檢視 */
  zoomIn: '放大',
  zoomOut: '縮小',
  center: '回到中央',
  fit: '符合畫面',
  grid: '顯示格線',
  zoomValue: (z: number) => `${Math.round(z * 100)}%`,
  layoutHint: '拖曳：移動　滾輪：以游標為中心縮放　點一下：選取　點兩下：開啟檢視器',
  layoutCanvas: (mode: Mode) =>
    mode === 'psd'
      ? 'PSD 圖層配置（方向鍵移動、＋／－縮放、0 回到中央）'
      : 'CCFOLIA 房間配置（方向鍵移動、＋／－縮放、0 回到中央）',
  noRoomData: '沒有房間資料',
  panelTitle: { room: '房間物件', psd: 'PSD 圖層', other: '素材' },
  panelLabel: '物件與圖層',
  showAll: '全部顯示',
  hideAll: '全部隱藏',
  unsolo: '解除獨顯',
  eyeShow: (name: string) => `顯示「${name}」`,
  eyeHide: (name: string) => `隱藏「${name}」`,
  soloOn: (name: string) => `獨顯「${name}」`,
  soloOff: (name: string) => `取消獨顯「${name}」`,
  background: '背景',
  foreground: '前景',
  rowName: (obj: string, file: string) => (obj ? `${obj}（${file}）` : file),
  rowZ: (z: number) =>
    z === Number.NEGATIVE_INFINITY
      ? '最下層'
      : z === Number.POSITIVE_INFINITY
        ? '最上層'
        : `z ${z}`,
  rowAsset: '素材',
  rowMeta: (a: string, w: number, h: number) => `${a}｜${w}×${h}`,

  /* ---------- 整體調色（F36～F58） ---------- */
  tabsLabel: '設定分類',
  tabGlobal: '整體調色',
  tabExport: '匯出設定',
  resetGlobal: '全部重設',
  resetGlobalDone: '整體調色已回到預設',
  undo: '復原',
  redo: '重做',
  tone: '色調',
  toneLabels: {
    hue: '色相',
    saturation: '飽和度',
    brightness: '亮度',
    contrast: '對比',
    exposure: '曝光',
  },
  toneHints: {
    hue: '所有顏色的色相轉一個角度；灰色不變。',
    saturation: '100% 不變；0% 變灰；200% 加倍。',
    brightness: '每個顏色直接加減這個數。',
    contrast: '以中間灰為中心拉開或收攏。',
    exposure: '每 +50 亮度加倍、每 −50 減半。',
  },
  assetSatHint: '乘在整體上：整體 150%、個別 −50% → 75%。',
  gradient: '漸層對應',
  gradientToggle: '使用漸層對應',
  gradientHint:
    '依每個像素的亮度在漸層上取色，再用混合模式與強度混回原色。點色帶空白處新增色標，拖曳色標移動。',
  gradientStops: '漸層色標',
  gradientMinStops: '色標至少要兩個。',
  gradientOpacity: '混合強度',
  gradientMode: '混合模式',
  blendModes: {
    normal: '一般',
    multiply: '色彩增值',
    screen: '濾色',
    overlay: '覆蓋',
    'soft-light': '柔光',
    color: '顏色',
  } satisfies Record<BlendMode, string>,
  gradientPresets: '漸層預設',
  gradientPresetNames: {
    mono: '黑白',
    sepia: '懷舊暖褐',
    neon: '霓虹',
    sunset: '夕陽',
    duo: '雙色',
  } as Record<string, string>,
  gradientPresetHint: '套用後會自動打開漸層對應（強度與模式不變）。',
  curves: 'RGB 曲線',
  curveChannel: '通道',
  curveChannels: { all: '三色一起', r: '紅', g: '綠', b: '藍' } satisfies Record<
    CurveChannel,
    string
  >,
  curveEditor: (ch: string) => `${ch}曲線`,
  curveHint:
    '點空白處新增控制點，拖曳移動（兩端點只能上下）；把中間的控制點拖出圖外、或選取後按 Delete 可以刪除。方向鍵微調選取的點。',
  curvePoint: (i: number, x: number, y: number) => `控制點 ${i}：輸入 ${x}、輸出 ${y}`,
  curvePresets: '曲線預設',
  curvePresetNames: {
    linear: '直線',
    scurve: 'S 形',
    darken: '中間調壓暗',
    lighten: '中間調提亮',
  } satisfies Record<CurvePreset['id'], string>,
  curvePresetHint: '只換掉目前通道的曲線。',
  presets: '自訂組合',
  presetName: '組合名稱',
  presetPlaceholder: '例：夜晚的冷色調',
  presetSave: '儲存',
  presetDefaultName: (i: number) => `自訂組合 ${i}`,
  presetEmpty: '還沒有自訂組合。調好整體調色後，取個名字儲存，下次一鍵套用。',
  presetSaved: (name: string) => `已儲存自訂組合「${name}」`,
  presetApplied: (name: string) => `已套用自訂組合「${name}」`,
  presetApply: (name: string) => `套用「${name}」`,
  presetDelete: (name: string) => `刪除「${name}」`,
  presetDeleteTitle: (name: string) => `刪除自訂組合「${name}」？`,
  presetDeleted: (name: string) => `已刪除自訂組合「${name}」`,
  presetHint: '存在這個瀏覽器裡；清除作業、全部重設都不影響。',

  /* ---------- 選取的素材（F59～F65） ---------- */
  selected: '選取的素材',
  noSelection: '還沒有選取素材。點清單或配置檢視裡的圖片就會選取（清單上點一下會直接開啟檢視器）。',
  openViewer: '開啟檢視器',
  openViewerOf: (name: string) => `開啟「${name}」的檢視器`,
  assetMeta: (w: number, h: number, kind: string) => `${n(w)} × ${n(h)} px｜${kind}`,
  kindPsdAt: (x: number, y: number) => `PSD 圖層（位置 ${x}, ${y}）`,
  kindApng: 'APNG',
  kindStaticImage: '靜態圖片',
  resetAsset: '個別重設',
  resetAssetHint: '清掉這個素材的個別調色',
  canvasSize: '畫布尺寸',
  canvasWidth: '寬',
  canvasHeight: '高',
  canvasApply: '套用',
  canvasHint: '內容置中、四周補透明；比原圖小時會置中裁切。',
  pad: '補到 24 倍數',
  padHint: '寬、高各自補到 24 的倍數（50×30 → 72×48）；CCFOLIA 一格是 24 px。',
  sameSize: (w: number, h: number) => `尺寸沒變（${w} × ${h} px）`,
  resized: (w: number, h: number) => `畫布改成 ${w} × ${h} px`,
  alreadyAligned: (w: number, h: number) => `${w} × ${h} px 已經是 24 的倍數，不必補`,
  cropConfirmTitle: '新尺寸比原圖小',
  cropConfirmBody: (ow: number, oh: number, w: number, h: number) =>
    `${ow} × ${oh} px → ${w} × ${h} px：超出的部分會被置中裁掉，之後無法復原。`,
  cropConfirmOk: '裁切',
  paddedAll: (count: number) => `補了 ${n(count)} 張`,
  paddedNone: '全部都已經是 24 的倍數',

  /* ---------- 單圖檢視器（F66～F83） ---------- */
  viewerTitleMeta: (w: number, h: number, kind: string) => `${n(w)} × ${n(h)} px（${kind}）`,
  kindPsdLayer: 'PSD 圖層',
  back: '回到清單',
  prev: '上一張',
  next: '下一張',
  compare: '按住對照原圖',
  compareHint: '按住（或聚焦後按住空白鍵）時顯示未調色的原圖',
  showingOriginal: '原圖',
  download: '下載這一張',
  downloaded: (name: string) => `${name} 下載完成`,
  compressDone: (scale: number, size: string) => `已壓縮：尺寸 ${scale}%、${size}`,
  viewerCanvas: (name: string) => `「${name}」的大畫面`,
  viewerLoading: '畫面準備中…',
  viewerFailed: '無法顯示這張圖片',
  individual: '個別調色',
  individualHint: '與整體調色疊加：色相、亮度、曝光相加，對比相加後最多 ±100，飽和度乘在整體上。',
  individualGradient: '個別漸層對應',
  individualGradientToggle: '套用（取代整體的漸層）',
  individualCurves: '個別曲線',
  individualCurvesHint: '套在整體曲線之後。',
  play: '播放',
  pause: '暫停',
  prevFrame: '上一格',
  nextFrame: '下一格',
  frameSlider: '影格',
  frameInfo: (i: number, total: number, ms: number) => `${n(i)} / ${n(total)} 格（${n(ms)} ms）`,
  speed: '播放速度',
  speedOptions: ['0.5', '1', '1.5', '2'],
  loops: 'APNG 播放次數',
  loopsOriginal: (plays: number) =>
    plays === 0 ? '原檔：無限循環' : plays === 1 ? '原檔：只播一次' : `原檔：播放 ${n(plays)} 次`,
  assetLoopOptions: {
    global: '跟隨整體設定',
    keep: '照原檔',
    once: '只播一次',
    infinite: '無限循環',
    custom: '指定次數',
  },
  loopCount: '次數',
  compressTest: '容量壓縮試算',
  compressTestRun: '試算壓縮結果',
  compressTestHint: '用目前的調色、目標容量與跳格設定試一次（不影響匯出）。',
  compressOffHint: '「壓縮」目前關閉，匯出時不會壓縮。',
  testResult: '試算結果',
  testSize: '壓縮後',
  testOrig: '原檔',
  testSaving: '節省',
  testDetail: (scale: number, colors: number | null, frames: number, skipped: boolean) =>
    `尺寸 ${scale}%｜${colors === null ? '無損（沒有減色）' : `${colors} 色`}｜${n(frames)} 格${skipped ? '（跳格）' : ''}`,
  testToast: (orig: string, out: string, saving: string) =>
    `原檔 ${orig} → ${out}（節省 ${saving}%）`,
  testOver: '最低設定仍超過目標容量',

  /* ---------- 匯出（F84～F100） ---------- */
  compress: '壓縮 APNG 到目標容量',
  compressHint:
    'APNG 與大圖超過目標容量時，先減色、再縮小尺寸，直到不超過目標（CCFOLIA 有上傳大小限制）。已經在目標內的不動。',
  target: '目標容量',
  targetOptions: { '4.8': '4.8 MB（CCFOLIA）', '2': '2.0 MB', '10': '10.0 MB' } as Record<
    string,
    string
  >,
  frameSkip: '允許跳格',
  frameSkipHint: '縮到最小仍超過目標時，每兩格合成一格（延遲相加）。',
  compressStatic: '靜態圖也壓縮',
  compressStaticHint: (mb: string) => `重新編碼後超過 ${mb} 的靜態圖也減色或縮小。`,
  loopsGlobal: 'APNG 播放次數',
  loopOptions: {
    keep: '照原檔',
    once: '只播一次',
    infinite: '無限循環',
    custom: '指定次數',
  } satisfies Record<GlobalLoopMode, string>,
  loopsHint: '單張的設定（檢視器裡）優先。',
  exportZip: (mode: Mode) => (mode === 'psd' ? '下載分割圖層（ZIP）' : '下載成品（ZIP）'),
  exportDone: (name: string) => `${name} 下載完成`,
  exportOver: (names: string[]) => `這些檔案壓到最低設定仍超過目標容量：${names.join('、')}`,
  exportFailed: '匯出失敗',
  needZip: '需要原本的房間 ZIP',
  needZipHint:
    '這個作業是從自動存檔還原的，但瀏覽器裡沒有原本的 ZIP。請重新放入當初的房間 ZIP 再匯出。',
  status: (scale: number, colors: number | null) =>
    colors === null ? `壓縮中：試無損` : `壓縮中：尺寸 ${scale}%、${colors} 色`,
  statusSkip: '壓縮中：正在計算跳格',
  noVisible: '沒有看得見的素材可以匯出',

  /* ---------- 存檔與還原（F104～F106） ---------- */
  restored: (count: number) => `已還原上次的作業（${n(count)} 個素材）`,
  restoreFailed: '還原上次的作業失敗',
  saveUnavailable: '自動存檔無法使用',
  saveFailed: '自動存檔失敗（瀏覽器空間不足？）',
  projectReset: '全部重來…',
  projectResetTitle: '全部重來？',
  projectResetBody: '清掉素材、整體調色與匯出設定，回到剛開頁的狀態（自訂組合保留）。',
  projectOpened: '已開啟專案檔',
  projectBadData: '這不是調色工作室的專案檔',

  /* ---------- 預設名 ---------- */
  emptyLayerName: (i: number) => `未命名圖層 ${i}`,
  fallbackZip: {
    idle: 'images',
    image: 'images',
    psd: 'psd_layers',
    room: 'ccfolia_room',
  } satisfies Record<Mode, string>,

  /* ---------- 說明（F108、F109） ---------- */
  usageIntro:
    '一次替一整批素材調色：CCFOLIA 匯出的房間 ZIP、Photoshop 的 PSD，或一批圖片（也可以整個資料夾）。所有圖片套用同一組「整體調色」，也可以替單張再加「個別調色」，最後打包成一個 ZIP 下載。',
  usageSteps: [
    '把檔案拖進視窗，或按「選擇檔案」「選擇資料夾」。房間 ZIP、PSD 會取代目前的內容；圖片會累加。',
    '在「整體調色」調色相、飽和度、亮度、對比、曝光、漸層對應與 RGB 曲線，所有預覽立刻更新。常用的組合可以存成「自訂組合」。',
    '在「圖片清單」點一下圖片開啟檢視器：看全解析度的結果、按住對照原圖、加上個別調色、改畫布尺寸、單張下載。',
    '「配置檢視」照位置排出房間（CCFOLIA 盤面）或 PSD（圖層位置）；右上的面板可以隱藏或獨顯素材，隱藏的不會匯出（房間模式保留原檔）。',
    '按「下載成品（ZIP）」。房間 ZIP 會依新內容重新命名圖片並同步改好房間資料，可以直接匯回 CCFOLIA；PSD 會把每個看得見的圖層各存成一張 PNG。',
  ],
  usageNotesTitle: '注意事項',
  usageNotes: [
    '檔案只在你的瀏覽器裡處理，不會上傳到任何地方。',
    '清單、配置檢視、面板上的是低解析度的預覽；檢視器與匯出才是全解析度（兩者逐像素相同）。',
    'JPG、WebP、GIF 會重新編碼成 PNG，副檔名改成 .png（房間 ZIP 的資料一併改正）；GIF 動畫只取第一格。',
    'CCFOLIA 一格是 24 px：「補到 24 倍數」會在四周補透明邊，內容置中。',
    'APNG 預設會壓到目標容量（4.8 MB 配合 CCFOLIA）以內：先減色，再縮小尺寸，還不行時允許跳格；已經在目標內的不動。壓到最低設定仍超過時會提醒。',
    '房間 ZIP 匯回 CCFOLIA 時，圖片檔名是新內容的 SHA-256，房間資料裡的引用全部改好；.token 與其他檔案原封不動。',
    'Windows 內建的解壓縮遇到中文檔名可能出錯，建議用 7-Zip 等工具，或直接把 ZIP 匯回 CCFOLIA。',
    '作業內容（素材、個別調色、房間資料、原本的 ZIP）會自動存在這個瀏覽器裡，重新整理後自動還原；「清除作業」會刪掉。',
  ],
  shortcutUndo: '復原整體調色',
  shortcutRedo: '重做整體調色',
  shortcutGroup: '調色',
};

export type Strings = typeof S;
