/* 輕量轉場 APNG 產生器（TRPG Toolkit 收錄版）
 * 上游是一個作者與來源都不明的單檔 HTML（日文原名意為「APNG 製作表」，見 ATTRIBUTION.md）。
 * 收錄版只有繁體中文；APNG 的編碼（PNG chunk、CRC、zlib）是上游自己寫的，照原樣保留。
 * 與上游不同的地方：存檔的副檔名從 .apng 改成 .png（APNG 規格建議的副檔名，上傳圖片的對話框也認得）。 */
'use strict';
const $=id=>document.getElementById(id),canvas=$('preview'),ctx=canvas.getContext('2d');
let started=performance.now();
const read=()=>({seconds:[.2,.5,1,1.5,2,2.5,3,3.5,4,4.5,5][Number($('seconds').value)],type:document.querySelector('input[name=type]:checked').value,freeWidth:Number($('freewidth').value),freeHeight:Number($('freeheight').value),color:currentColor,angle:Number($('angle').value)*45,mode:document.querySelector('input[name=mode]:checked').value,cover:document.querySelector('input[name=direction]:checked').value==='cover',loop:document.querySelector('input[name=loop]:checked').value});
function validate(p){if(!Number.isFinite(p.seconds)||p.seconds<.2||p.seconds>5)throw Error('請選擇時間。');if(!Number.isFinite(p.angle)||p.angle<0||p.angle>=360)throw Error('角度請指定在 0～359 度之間。');if(p.type==='free'&&[p.freeWidth,p.freeHeight].some(n=>!Number.isInteger(n)||n<1||n>1200))throw Error('寬與高請輸入 1～1200 之間的整數（px）。');}
function dimensions(p){return p.type==='free'?[Math.max(1,Math.min(1200,Math.floor(p.freeWidth)||1)),Math.max(1,Math.min(1200,Math.floor(p.freeHeight)||1))]:p.type==='portrait'?[15,30]:p.type==='landscape'?[30,15]:[15,15];}
function geometry(angle,w,h){const a=angle*Math.PI/180,dx=Math.cos(a),dy=Math.sin(a),corners=[0,w*dx,h*dy,w*dx+h*dy];return {w,h,dx,dy,min:Math.min(...corners),max:Math.max(...corners)};}
const wipeProfiles=[[0,0,0,0,0,0,0,0,0,0],[0.0,0.0,0.0,0.0,1.5,4.8,8.5,13.0,17.5,23.0],[0.0,2.0,5.5,9.0,13.5,18.2,23.5,29.2,35.5,42.0],[9.6,14.0,19.2,24.5,30.5,36.5,43.5,50.4,58.1,66.0],[25.5,31.0,37.5,44.1,51.5,59.0,67.5,76.0,85.2,94.7],[45.5,53.0,60.5,69.0,77.5,86.7,96.5,106.0,116.5,127.7],[70.2,79.0,88.0,98.0,107.7,118.2,129.5,140.0,150.5,160.6],[99.5,109.3,120.1,131.0,141.7,152.0,162.0,171.5,180.5,189.0],[132.5,143.2,153.5,163.5,172.7,181.7,190.3,198.0,205.5,212.7],[164.8,174.0,183.0,191.3,199.5,206.8,213.5,220.0,226.5,232.0],[192.5,200.3,207.5,215.0,221.2,227.0,232.5,238.0,242.5,246.7],[215.5,222.0,228.0,233.5,238.5,243.0,247.4,251.0,253.8,255.0],[234.5,239.1,243.5,248.0,251.5,254.2,255.0,255.0,255.0,255.0],[248.5,252.0,254.9,255.0,255.0,255.0,255.0,255.0,255.0,255.0],[255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0,255.0]];
function mask(g,t,cover,mode){const result=new Uint8Array(g.w*g.h);if(mode==='normal'){const progress=cover?Math.max(0,Math.min(1,(t-.25)/.60)):Math.max(0,Math.min(1,(t-.15)/.60));result.fill(Math.round(255*(cover?progress:1-progress)));return result;}const frame=Math.max(0,Math.min(14,t*14)),f0=Math.floor(frame),f1=Math.min(14,f0+1),ft=frame-f0,range=g.max-g.min||1;for(let y=0;y<g.h;y++)for(let x=0;x<g.w;x++){const q=((x+.5)*g.dx+(y+.5)*g.dy-g.min)/range,u=Math.max(0,Math.min(9,(1-q)*9)),x0=Math.floor(u),x1=Math.min(9,x0+1),xt=u-x0;const a=wipeProfiles[f0][x0]*(1-xt)+wipeProfiles[f0][x1]*xt,b=wipeProfiles[f1][x0]*(1-xt)+wipeProfiles[f1][x1]*xt,alpha=Math.round(a*(1-ft)+b*ft);result[y*g.w+x]=cover?alpha:255-alpha;}return result;}
function render(now){const p=read(),[w,h]=dimensions(p),scale=Math.min(4,180/Math.max(w,h)),pw=Math.max(1,Math.round(w*Math.min(1,scale))),ph=Math.max(1,Math.round(h*Math.min(1,scale)));$('previewsize').textContent=w+'×'+h+'px · '+(scale<1?'縮小顯示':'放大 '+(Math.round(scale*10)/10)+' 倍');if(canvas.width!==pw||canvas.height!==ph){canvas.width=pw;canvas.height=ph;canvas.style.width=Math.round(w*scale)+'px';canvas.style.height=Math.round(h*scale)+'px';}const duration=p.seconds*1000,t=p.loop==='forever'?Math.min(1,((now-started)%(duration+(p.mode==='normal'?0:34)))/duration):Math.min(1,(now-started)/duration),g=geometry(p.angle,pw,ph),m=mask(g,t,p.cover,p.mode),rgb=hex(p.color),img=ctx.createImageData(pw,ph);for(let i=0;i<m.length;i++){img.data[i*4]=rgb[0];img.data[i*4+1]=rgb[1];img.data[i*4+2]=rgb[2];img.data[i*4+3]=m[i];}ctx.putImageData(img,0,0);requestAnimationFrame(render);}
function hex(s){return [1,3,5].map(i=>parseInt(s.slice(i,i+2),16));}
let currentColor='#28212f',hue=268,saturation=.3,brightness=.18;const colorpad=$('colorpad'),padctx=colorpad.getContext('2d');function hsv(h,s,v){const f=n=>{const k=(n+h/60)%6;return Math.round((v-v*s*Math.max(0,Math.min(k,4-k,1)))*255)};return [f(5),f(3),f(1)];}function colorHex(rgb){return '#'+rgb.map(v=>v.toString(16).padStart(2,'0')).join('');}function moveMark(){const mark=$('colorpadmark');mark.style.left=(saturation*100)+'%';mark.style.top=((1-brightness)*100)+'%';}function drawPad(){const img=padctx.createImageData(240,150);for(let y=0;y<150;y++)for(let x=0;x<240;x++){const rgb=hsv(hue,x/239,1-y/149),i=(y*240+x)*4;img.data.set([...rgb,255],i);}padctx.putImageData(img,0,0);}function setColor(value){if(!/^#[0-9a-f]{6}$/i.test(value))return;currentColor=value.toLowerCase();$('color').value=currentColor;$('swatch').style.background=currentColor;started=performance.now();}drawPad();moveMark();colorpad.addEventListener('pointerdown',e=>{colorpad.setPointerCapture(e.pointerId);pick(e);});colorpad.addEventListener('pointermove',e=>{if(e.buttons)pick(e);});function pick(e){const box=colorpad.getBoundingClientRect(),s=Math.max(0,Math.min(1,(e.clientX-box.left)/box.width)),v=1-Math.max(0,Math.min(1,(e.clientY-box.top)/box.height));saturation=s;brightness=v;moveMark();setColor(colorHex(hsv(hue,s,v)));} $('hue').addEventListener('input',e=>{hue=Number(e.target.value);drawPad();setColor(colorHex(hsv(hue,saturation,brightness)));});$('color').addEventListener('change',e=>{if(/^#[0-9a-f]{6}$/i.test(e.target.value))setColor(e.target.value);else e.target.value=currentColor;});const u32=n=>[(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255],u16=n=>[(n>>>8)&255,n&255];
const cat=(...arrays)=>{const out=new Uint8Array(arrays.reduce((n,a)=>n+a.length,0));let p=0;for(const a of arrays){out.set(a,p);p+=a.length;}return out;};
const ascii=s=>Uint8Array.from([...s].map(c=>c.charCodeAt(0)));
const crcTable=Uint32Array.from({length:256},(_,i)=>{let c=i;for(let j=0;j<8;j++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
function crc(bytes){let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function chunk(type,data){const body=cat(ascii(type),data);return cat(u32(data.length),body,u32(crc(body)));}
function scanlines(mask,w,h){const out=new Uint8Array(h*(w+1));for(let y=0;y<h;y++)out.set(mask.subarray(y*w,(y+1)*w),y*(w+1)+1);return out;}
function adler(bytes){let a=1,b=0;for(const v of bytes){a=(a+v)%65521;b=(b+a)%65521;}return ((b<<16)|a)>>>0;}
function storedZlib(bytes){let offset=0,parts=[Uint8Array.of(0x78,0x01)];while(offset<bytes.length){const count=Math.min(65535,bytes.length-offset),last=offset+count===bytes.length;parts.push(Uint8Array.of(last?1:0,count&255,count>>>8,(~count)&255,((~count)>>>8)&255),bytes.subarray(offset,offset+count));offset+=count;}parts.push(Uint8Array.from(u32(adler(bytes))));return cat(...parts);}
async function compress(bytes){if(typeof CompressionStream==='undefined')return storedZlib(bytes);const s=new Blob([bytes]).stream().pipeThrough(new CompressionStream('deflate'));return new Uint8Array(await new Response(s).arrayBuffer());}
function equal(a,b){return a.every((v,i)=>v===b[i]);}
async function makeAPNG(p){validate(p);const [w,h]=dimensions(p),g=geometry(p.angle,w,h),total=Math.max(1,Math.round(p.seconds*1000)),steps=Math.max(1,Math.round(p.seconds*30)),large=w*h>65536,frames=[];if(p.seconds===0)frames.push({m:large?null:mask(g,1,p.cover,p.mode),at:0,t:1});else for(let i=0;i<=(p.mode==='normal'?steps-1:steps);i++){const at=Math.round(total*i/steps),t=at/total,m=large?null:mask(g,t,p.cover,p.mode);if(!large&&frames.length&&equal(m,frames.at(-1).m))continue;frames.push({m:large?null:m,at,t});}const durations=frames.map((f,i)=>i+1<frames.length?Math.max(1,frames[i+1].at-f.at):Math.max(p.mode==='normal'?1:34,total-f.at));const rgb=hex(p.color),palette=new Uint8Array(256*3),alpha=new Uint8Array(256);for(let i=0;i<256;i++){palette.set(rgb,i*3);alpha[i]=i;}const parts=[Uint8Array.of(137,80,78,71,13,10,26,10),chunk('IHDR',Uint8Array.from([...u32(w),...u32(h),8,3,0,0,0])),chunk('PLTE',palette),chunk('tRNS',alpha),chunk('acTL',Uint8Array.from([...u32(frames.length),...u32(p.loop==='forever'?0:1)]))];let seq=0;for(let i=0;i<frames.length;i++){const delay=durations[i];parts.push(chunk('fcTL',Uint8Array.from([...u32(seq++),...u32(w),...u32(h),...u32(0),...u32(0),...u16(delay),...u16(1000),0,0])));const compressed=await compress(scanlines(frames[i].m||mask(g,frames[i].t,p.cover,p.mode),w,h));parts.push(i===0?chunk('IDAT',compressed):chunk('fdAT',cat(u32(seq++),compressed)));}parts.push(chunk('IEND',new Uint8Array()));return {blob:new Blob(parts,{type:'image/png'}),count:frames.length};}
document.querySelectorAll('input, select').forEach(control=>control.addEventListener('input',()=>{started=performance.now();}));$('seconds').addEventListener('input',()=>{$('secondsvalue').textContent=read().seconds.toFixed(1)+' 秒';});$('angle').addEventListener('input',()=>{$('anglevalue').textContent=['0°・向右','45°・向右下','90°・向下','135°・向左下','180°・向左','225°・向左上','270°・向上','315°・向右上'][Number($('angle').value)];});document.querySelectorAll('input[name=type]').forEach(control=>control.addEventListener('change',()=>{$('customsize').hidden=document.querySelector('input[name=type]:checked').value!=='free';}));document.querySelectorAll('input[name=mode]').forEach(control=>control.addEventListener('change',()=>{$('anglewrap').hidden=document.querySelector('input[name=mode]:checked').value!=='wipe';}));document.querySelectorAll('input[name=previewbg]').forEach(control=>control.addEventListener('change',()=>{$('previewbg').classList.toggle('black',control.value==='black'&&control.checked);}));$('restart').onclick=()=>{started=performance.now();};$('download').onclick=async()=>{const button=$('download'),status=$('status');button.disabled=true;status.textContent='產生中…';try{const p=read(),{blob,count}=await makeAPNG(p),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`transition-${p.type}-${p.mode}-${p.cover?'cover':'reveal'}-${p.angle}deg.png`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);status.textContent=`已儲存：${count} 格，${(blob.size/1024).toFixed(1)} KB`; }catch(e){status.textContent=e.message; }finally{button.disabled=false;}};requestAnimationFrame(render);
