/**
 * 跑團紀錄簿的介面文字（全部自寫；範例資料與範本也是自寫的繁中內容）。用詞照 DESIGN.md 第 5 節。
 */
import type { SheetField } from './importSheet';

/** 範例列（F34）：日期、劇本、人名都是虛構的 */
interface SampleRow {
  dates: string[];
  scenario: string;
  system: string;
  role: string;
  gm: string;
  players: string;
  pc: string;
  status: string;
  time: string;
  note: string;
  longNote: string;
}

const SAMPLES: readonly SampleRow[] = [
  {
    dates: ['2026-06-14'],
    scenario: '（範例）霧港燈塔的最後一盞燈',
    system: 'CoC 6版',
    role: 'PL',
    gm: '範例主持人小林',
    players: '同團玩家阿德、同團玩家米可',
    pc: '調查員・溫書亭',
    status: '新規',
    time: '4',
    note: '（範例）第一次玩海邊的劇本。',
    longNote: '【最有印象的一幕】\n\n【想記住的台詞】\n\n【角色之後的打算】\n',
  },
  {
    dates: ['2026-05-02', '2026-05-09'],
    scenario: '（範例）雨夜的郵差',
    system: 'CoC 7版',
    role: 'KP',
    gm: '自己',
    players: '同團玩家小雨、同團玩家阿哲、同團玩家佩佩',
    pc: '調查員甲 / 調查員乙 / 調查員丙',
    status: '完結',
    time: '7.5',
    note: '（範例）分兩天帶完。',
    longNote: '',
  },
  {
    dates: ['2026-03-21'],
    scenario: '（範例）星砂與回聲',
    system: 'エモクロア',
    role: 'DL',
    gm: '自己',
    players: '同團玩家芙蘭、同團玩家阿凱',
    pc: '共鳴者・星見 / 共鳴者・回音',
    status: '継続',
    time: '3.5',
    note: '（範例）下次接著第二章。',
    longNote: '',
  },
  {
    dates: ['2026-02-07'],
    scenario: '（範例）鐘樓下的晚餐會',
    system: 'マダミス',
    role: 'PL',
    gm: '範例主持人小林',
    players: '同團玩家阿德、同團玩家小雨、同團玩家阿凱',
    pc: '管家',
    status: '完結',
    time: '5',
    note: '（範例）猜錯了兇手。',
    longNote: '',
  },
];

/** 範本 CSV 的範例列（3.11；系統、狀態、生還寫正規值，輸出時換成顯示名稱） */
const TEMPLATE_ROWS: readonly Partial<Record<SheetField, string>>[] = [
  {
    date: '2025-11-08',
    scenario: '範本劇本・海邊的旅館',
    system: 'CoC 6版',
    role: 'PL',
    gm: '主持人小林',
    players: '玩家阿德、玩家米可',
    pc: '調查員・溫書亭',
    status: '完結',
    time: '4',
    note: '可以自由填寫',
    hashtag: '#CoC #團報',
    ending: 'END A',
    survival: '生還',
  },
  {
    date: '2025/12/6, 2025/12/13',
    scenario: '範本劇本・長夜車站',
    system: 'CoC 7版',
    role: 'KP',
    gm: '自己',
    players: '玩家小雨、玩家阿哲',
    status: '継続',
    time: '6',
    note: '跑了好幾天就用逗號分隔日期',
    campaign: '範本長團',
  },
];

export const S = {
  samples: SAMPLES,
  dateMore: (latest: string, more: number) => `${latest} 另 ${more} 天`,
  hours: (n: string) => `${n} 小時`,
  jsonFilePrefix: '跑團紀錄簿',
  disclaimer:
    '本工具為玩家自製的非官方工具。各 TRPG 系統、劇本與外部服務的規則與授權，請以各自的公告與條款為準。',

  header: {
    reportLink: '團報產生器',
    reportLinkTitle: '開啟團報產生器',
    undo: '復原',
    redo: '重做',
  },

  usage: {
    intro:
      '把玩過、帶過的團一筆筆記下來，統計場次與時數，整理成已通關劇本清單，也能把一團帶到團報產生器寫團報。',
    steps: [
      '按「新增團」填日期、劇本、系統與一起玩的人；雙擊表格的一列可以修改。',
      '點一列再按「詳細・感想」，可以寫長篇感想、結果，記下貼文與防雷連結。',
      '用「新增欄位」「移除欄位」決定表格要顯示哪些欄；拖曳欄位標題左邊的把手調整順序，拖曳右緣調整寬度。',
      '已經有試算表、舊團報或 CCFOLIA 的紀錄時，用「匯入」一次加進來。',
      '每一列最右邊的「送出」會把這一團帶到團報產生器。',
    ],
    notesTitle: '小提醒',
    notes: [
      '資料只存在這台裝置的瀏覽器裡；換電腦或清除瀏覽資料前，請先「匯出 JSON」備份。',
      '一開始的 4 筆是範例，不計入統計，可以按「刪除範例」一次刪掉。',
      '匯入時填「你的稱呼」，就能自動判斷你在那一團是 PL 還是 KP，同團玩家也不會算到自己。',
    ],
  },

  stats: {
    aria: '統計',
    days: { label: '跑團天數', unit: '天' },
    scenarios: { label: '劇本數', unit: '部' },
    hours: { label: '總遊玩時間', unit: '小時' },
    coPlayers: { label: '同團玩家', unit: '人' },
    note: '不含範例。',
  },

  toolbar: {
    title: '跑團紀錄',
    add: '新增團',
    detail: '詳細・感想',
    import: '匯入',
    exportJson: '匯出 JSON',
    exportText: '匯出文字',
    search: '搜尋紀錄',
    searchPlaceholder: '搜尋劇本、PC、GM、PL、備註…',
    systemFilter: '依系統篩選',
    allSystems: '所有系統',
    roleFilter: '依身分篩選',
    roles: { all: '所有身分', PL: 'PL', GM: 'GM・KP・DL' },
    sort: '排序',
    sorts: { newest: '由新到舊', oldest: '由舊到新', scenario: '依劇本', gm: '依 GM／KP' },
    shown: (n: number, total: number) =>
      n === total ? `共 ${total} 團` : `顯示 ${n}／${total} 團`,
  },

  samplesNotice: (n: number) =>
    `目前有 ${n} 筆範例（不計入統計與清單）。新增自己的紀錄後，可以把範例刪掉。`,
  deleteSamples: '刪除範例',

  columns: {
    add: '新增欄位',
    remove: '移除欄位',
    reset: '重設欄位',
    resetDone: '欄位已回到預設',
    addTitle: '可以加進表格的欄位',
    addDesc: '加進來的欄位也會一起帶到團報產生器（有對應的項目時）。',
    removeTitle: '表格裡的欄位',
    removeDesc: '取消勾選只是不顯示，已經填的資料會留著，隨時可以再加回來。',
    added: '已在表格',
    addOne: '加入',
    customCreate: '建立自訂欄位',
    customDesc: '自訂欄位',
    close: '關閉',
    customDialogTitle: '建立自訂欄位',
    customDialogDesc: '新的欄位會加在表格最右邊（送出欄前面），新增／編輯對話框也會出現。',
    customLabel: '欄位名稱',
    customPlaceholder: '例：使用的骰子、團的地點',
    customCreateButton: '建立',
    moveHandle: (label: string) => `移動「${label}」欄（←／→）`,
    resizeHandle: (label: string) => `「${label}」欄的寬度（←／→ 調整）`,
  },

  table: {
    aria: '跑團紀錄表格',
    addRow: '新增團',
    openDetail: (scenario: string) => `開啟「${scenario || '未命名'}」的詳細・感想`,
    reported: '已發團報',
    notReported: '還沒發團報',
    reportedAria: (scenario: string) => `「${scenario || '未命名'}」已發團報`,
    send: '送出',
    sendTitle: '送到團報產生器',
    sendAria: (scenario: string) => `把「${scenario || '未命名'}」送到團報產生器`,
    empty: '沒有符合搜尋或篩選的團。',
    emptyAll: '還沒有任何紀錄。按「新增團」開始記錄吧。',
    sample: '範例',
    fab: '新增團',
  },

  dialog: {
    addTitle: '新增團',
    editTitle: '編輯團資訊',
    groups: { basic: '基本資訊', people: '參加者', note: '備註', extra: '額外欄位' },
    date: '日期',
    dateRow: (n: number) => `日期 ${n}`,
    addDate: '新增日期',
    removeDate: (n: number) => `刪除日期 ${n}`,
    system: '系統',
    systemCustom: '自行輸入',
    systemCustomLabel: '系統名稱',
    systemCustomPlaceholder: '輸入系統名稱',
    role: '身分',
    status: '狀態',
    time: '時間',
    timePlaceholder: '例：4',
    hoursUnit: '小時',
    gm: 'GM／KP／DL',
    players: 'PL（同團玩家）',
    pc: 'PC',
    note: '備註',
    fav: '最愛',
    favLabel: '標記為最愛',
    survivalUnset: '未設定',
    longNote: '長篇感想',
    urlInvalid: '請輸入完整的網址（例如 https://…）。',
    delete: '刪除',
    cancel: '取消',
    save: '儲存',
    deleteTitle: '要刪除這一團嗎？',
    deleteDesc: (scenario: string) =>
      `「${scenario || '未命名'}」會從紀錄裡刪掉（可以用「復原」找回來）。`,
    deleteConfirm: '刪除',
    saved: '已儲存',
    added: '已新增',
    deleted: '已刪除',
  },

  detail: {
    title: '詳細・感想',
    description: (scenario: string) => `目前選取：${scenario || '未命名的團'}`,
    empty: '目前沒有選取的團。先新增一團，或點表格的一列再打開這裡。',
    emptyDesc: '沒有選取的團',
    scenario: '劇本名稱',
    scenarioPlaceholder: '劇本名稱',
    dates: '日期（多個用「, 」分隔）',
    datesInvalid: '看不懂這個日期，請寫成 2026-06-14 這種格式。',
    system: '系統',
    role: '身分',
    status: '狀態',
    none: '—',
    gm: 'GM／KP／DL',
    players: 'PL（同團玩家）',
    pc: 'PC',
    time: '時間（小時）',
    ending: '結局',
    survival: '生還／撕卡',
    media: '貼文與連結',
    mediaUrl: '貼文或圖片的網址',
    mediaAdd: '新增',
    mediaHint: 'X 貼文、團報、圖片網址都可以；圖片會直接顯示，其他顯示成連結。',
    mediaBadUrl: '請輸入 http:// 或 https:// 開頭的網址。',
    xPost: 'X 貼文',
    image: '圖片',
    caption: '說明',
    captionPlaceholder: '說明文字',
    remove: '刪除',
    removeMedia: (n: number) => `刪除第 ${n} 個貼文／連結`,
    nothing: '還沒有內容。',
    result: '結果',
    resultPlaceholder: 'END、生還、走到的路線…',
    longNote: '長篇感想',
    longNotePlaceholder: '這一團的感想',
    links: '防雷連結',
    linksHint: '放有劇透的感想、心得的連結（例如 Fusetter、Privatter）。',
    addLink: '新增連結',
    linkLabel: (n: number) => `連結 ${n} 的標籤`,
    linkUrl: (n: number) => `連結 ${n} 的網址`,
    linkLabelPlaceholder: '標籤',
    openLink: (n: number) => `開啟連結 ${n}`,
    removeLink: (n: number) => `刪除連結 ${n}`,
    note: '備註（表格顯示）',
    notePlaceholder: '一句話的簡短備註',
    deleteSession: '刪除這一團',
    editAll: '編輯全部欄位',
    toReport: '前往團報產生器',
    save: '儲存',
    close: '關閉',
    saved: '已儲存',
  },

  import: {
    title: '匯入跑團紀錄',
    description: '從試算表、團報文字、CCFOLIA 的紀錄或本工具的 JSON 把團加進來。',
    selfName: '你的稱呼',
    selfNamePlaceholder: '例：阿德（多個用「、」分隔）',
    selfNameHint: '用來判斷你在那一團是 PL 還是 KP，同團玩家也不會算到自己。只存在這台裝置。',
    tabs: { sheet: '試算表', text: '團報文字', ccfolia: 'CCFOLIA・紀錄', json: 'JSON' },
    tabsAria: '匯入來源',
    sheetHint:
      '從 Excel、Google 試算表、Notion 複製表格後貼上，或讀入 CSV／TSV 檔。第一列放標題（日期、劇本、系統…）會自動對應欄位；讀進來後可以直接修改。',
    sheetPaste: '貼上表格',
    sheetPlaceholder:
      '日期\t劇本名稱\t系統\t身分\tGM\tPL\tPC\n2025-11-08\t海邊的旅館\tCoC 6版\tPL\t主持人小林\t玩家阿德\t調查員・溫書亭',
    pickSheet: '讀入 CSV／TSV 檔',
    template: '下載範本 CSV',
    templateFileName: '跑團紀錄簿-匯入範本.csv',
    fileRead: (name: string) => `已讀入「${name}」`,
    fileEncoding: (name: string, encoding: string) => `已讀入「${name}」（以 ${encoding} 解讀）`,
    fileReadError: '無法讀取這個檔案。',
    headerFound: (n: number) => `認得第一列的標題，共 ${n} 列。可以直接修改儲存格。`,
    noHeader: (n: number) =>
      `第一列看起來不是標題，所以每一列都當成資料（${n} 列）。請在每一欄上方選擇要對應的欄位。`,
    gridAria: '要匯入的表格',
    gridHint: '點儲存格就能修改；每一欄上方的選單決定對應到哪個欄位。',
    mapping: (n: number, name: string) => `第 ${n} 欄「${name}」對應的欄位`,
    cell: (row: number, col: number) => `第 ${row} 列第 ${col} 欄`,
    skip: '不匯入',
    dup: '重複',
    deleteRow: (n: number) => `刪除第 ${n} 列`,
    addRow: '新增一列',
    repaste: '改貼其他資料',
    count: (n: number) => `匯入 ${n} 筆`,
    countOverwrite: '（清除所有既有資料）',
    countDup: (n: number) => `／重複 ${n} 筆`,
    previewDupSkip: (n: number) => `／略過重複的 ${n} 筆`,
    previewDupKeep: (n: number) => `／重複的 ${n} 筆照樣新增`,
    textHint:
      '貼上以前發的團報（例如 X 的貼文），或本工具「已通關劇本清單」的文字。好幾篇時，篇與篇之間空兩行以上，或放一行「---」。',
    textPaste: '貼上團報',
    textPlaceholder:
      '新克蘇魯神話TRPG\n「海邊的旅館」\nKP：主持人小林\nPC/PL\n調查員・溫書亭 / 玩家阿德\n調查員・林小滿 / 玩家米可\nEND A 全員生還\n2025/11/8\n#團報 #CoC',
    textParsed: (n: number) => `認出 ${n} 篇。請在下面的預覽確認，匯入後還可以再修改。`,
    textFailed:
      '認不出來。請確認篇與篇之間空兩行以上（或用 --- 分隔），並且寫了系統名稱、用「」括起來的劇本名稱與日期。',
    ccHint:
      '選擇 CCFOLIA 的房間資料（JSON 或房間 ZIP）、聊天紀錄（HTML），或其他平台的文字紀錄，可以一次選好幾個。會從房間名稱推測劇本、從角色與擲骰次數推測 PC、從時間推測日期，轉成試算表格式後再匯入。好幾份聊天紀錄時，每一份當成一場。',
    ccPick: '選擇檔案',
    ccDrop: '把房間資料或聊天紀錄拖到這裡',
    ccFiles: (names: string) => `已選：${names}`,
    ccScenario: '劇本名稱',
    ccScenarioPlaceholder: '從房間名稱或檔名推測',
    ccDate: '日期',
    ccDatePlaceholder: 'YYYY-MM-DD（多個用「, 」分隔）',
    ccDateHint: '有擲骰的日子都會列出來；只是跨過午夜才多出來的日期，請在這裡刪掉。',
    ccSystem: '系統',
    ccSystemPlaceholder: '例：CoC 6版',
    ccRole: '身分',
    ccRolePlaceholder: 'PL／KP／GM／DL',
    ccGm: 'GM／KP',
    ccGmPlaceholder: '多個用「、」分隔',
    ccPl: 'PL（同團玩家）',
    ccPlPlaceholder: '多個用「、」分隔',
    ccSpeakers: '發言者（依擲骰次數由多到少；指定為 PC 的會填進 PC 欄）',
    ccSpeakerRole: (name: string) => `「${name}」的身分`,
    ccRoles: { pc: 'PC', pl: 'PL', kp: 'KP・GM', '': '排除' },
    ccPiece: '棋子',
    ccMessages: (n: number) => `發言 ${n}`,
    ccDice: (n: number) => `擲骰 ${n}`,
    ccFound: (n: number) => `找到 ${n} 位發言者。請確認誰是 PC；身分、GM、PL、日期都可以直接修改。`,
    ccNone: '找不到角色名稱或發言者。請確認選的是房間資料（JSON、ZIP）或聊天紀錄（HTML）。',
    ccToSheet: '轉成試算表格式',
    ccConverted: '已從 CCFOLIA・紀錄轉成試算表格式。確認內容後按「匯入」。',
    ccMulti: (n: number) => `找到 ${n} 份紀錄，已經依場次各轉成一列。確認內容後按「匯入」。`,
    ccMultiNote: (n: number) => `找到 ${n} 份紀錄，已經依場次轉成試算表格式。`,
    jsonHint: '選擇用本工具「匯出 JSON」存下的檔案（舊版的也可以）。',
    jsonPick: '選擇 JSON 檔',
    jsonRows: (name: string, n: number) => `${name}（${n} 列）`,
    jsonError: '讀不到紀錄。請選擇用「匯出 JSON」存下的檔案。',
    preview: '預覽',
    previewAria: '匯入預覽',
    previewMore: (n: number) => `另外還有 ${n} 筆…`,
    target: '匯入方式',
    append: '加在後面',
    overwrite: '覆寫（清除所有既有資料）',
    skipDup: '略過重複',
    skipDupHint: '同一天、同一個劇本視為重複。',
    run: '匯入',
    cancel: '取消',
    done: (n: number) => (n ? `已匯入 ${n} 筆` : '已匯入'),
    noRows: '沒有可以匯入的列。',
    noReports: '沒有可以匯入的團報。',
  },

  sheet: {
    colN: (n: number) => `第 ${n} 欄`,
    fields: {
      date: '日期',
      scenario: '劇本名稱',
      system: '系統',
      role: '身分（PL／KP／GM／DL）',
      roleKp: 'KP 旗標（是 → KP）',
      rolePl: 'PL 旗標（是 → PL）',
      gm: 'GM／KP／DL',
      players: 'PL（同團玩家）',
      pc: 'PC',
      status: '狀態',
      time: '遊玩時間（小時）',
      note: '備註',
      longNote: '長篇感想',
      campaign: '長團',
      hashtag: '主題標籤',
      ending: '結局',
      survival: '生還／撕卡',
      sessionUrl: '跑團紀錄網址',
      scenarioUrl: '劇本網址',
      kansouUrl: '感想網址',
      scenarioCountKey: '劇本計數鍵',
    } satisfies Record<SheetField, string>,
    /** 範本 CSV 的標題（要能被標題辨識認回原欄位） */
    templateHeaders: {
      date: '日期',
      scenario: '劇本名稱',
      system: '系統',
      role: '身分',
      roleKp: 'KP 旗標',
      rolePl: 'PL 旗標',
      gm: 'GM',
      players: 'PL',
      pc: 'PC',
      status: '狀態',
      time: '遊玩時間',
      note: '備註',
      longNote: '長篇感想',
      campaign: '長團',
      hashtag: '主題標籤',
      ending: '結局',
      survival: '生還',
      sessionUrl: '跑團紀錄網址',
      scenarioUrl: '劇本網址',
      kansouUrl: '感想網址',
      scenarioCountKey: '劇本計數鍵',
    } satisfies Record<SheetField, string>,
    templateRows: TEMPLATE_ROWS,
  },

  out: {
    title: '已通關劇本清單',
    description: '把紀錄整理成可以貼到社群的清單。先選類型，需要時再用名字篩選。',
    mode: '輸出類型',
    modes: {
      all: { label: '全部劇本', desc: '以劇本為單位，依日期全部列出。' },
      system: { label: '依系統', desc: '系統 → PL 人數。' },
      role: { label: '依 PL／KP', desc: '通關身分 → 系統 → PL 人數。' },
      sessions: { label: '場次明細', desc: '每一團一行，列出日期、PL 與 PC。' },
    },
    filter: '用名字篩選（選填）',
    filterPlaceholder: '玩家、KP、劇本名稱…',
    clear: '清除',
    output: '輸出結果',
    outputPlaceholder: '還沒有可以輸出的團（範例不列入）。',
    lines: (n: number) => `共 ${n} 行`,
    copied: '已複製清單',
    noMatch: (q: string) => `沒有符合「${q}」的團。`,
    match: (q: string, n: number, m: number) => `符合「${q}」：${n} 團／${m} 部劇本`,
    unset: '未設定',
    noSystem: '未設定系統',
    noDate: '未設定日期',
    roleNames: { PL: 'PL', GM: 'KP / GM', other: '其他' },
    allHead: (n: number, m: number) => `【全部劇本】共 ${n} 部（${m} 團）`,
    systemHead: (system: string, n: number) => `【${system}】共 ${n} 部`,
    roleHead: (role: string, n: number) => `■ 以 ${role} 身分通關（${n} 部）`,
    sessionsHead: (n: number) => `【場次一覽】${n} 團`,
  },

  send: {
    title: '送到團報產生器',
    lead: '會用這一團的紀錄建立團報產生器的輸入資料，之後在新分頁開啟團報產生器，可以在那邊確認、修改後再產生團報。',
    overwrite: '瀏覽器裡還有一筆還沒被團報產生器讀取的資料，這次會覆寫它。',
    items: '送出的內容：劇本、日期、系統、GM／KP、PL／PC、備註與感想、相關網址、主題標籤。',
    confirm: '送出並開啟',
    failedTitle: '無法寫入瀏覽器的儲存空間',
    failedDesc: '請複製下面的資料，到團報產生器那邊貼上讀入。',
    failedData: '交接資料',
    sent: '已送出，正在開啟團報產生器',
  },

  keys: {
    groupEdit: '紀錄',
    groupFile: '匯入與匯出',
    add: '新增一團',
    search: '移到搜尋欄',
    import: '開啟匯入',
    exportJson: '匯出 JSON',
    undo: '復原',
    redo: '重做',
    escape: '關閉側欄、欄位面板',
  },

  toast: {
    exported: (name: string) => `已匯出「${name}」`,
    samplesDeleted: (n: number) => `已刪除 ${n} 筆範例`,
    persistFailed: '無法自動存檔（瀏覽器的儲存空間已滿或被封鎖）。請先匯出 JSON 備份。',
  },
} as const;
