/**
 * 狀態條產生器的介面文字（台灣繁體中文，用詞照 DESIGN.md 第 5 節）。
 */
import type {
  AvatarFit,
  AvatarPos,
  Corner,
  Direction,
  FillKind,
  FrameKind,
  InsideAlign,
  ItemKind,
  ItemSide,
  NameAlign,
  NameLook,
  NameOverflow,
  NamePos,
  PanelTexture,
  Shape,
  SymbolKind,
  TextPos,
  TroughKind,
  ValueMode,
} from './settings';

type Opts<T extends string> = readonly (readonly [T, string])[];

export const S = {
  tabs: {
    layout: '排列',
    avatar: '頭像',
    bar: '條',
    text: '文字',
    name: '名稱',
    effects: '演出',
    deco: '裝飾',
    characters: '角色',
  },
  tabsLabel: '設定分類',

  /* ---- 範本 ---- */
  template: {
    title: '範本',
    pick: '選擇範本',
    apply: '套用',
    replaces:
      '套用後會換掉：形狀、填色、文字、名稱、頭像、先攻、符號、演出、損壞效果、裝飾、排列尺寸，以及每一條的顏色、符號與道具種類。',
    keeps:
      '會保留：條數、隱藏多餘的條、每條的名稱覆寫與危急勾選、測試數值、角色清單、房間網址、檔名。',
    applied: (name: string) => `已套用範本「${name}」（可以按「復原」回到套用前）。`,
    current: (name: string) => `目前以範本「${name}」為基礎。`,
  },

  /* ---- 排列 ---- */
  layout: {
    section: '條的數量與排列',
    count: '條數',
    countHint: '對應 CCFOLIA 角色「狀態」由上而下的第 1、2…條。',
    countUnit: '條',
    hideExtra: '隱藏多餘的條',
    hideExtraHint: 'CCFOLIA 上排在條數之後的狀態整列不顯示。',
    direction: '排列方向',
    columns: '欄數',
    barWidth: '單條寬度',
    barWidthHint: '一條（含文字欄、符號欄）的總寬。',
    barHeight: '條本體高度',
    barGap: '條與條的間距',
    margin: '外側留白',
    marginHint: '四周預留的空白，讓光暈、陰影不會被瀏覽器來源的邊界切掉；也算進來源大小。',
    textSection: '文字的位置',
    textPos: '文字位置',
    insideAlign: '對齊',
    textInset: '文字與條本體邊緣的距離',
    labelWidth: '標籤欄寬',
    valueWidth: '數值欄寬',
    textGap: '文字與條本體的間距',
  },
  direction: [
    ['vertical', '直向'],
    ['horizontal', '橫向'],
    ['grid', '多欄'],
  ] as Opts<Direction>,
  textPos: [
    ['inside', '壓在條上'],
    ['top', '上方一行'],
    ['bottom', '下方一行'],
    ['three', '三欄'],
    ['two', '兩欄'],
  ] as Opts<TextPos>,
  textPosHint: {
    inside: '標籤與數值直接壓在條本體上。',
    top: '標籤與數值在條本體上方另起一行。',
    bottom: '標籤與數值在條本體下方另起一行。',
    three: '標籤欄｜條本體｜數值欄，三欄並排。',
    two: '標籤欄｜條本體，數值壓在條本體內靠右。',
  } as Record<TextPos, string>,
  insideAlign: [
    ['split', '左右分開'],
    ['center', '數值置中'],
    ['value', '只顯示數值'],
  ] as Opts<InsideAlign>,

  /* ---- 頭像 ---- */
  avatar: {
    section: '頭像',
    show: '顯示頭像',
    showHint: '顯示 CCFOLIA 的棋子圖片。關閉時頭像與先攻都不顯示。',
    pos: '位置',
    width: '寬',
    height: '高',
    fit: '圖片裁切',
    radius: '圓角',
    borderWidth: '外框粗細',
    borderColor: '外框顏色',
    borderUseChar: '外框改用角色顏色',
    background: '頭像背景',
    backgroundHint: '圖片透明處或「完整收進」時露出來的底色。',
    gap: '頭像與條的距離',
    iniSection: '先攻值',
    ini: '顯示先攻值',
    iniHint: '在頭像的一角顯示先攻值；先攻為 0 時 CCFOLIA 會自動隱藏。',
    iniCorner: '位置',
    iniSize: '大小',
    iniColor: '文字顏色',
    iniBackground: '底色',
  },
  avatarPos: [
    ['left', '左邊'],
    ['right', '右邊'],
    ['top', '上方'],
  ] as Opts<AvatarPos>,
  avatarFit: [
    ['top', '保留上緣'],
    ['center', '置中裁切'],
    ['contain', '完整收進'],
  ] as Opts<AvatarFit>,
  corner: [
    ['tl', '左上'],
    ['tr', '右上'],
    ['bl', '左下'],
    ['br', '右下'],
  ] as Opts<Corner>,

  /* ---- 條 ---- */
  bar: {
    shapeSection: '形狀',
    shape: '形狀',
    radius: '圓角半徑',
    cut: '切角大小',
    skew: '傾斜量',
    borderWidth: '外框粗細',
    borderHint: '沿著輪廓內側畫，不會讓條變大。',
    borderColor: '外框顏色',
    borderDouble: '雙線外框',
    fillSection: '填色',
    trough: '底槽',
    troughHint: '填充後面、代表已消耗部分的底。',
    troughColor: '底槽顏色',
    troughMix: '混色比例',
    fill: '填色方式',
    stripeFlow: '斜紋流動',
    segments: '分段',
    segmentsHint: '把條本體切成等寬的格子；0 或 1 表示不分段。',
    segmentGap: '格子間的空隙',
    speed: '增減速度',
    speedHint: '數值改變時填充伸縮的時間；0 表示瞬間跳到新長度。',
    shadow: '條的陰影',
    barsSection: '每一條',
    barsHint: '第 1 條對應 CCFOLIA 角色的第 1 個狀態，依此類推。',
    barN: (n: number) => `第 ${n} 條`,
    label: '名稱覆寫',
    labelHint: '填了就取代 CCFOLIA 的狀態名稱（例如把 SAN 顯示成「理智」）。',
    color1: '顏色 1',
    color2: '顏色 2',
    symbol: '符號',
    item: '道具',
    critical: '套用危急演出',
    symbolSection: '符號',
    symbolsShow: '顯示符號',
    symbolsHint: '在每條最左邊放一個符號（以顏色 1 上色）。開了道具時不顯示。',
    symbolsOffByItems: '已開啟道具，符號不會顯示。',
    symbolSize: '符號大小',
    symbolGap: '符號與條的間距',
  },
  shape: [
    ['round', '圓角矩形'],
    ['pill', '膠囊形'],
    ['slant', '平行四邊形'],
    ['chamfer', '四角切斜角'],
    ['arrow', '箭形'],
    ['notch', '兩角切斜角'],
  ] as Opts<Shape>,
  trough: [
    ['dark', '深色底'],
    ['mix', '混入條色'],
    ['none', '透明'],
  ] as Opts<TroughKind>,
  fill: [
    ['solid', '單色'],
    ['vgrad', '垂直漸層'],
    ['hgrad', '水平漸層'],
    ['gloss', '上下兩段光澤'],
    ['stripe', '斜紋'],
    ['neon', '霓虹'],
  ] as Opts<FillKind>,
  symbols: [
    ['none', '無'],
    ['heart', '愛心'],
    ['star', '星星'],
    ['drop', '水滴'],
    ['bolt', '閃電'],
    ['shield', '盾牌'],
    ['sword', '劍'],
    ['flame', '火焰'],
    ['skull', '骷髏'],
    ['moon', '月亮'],
    ['clover', '幸運草'],
    ['eye', '眼睛'],
    ['gem', '寶石'],
    ['hourglass', '沙漏'],
  ] as Opts<SymbolKind>,
  items: [
    ['none', '無'],
    ['heart', '愛心'],
    ['shield', '盾牌'],
    ['gem', '寶石'],
    ['potion', '藥瓶'],
    ['candle', '蠟燭'],
    ['die', '骰子'],
  ] as Opts<ItemKind>,

  /* ---- 文字 ---- */
  text: {
    fontSection: '字型',
    labelFont: '標籤字型',
    valueFont: '數值字型',
    valueFontHint: '先攻值也用這個字型。',
    weight: '字重',
    weightHint: '標籤與數值共用；字型沒有這個字重時使用最接近的。',
    localWarn: '有用到電腦字型：跑 OBS 的電腦也必須安裝同一套字型。',
    sizeSection: '大小與間距',
    labelSize: '標籤字級',
    currentSize: '目前值字級',
    maxSize: '最大值字級',
    spacing: '字距',
    spacingHint: '以字級的倍數表示。',
    showSection: '顯示',
    showLabel: '顯示標籤',
    valueMode: '數值顯示',
    colorSection: '顏色與外框線',
    color: '文字顏色',
    colorHint: '標籤與目前值的顏色。',
    maxColor: '最大值顏色',
    labelBarColor: '標籤改用條色',
    outline: '文字外框線',
    outlineColor: '外框線顏色',
    outlineWidth: '描邊粗細',
    preview: 'HP 理智 123/456',
  },
  valueMode: [
    ['both', '目前值/最大值'],
    ['current', '只有目前值'],
    ['none', '不顯示'],
  ] as Opts<ValueMode>,
  outline: [
    ['soft', '柔邊陰影'],
    ['stroke', '描邊'],
    ['glow', '發光'],
    ['none', '無'],
  ] as const,
  weights: '字重',

  /* ---- 名稱 ---- */
  name: {
    section: '角色名稱',
    intro:
      'CCFOLIA 的角色狀態頁不會顯示角色名稱，所以名稱是寫進 CSS 的固定文字；每個角色各自一份 CSS（見「角色」分頁）。',
    pos: '名稱位置',
    look: '名稱外觀',
    font: '名稱字型',
    size: '名稱大小',
    color: '文字顏色',
    background: '名稱背景',
    accent: '強調色',
    accentHint: '底線、側色條、頁籤、徽章的顏色。預覽「範例」時也拿來代替角色顏色。',
    accentUseChar: '強調色改用角色顏色',
    align: '對齊',
    overflow: '名稱太長時',
    vertical: '直書',
    verticalWrap: '過長時依條群高度換行',
    gap: '名稱與條的距離',
    avatarOff: '頭像沒有開啟，名稱不會顯示。',
    preview: '白鴉',
  },
  namePos: [
    ['top', '整體最上方'],
    ['group', '條群上方'],
    ['bottom', '整體最下方'],
    ['left', '整體左側'],
    ['avatar', '壓在頭像底部'],
    ['none', '不顯示'],
  ] as Opts<NamePos>,
  nameLook: [
    ['plate', '底板'],
    ['text', '只有文字'],
    ['underline', '底線'],
    ['side', '側色條'],
    ['tab', '頁籤'],
    ['badge', '徽章'],
  ] as Opts<NameLook>,
  nameAlign: [
    ['left', '靠左'],
    ['center', '置中'],
    ['right', '靠右'],
  ] as Opts<NameAlign>,
  nameOverflow: [
    ['ellipsis', '省略'],
    ['wrap', '換行'],
    ['grow', '隨長度變寬'],
  ] as Opts<NameOverflow>,

  /* ---- 演出 ---- */
  effects: {
    redSection: 'CCFOLIA 紅字',
    red: '紅字顏色',
    redHint: 'CCFOLIA 在目前值 ≤ 最大值 80% 時把目前值標成紅字。關閉時目前值永遠用一般文字顏色。',
    redOn: '使用紅字',
    redColor: '紅字顏色',
    redBlink: '閃爍',
    critSection: '危急',
    critOn: '危急演出',
    critHint: '剩餘比例低於門檻（不含等於）、而且在「條」分頁勾了「套用危急演出」的條才會有。',
    threshold: '門檻',
    thresholdText: (v: number) => `${v}% 以下`,
    critColor: '危急顏色',
    pulse: '脈動發光',
    blink: '填充閃爍',
    shake: '震動',
    barColor: '條變色',
    valueColor: '數值變色',
    zeroSection: '歸零',
    zeroOn: '歸零演出',
    zeroHint: '只在剩餘比例剛好 0% 時。歸零也算低於危急門檻，危急演出會同時作用。',
    gray: '變灰',
    zeroBlink: '文字閃爍',
    damageSection: '損壞',
    cracks: '裂痕',
    cracksHint: '低於 75%、50%、25% 各多一處裂痕，0% 時整條碎裂變暗。',
    crackColor: '裂痕顏色',
    crackOpacity: '裂痕濃度',
    items: '道具',
    itemsHint:
      '在每條旁邊排一列小道具，隨剩餘比例由右而左逐個損壞。數量與最大值相同時，每少 1 點壞掉 1 個。',
    itemCount: '數量',
    itemSize: '大小',
    itemGap: '道具間距',
    itemGapHint: '可以是負的（互相重疊）。',
    itemSide: '放在條的',
    itemDistance: '與條的距離',
    itemKinds: '每條的道具',
    flash: '損壞瞬間發光',
    flashHint: '跨進另一個損壞階段的瞬間閃一下（數值回升時也會閃）。',
    obsNote:
      '危急、歸零、裂痕、道具需要 OBS 31 以上；較舊的 OBS 只是這些演出不會動，其他照常顯示。',
  },
  itemSide: [
    ['left', '左邊'],
    ['right', '右邊'],
  ] as Opts<ItemSide>,

  /* ---- 裝飾 ---- */
  deco: {
    panel: '背景面板',
    panelHint: '在整體（名稱、頭像、條群）後面鋪一塊面板。',
    panelColor: '面板顏色',
    panelRadius: '圓角',
    panelPadding: '內距',
    panelBorder: '外框粗細',
    panelBorderColor: '外框顏色',
    panelBorderOpacity: '外框濃度',
    strip: '左側加一道角色顏色的線',
    texture: '質感',
    frame: '整體外框',
    frameHint: '圍住整體的框，不改變內容位置；外框越大，來源大小也越大。',
    frameKind: '線條種類',
    frameWidth: '粗細',
    frameUseChar: '改用角色顏色',
    frameColor: '顏色',
    frameOpacity: '濃度',
    frameGap: '與內容的距離',
    frameGapHint: '負的表示往內縮。',
    frameRadius: '圓角',
    frameCorner: '四角長度',
    gloss: '光澤',
    glossHint: '條本體上半部一層由上往下漸淡的白色光澤。',
    glow: '外圈光暈',
    glowHint: '每條本體外圍以顏色 1 發出的光暈。',
    spread: '擴散',
    lead: '前端光線',
    leadHint: '填充右端（剩餘量的前緣）一道細白亮線。',
    sweep: '流動光線',
    sweepHint: '一道斜的白色光帶週期性地由左向右掃過填充。',
    interval: '間隔',
    scanlines: '掃描線',
    scanlinesHint: '條本體上疊等距的深色橫線。',
    period: '間隔',
    ticks: '刻度',
    ticksHint: '條本體下緣等距的細直線。',
    tickCount: '分割數',
    grain: '顆粒',
    grainHint: '條本體上疊細微的暗色雜訊。',
    brackets: '角落括號',
    bracketsHint: '每一條（整列）四角的 L 形括號。',
    length: '長度',
    width: '粗細',
    bracketGap: '與條的距離',
    strength: '強度',
    density: '濃度',
    color: '顏色',
  },
  frameKind: [
    ['single', '單線'],
    ['double', '雙線'],
    ['dashed', '虛線'],
    ['glow', '發光線'],
    ['corners', '只畫四角'],
    ['thin', '細框加四角'],
  ] as Opts<FrameKind>,
  texture: [
    ['none', '無'],
    ['paper', '舊紙'],
    ['grain', '顆粒'],
  ] as Opts<PanelTexture>,

  /* ---- 角色 ---- */
  chars: {
    roomSection: '房間',
    room: '房間網址',
    roomPlaceholder: 'https://ccfolia.com/rooms/…（也可以只貼房間 ID）',
    roomHint: '貼上 CCFOLIA 房間的網址；角色的瀏覽器來源網址會用這個房間。',
    listTitle: '角色',
    listLabel: '角色清單',
    add: '新增角色',
    empty: '還沒有角色。按「新增角色」，填好名稱、顏色與角色 ID，就能各自複製網址與 CSS。',
    name: '名稱',
    unnamed: '未命名',
    color: '角色顏色',
    ref: '角色 ID',
    refPlaceholder: '角色 ID 或棋子的網址',
    refHint: '在盤面的棋子上按右鍵 →「Copy Id (for dev)」取得；也可以直接貼棋子的網址。',
    hintId: '請填角色 ID（或貼棋子的網址）。',
    hintRoom: '請填房間網址（上方的房間網址欄，或在這裡貼含房間的完整網址）。',
    hintName: '名稱是空白的，CSS 不會顯示名稱。',
    copyUrl: '複製網址',
    copyCss: '複製 CSS',
    preview: '預覽',
    previewing: '預覽中',
    urlCopied: (name: string) => `已複製「${name}」的瀏覽器來源網址。`,
    urlMissing: '缺少房間或角色 ID，無法組出網址。',
    copyFailed: '無法自動複製，請從「查看 CSS」手動選取後按 Ctrl＋C。',
    urlCopyFailed: '無法自動複製網址。',
  },

  /* ---- 預覽與測試 ---- */
  preview: {
    target: '預覽對象',
    example: '範例',
    exampleNote: '名稱最多 10 個字',
    frameLabel: '狀態條預覽',
    testsSection: '測試數值',
    testsHint: '只影響預覽，不會寫進 CSS。',
    initiative: '先攻值',
    showExtras: '預覽時多放兩個狀態',
    showExtrasHint: '用來看「隱藏多餘的條」的效果。',
    extraTag: '（多餘的條）',
    avatar: '換預覽頭像',
    avatarReset: '換回範例頭像',
    avatarNote: '換掉的預覽頭像只在這次開頁期間有效，不會儲存，也不會寫進 CSS。',
    avatarLoaded: (name: string) => `已換上預覽頭像「${name}」（不會儲存）。`,
  },

  /* ---- 匯出 ---- */
  export: {
    section: 'CSS',
    fileName: '檔名',
    fileNameHint: '儲存 CSS 與專案檔時使用；預覽角色時 CSS 檔名會加上角色名。',
    url: '瀏覽器來源網址',
    urlMissingExample:
      '目前預覽的是範例：CSS 開頭會寫範例網址。到「角色」分頁新增角色就能得到真正的網址。',
    urlMissing: '這個角色缺少房間或角色 ID。',
    copied: (who: string, w: number, h: number) =>
      `已複製${who}的 CSS，請貼到寬 ${w} × 高 ${h} 的瀏覽器來源。`,
    saved: (name: string) => `已儲存「${name}」。`,
    exampleWho: '範例',
    charWho: (name: string) => `「${name || '未命名'}」`,
  },

  /* ---- 狀態與外框 ---- */
  status: {
    ready: '就緒。改設定會立即反映在預覽；設定會自動儲存在這個瀏覽器。',
    opened: (name: string) => `已開啟專案檔「${name}」。`,
    reset: '已全部重來。',
  },
  undo: '復原（Ctrl＋Z）',
  redo: '重做（Ctrl＋Shift＋Z）',
  resetAll: '全部重來',
  resetConfirm: {
    title: '全部重來？',
    description:
      '所有設定、角色清單與測試數值都會回到一開始的樣子，換過的預覽頭像也會還原。這個動作無法復原。',
  },
  projectName: '狀態條',
  shortcuts: {
    undo: '復原',
    redo: '重做',
    group: '編輯',
  },
} as const;

export const OUTLINE_OPTIONS = S.outline;
