/** 魔法陣製作器的介面文字（台灣繁體中文；原作 MIT，意思沿用、文字改寫） */

export const S = {
  usage: [
    '先在「畫布」分頁設定對稱尺（份數、中心、左右鏡射）與吸附；也可以從快速範本開始。',
    '用鋼筆畫曲線與轉角：點一下產生轉角點，按住拖曳拉出曲線把手；點回起點或按 Enter 完成。手繪、直線、圓形、多邊形、星形直接拖曳。',
    '只要編輯原始的那一筆：對稱的複本會自動跟著更新；個別元素也可以在「形狀」分頁關掉對稱。',
    '文字工具放好文字後，在「形狀」分頁挑盧恩字母，或把拉丁字母近似轉換成盧恩。',
    '在「元素」分頁按住 Shift 或 Ctrl（⌘）點選多個元素，對齊畫布、選取範圍或基準元素，也能沿對稱線與扇形分佈。',
    '在「動態」分頁選出場效果，再到下方時間軸拖曳長條或兩端，調整開始時間與持續時間。',
    '在匯出區選格式與倍率：PNG、WebP（目前畫面），或 GIF、APNG、動態 WebP（整段動畫）。',
  ],
  about: '所有處理都在這台電腦的瀏覽器裡進行，作品不會上傳。',

  tools: {
    label: '繪圖工具',
    select: { name: '選取', hint: '拖曳元素即可移動。按住 Shift 或 Ctrl（⌘）點擊可選取多個元素。' },
    pen: { name: '貝茲鋼筆', hint: '點擊產生轉角點，點擊後拖曳產生曲線。按 Enter 完成路徑。' },
    freehand: { name: '手繪筆畫', hint: '用滑鼠或觸控筆繪製，會自動整理成曲線控制點。' },
    line: { name: '直線', hint: '從起點拖曳到終點。' },
    circle: { name: '圓形', hint: '從中心向外拖曳。按住 Alt 則以起點為邊緣。' },
    polygon: { name: '多邊形', hint: '從中心拖曳出半徑。' },
    star: { name: '星形', hint: '從中心拖曳出半徑。' },
    text: { name: '文字・盧恩', hint: '在畫布上點擊後，於「形狀」分頁編輯文字。' },
    pan: { name: '平移畫面', hint: '拖曳可移動畫面，滾輪可縮放。' },
  },

  toolbar: {
    undo: '復原',
    redo: '重做',
    zoomIn: '放大',
    zoomOut: '縮小',
    zoomFit: '點一下符合畫面',
    fit: '符合畫面',
    guides: '顯示輔助線',
    view: '檢視',
  },

  toolOpt: {
    label: '工具選項',
    finish: '完成路徑',
    close: '閉合並完成',
    penNote: '拖曳控制點＝曲線',
    simplify: '簡化強度',
    polygonSides: '頂點數',
    starPoints: '星形頂點',
    starInner: '內半徑比例',
    copyStyle: '複製樣式',
    pasteStyle: '貼上樣式',
    circleNote: 'Alt＋拖曳：以起點與終點為對角線的橢圓',
    fontPreset: '預設字型',
  },

  canvas: {
    label: '魔法陣編輯畫面',
    emptyTitle: '目前是空白畫布',
    emptyHint: '用上方的工具開始繪製，或從「畫布」分頁載入範本。',
    snap: {
      grid: '格線',
      centerX: '中心 X',
      centerY: '中心 Y',
      center: '中心',
      guide: '對稱線',
      angle: (deg: number) => `${deg}°`,
    },
  },

  status: {
    label: '狀態',
    ready: '準備就緒 · 可從鋼筆或手繪筆畫開始。',
    restored: '已還原自動儲存的專案。',
    none: '未選取',
    multi: (n: number, key: string) => `已選取 ${n} 個 · 基準：${key}`,
    path: (name: string, n: number) => `${name} · ${n} 點`,
    circle: (name: string) => `${name} · 圓形`,
    text: (name: string) => `${name} · 文字`,
    cursor: (x: number, y: number) => `X ${x} · Y ${y}`,
    docName: (name: string) => `作品：${name}`,
  },

  tabs: {
    label: '設定分類',
    layers: '元素',
    style: '樣式',
    geometry: '形狀',
    motion: '動態',
    canvas: '畫布',
  },

  layers: {
    heading: '元素與筆畫順序',
    sub: '越上方的元素顯示在越前面。拖曳左邊的把手可以調整順序。',
    listLabel: '元素清單',
    empty: '目前還沒有任何元素。',
    duplicate: '再製',
    remove: '刪除',
    selectAria: (name: string) => `選取「${name}」`,
    show: (name: string) => `顯示「${name}」`,
    hide: (name: string) => `隱藏「${name}」`,
    lock: (name: string) => `鎖定「${name}」`,
    unlock: (name: string) => `解除鎖定「${name}」`,
    keyPrefix: '基準元素',
    symPrefix: (n: number) => `${n} 重對稱`,
    moveUp: '基準元素上移',
    moveDown: '基準元素下移',
    moveHint: '只移動基準元素（多選時最後選取的那一個）。',
    swatch: (stroke: string, glow: string) => `線條 ${stroke}、發光 ${glow}`,
  },

  align: {
    title: '對齊 · 等距分佈',
    countNone: '已選取 0 個',
    count: (n: number) => `已選取 ${n} 個`,
    countMovable: (n: number, m: number) => `已選取 ${n} 個 · 可移動 ${m} 個`,
    selectAll: '全選可編輯',
    selectAllHint: '選取所有顯示中、未鎖定的元素',
    clear: '取消選取',
    reference: '對齊基準',
    ref: { canvas: '畫布', selection: '選取範圍', key: '基準元素（最後選取）' },
    refName: { canvas: '以畫布為基準', selection: '以選取範圍為基準' },
    refKey: (name: string) => `以基準元素「${name}」為基準`,
    boundsGroup: '邊界與置中對齊',
    distributeTitle: '選取範圍等距',
    distributeGroup: '等距分佈',
    symmetryTitle: '以對稱尺為基準',
    symmetryGroup: '對稱尺對齊',
    actions: {
      'align-left': { short: '靠左', label: '靠左對齊' },
      'align-center-x': { short: '水平置中', label: '水平置中對齊' },
      'align-right': { short: '靠右', label: '靠右對齊' },
      'align-top': { short: '靠上', label: '靠上對齊' },
      'align-center-y': { short: '垂直置中', label: '垂直置中對齊' },
      'align-bottom': { short: '靠下', label: '靠下對齊' },
      'distribute-x': { short: '水平間距', label: '水平等距分佈' },
      'distribute-y': { short: '垂直間距', label: '垂直等距分佈' },
      'symmetry-center': { short: '對稱中心', label: '對齊到對稱中心' },
      'symmetry-guide': { short: '最近對稱線', label: '對齊到最近的對稱線' },
      'symmetry-sector': { short: '扇形中央', label: '對齊到對稱扇形中央' },
      'symmetry-radius': { short: '基準半徑', label: '對齊到基準元素的半徑' },
      'symmetry-angle-space': { short: '角度等距', label: '角度等距分佈' },
      'symmetry-radius-space': { short: '半徑等距', label: '半徑等距分佈' },
    },
    helpDefault: '按住 Shift 或 Ctrl（⌘）點選可以選取多個元素。鎖定的元素不會移動。',
    helpMirror: '開啟左右鏡射時，扇形中央與角度等距無法使用。',
    helpKey: (name: string) => `基準元素：${name} · 對齊只移動原始元素，鎖定的元素會略過。`,
    mirrorDisabled: '開啟左右鏡射時複本可能重疊，所以無法使用。',
    done: (n: number, label: string) => `已將 ${n} 個元素${label}。`,
    doneLocked: (n: number, label: string, locked: number) =>
      `已將 ${n} 個元素${label}，${locked} 個鎖定的元素保持不動。`,
    already: (label: string) => `選取的元素已經是「${label}」的狀態。`,
    nothing: '沒有可移動的選取元素。',
    needKey: '請先選取基準元素。',
    noTargets: '以這個基準沒有可移動的元素。',
    needThree: '等距分佈需要 3 個以上未鎖定的元素。',
    needThreeAngle: '角度等距分佈需要 3 個以上未鎖定的元素。',
    needThreeRadius: '半徑等距分佈需要 3 個以上未鎖定的元素。',
    needSymmetry: '請先在「畫布」分頁開啟對稱尺。',
    mirrorBlocked: '開啟左右鏡射時，為了避免複本重疊，無法使用這種分佈。',
  },

  style: {
    placeholder: '請選取要調整樣式的元素。',
    basic: '線條與填色',
    stroke: '線條顏色',
    strokeWidth: '線條粗細',
    opacity: '不透明度',
    fillEnabled: '填滿',
    fill: '填色',
    lineCap: '線端',
    lineJoin: '轉角',
    cap: { round: '圓頭', butt: '平頭', square: '方頭' },
    join: { round: '圓頭', miter: '尖角', bevel: '斜角' },
    dash: '虛線',
    dashHint: '數字以逗號或空白分隔，例如「20, 10」；空白＝實線。',
    dashPlaceholder: '例如：20, 10',
    blend: '混合',
    blends: {
      'source-over': '一般',
      screen: '濾色',
      lighter: '加亮發光',
      multiply: '色彩增值',
      overlay: '覆蓋',
    },
    shadow: '陰影',
    shadowColor: '陰影顏色',
    shadowBlur: '模糊',
    shadowX: '水平位移',
    shadowY: '垂直位移',
    glow: '發光效果',
    glowEnabled: '發光',
    glowColor: '發光顏色',
    glowBlur: '發光範圍',
    glowStrength: '發光強度',
    presets: '樣式預設',
    preset: {
      'arcane-blue': '幽藍魔力',
      'holy-gold': '聖光金輝',
      'blood-red': '赤紅咒術',
      ink: '墨線簽名',
    },
  },

  geo: {
    placeholder: '請選取要編輯形狀的元素。',
    info: '元素資訊',
    name: '名稱',
    symmetry: '套用旋轉對稱',
    visible: '顯示',
    locked: '鎖定',
    path: '路徑',
    closed: '閉合路徑',
    smooth: '選取點平滑化',
    corner: '選取點轉角化',
    reverse: '反轉筆畫方向',
    pathHint: '鋼筆拖曳控制點會產生左右兩側的曲線把手，之後可以用選取工具再調整把手。',
    circle: '圓形',
    cx: '中心 X',
    cy: '中心 Y',
    rx: '半徑 X',
    ry: '半徑 Y',
    text: '文字・盧恩',
    content: '內容',
    fontSize: '大小',
    fontFamily: '字型',
    fontHint: 'CSS 字型名稱，例如 serif、sans-serif、"Noto Serif TC"。',
    textAlign: '對齊',
    aligns: { left: '靠左', center: '置中', right: '靠右' },
    nudge: '微調位移',
    nudgeHint: '按住 Shift 再點，每次移動 10 px。◎＝移到對稱中心。',
    nudgeUp: '往上移',
    nudgeDown: '往下移',
    nudgeLeft: '往左移',
    nudgeRight: '往右移',
    nudgeCenter: '移到對稱中心',
  },

  rune: {
    title: '盧恩字盤 · 拉丁字母轉換',
    system: '文字系統',
    sets: {
      elder: { label: '古弗薩克', option: '古弗薩克 24 字' },
      younger: { label: '新弗薩克', option: '新弗薩克 16 字' },
      futhorc: { label: '盎格魯撒克遜弗托克', option: '盎格魯撒克遜弗托克 29 字' },
    },
    search: '搜尋',
    searchPlaceholder: '盧恩名稱・讀音',
    paletteLabel: '盧恩字母',
    paletteStatus: (set: string, n: number) => `${set} · 顯示 ${n} 字`,
    empty: '找不到相符的盧恩字母。',
    runeTitle: (name: string, reading: string, sound: string) => `${name} · ${reading} · ${sound}`,
    runeAria: (name: string, reading: string, sound: string, glyph: string) =>
      `${name}，${reading}，${sound}，${glyph}`,
    converter: '拉丁字母近似轉換',
    converterPlaceholder: '例如：futhark, thing',
    result: '轉換結果',
    replace: '取代內容',
    insert: '插入游標處',
    converterHint: '依所選的文字系統把拉丁拼寫近似轉換成盧恩，不是歷史語言的正式拼法。',
  },

  motion: {
    placeholder: '請選取要設定動態的元素。',
    enter: '出現方式',
    mode: '效果',
    modes: {
      none: '一直顯示',
      draw: '依筆順繪製',
      drawGlow: '邊繪製邊發光',
      fadeIn: '淡入',
      fadeOut: '淡出',
      centerSpread: '由中心擴散',
      scaleIn: '由中心放大',
      spinIn: '旋轉出現',
      pulse: '脈動發光',
    },
    short: {
      none: '一直顯示',
      draw: '筆畫繪製',
      drawGlow: '繪製發光',
      fadeIn: '淡入',
      fadeOut: '淡出',
      centerSpread: '中心擴散',
      scaleIn: '中心放大',
      spinIn: '旋轉出現',
      pulse: '脈動發光',
    },
    start: '開始',
    duration: '持續',
    easing: '加速曲線',
    easings: {
      linear: '等速',
      easeOut: '快進慢出',
      easeIn: '慢進快出',
      easeInOut: '平滑進出',
      overshoot: '彈跳',
    },
    direction: '筆畫方向',
    directions: { forward: '繪製方向', reverse: '反方向' },
    copies: '對稱複本動態',
    stagger: '複本間延遲',
    order: '複本順序',
    orders: { clockwise: '順時針', counter: '逆時針', alternate: '兩側交錯', random: '固定隨機' },
    hold: '效果結束後保持顯示',
    presets: '動態預設',
    preset: { trace: '繪製魔法陣', burst: '中心爆發', summon: '召喚旋轉', vanish: '消散' },
  },

  doc: {
    canvas: '畫布',
    name: '作品名稱',
    width: '寬度',
    height: '高度',
    transparent: '透明背景',
    background: '背景色',
    symmetry: '對稱尺',
    symmetryToggle: '使用對稱尺',
    count: '對稱數量',
    offset: '旋轉起始角',
    mirror: '奇數複本左右鏡射',
    centerX: '中心 X',
    centerY: '中心 Y',
    centerButton: '移到畫布中央',
    snap: '吸附',
    snapToggle: '使用吸附',
    snapGrid: '吸附格線',
    gridSize: '格線間距',
    snapCenter: '吸附中心軸',
    snapRadial: '吸附對稱線',
    snapAngles: '吸附角度',
    angleStep: '角度單位',
    threshold: '感應距離',
    templates: '快速範本',
  },

  templates: {
    classic: { name: '古典魔法陣', description: '同心圓・星形・盧恩' },
    rune: { name: '盧恩輪', description: '以文字為中心的放射狀' },
    sigil: { name: '簽名・印記', description: '透明背景自由筆畫' },
    blank: { name: '空白作品', description: '保留畫布設定，只清空元素' },
    label: '快速範本',
  },

  timeline: {
    label: '時間軸',
    stop: '回到開頭',
    duration: '長度',
    fps: 'FPS',
    autoLayers: '依圖層排序',
    autoLayersHint: '依圖層順序排列開始時間',
    autoCenter: '中心→外圍',
    autoCenterHint: '從靠近中心的元素開始排列開始時間',
    reverse: '反轉順序',
    collapse: '收合動態長條',
    expand: '展開動態長條',
    names: '元素',
    empty: '新增元素後就會出現動態長條。',
    bar: (start: number, dur: number) => `第 ${start} 秒開始，持續 ${dur} 秒`,
    readout: (t: string, d: string) => `${t} / ${d} 秒`,
    tracks: '動態長條',
    track: (name: string) => `「${name}」的動態時間`,
    barLabel: (name: string, mode: string) => `${name}：${mode}`,
  },

  export: {
    formats: {
      png: { label: 'PNG', description: '目前畫面 · 無損' },
      'webp-still': { label: '靜態 WebP', description: '目前畫面 · 壓縮' },
      gif: { label: 'GIF', description: '通用動畫；最多 256 色，半透明會變成全透明或不透明。' },
      apng: { label: 'APNG', description: '高品質透明動態，CCFOLIA 可直接使用（副檔名 .png）。' },
      webp: { label: '動態 WebP', description: '高效率透明動態；Safari 無法匯出。' },
    },
    webpUnsupported: '這個瀏覽器無法匯出 WebP（Safari 不支援），請改用 PNG、GIF 或 APNG。',
    transparent: '以透明背景儲存',
    transparentHint: '與「畫布」分頁的透明背景是同一個設定。',
    quality: 'WebP 品質',
    qualityHint: '100＝無損。',
    loopHint: '與時間軸的「循環」是同一個設定。',
    gifNote: 'GIF 最多 256 色，半透明像素會變成單一透明色；APNG 與 WebP 能保留平滑的透明度。',
    stillNote: (t: string) => `匯出播放頭所在的畫面（第 ${t} 秒）。`,
    tooManyFrames: (n: number) =>
      `目前是 ${n} 格。為了瀏覽器的穩定，請把影格數降到 900 以下（縮短長度或降低 FPS）。`,
    tooHeavy: '處理量太大，請降低倍率、縮短長度或降低 FPS。',
    noWebp: '這個瀏覽器不能產生 WebP 圖片，請改用 PNG。',
    step: {
      frames: (fmt: string) => `算繪並編碼 ${fmt} 影格`,
      still: '編碼目前影格',
    },
    resultTime: '畫面時間',
    resultFrames: '影格',
  },

  project: {
    newLabel: '新的空白魔法陣…',
    newTitle: '建立新的空白魔法陣？',
    newDescription: '目前的作品會換成空白的新作品（可以用「復原」回來）。',
    newConfirm: '建立',
    legacyOpen: '開啟舊版專案檔（.arcana.json）…',
    invalid: '專案資料的格式不正確。',
    newer: '這個專案檔是較新版本的工具存的，請更新頁面後再開啟。',
  },

  msg: {
    undone: '已復原上一步。',
    redone: '已重做上一步。',
    newDocument: '已建立新文件。',
    projectSaved: '已儲存專案 JSON。',
    projectSavedStatus: '已儲存專案檔案。',
    projectLoaded: '已載入專案。',
    loadFailed: (reason: string) => `載入失敗：${reason}`,
    autosaveRestored: '已還原自動儲存的內容。',
    legacyImported: '已帶入舊版自動儲存的作品。',
    templateClassic: '已載入古典魔法陣範本。',
    templateRune: '已載入盧恩輪範本。',
    templateSigil: '已切換到簽名・印記模式。',
    templateBlank: '已建立清空元素的新畫布。',
    noSelectable: '沒有可見且未鎖定的元素。',
    selectedAll: (n: number) => `已選取 ${n} 個可編輯的元素。`,
    pathAdded: '已新增路徑。',
    drawCancelled: '已取消繪製。',
    deletedOne: (name: string) => `已刪除元素「${name}」。`,
    deletedMany: (n: number) => `已刪除 ${n} 個元素。`,
    duplicatedOne: '已再製元素。',
    duplicatedMany: (n: number) => `已再製 ${n} 個元素。`,
    selectTextFirst: '請先選取文字・盧恩元素。',
    runeInserted: '已插入盧恩文字。',
    runeReplaced: '已用轉換後的盧恩取代內容。',
    enterLatin: '請輸入要轉換的拉丁字母。',
    sequencedLayers: '已依圖層順序排列。',
    sequencedCenter: '已依中心到外圍的順序排列。',
    sequenceReversed: '已反轉動態開始順序。',
    selectNodeFirst: '請先選取路徑上的控制點。',
    pathReversed: '已反轉筆畫的記錄方向。',
    stylePreset: '已套用樣式預設。',
    motionPreset: '已套用動態預設。',
    nothingToMove: '沒有可移動的選取元素，請檢查是否已鎖定。',
    selectStyleSource: '請選取要複製樣式的元素。',
    styleCopied: '已複製樣式。',
    stylePasted: '已貼上樣式。',
    exportDone: '檔案已建立。',
    exportCancelled: '已取消匯出。',
  },

  names: {
    path: '路徑',
    circle: '圓形',
    ellipse: '橢圓',
    text: '盧恩文字',
    textShort: '文字',
    line: '直線',
    polygon: (n: number) => `${n} 邊形`,
    star: (n: number) => `${n} 角星`,
    closedShape: '封閉圖樣',
    stroke: '魔法筆畫',
    freehand: '手繪筆畫',
    symFreehand: '對稱手繪筆畫',
    copy: (name: string) => `${name} 複本`,
    unnamed: '未命名元素',
    newProject: '新魔法陣',
    loadedProject: '載入的魔法陣',
    classicProject: '古典魔法陣',
    classic: {
      outerRing: '外圈環',
      outerGuide: '外圈輔助線',
      innerRing: '內圈環',
      hexagram: '中央六芒圖樣',
      radialRunes: '放射盧恩裝飾',
      radialGems: '放射寶石點',
      core: '中央核心',
    },
    runeProject: '盧恩輪',
    rune: {
      outerCircle: '外圈圓',
      runeCircle: '盧恩圓',
      pentagon: '五芒結界',
      glyph: '盧恩文字',
      core: '核心',
    },
    sigilProject: '發光簽名',
    sigilStroke: '簽名筆畫',
  },

  keys: {
    tools: '工具',
    edit: '編輯',
    play: '播放',
    file: '檔案',
    playPause: '播放／暫停（按住拖曳＝暫時平移）',
    finishPath: '完成鋼筆路徑',
    cancel: '取消繪製／取消選取',
    remove: '刪除選取的元素',
    undo: '復原',
    redo: '重做',
    save: '儲存專案檔',
    duplicate: '再製',
    selectAll: '全選可編輯的元素',
    nudge: '微調位移 1 px',
    nudge10: '微調位移 10 px',
    tool: (name: string) => name,
  },
} as const;

export type Strings = typeof S;
