/** 首頁卡片的圖示（工具 id → lucide 圖示）；沒有列的用扳手 */
import {
  Blend,
  BookOpen,
  Box,
  ChartNoAxesColumnIncreasing,
  ChartScatter,
  CircleUser,
  Clapperboard,
  ClipboardList,
  Crop,
  Dices,
  Eraser,
  FileImage,
  Film,
  FlaskConical,
  FolderArchive,
  Frame,
  Gauge,
  Grid3x3,
  HeartHandshake,
  Highlighter,
  House,
  IdCard,
  Images,
  Keyboard,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  ListChecks,
  Loader,
  type LucideIcon,
  Mail,
  Map as MapIcon,
  MapPinned,
  MessageCircleMore,
  MessageSquareText,
  MessagesSquare,
  MicVocal,
  Music,
  Newspaper,
  NotebookPen,
  NotebookTabs,
  Orbit,
  Palette,
  Ruler,
  Scaling,
  ScanEye,
  ScanFace,
  ScrollText,
  Smile,
  Sparkles,
  Spline,
  SquareUser,
  Table,
  TextQuote,
  Trophy,
  UserCog,
  Users,
  Waves,
  Wrench,
  Zap,
} from 'lucide-react';

const ICONS: Record<string, LucideIcon> = {
  _gallery: LayoutDashboard,
  /* G1 文字演出 */
  'text-fx': Sparkles,
  typewriter: Keyboard,
  cutin: Zap,
  'text-path': Spline,
  'collage-letter': Mail,
  textbox: Table,
  'discord-color': Highlighter,
  'speech-bubble': MessageCircleMore,
  /* G2 轉場與動態 */
  'scene-transition': Clapperboard,
  'apng-wipe': Blend,
  'bg-motion': Waves,
  'loading-maker': Loader,
  /* G3 立繪工作台 */
  'ccfolia-cropper': Crop,
  'portrait-size': Scaling,
  'bg-remover': Eraser,
  'icon-maker': CircleUser,
  'variant-manager': Layers,
  'height-board': ChartNoAxesColumnIncreasing,
  'color-palette': Palette,
  'emotion-maker': Smile,
  'anime-rig': ScanFace,
  /* G4 OBS 疊加 */
  'status-bar': Gauge,
  'chat-window': MessagesSquare,
  'message-box': MessageSquareText,
  'obs-tachie': SquareUser,
  /* G5 CCFOLIA 資料 */
  'character-editor': IdCard,
  'room-zip': FolderArchive,
  'psd-studio': FileImage,
  'foreground-frame': Frame,
  'log-converter': ScrollText,
  'scenario-cards': LayoutGrid,
  'scenario-text': TextQuote,
  /* G6 劇本與紀錄 */
  'scenario-editor': BookOpen,
  'coc-typesetter': Newspaper,
  'session-log': NotebookPen,
  'session-report': ClipboardList,
  /* G7 介紹圖與宣傳 */
  'pair-maker': HeartHandshake,
  'character-select': Users,
  'magic-circle': Orbit,
  'acrylic-goods': Box,
  'ai-fail': ScanEye,
  'rank-chart': Trophy,
  'char-chart': ChartScatter,
  /* G8 影像與動圖 */
  'video-anim': Film,
  'gif-combiner': Images,
  'music-frame': Music,
  /* G9 CoC 跑團輔助 */
  'coc-dice': Dices,
  'coc-npc': UserCog,
  'house-rules': ListChecks,
  'coc-sheet': NotebookTabs,
  'trpg-lab': FlaskConical,
  /* G10 地圖與網格 */
  battlemap: MapIcon,
  'map-editor': MapPinned,
  'grid-maker': Grid3x3,
  'range-ruler': Ruler,
  'floor-plan': House,
  /* 其他網站 */
  jizura: MicVocal,
};

export function toolIcon(id: string): LucideIcon {
  return ICONS[id] ?? Wrench;
}
