/**
 * 2.5D 動態立繪的介面文字（台灣繁體中文；用詞照 DESIGN.md 第 5 節）。
 * 綁定與 PSD 檢查的訊息在 rigText.ts（Worker 也會用）。
 */
import type {
  AutoKey,
  BackgroundId,
  ExportBackground,
  ParamKey,
  ParamSection,
  PresetId,
} from './params';
import type { PartGroup } from './rigger';

/** 臉部特徵點模型的大小（3,758,596 位元組）：下載卡的說明、按鈕、刪除確認與使用說明都用同一個寫法 */
const MODEL_SIZE = '約 3.6 MB';

export const S = {
  /* ---------- 頁首、讀入 ---------- */
  open: '開啟 PSD',
  undo: '復原',
  redo: '重做',
  noModel: '未讀入模型',
  modelLabel: (name: string) => `模型：${name}`,

  dropTitle: '讓插畫動起來',
  dropLead: '拖進分好部件的 PSD，自動找出眼睛、嘴巴和頭髮，當場動起來。',
  dropHint:
    'RGB／8 位元的 PSD，最大 128 MB。圖層名稱用 face、eyewhite、mouth_open，或「顔・白目・前髪」等日文名稱；資料夾裡的圖層也讀得到。',
  dropPick: '選擇 PSD 檔案',
  dropHelp: '使用說明',
  helpTitle: '2.5D 動態立繪：使用方式',
  dropOverlay: '放開就讀入（PSD 或設定 JSON）',
  cancelLoad: '中止讀取',
  loadReading: (name: string) => `正在讀取 ${name}…`,
  loadDone: (name: string) => `已讀入 ${name}`,
  loadError: (msg: string) => `錯誤：${msg}`,
  loadCancelled: '已中止讀取。',
  errExt: '請選擇副檔名為 .psd 的檔案。',
  errTooLarge: 'PSD 請控制在 128 MB 以下。',
  errWorker: '無法開始解析 PSD（可能是記憶體不足），請縮小 PSD 或重新整理頁面再試一次。',
  /** 解析 PSD 的函式庫丟出的錯誤（英文）：說明加上原文（對等驗證後新增） */
  errParse: (detail: string) => `無法解析這個 PSD，檔案可能已損壞（${detail}）。`,
  errWebgl: '這個瀏覽器無法使用 WebGL，請開啟硬體加速。',
  errGlInit: (msg: string) => `繪圖初始化失敗：${msg}`,
  errViewport: (px: number) => `超過這台裝置能繪製的尺寸（${px} px），請縮小 PSD。`,
  errTexture: (px: number) => `圖像部件超過這台裝置的上限 ${px} px。`,
  errContextLost: '請等繪圖復原後再讀入。',
  glLost: '繪圖暫時停止，正在等待復原。',
  glRestored: '繪圖已復原。',
  glRestoreFailed: '繪圖復原失敗，請重新載入頁面。',
  glMaskDisabled: (msg: string) => `${msg}（已停用瞳孔裁切）`,

  /* ---------- 預覽工具列 ---------- */
  previewLabel: '立繪的預覽',
  overlayTitle: '錨點與部件的範圍',
  pause: '暫停',
  play: '播放',
  paused: '暫停中，可以調整數值並匯出靜止畫面。',
  playing: '播放中。',
  anchorEdit: '編輯錨點',
  anchorHint:
    '拖曳圓點調整基準位置（方向鍵移動 1 px，Shift＋方向鍵移動 10 px）。按 Esc 或 E 結束。',
  anchorEditing: '錨點編輯中：在靜止的姿勢下調整基準點。',
  savePng: '儲存 PNG',
  record: '錄影',
  recordStop: '停止錄影並儲存',
  recBadge: (t: number, total: number) => `● REC ${t.toFixed(1)}／${total} 秒`,
  fps: (n: number) => `${n} fps`,
  checkerNote: '背景的棋盤格不會匯出',
  camPreviewLabel: '攝影機畫面的預覽',
  camPreviewHide: '隱藏攝影機小畫面',
  noFace: '偵測不到臉',

  /* ---------- 設定欄 ---------- */
  searchLabel: '搜尋設定',
  searchPlaceholder: '眼睛、頭髮、嘴巴、圖層…',
  searchEmpty: '沒有符合的設定',
  collapseAll: '全部收合',
  expandAll: '全部展開',

  sections: {
    auto: '自動',
    preset: '表情預設',
    head: '臉部朝向',
    eyes: '眼睛',
    brow: '眉毛',
    mouth: '嘴巴',
    bangs: '瀏海',
    body: '身體與物理',
    anchors: '錨點（基準點）',
    tracking: '攝影機與麥克風',
    export: '匯出',
    save: '儲存與設定',
    background: '背景',
    layers: '圖層',
    info: '模型資訊與診斷',
  } satisfies Record<string, string>,

  auto: {
    idle: '待機動作',
    blink: '自動眨眼',
    rand: '隨機動作',
    talk: '隨機嘴型',
    mouse: '滑鼠追蹤',
    phys: '頭髮物理',
  } satisfies Record<AutoKey, string>,
  autoHints: {
    idle: '頭部與身體輕輕搖擺，頭髮有微風。',
    blink: '每隔幾秒眨一次眼。',
    rand: '每隔幾秒換一個頭部角度與視線。',
    talk: '像在說話一樣開合嘴巴。',
    mouse: '頭部與視線朝向預覽上的滑鼠。',
    phys: '頭髮、耳飾、尾巴跟著動作擺動。',
  } satisfies Record<AutoKey, string>,
  cam: '攝影機追蹤',
  camLoading: '攝影機準備中…',
  camOn: '攝影機追蹤中',
  mic: '麥克風嘴型',
  micLoading: '麥克風準備中…',
  micOn: '麥克風使用中',

  presets: {
    neutral: '一般',
    smile: '笑臉',
    usume: '瞇眼',
    surprise: '驚訝',
    jito: '鄙視眼',
    winkL: '左眼眨眼',
    winkR: '右眼眨眼',
  } satisfies Record<PresetId, string>,
  presetHint: '再按一次同一個按鈕或按鍵就解除；按 0 解除。',

  paramSections: {
    head: '臉部朝向',
    eyes: '眼睛',
    brow: '眉毛',
    mouth: '嘴巴',
    bangs: '瀏海',
    body: '身體與物理',
  } satisfies Record<ParamSection, string>,
  params: {
    angleX: '角度 X',
    angleY: '角度 Y',
    angleZ: '角度 Z',
    eyeOpenL: '左眼張開度',
    eyeOpenR: '右眼張開度',
    eyeX: '視線 X',
    eyeY: '視線 Y',
    irisScale: '瞳孔縮放',
    eyeScaleL: '閉眼縮放 左',
    eyeScaleR: '閉眼縮放 右',
    eyeEase: '閉合難易度',
    eyeCY: '差分 上下',
    eyeCAng: '差分 角度',
    brow: '眉毛（上下）',
    browAngSym: '眉毛角度 對稱',
    browAngL: '眉毛角度 左',
    browAngR: '眉毛角度 右',
    mouthOpen: '張開',
    mouthForm: '形狀（笑）',
    mouthCY: '閉嘴 上下',
    mouthEase: '閉合難易度',
    mouthCAng: '閉嘴 角度',
    mouthScale: '嘴巴縮放',
    fhAmp: '擺動',
    fhSoft: '柔軟度',
    bangL: '區塊 左',
    bangC: '區塊 中央',
    bangR: '區塊 右',
    body: '身體傾斜',
    armY: '手臂高度',
    armPos: '手臂位置修正',
    bust: '胸部晃動',
    bustY: '胸部位置 上下',
    physAmp: '後髮擺動',
    soft: '後髮柔軟度',
    accAmp: '小物擺動',
  } satisfies Record<ParamKey, string>,
  /** 同名的滑桿（兩個「閉合難易度」）在搜尋與螢幕閱讀器裡加上區塊名 */
  paramAria: (section: string, label: string) => `${section}：${label}`,
  resetHint: '在滑桿上按兩下還原成初始值。',

  /* 錨點 */
  anchorsHint: '眼睛、嘴巴、脖子等自動偵測的位置有偏差時，可以在預覽上拖曳修正。',
  anchorReset: '還原成自動偵測的位置',
  anchorResetDone: '已把錨點還原成自動偵測的位置。',
  anchorManual: (n: number) => `已手動調整 ${n} 處`,
  anchorAuto: '全部都是自動偵測的位置',
  anchorNames: {
    face: '臉部中心',
    eyeL: '左眼',
    eyeR: '右眼',
    eyeLClose: '左眼 閉眼位置',
    eyeRClose: '右眼 閉眼位置',
    mouth: '嘴巴',
    neck: '脖子旋轉軸',
    chest: '胸部',
  },
  anchorHandle: (name: string) => `${name}（拖曳或用方向鍵移動）`,

  /* 攝影機與麥克風 */
  trackHint:
    '攝影機追蹤會從臉部特徵點讀取頭部朝向、眨眼、視線、嘴巴、眉毛與笑臉。攝影機畫面只在這個瀏覽器裡處理。',
  modelSize: MODEL_SIZE,
  modelIntro: `攝影機追蹤要先下載臉部特徵點模型（MediaPipe Face Landmarker，${MODEL_SIZE}）。`,
  modelNeeded: '要先下載臉部追蹤模型。',
  calibrate: '記錄正面（校正）',
  calibrateHint: '攝影機追蹤時面向正前方，以自然的表情按下。',
  calibrateClear: '清除記錄',
  calDone: '已記錄（以你的自然表情為基準判定）',
  calNone: '未記錄（以標準的臉部比例判定）',
  calHold: '請面向正前方，保持自然的表情約 1 秒…',
  calFailed: '偵測不到臉，無法記錄。',
  calSaved: (n: number) => `已記錄正面的表情（${n} 個影格）`,
  calCleared: '已清除校正。',
  linkEyes: '左右眼同步眨眼（關閉時可以偵測單眼眨眼）',
  trackBrow: '追蹤眉毛',
  trackSmile: '追蹤笑臉（嘴巴形狀）',
  camPreview: '顯示攝影機小畫面',
  gains: {
    headGain: '頭部靈敏度',
    eyeGain: '眨眼靈敏度',
    mouthGain: '嘴巴靈敏度',
    browGain: '眉毛靈敏度',
    gazeGain: '視線靈敏度',
    smoothing: '平滑度',
    micGain: '麥克風靈敏度',
    micGate: '噪音閘門',
  },
  micMeter: '麥克風輸入（線條是噪音閘門）',
  camStartError: (msg: string) => `無法啟動攝影機：${msg}`,
  micStartError: (msg: string) => `無法啟動麥克風：${msg}`,
  devErrors: {
    camPermission: '請確認瀏覽器的攝影機權限。',
    camBusy: '其他應用程式正在使用攝影機。',
    camNotFound: '找不到攝影機。',
    insecure: '請用 https 或 localhost 開啟。',
    trackingStopped: '臉部追蹤已停止，請重新開啟攝影機。',
    camDisconnected: '攝影機已中斷連線。',
    micDisconnected: '麥克風已中斷連線。',
    micPermission: '請確認瀏覽器的麥克風權限。',
    noSimd: '這個瀏覽器不支援臉部追蹤需要的 WebAssembly SIMD，請更新瀏覽器。',
    loadFailed: (msg: string) => `無法載入臉部追蹤：${msg}`,
  },

  /* 背景 */
  backgrounds: { checker: '透明', green: '綠幕', dark: '深色' } satisfies Record<
    BackgroundId,
    string
  >,
  backgroundLabel: '預覽背景',

  /* 匯出 */
  exportBg: '背景',
  exportBgs: { transparent: '透明', green: '綠幕', dark: '深色' } satisfies Record<
    ExportBackground,
    string
  >,
  recSeconds: '錄影長度',
  recSecondsValue: (s: number) => `${s} 秒`,
  recFps: '影格率',
  recFormat: '格式',
  recFormatNone: '（不支援）',
  recordStart: '開始錄影',
  exportHint: '影片會以 PSD 的原尺寸匯出。WebM（Chrome／Edge）可以保留透明背景。',
  recUnsupported: '這個瀏覽器不支援匯出影片（請使用 Chrome／Edge／Firefox）。',
  recDone: (w: number, h: number, sec: string, mb: string, noAlpha: boolean) =>
    `已匯出影片（${w} × ${h} px，${sec} 秒，${mb} MB）${noAlpha ? '（這個格式不會保留透明背景）' : ''}`,
  recCancelled: '已中止錄影。',
  recError: (msg: string) => `無法錄影：${msg}`,
  recEmpty: '影片資料是空的。',
  pngDone: (w: number, h: number, transparent: boolean) =>
    `已匯出 PNG（${w} × ${h} px${transparent ? '，透明' : ''}）`,
  pngFailed: '無法匯出 PNG。',

  /* 儲存與設定 */
  saveSettings: '儲存調整',
  saveSettingsDirty: '儲存調整 ●',
  saveTitle: '儲存到這個瀏覽器',
  saveTitleDirty: '有尚未儲存的變更',
  restoreSettings: '還原成已儲存的狀態',
  exportJson: '匯出設定 JSON',
  importJson: '讀入設定 JSON',
  resetParams: '重設數值',
  savePsd: '儲存輕量 PSD',
  saveHint:
    '調整依模型分別存在這個瀏覽器。要帶到其他電腦可以用設定 JSON（把 JSON 拖進視窗也能讀入）。設定 JSON 不含 PSD 的圖像，也不含攝影機與麥克風的開關。',
  resetDone: '已將所有參數還原成初始值。',
  needModel: '請先讀入 PSD。',
  psdExporting: '匯出中…',
  psdDone: (mb: string) => `已儲存輕量 PSD（${mb} MB，已去除雜訊並裁切）。`,
  psdError: (msg: string) => `匯出錯誤：${msg}`,
  layerDiff: (n: number) => (n ? `（圖層結構不同的 ${n} 項維持初始值）` : ''),
  noneSaved: '這個模型沒有已儲存的調整。',
  restored: (diff: string) => `已還原儲存的調整${diff}`,
  restoreError: (msg: string) => `無法還原調整：${msg}`,
  saved: '已把這個模型的調整儲存到瀏覽器。',
  saveError: '無法儲存到瀏覽器，請匯出設定 JSON。',
  jsonExported: '已匯出設定 JSON。',
  jsonTooLarge: '設定 JSON 請控制在 1 MB 以下。',
  jsonInvalid: '不是有效的 JSON 檔案。',
  modelChanged: '模型已經換了，請重新選擇設定。',
  imported: (diff: string) => `已讀入設定${diff}。按「儲存調整」就能記住。`,
  importError: (msg: string) => `無法讀入設定：${msg}`,
  undone: '已復原。',
  redone: '已重做。',
  leaveConfirm: '有尚未儲存的調整。',

  /* 圖層 */
  layersHint: '上面在後、下面在前。拖曳把手或按「往後」「往前」調整順序，展開可以調整濃度與深度。',
  layersReset: '重設圖層設定',
  layersResetDone: '已重設圖層設定。',
  layersEmpty: '讀入 PSD 後會顯示在這裡',
  layersAria: '圖層（上面在後、下面在前）',
  layerBack: '往後',
  layerFront: '往前',
  layerDetails: (name: string) => `${name} 的詳細設定`,
  layerOpacity: '濃度',
  layerDepth: '深度',
  layerShow: (name: string) => `顯示「${name}」`,
  sideL: '左',
  sideR: '右',
  strands: (n: number) => `髮束 ${n}`,
  sway: (n: number) => `擺動 ${n}`,
  synthetic: '自動產生',
  unknown: (group: PartGroup) => `未分類 → 跟著${group === 'head' ? '頭部' : '身體'}`,
  roles: {
    wings: '翅膀',
    tail: '尾巴',
    'back hair': '後髮',
    footwear: '鞋子',
    legwear: '腿',
    bottomwear: '下身服裝',
    neck: '脖子',
    topwear: '上身服裝',
    neckwear: '領口',
    handwear: '手臂與手',
    objects: '小物',
    earwear: '耳飾',
    ears: '耳朵',
    face: '臉',
    facedetail: '臉部細節',
    headwear: '頭飾',
    mouth_close: '閉嘴',
    mouth_open: '張嘴',
    nose: '鼻子',
    eyewhite: '眼白',
    eyebrow: '眉毛',
    irides: '瞳孔',
    eyelash: '睫毛',
    eye_close: '閉眼',
    eye_close2: '長閉眼',
    eyewear: '眼鏡',
    'side hair': '側髮',
    'front hair': '瀏海',
    ahoge: '呆毛',
  } as Record<string, string>,

  /* 模型資訊與診斷 */
  infoNone: '未讀入模型',
  infoSummary: (parts: number, strands: number) =>
    `已自動綁定 ${parts} 個部件／${strands} 條擺動部件`,
  infoSize: (w: number, h: number) => `${w} × ${h} px`,
  infoNoise: (n: number, total: number) => `已去除雜訊：${n}／${total} 個圖層`,
  diagAria: '綁定的檢查結果',
  diag: {
    oneSide: '只找到單側',
    missing: '找不到',
    face: '臉（face）',
    faceGuess: '找不到，因此推測臉的位置',
    eyewhite: '眼白（eyewhite）',
    irides: '瞳孔（irides）',
    eyelash: '睫毛（eyelash）',
    eyeClose: '閉眼（eye_close）',
    eyeCloseShort: '閉眼',
    eyeCloseAuto: '已自動放上通用差分（可以用「眼睛」的差分滑桿調整）',
    eyeCloseNone: '只靠壓縮眼皮來眨眼',
    eyeClose2: '長閉眼（eye_close2）',
    eyebrow: '眉毛（eyebrow）',
    mouthOpen: '張嘴（mouth_open）',
    noLipSync: '無法做出嘴型',
    mouthClose: '閉嘴（mouth_close）',
    mouthCloseShort: '閉嘴',
    mouthCloseAuto: '已自動放上通用差分（可以用「嘴巴」的滑桿調整）',
    hair: '頭髮物理',
    hairStrands: (role: string, n: number) => `${role} ${n} 束`,
    hairNone: '找不到 front hair／back hair（瀏海、後髮）',
    unknown: (n: number) => `未分類的圖層 ${n} 個`,
    unknownNote: (names: string) => `${names}（依照命名規則改名就會動起來）`,
  },
  diagLevels: { ok: '有', warn: '注意', bad: '缺少', auto: '自動' },

  /* 快捷鍵 */
  keys: {
    groupPlay: '播放',
    groupEdit: '編輯',
    groupView: '預覽',
    pause: '暫停／播放',
    preset: (name: string) => `表情預設：${name}（再按一次解除）`,
    presetClear: '解除表情預設',
    undo: '復原',
    redo: '重做',
    save: '把調整儲存到瀏覽器',
    open: '開啟 PSD',
    anchor: '錨點編輯（Esc 結束）',
    fit: '預覽回到全圖',
    bg: '切換預覽背景',
    zoom: '放大／縮小預覽（滾輪）',
    pan: '移動放大中的預覽（拖曳）',
    dblclick: '預覽回到全圖（在預覽上按兩下）',
    esc: '結束錨點編輯',
  },
} as const;

export const SECTION_IDS = [
  'auto',
  'preset',
  'head',
  'eyes',
  'brow',
  'mouth',
  'bangs',
  'body',
  'anchors',
  'tracking',
  'export',
  'save',
  'background',
  'layers',
  'info',
] as const;
export type SectionId = (typeof SECTION_IDS)[number];

/** 使用方式（依原作 Anime2.5DRig 的說明〔MIT〕改寫；規格 F91、D4） */
export const USAGE = {
  intro:
    '把分好部件的 PSD 拖進來，就會自動綁定並動起來（待機、眨眼、嘴型、頭髮物理）。調整表情與動作後，可以匯出透明背景的 PNG 或影片。PSD 與攝影機畫面都只在這個瀏覽器裡處理，不會上傳。',
  steps: [
    '把分好部件的 PSD 拖到頁面上，或按「開啟 PSD」（Ctrl＋O）選檔。讀入中可以中止；換 PSD 失敗時，正在編輯的模型會保留。',
    '自動綁定完成後立刻動起來。在左邊調整表情預設、眼睛、嘴巴、頭髮與身體；在預覽上用滾輪縮放、拖曳移動，按 F 或按兩下回到全圖。',
    '在「匯出」選背景，按「儲存 PNG」或「錄影」。',
  ],
  sections: [
    {
      title: '編輯與儲存',
      items: [
        '設定欄最上面可以搜尋設定（眼睛、頭髮、嘴巴、圖層…）；區塊可以收合，展開狀態會記住。',
        '滑桿右邊的數值可以直接輸入；在滑桿上按兩下，只有這一項還原成初始值。',
        '參數、表情預設、圖層、錨點、背景的變更可以復原與重做（Ctrl＋Z／Ctrl＋Shift＋Z）。',
        '「儲存調整」（Ctrl＋S）依模型把調整存在這個瀏覽器；有未儲存的變更時按鈕會標「●」，關閉頁面前也會確認。再讀入同一個 PSD 時自動還原。',
        '要搬到別的瀏覽器或電腦時用「匯出設定 JSON」，在那邊讀入同一個 PSD 後「讀入設定 JSON」（或把 JSON 拖進頁面）。舊版的 v1 設定 JSON 也讀得到。PSD 重新編輯過就會被當成另一個模型。',
        '「暫停」（Space）讓動作停住，方便調整數值、匯出靜止畫面。表情預設套用中不會被自動眨眼與隨機嘴型蓋掉。',
        '「圖層」可以調整顯示、濃度、深度與繪製順序（上面在後、下面在前）；滑鼠移到列上時預覽會標出範圍。深度影響轉頭時的移動量，和繪製順序分開。',
        '「儲存輕量 PSD」存下去掉雜點、裁過的 PSD；動作與圖層設定請存成設定 JSON。',
      ],
    },
    {
      title: '錨點（基準點）',
      items: [
        '眼睛、嘴巴、脖子的位置是自動偵測的，畫風不同時可能有偏差。按「編輯錨點」（E）會停在靜止的姿勢、顯示基準點。',
        '臉部中心：轉頭的深度與瀏海區塊的交界；左眼／右眼：瞳孔縮放與視線的中心；閉眼位置（藍色）：眼皮閉上的高度，拖曳時那一隻眼睛會閉上；嘴巴：開合、縮放、閉嘴旋轉的中心；脖子旋轉軸：頭部的支點；胸部（紫色）：晃動的中心。',
        '直接拖曳，或選取圓點後用方向鍵（1 px）／Shift＋方向鍵（10 px）移動；Esc 或 E 結束。錨點也會存進設定與 JSON。',
      ],
    },
    {
      title: '攝影機與麥克風',
      items: [
        `第一次開「攝影機追蹤」前要先下載臉部特徵點模型（${MODEL_SIZE}，Google 的 MediaPipe，Apache-2.0）；只要下載一次，存在這個瀏覽器裡。`,
        '追蹤頭部朝向、眨眼、視線、嘴巴開合、眉毛與笑臉。預覽左上角有攝影機小畫面（可以關掉）。網址加 ?cam=1 時開頁就開始追蹤。',
        '「記錄正面（校正）」：追蹤中面向正前方、以自然的表情按下，之後以你的臉為基準判斷，眼睛偏細、嘴角上揚等個人差異比較不會誤判。',
        '關掉「左右眼同步眨眼」就能偵測單眼眨眼；眉毛與笑臉的追蹤可以個別關掉；頭部、眨眼、嘴巴、眉毛、視線的靈敏度與平滑度都可以調整。',
        '「麥克風嘴型」可以調整靈敏度與噪音閘門（比它小聲的聲音不算），音量表的線是閘門的位置。',
        '攝影機與麥克風只能在 https 或 localhost 下使用（瀏覽器的規定）。',
      ],
    },
    {
      title: '匯出',
      items: [
        '「儲存 PNG」以 PSD 的原尺寸匯出目前的姿勢，不含錨點等操作介面。',
        '「錄影」以原尺寸錄下動作：長度 3～60 秒、30／60 fps、格式依瀏覽器。錄影中再按一次就儲存到目前為止的內容。',
        '背景可以選透明、綠幕、深色，PNG 與影片都套用。能保留透明的是 WebM（Chrome／Edge），MP4 不支援透明。',
      ],
    },
    {
      title: '在 OBS 裡使用',
      items: [
        '直接放進 OBS：預覽背景選「綠幕」，在 OBS 用「視窗擷取」擷取這個頁面，再加「色度鍵」濾鏡去掉綠色。用攝影機或麥克風帶動時這個方法最方便。',
        '錄好的片段：匯出背景選「透明」、格式選 WebM（VP9 或 VP8）錄影，在 OBS 用「媒體來源」播放（可以勾選循環），透明的地方會直接透出底下的畫面。',
      ],
    },
    {
      title: '自動處理的項目',
      items: [
        '直接接受 see-through 輸出的 PSD（mouth 視為張嘴；hair 在臉的上層視為瀏海、下層視為後髮）。',
        '自動辨認英文與日文的圖層名稱（前髪、白目、瞳、まつ毛、閉じ目、bangs、iris…）；全形、大小寫、「のコピー」「copy」、底線與空白的差異都會忽略。中文名稱不辨認。',
        '沒有閉眼、閉嘴圖層時，自動放上通用的差分（依錨點縮放擺放，顏色配合睫毛、嘴巴；可以用差分滑桿微調）。',
        '去除低透明度的雜點；資料夾裡的圖層也讀（隱藏的不讀）；眼睛、眉毛、睫毛、閉眼自動分左右；偵測頭髮的髮束（每個圖層最多 6 束）；耳飾與尾巴像鐘擺一樣擺動。',
        '依部位分配深度，轉頭時有立體感；每一束頭髮有自己的彈簧（髮根硬、髮梢軟），身體傾斜、胸部晃動、呼吸。',
        '加一個名為 eye_close2（eyeclose2、閉じ目2）的長閉眼圖層時，自動眨眼有 20% 的機率改用它，閉眼時間是一般的 10 倍。',
      ],
    },
    {
      title: '已知限制',
      items: [
        '不會拆解單張插圖：請先用 see-through 等工具把插圖分成部件的 PSD。',
        '支援 RGB、8 位元／色版、128 MB 以下、2,400 萬像素以下、單邊 16,384 px 以下的 PSD；還受圖層總像素、記憶體與顯示卡上限的限制。',
        '只用圖層本身的像素：群組的不透明度、特殊混合模式、調整圖層、遮色片不會套用，需要的效果請先合併進部件。',
        '建議使用正方形畫布（768 × 768～2048 × 2048）。脖子與身體的交界容易破圖時，把脖子合併進上身圖層（不用 neck）比較好。',
        '設定存在瀏覽器的本機儲存空間；無痕模式等存不進去時請匯出設定 JSON。',
      ],
    },
  ],
  namingTitle: '圖層命名規則',
  namingIntro:
    '用下表的名稱（或別名）命名圖層。同一部位分成好幾個圖層時加上流水號（front hair_1、前髪2…），每個圖層各自做髮束物理。不符合的圖層也會讀入（依位置跟著頭部或身體），在「模型資訊與診斷」列為未分類。',
  namingHead: ['圖層名稱', '別名範例', '部位'],
  naming: [
    ['face', '顔、輪郭', '臉（錨點的基準，一定要有）'],
    ['eyewhite', '白目', '眼白（自動分左右，也是瞳孔的裁切範圍）'],
    ['irides', '瞳、黒目、iris', '瞳孔（視線、瞳孔縮放）'],
    ['eyelash', 'まつ毛、アイライン', '睫毛（睜眼）'],
    ['eye_close', '閉じ目', '閉眼（眨眼時交叉淡化）'],
    ['eye_close2', '閉じ目2', '長閉眼'],
    ['eyebrow', '眉、眉毛', '眉毛'],
    ['mouth_open', '口、開き口、mouth', '張嘴'],
    ['mouth_close', '閉じ口', '閉嘴'],
    ['nose／ears／earwear', '鼻／耳／ピアス、イヤリング', '鼻子、耳朵、耳飾（耳飾會擺動）'],
    ['eyewear／facedetail', '眼鏡、メガネ／頬、blush', '眼鏡、臉部細節'],
    ['neck／neckwear', '首／ネクタイ、チョーカー', '脖子、領口配件'],
    ['topwear／bottomwear', '服、体、上半身／スカート、ズボン', '上身（呼吸、胸部晃動）、下身'],
    ['handwear／legwear／footwear', '腕、手／脚、靴下／靴', '手臂（可以調高度）、腿、鞋子'],
    ['headwear', '帽子、髪飾り、カチューシャ', '頭飾'],
    [
      'front hair／side hair／ahoge',
      '前髪、bangs／横髪、もみあげ／アホ毛',
      '瀏海、側髮、呆毛（髮束物理）',
    ],
    ['back hair', '後ろ髪、後髪', '後髮（髮束物理）'],
    ['hair', '髪', '頭髮（在臉的上層＝瀏海、下層＝後髮）'],
    ['tail／wings', '尻尾／羽、翼', '尾巴（擺動）、翅膀'],
  ],
};
