/**
 * 室內平面圖產生器的介面文字（台灣繁體中文）。
 */
import type { RoomPresetGroupId, RoomPresetId } from './model/catalog';
import type { OpeningKind, RoomCategory, SizeMode, ThemeId, WallKind } from './model/types';

export const S = {
  title: '室內平面圖產生器',
  untitled: '未命名地圖',
  newMapName: '新的地圖',
  newRoom: '房間',
  newText: '文字',
  undo: '復原',
  badgeGm: 'GM 用',
  canvasLabel: '平面圖的畫布',

  bar: {
    templates: '範本',
    undo: '復原',
    redo: '重做',
    view: '檢視',
    gm: 'GM 檢視',
    pl: 'PL 檢視',
    export: '匯出圖片',
    clues: '隱藏線索',
    cluesOn: '隱藏線索：顯示中（C 切換）。和 GM／PL 檢視分開切換。',
    cluesOff: '隱藏線索：已隱藏（C 切換）。房間裡的東西照常顯示，只藏線索。',
    on: '顯示',
    off: '隱藏',
  },

  tools: {
    label: '工具',
    select: '選取',
    hand: '平移畫面',
    room: '房間',
    wall: '牆',
    door: '門',
    window: '窗',
    text: '文字',
    eraser: '橡皮擦',
  },

  hints: {
    select:
      '點一下選取、拖曳移動；在空白處拖曳可以框選。移動房間時裡面的東西一起移動（按住 Alt 只移動房間）。',
    hand: '拖曳移動畫面；滾輪縮放。',
    room: '拖曳畫出房間。左邊「房間」分頁可以選種類與預設尺寸。',
    roomPreset: (name: string, size: string) =>
      `「${name}」：拖曳畫出任意大小，點一下放預設尺寸（${size}）。`,
    wall: (name: string) =>
      `「${name}」：拖曳畫牆（自動對齊水平或垂直，按住 Shift 畫斜線）。房間外圍的牆會自動產生，這裡畫的是隔間、圍籬等額外的牆。`,
    opening: (name: string) =>
      `「${name}」：靠近牆會自動貼上，點一下放置；門往游標那一側開（按 R 換鉸鍊那一邊）。`,
    place: (name: string) =>
      `「${name}」：點一下放置（按住 Shift 連續放）；靠牆時背面自動朝牆。R 轉向，按住 Alt 不吸附。`,
    text: '點一下放一段文字。',
    eraser: '點一下刪掉東西；拖曳可以連續刪掉家具等（房間只能用點的）。',
    noWall: '這裡沒有牆。請靠近房間的外圍，或用牆工具畫的牆。',
  },

  lib: {
    label: '素材',
    rooms: '房間',
    openings: '門窗',
    furniture: '家具・小物',
    roomsNote: '選好之後在畫布上拖曳畫出房間，或點一下放預設尺寸；也可以直接把卡片拖到畫布上。',
    doors: '門',
    windows: '窗',
    walls: '牆・隔間',
    wallsNote: '房間外圍的牆會自動產生；這些是額外的牆（隔間、圍籬、崩塌的牆…）。',
    search: '搜尋家具',
    all: '全部',
    noResult: '找不到符合的家具。',
    group: '家具分類',
  },

  presetGroups: {
    home: '住家',
    service: '衛浴・走道・收納',
    facility: '設施',
    special: '特殊・戶外',
    world: '和風・科幻・自然',
  } satisfies Record<RoomPresetGroupId, string>,

  presets: {
    ldk: '客餐廳',
    living: '客廳',
    dining: '餐廳',
    kitchen: '廚房',
    master: '主臥室',
    bedroom: '臥室',
    washitsu: '和室',
    kids: '兒童房',
    study: '書房',
    bath: '浴室',
    laundry: '洗衣間',
    toilet: '廁所',
    entrance: '玄關',
    hall: '走廊',
    stairs: '樓梯間',
    closet: '衣櫃',
    storage: '儲藏室',
    office: '辦公室',
    meeting: '會議室',
    lobby: '大廳',
    guest: '客房',
    ward: '病房',
    exam: '診間',
    surgery: '手術室',
    lab: '研究室',
    ritual: '儀式之間',
    sealed: '封鎖區',
    cell: '牢房',
    garage: '車庫',
    balcony: '陽台',
    garden: '庭院',
    porch: '門廊',
    doma: '土間',
    deck: '艙內區塊',
    cave: '洞窟',
    water: '池塘・河川',
    field: '田地',
  } satisfies Record<RoomPresetId, string>,

  categories: {
    living: '客廳・起居室',
    bedroom: '臥室・個人房',
    washitsu: '和室',
    kitchen: '廚房・餐廳',
    wet: '浴室・盥洗・廁所',
    hall: '玄關・走廊・樓梯',
    storage: '收納・倉庫',
    public: '大廳・公共空間',
    office: '辦公・員工區',
    medical: '醫療・研究',
    special: '特殊・儀式',
    danger: '危險・禁止進入',
    garage: '車庫・機房',
    balcony: '陽台・露台（戶外）',
    garden: '庭院・戶外',
    porch: '門廊・步道（戶外）',
    doma: '土間（泥土地面）',
    tech: '艙內・機艙（科幻）',
    field: '田地（戶外）',
    water: '水邊・池塘・河川（戶外）',
    cave: '洞窟・岩地（戶外）',
  } satisfies Record<RoomCategory, string>,

  openings: {
    door: '單開門',
    door2: '雙開門',
    sliding: '拉門',
    sliding2: '雙片拉門・紙門',
    folding: '摺疊門・衣櫃門',
    auto: '自動門',
    shutter: '鐵捲門',
    open: '開口（沒有門）',
    locked: '上鎖的門',
    secret: '暗門（只有 GM 看得到）',
    broken: '壞掉的門',
    hole: '牆上的破洞',
    window: '窗戶',
    window2: '落地窗・大窗',
    barred: '鐵窗',
    boarded: '釘上木板的窗',
    brokenwin: '破掉的窗',
  } satisfies Record<OpeningKind, string>,

  walls: {
    ext: '外牆（厚）',
    int: '內牆',
    thin: '隔間（薄）',
    glass: '玻璃牆',
    rail: '欄杆・矮牆',
    fence: '圍籬',
    bars: '鐵欄杆',
    broken: '崩塌的牆',
    rock: '岩壁',
  } satisfies Record<WallKind, string>,

  themes: {
    clean: '彩色',
    mono: '黑白圖面',
    blueprint: '藍圖',
    paper: '泛黃的舊圖面',
    horror: '恐怖調查',
  } satisfies Record<ThemeId, string>,

  sizeModes: {
    none: '不顯示',
    ping: '坪',
    m2: '平方公尺（㎡）',
    m: '長 × 寬（m）',
  } satisfies Record<SizeMode, string>,

  props: {
    label: '屬性',
    mapTitle: '地圖設定',
    mapName: '地圖名稱',
    mapNamePh: '例：山丘上的洋館',
    style: '顯示樣式',
    showNames: '顯示房間名字',
    sizeLabel: '房間面積',
    grid: '顯示格線（G）',
    ghost: '淡淡地顯示下一層',
    stats: (rooms: number, items: number, openings: number) =>
      `${rooms} 個房間・${items} 件家具・${openings} 個門窗`,
    mapTip: '點一下房間或家具，這裡就可以改名字、大小與顏色。',
    room: '房間',
    item: '家具・小物',
    opening: '門窗',
    wall: '牆',
    text: '文字',
    multi: (n: number) => `已選取 ${n} 個`,
    name: '名字',
    plName: '給 PL 看的名字',
    plNamePh: '空白＝和名字相同',
    plNameNote: 'PL 檢視與 PL 用的圖片顯示這個名字（例：GM「祕密房間」→ PL「？？？」）。',
    category: '種類',
    openingKind: '種類',
    x: 'X',
    y: 'Y',
    w: '寬',
    h: '深',
    len: '寬度',
    cells: '格',
    area: '面積',
    color: '顏色',
    colorAuto: '自動',
    colorReset: '改回自動',
    gmOnly: '只有 GM 看得到（PL 看不到）',
    clue: '隱藏線索（可以用「隱藏線索」開關藏起來）',
    hideLabel: '不顯示名字',
    noWall: '不產生牆（例如客餐廳的分區）',
    note: 'GM 筆記',
    notePh: '線索、檢定、事件…（不會畫進圖片）',
    lockedNote: '鎖定中：不能移動、改大小、旋轉或刪除。房間裡的家具與門照常可以編輯。',
    labelReset: '名字回到中央',
    labelText: '標籤',
    labelPh: '例：日記在這裡',
    rotation: '方向',
    flip: '左右翻轉',
    swingFlip: '換開門的方向（內開／外開）',
    hingeFlip: '換鉸鍊那一邊',
    textBody: '文字',
    textSize: '字級',
    bold: '粗體',
    front: '移到最上層',
    back: '移到最下層',
    duplicate: '複製',
    delete: '刪除',
    wallKind: '牆的種類',
    length: '長度',
    lock: '鎖定（L）',
    unlock: '解除鎖定（L）',
    rotate: '旋轉（R）',
    multiNote: '按住 Shift 點一下可以加入或取消選取。',
  },

  mini: {
    label: '選取的東西',
    rotate: '旋轉（R）',
    flip: '翻轉（F）',
    hinge: '換鉸鍊那一邊',
    gmOn: '只有 GM 看得到（按一下讓 PL 也看得到）',
    gmOff: 'PL 也看得到（按一下改成只有 GM）',
    clueOn: '隱藏線索（按一下取消）',
    clueOff: '設成隱藏線索',
    lock: '鎖定（L）',
    unlock: '解除鎖定（L）',
    duplicate: '複製（Ctrl＋D）',
    delete: '刪除（Delete）',
  },

  zoom: {
    label: '縮放',
    in: '放大',
    out: '縮小',
    fit: '顯示全部（0）',
  },

  floors: {
    label: '樓層',
    add: '新增樓層',
    rename: '重新命名',
    renameLabel: '樓層名稱',
    duplicate: '複製這一層',
    left: '往左移',
    right: '往右移',
    remove: '刪除這一層',
    confirmTitle: (name: string) => `刪除「${name}」？`,
    confirmText: '這一層的房間、家具與門窗都會刪掉（可以用「復原」回來）。',
  },

  tpl: {
    title: '從範本開始',
    intro:
      '依常見的格局畫的平面圖，載入之後可以自由修改。目前的地圖會被取代（可以用「復原」回來）。',
    structureOnly: '只載入格局（不含家具）',
    clues: '放入隱藏線索',
    floors: (n: number) => `${n} 層`,
    blank: '空白地圖',
    blankDesc: '沒有房間、也沒有家具，從頭畫起。',
    gallery: '範本',
  },

  exp: {
    title: '匯出圖片',
    range: '範圍',
    current: '只有這一層',
    all: '所有樓層排成一張',
    each: '每層各一張',
    view: '對象',
    pl: 'PL 用（藏起 GM 專用）',
    gm: 'GM 用（全部顯示）',
    clues: '隱藏線索',
    cluesShow: '顯示',
    cluesHide: '藏起來',
    noClueSuffix: '無線索',
    style: '樣式',
    px: '每格大小',
    pxNote: '1 格 = 0.5 m。要放進 CCFOLIA 等線上桌面時，配合地圖的格子大小選。',
    grid: '畫格線',
    transparent: '透明背景',
    download: '下載 PNG',
    copy: '複製到剪貼簿',
    copied: '圖片已複製到剪貼簿',
    copyFailed: '這個瀏覽器不能複製圖片，請改用下載。',
    info: (w: number, h: number) => `${w} × ${h} px`,
    tooLarge: '圖片太大，已自動縮小',
    saved: (n: number) => (n > 1 ? `已下載 ${n} 張 PNG` : '已下載 PNG'),
    empty: '這一層沒有東西可以匯出。',
    failed: '無法產生圖片（記憶體不足？請把每格大小調小）。',
    preview: '匯出預覽',
  },

  project: {
    import: '匯入「TRPG 室內圖メーカー」的地圖檔…',
    resetLabel: '新的空白地圖',
    resetTitle: '開一張新的空白地圖？',
    resetText: '目前的地圖會被清空（可以用「復原」回來）。顯示樣式等設定會保留。',
    resetConfirm: '開新地圖',
    openFailed: '這個檔案讀不進來。請選本工具的專案檔，或原作存的 .trpgmap.json。',
    /** 讀不進來的原因（寫在通知的說明裡） */
    newer: '這個專案檔是用較新版本的工具存的，請重新整理頁面後再開啟。',
    unusable: '專案檔的內容無法使用。',
    dropHint: '放開即可開啟地圖檔',
  },

  msg: {
    opened: (name: string) => `已開啟「${name}」`,
    saved: (file: string) => `已存成專案檔：${file}`,
    imported: (name: string) => `已匯入「${name}」`,
    droppedItems: (n: number) => `有 ${n} 件家具的種類本工具沒有，已略過。`,
    templateLoaded: (name: string) => `已載入「${name}」`,
    newMap: '已開新的空白地圖',
    cluesShown: (n: number) => `顯示隱藏線索（${n} 個）`,
    cluesHidden: (n: number) => `隱藏線索已藏起來（${n} 個）`,
    deleted: (n: number) => `已刪除 ${n} 個`,
    pasted: (n: number) => `已貼上 ${n} 個`,
    noUndo: '沒有可以復原的步驟',
    locked: '這個房間鎖定中，要移動請先解除鎖定。',
    lockedSkip: '鎖定的房間沒有改動。',
    storageFull: '自動儲存失敗（瀏覽器的儲存空間可能滿了）。請用「專案 → 存成專案檔」另外存一份。',
  },

  keys: {
    tools: '工具',
    edit: '編輯',
    view: '檢視',
    file: '檔案',
    select: '選取工具',
    hand: '平移畫面（也可以按住空白鍵、右鍵或中鍵拖曳）',
    room: '房間工具（拖曳畫房間）',
    wall: '牆工具（按住 Shift 畫斜線）',
    door: '門工具',
    window: '窗工具',
    text: '文字工具',
    eraser: '橡皮擦',
    rotate: '旋轉選取的東西（房間連同裡面一起）；放置中的家具轉向、門換鉸鍊',
    flip: '左右翻轉（門：換開的方向）',
    lock: '鎖定／解除鎖定選取的房間',
    del: '刪除選取的東西',
    nudge: '一點一點移動（按住 Shift 移動多一點）',
    undo: '復原',
    redo: '重做',
    copy: '複製',
    cut: '剪下',
    paste: '貼上',
    duplicate: '再製一份',
    selectAll: '全選',
    save: '存成專案檔',
    open: '開啟專案檔',
    export: '匯出圖片',
    grid: '顯示／隱藏格線',
    pl: '切換 GM／PL 檢視',
    clues: '顯示／隱藏「隱藏線索」',
    fit: '顯示全部',
    zoomIn: '放大',
    zoomOut: '縮小',
    floorDown: '往下一層',
    floorUp: '往上一層',
    esc: '放下工具、取消選取、取消拖曳；在輸入欄裡＝離開輸入欄',
    space: '按住拖曳平移畫面',
  },
  usage: {
    steps: [
      '按「範本」挑一個格局（套房、透天厝、洋館、飯店、醫院、廢墟…），或在範本裡選「空白地圖」從頭畫。',
      '左邊「房間」分頁選好種類，在畫布上拖曳就畫出房間（點一下放預設尺寸）。相鄰的房間之間自動產生內牆，外圍是外牆；陽台是欄杆，庭院、水邊、洞窟等戶外房間彼此之間沒有牆。',
      '「門窗」分頁選好之後，靠近牆就會自動貼上，點一下放置；門往游標那一側開。',
      '「家具・小物」可以點一下再放，或直接拖到畫布上；靠牆時家具的背面自動朝牆。',
      '點一下選取，右邊可以改名字、大小、方向、顏色。移動房間時，裡面的家具、門窗、文字一起移動（按住 Alt 只移動房間）；旋轉房間（R）也是整間一起轉。鎖定（L）的房間不會被不小心移動或刪除。',
      '設成「只有 GM 看得到」的房間，在 PL 檢視與 PL 用的圖片裡只剩牆框、裡面蓋灰；家具、文字、暗門也一樣藏起來。房間可以另外取一個給 PL 看的名字（例如「？？？」）。',
      '設成「隱藏線索」的家具與文字（右上角有放大鏡）可以用畫布右上的開關（C）一起藏起來——和 GM／PL 檢視分開，可以讓 PL 看到房間裡面、但還沒找到的線索先不顯示。範本可以勾「放入隱藏線索」一起載入。',
      '下方的樓層列可以新增、複製、改名、排序樓層；按［與］切換。下一層會淡淡地顯示，方便對齊樓梯。',
      '「匯出圖片」存成 PNG（1 格＝0.5 m，可以選每格幾 px）：這一層、所有樓層排成一張、或每層各一張；PL 用的圖不含 GM 專用的東西。太大的圖會自動縮小到瀏覽器畫得出來的大小。',
    ],
    note: '地圖自動存在這個瀏覽器裡；要換電腦接著做，用「專案 → 存成專案檔」存下來，再在另一台開啟。原作（TRPG 室內圖メーカー）存的 .trpgmap.json 也可以從「專案」選單匯入。做好的平面圖可以自由用在團務、直播與劇本。',
  },
} as const;
