/**
 * 範本（本工具自己設計的繁中範本）：克蘇魯（CoC）常用 6 張、通用 3 張、外觀風格 5 張，依序排列。
 * 範本只決定外觀與範例文字（字型、樣式、配色、背景、特效、動態），尺寸與匯出設定跟著用途。
 */
import type { CutinTemplate, TemplateCategory } from './model';

export const TEMPLATE_CATEGORIES: readonly TemplateCategory[] = ['coc', 'general', 'style'];

export const TEMPLATES: readonly CutinTemplate[] = [
  /* ---- 克蘇魯（CoC）常用 ---- */
  {
    id: 'success',
    name: '成功',
    category: 'coc',
    text: '成功',
    font: 'noto-sans-tc',
    style: 'single',
    palette: 'ice',
    fx: 'rings',
    motion: 'pulse',
    motionAmount: 0.04,
  },
  {
    id: 'critical',
    name: '大成功',
    category: 'coc',
    text: '大成功！',
    font: 'noto-sans-tc',
    style: 'double',
    palette: 'rainbow-gold',
    fx: 'speedLines',
    motion: 'pulse',
  },
  {
    id: 'failure',
    name: '失敗',
    category: 'coc',
    text: '失敗…',
    font: 'noto-serif-tc',
    style: 'single',
    palette: 'mono',
    fx: 'none',
    motion: 'bounce',
    motionAmount: 0.02,
  },
  {
    id: 'fumble',
    name: '大失敗',
    category: 'coc',
    text: '大失敗',
    font: 'noto-serif-tc',
    style: 'hard',
    palette: 'blood',
    fx: 'rings',
    fxParams: { color: '#ff6b6b', count: 2 },
    motion: 'jitter',
    motionAmount: 0.025,
  },
  {
    id: 'sanity',
    name: '理智喪失',
    category: 'coc',
    text: 'SAN 值\n歸零',
    font: 'noto-sans-tc',
    style: 'glitch',
    palette: 'blood',
    background: 'solid',
    bgColor: '#120609',
    fx: 'none',
    motion: 'jitter',
  },
  {
    id: 'secret',
    name: '秘密擲骰',
    category: 'coc',
    text: '秘密擲骰',
    font: 'cactus',
    style: 'neon',
    palette: 'ice',
    background: 'solid',
    bgColor: '#0c1024',
    fx: 'stars',
    fxParams: { count: 12, color: '#d6f3ff' },
    motion: 'wave',
    motionAmount: 0.05,
  },
  /* ---- 通用 ---- */
  {
    id: 'victory',
    name: '勝利',
    category: 'general',
    text: '勝利！',
    font: 'noto-sans-tc',
    style: 'extrude',
    palette: 'gold',
    fx: 'confetti',
    motion: 'bounce',
  },
  {
    id: 'defeat',
    name: '敗北',
    category: 'general',
    text: '敗北……',
    font: 'noto-serif-tc',
    style: 'single',
    palette: 'ice',
    fx: 'none',
    motion: 'wave',
    motionAmount: 0.03,
  },
  {
    id: 'gm-headache',
    name: '主持人頭痛中',
    category: 'general',
    text: 'GM\n頭痛中',
    font: 'mplus-rounded',
    style: 'sticker',
    palette: 'candy',
    fx: 'stars',
    fxParams: { count: 8, color: '#fff7c2' },
    motion: 'jitter',
    motionAmount: 0.015,
  },
  /* ---- 外觀風格 ---- */
  {
    id: 'neon-city',
    name: '霓虹夜城',
    category: 'style',
    text: 'NEON\n夜城',
    font: 'noto-sans-tc',
    style: 'neon',
    palette: 'rainbow-ink',
    background: 'solid',
    bgColor: '#090614',
    fx: 'speedLines',
    fxParams: { count: 32, color: '#9b7bff', groups: 3 },
    motion: 'pulse',
    motionAmount: 0.03,
  },
  {
    id: 'pop',
    name: '普普漫畫',
    category: 'style',
    text: '命中！',
    font: 'reggae',
    style: 'hard',
    palette: 'sunset',
    fx: 'speedLines',
    fxParams: { color: '#ffe14d', count: 40 },
    motion: 'pulse',
    motionAmount: 0.06,
  },
  {
    id: 'retro-game',
    name: '復古電玩',
    category: 'style',
    text: 'LEVEL UP!',
    font: 'dotgothic',
    style: 'extrude',
    palette: 'rainbow-ink',
    fx: 'stars',
    motion: 'bounce',
    motionAmount: 0.03,
  },
  {
    id: 'caution',
    name: '警示條紋',
    category: 'style',
    text: '注意！',
    font: 'noto-sans-tc',
    style: 'stripes',
    palette: 'mono',
    fx: 'none',
    motion: 'pulse',
    motionAmount: 0.03,
  },
  {
    id: 'handwritten',
    name: '手寫便條',
    category: 'style',
    text: '辛苦了～',
    font: 'wenkai',
    style: 'sticker',
    palette: 'candy',
    fx: 'confetti',
    fxParams: { count: 20 },
    motion: 'wave',
  },
];

export const templateOf = (id: string | null | undefined): CutinTemplate | null =>
  (id && TEMPLATES.find((t) => t.id === id)) || null;
