/**
 * 房間 ZIP 產生器的介面文字（本站自寫；用詞照 DESIGN.md 第 5 節）。
 */
import { formatKb } from './materials';

export const S = {
  /* ---------- 外框 ---------- */
  subtitle: '放進圖片、排好房間與場景，產生可以直接匯入 CCFOLIA 的房間 ZIP',
  summary: (img: number, scenes: number, parts: number, pieces: number) =>
    `素材 ${img}・場景 ${scenes}・部件 ${parts}・棋子 ${pieces}`,
  projectNameTitle: '專案名稱',
  projectNameHint: '同時是匯出 ZIP 與專案檔的檔名。',
  projectNameEmpty: '名稱不能是空白',
  projectRenamed: (n: string) => `專案名稱改成「${n}」`,
  undo: '復原',
  redo: '重做',
  save: '儲存',
  saveAs: '另存新檔',
  open: '讀取',
  exportZip: '匯出房間 ZIP',
  exporting: '製作中…',
  navLabel: '頁面',
  navCollapse: '收合導覽',
  navExpand: '展開導覽',
  navFootnote: '頁面可以照任何順序做，隨時回來修改。',
  navGroups: { base: '房間的基底', scenes: '場景製作', pieces: '棋子', save: '儲存' },
  pages: {
    home: '首頁',
    room: '房間設計',
    materials: '素材',
    scenes: '場景',
    tachie: '立繪庫',
    cutins: '切入',
    story: '劇本文字',
    pieces: '棋子',
    save: '儲存與說明',
    settings: '工具設定',
  },
  rightTabs: { media: '素材', preview: '預覽' },
  rightPin: '釘選面板（和主畫面並排）',
  rightUnpin: '取消釘選（疊在主畫面上）',
  rightPinned: '面板改成和主畫面並排',
  rightFloating: '面板改成疊在主畫面上，點旁邊就收起',
  rightClose: '關閉面板',
  rightOpen: '打開面板',
  rightResize: '拖曳調整面板寬度',
  bottomToggle: '備忘與待辦',
  bottomTodoLeft: (n: number) => `未完成待辦 ${n} 項`,
  bottomTodoDone: '待辦全部完成',
  bottomHasMemo: '有備忘',
  memoTitle: '整體備忘',
  memoPlaceholder: '這個房間的整體筆記（會跟著專案存檔）',
  todoTitle: '待辦事項',
  todoPlaceholder: '輸入待辦後按 Enter',
  todoEmpty: '還沒有待辦事項。',
  todoUp: '上移',
  todoDown: '下移',
  todoSub: '切換子項目',
  todoDelete: '刪除',
  busyWait: '請稍候',
  leaveWarn: '專案還沒儲存',

  /* ---------- 通知 ---------- */
  nothingToUndo: '沒有可以復原的步驟',
  nothingToRedo: '沒有可以重做的步驟',
  undone: '已復原',
  redone: '已重做',

  /* ---------- 首頁 ---------- */
  homeLead: '照下面的流程一步步完成；每一頁都可以先跳過，之後再回來補。',
  homeResume: '回到上次的頁面',
  homeOpen: '開啟專案檔',
  homeSample: '載入範例專案',
  homeSampleConfirm: '載入範例會取代目前的內容（可以復原）。要繼續嗎？',
  homeSampleDone: '已載入範例房間',
  homeSampleFailed: (e: string) => `範例載入失敗：${e}`,
  brokenBar: (n: number) => `有 ${n} 張圖片找不到資料`,
  brokenOpen: '開啟修復',
  next: {
    broken: {
      title: '先修復找不到的圖片',
      text: '有些地方引用的圖片沒有資料，匯出前要先處理。',
      go: '開啟修復',
    },
    name: {
      title: '先替房間取個名字',
      text: '專案名稱會成為 ZIP 的檔名；接著設定盤面大小與背景。',
      go: '前往房間設計',
    },
    materials: {
      title: '放進圖片',
      text: '把背景、立繪、演出用的圖片拖進畫面，工具會自動推測用途。',
      go: '前往素材',
    },
    parts: {
      title: '擺放共用部件（可省略）',
      text: '每個場景都會出現的框、標誌、看板可以在房間設計加入。',
      go: '前往房間設計',
    },
    scenes: { title: '建立場景', text: '從素材挑選前景圖，一張圖就是一個場景。', go: '前往場景' },
    export: {
      title: '可以匯出了',
      text: '儲存專案檔備份，再匯出房間 ZIP 到 CCFOLIA 讀入。',
      go: '前往儲存與匯出',
    },
  },
  stepsTitle: '製作流程',
  steps: [
    { title: '盤面與房間', text: '設定盤面格數、房間背景與前景。' },
    { title: '素材', text: '放進要用的圖片，整理名稱與用途。' },
    { title: '共用部件', text: '跨場景共用的標記與螢幕面板。' },
    { title: '場景', text: '每個場景的前景、立繪、演出與切入。' },
    { title: '棋子與文字', text: 'NPC、KP 用棋子與劇本文字。' },
    { title: '匯出', text: '產生 ZIP，在 CCFOLIA 的房間設定讀入。' },
  ],
  stepState: {
    board: (w: number, h: number) => `${w}×${h} 格`,
    count: (n: number, unit: string) => `${n} ${unit}`,
    none: '還沒有',
    optional: '可省略',
    ready: '可以匯出',
    notReady: '準備中',
  },
  statsTitle: '目前的房間',
  stats: {
    materials: '素材',
    scenes: '場景',
    markers: '共用標記',
    panels: '螢幕面板',
    tachie: '立繪庫',
    pieces: '棋子',
  },
  statsNote: '共用部件、棋子、切入都可以不做，只有場景也能匯出。',

  /* ---------- 素材 ---------- */
  materialsTitle: '素材',
  materialsDrop: '把圖片拖到這裡（或拖到畫面任何地方）',
  materialsPick: '選擇圖片',
  maxEdge: '長邊上限',
  convert: '轉成 WebP 並縮小',
  convertHint: '動態圖（GIF、APNG、動態 WebP）一律保留原檔；轉完比原檔大時也保留原檔。',
  totals: (b: number, a: number, pct: number) =>
    `原始 ${formatKb(b)} → 處理後 ${formatKb(a)}（減少 ${pct}%）`,
  filterName: '以名稱篩選',
  filterClear: '取消篩選',
  selectAll: '全選',
  selectNone: '取消選取',
  selected: (n: number) => `已選 ${n} 張`,
  selectHelp: '點卡片選取；Shift＋點可以一次選一段。',
  selectedHelp: '操作面板在畫面下方。',
  batchRename: '批次改名',
  batchTitle: (n: number) => `已選 ${n} 張`,
  batchHide: '暫時收起',
  batchShow: '展開',
  batchEnd: '結束',
  addTag: (t: string) => `加上「${t}」`,
  removeTag: (t: string) => `移除「${t}」`,
  tagChanged: (n: number) => `${n} 張的標籤已更新`,
  needSelection: '請先選取素材',
  seqTitle: '依序編號改名',
  seqPrefix: '前綴',
  seqStart: '起始號碼',
  seqDigits: '位數',
  seqGo: '套用編號',
  seqDone: (n: number) => `已改名 ${n} 張`,
  replaceTitle: '名稱取代',
  replaceFind: '尋找',
  replaceWith: '取代為',
  replaceGo: '全部取代',
  replaceEmpty: '請輸入要尋找的文字',
  replaceNone: '沒有符合的名稱',
  replaceDone: (n: number) => `已取代 ${n} 張的名稱`,
  createTitle: '以選取的素材建立',
  createAs: {
    tachie: '建成立繪',
    marker: '建成共用標記',
    panel: '建成螢幕面板',
    scene: '建成場景',
    cutin: '建成切入',
  },
  created: (n: number) => `已建立 ${n} 個`,
  deleteSelected: '刪除選取的素材',
  deleteConfirm: (n: number, used: number) =>
    used
      ? `要刪除 ${n} 張素材嗎？其中 ${used} 張正在使用，使用的地方會變成沒有圖。`
      : `要刪除 ${n} 張素材嗎？`,
  deleted: (n: number) => `已刪除 ${n} 張`,
  renamed: (n: number) => `已改名 ${n} 張`,
  favorite: '加入最愛',
  favorited: '已加入最愛（同一瀏覽器的其他專案也能用）',
  detail: '詳細',
  edit: '加工',
  remove: '刪除',
  animated: '動態圖',
  templateUsed: (n: number) => `範本 ${n} 個`,
  noMaterials: '還沒有素材。把圖片拖進畫面就會加入。',
  noMatch: '沒有符合篩選的素材。',
  favoritesTitle: '最愛（跨專案）',
  favoritesEmpty: '素材卡片上的星號可以把圖存進最愛，之後其他專案也能直接放進來。',
  favoriteUse: '放進本專案',
  favoriteRemove: '解除',
  favoriteAdded: '已從最愛放進本專案',
  templateMediaTitle: '範本內含的圖',
  templateMediaUsed: (n: number) => `被 ${n} 個範本使用`,
  templateMediaAll: '全部',
  templateMediaKinds: { marker: '共用標記', panel: '螢幕面板', piece: '棋子' },
  searchTitle: '找圖',
  searchPlaceholder: '關鍵字',
  searchNote: '使用前請確認各網站的授權與使用規定（商用、改作、署名）。',
  brokenTitle: '有圖片找不到資料',
  makeTitle: '製作素材',
  makeSolid: '單色圖',
  makeFade: '淡入淡出動態圖',
  makeMaker: '文字＋圖形合成圖',
  importHeavyTitle: '動態圖比較大',
  importHeavy: (list: string) =>
    `${list}\n\n動態圖不會被壓縮。檔案太大時 CCFOLIA 讀入與播放可能比較慢，建議減少影格或縮小尺寸。`,

  /* ---------- 素材詳細 ---------- */
  infoTitle: '素材詳細',
  infoSize: '像素尺寸',
  infoUnknown: '未知（動態圖或讀不到尺寸）',
  infoBytes: '容量',
  infoTags: '用途',
  infoAnimated: '動態圖不壓縮，以免失去動畫。',
  infoZipName: 'ZIP 內的檔名',
  infoUsages: '使用的地方',
  infoNoUsage: '還沒有用在任何地方。',
  infoUse: '立即使用',
  infoUseScene: '設成目前場景的前景',
  infoUseRoomFg: '設成房間前景',

  /* ---------- 選圖 ---------- */
  pickerTitle: '選擇圖片',
  pickerFilter: '以名稱或用途篩選',
  pickerUpload: '載入圖片',
  pickerNone: '無',
  pickerNoMatch: '沒有符合的素材。',
  pickerEmpty: '還沒有素材，可以直接把圖片拖進這裡。',
  pickerAll: '全部',
  pickerRole: (t: string) => `${t} ×`,
  pickerRoleNote: '目前只列這個用途：',
  pickerEdit: '加工這張圖',
  dropHere: '放開以放入',
  dropped: '已放入',
  imgEmpty: '無',

  /* ---------- 單色圖 ---------- */
  solidTitle: '單色圖',
  solidLead: '當背景、前景或全黑畫面用。CCFOLIA 會把圖拉滿盤面，所以小尺寸就夠了。',
  solidColor: '顏色',
  solidName: '名稱',
  solidNamePlaceholder: '留空時用「單色_色碼」',
  solidSize: '大小',
  solidSwatches: '常用色',
  solidGo: '製作',
  solidDefaultName: (c: string) => `單色_${c}`,
  solidDone: (n: string) => `已加入「${n}」`,
  solidFailed: '製作失敗',

  /* ---------- 動態圖 ---------- */
  fadeTitle: '淡入淡出動態圖（APNG）',
  fadeTarget: '完成後：',
  fadeTargets: {
    material: '加入素材',
    picker: '放進原本的欄位',
    scene: '換成這個演出的圖',
    preset: '換成演出預設的圖',
    edit: '加入素材（回到加工）',
    room: '加入素材',
  },
  fadeSource: '原圖',
  fadeNoSource: '不用原圖（純色）',
  fadeEdited: '加工後的圖',
  fadeRejected: '動態圖不能當原圖，已改成不用原圖。',
  fadeStart: '開始',
  fadeEnd: '結束',
  fadeEndpoints: { transparent: '透明', image: '圖片', color: '顏色' },
  fadeColor: '顏色',
  fadeTime: '時間',
  fadeLoop: '循環',
  fadeLoopOff: '無',
  fadeLoopOn: '有',
  fadeSummary: (sec: string, frames: number) => `約 ${sec} 秒・${frames} 格`,
  fadeSummaryLoop: (on: boolean) => `循環：${on ? '有' : '無'}`,
  fadeSummaryEdge: '大圖在產生時會縮小到長邊 1024 px',
  fadeSummarySize: '檔案大小要產生後才知道',
  fadePreviewNote: '預覽只是示意，按「產生」才會做出檔案。',
  fadeGo: '產生',
  fadeBusy: '產生中…',
  fadeDone: '已加入動態圖',
  fadeResult: (size: string, name: string) => `${name}（${size}）`,
  fadeLarge: '超過 1 MB：CCFOLIA 上傳時會再最佳化；縮短時間可以減量。',
  fadeLost: '原本要放的地方已經不在了，只加入素材。',
  fadeAssigned: '已放進原本的地方',
  fadeFailed: (e: string) => `產生失敗：${e}`,

  /* ---------- 合成圖 ---------- */
  makerTitle: '文字＋圖形合成圖',
  makerCanvas: '畫布',
  makerWidth: '寬',
  makerHeight: '高',
  makerBackground: '背景',
  makerBg: { transparent: '透明', color: '單色', image: '圖片' },
  makerBgColor: '背景色',
  makerBgImage: '背景圖',
  makerAdd: '加入元素',
  makerLayers: '圖層',
  makerNoLayer: '點畫布上的元素或圖層清單來編輯；可以 Shift＋點多選。',
  makerMulti: (n: number) => `已選 ${n} 個元素`,
  makerAlign: {
    left: '靠左',
    center: '水平置中',
    right: '靠右',
    top: '靠上',
    middle: '垂直置中',
    bottom: '靠下',
    'distribute-x': '水平均分',
    'distribute-y': '垂直均分',
  },
  makerText: '內容',
  makerFont: '字型',
  makerSize: '大小',
  makerColor: '顏色',
  makerWeight: '粗細',
  makerWeights: { 400: '標準', 700: '粗體' },
  makerAlignText: '對齊',
  makerAligns: { left: '左', center: '中', right: '右' },
  makerLineHeight: '行距倍率',
  makerSpacing: '字距',
  makerStroke: '描邊',
  makerStrokeColor: '描邊顏色',
  makerStrokeWidth: '描邊粗細',
  makerImage: '圖片',
  makerLockAspect: '固定長寬比',
  makerResetAspect: '回到原本比例',
  makerOpacity: '不透明度',
  makerVisible: '顯示／隱藏',
  makerLock: '鎖定／解除',
  makerUp: '往前',
  makerDown: '往後',
  makerDuplicate: '複製',
  makerDelete: '刪除',
  makerDeleteConfirm: '要刪除這個元素嗎？',
  makerCopySuffix: ' 複本',
  makerFile: '檔名',
  makerFilePlaceholder: '留空時用「合成圖_日期_時間」',
  makerQuality: '品質',
  makerQualities: { high: '高', standard: '標準', light: '輕量' },
  makerEstimate: (s: string) => `預估大小：${s}`,
  makerGo: '製作',
  makerBusy: '製作中…',
  makerDone: '已加入合成圖',
  makerFailed: (e: string) => `製作失敗：${e}`,
  makerHint: '拖曳移動、拖四角改大小；點空白處取消選取。選取框不會輸出。',

  /* ---------- 加工 ---------- */
  editTitle: (name: string, w: number, h: number) => `加工：${name}（${w}×${h}）`,
  editScope: '套用範圍',
  editScopes: { content: '只有圖案部分', all: '連透明部分' },
  editLook: '顏色與外觀',
  editSliders: {
    brightness: '亮度',
    contrast: '對比',
    saturate: '飽和度',
    hue: '色相',
    opacity: '透明度',
    blur: '模糊',
    noise: '雜訊',
    gray: '黑白',
    sepia: '復古褐',
    filterStrength: '強度',
  },
  editFilters: '效果濾鏡',
  editFilterColor: '色彩濾鏡',
  editGradient: '漸層',
  editGradientDir: '方向',
  editGradientDirs: {
    'top-bottom': '上 → 下',
    'bottom-top': '下 → 上',
    'left-right': '左 → 右',
    'right-left': '右 → 左',
  },
  editGradientStart: '起點',
  editGradientMid: '中間點',
  editGradientEnd: '終點',
  editGradientColor: '顏色',
  editGradientOpacity: '不透明度',
  editCrop: '裁切',
  editCropSides: { cropLeft: '左', cropRight: '右', cropTop: '上', cropBottom: '下' },
  editFlip: (on: boolean) => `左右翻轉${on ? '（開）' : ''}`,
  editRotate: (deg: number) => `轉 90°（目前 ${deg}°）`,
  editReset: '回到最初',
  editReplace: '取代原素材（引用舊圖的地方全部改用新圖）',
  editGo: '製作',
  editToFade: '轉成動態圖',
  editSuffix: '_加工',
  editSame: '加工結果和既有的素材相同，沒有新增',
  editDone: '已加入加工後的圖',
  editReplaced: '已取代原素材',
  editFailed: '加工失敗',

  /* ---------- 房間設計 ---------- */
  roomTitle: '房間設計',
  roomBasics: '基本',
  boardSize: '盤面大小',
  boardPresets: { '40x30': '40×30', '37x17': '37×17（橫長）', '32x18': '32×18（16:9）' },
  boardWidth: '寬（格）',
  boardHeight: '高（格）',
  boardNote: '只影響之後新建的場景；既有場景可以用「同步房間設計」套用。',
  roomBackground: '房間背景',
  roomForeground: '房間前景',
  roomBgHint: '背景＝盤面外側；前景＝盤面上的圖。',
  tachieBase: '立繪基準',
  tachieAlign: '對齊方式',
  tachieAligns: { bottom: '靠下', top: '靠上', center: '置中', position: '指定位置' },
  tachieLine: {
    bottom: '腳底的高度',
    top: '頭頂的高度',
    center: '中線的高度',
    position: '腳底的高度',
  },
  tachieDefaultSize: '立繪預設大小（格）',
  tachieDefaultSizeHint: '改了會把立繪庫所有立繪的高度一起改成這個值。',
  tachieX: '指定的水平位置',
  tachieGap: '等距排列間隔（格）',
  tachieGapHint: '跨專案的工具設定，與場景頁的間隔是同一個值。',
  projectDefaults: '本專案初始值',
  projectDefaultsCommon: '沿用共用值',
  projectDefaultsOwn: '本專案有自訂值',
  projectDefaultsRows: { z: '堆疊順序', size: '大小' },
  defaultsFields: {
    part: '共用標記大小',
    panelW: '螢幕面板寬度',
    tachieH: '立繪高度',
    zPart: '共用標記',
    zPanel: '螢幕面板',
    zTachie: '立繪',
    zEffect: '演出',
  },
  defaultsOwnNote: '本專案專用',
  defaultsHint:
    '留空＝用工具設定的共用值。只影響之後新建的東西；立繪的堆疊順序例外，沒有個別設定的立繪都會跟著改。',
  canvasNote: '這是房間本身（還沒切換場景時的樣子），與各場景無關。',
  zoomOut: '縮小',
  zoomIn: '放大',
  zoomFit: '顯示全部',
  guides: '前景參考線',
  guideColor: '參考線顏色',
  layersPanel: '圖層面板',
  realistic: '實際顯示',
  keysHelp: '操作說明',
  keysHelpItems: [
    '點部件選取；Shift／Ctrl（⌘）＋點加選或取消',
    '拖曳移動（1 格為單位）；按住 Shift 只能水平、垂直或 45°',
    '拖右下角改大小（以中心為準）',
    '方向鍵移動 1 格',
    '按住空白鍵或滑鼠中鍵拖曳平移畫布；滾輪縮放',
  ],
  selectHint: '點畫布上的部件選取；Shift／Ctrl＋點可以多選。',
  selCount: (n: number) => `已選 ${n} 個`,
  selDetail: '詳細',
  selClear: '取消選取',
  alignOps: {
    left: '靠左',
    hcenter: '水平置中',
    right: '靠右',
    top: '靠上',
    vcenter: '垂直置中',
    bottom: '靠下',
    hdist: '水平均分',
    vdist: '垂直均分',
    shrink: '縮小 ×0.9',
    grow: '放大 ×1.1',
  },
  quickCrop: '裁切',
  quickAlpha: '透明',
  quickFlip: '左右翻轉',
  quickFull: '完整加工…',
  quickCropSides: { left: '左', right: '右', top: '上', bottom: '下' },
  quickApply: '確定',
  quickCancel: '取消',
  quickReplace: '取代原素材',
  quickDiscard: '還沒確定的快速加工要捨棄嗎？',
  layerFront: '前景（固定）',
  layerLocked: '已鎖定',
  layerUnlocked: '未鎖定',
  layerVisible: '顯示',
  placeholder: '暫用立繪',
  placeholderAdd: '增加暫用立繪',
  placeholderNote: '暫用立繪只用來對位，不會輸出。拖本體改基準線，拖右下角改立繪預設大小。',
  partsTitle: '部件',
  partsLead: '放在哪一欄就建立哪一種；建立後畫面停在原處。',
  markersCol: '共用標記',
  panelsCol: '螢幕面板',
  markersHint: '所有場景都會出現的圖（マーカーパネル）。',
  panelsHint: '不隨場景切換的圖（スクリーンパネル）。',
  addMarker: '新增共用標記',
  addTachieSized: '新增立繪尺寸的部件',
  addPanel: '新增螢幕面板',
  fromMaterials: '從素材挑選',
  fromTemplates: '從共用範本加入',
  dropCreate: '把素材或圖片檔拖到這裡建立',
  partVisible: '顯示',
  partName: '名稱',
  partUp: '上移',
  partDown: '下移',
  toPanel: '改成螢幕面板',
  toMarker: '改成共用標記',
  switchedPanel: '已改成螢幕面板',
  switchedMarker: '已改成共用標記',
  partCopy: '複製',
  partDelete: '刪除',
  partImage: '圖片',
  partLockAspect: '固定長寬比',
  partLocked: '鎖定（畫布上不能拖）',
  posX: '水平位置',
  posY: '垂直位置',
  zOrder: '堆疊順序',
  width: '寬',
  height: '高',
  partDetails: '詳細',
  partToTemplate: '收進共用範本',
  partText: '盤面文字',
  partTextMarker: '共用標記上顯示的文字',
  partTextPanel: '螢幕面板的備註',
  partUsage: '場景使用狀況',
  partUsageNone: '沒有任何場景的差異，會出現在所有場景。',
  partUsageKinds: { hidden: '隱藏', image: '換圖', moved: '位置不同' },
  partUsageCount: (n: number) => `${n} 個場景`,
  partNoImage: '沒有圖的部件不會輸出。',
  noParts: '還沒有部件。',
  templateNeedImage: '只有有圖的部件可以收進範本',
  templateSaved: '已收進共用範本',
  templateOverwrite: (n: string) =>
    `已經有叫「${n}」的範本了。要覆蓋嗎？（選「另取名稱」可以換個名字）`,
  templateRename: '另取名稱',
  templateOverwriteBtn: '覆蓋',
  templateNameDup: (n: string) => `「${n}」也已經有了，沒有儲存`,
  templateNewName: '新的範本名稱',
  partTemplatesTitle: '從共用範本加入',
  partTemplatesNote: '這裡只能加入；要刪除範本請到工具設定的「範本與預設」。',
  partTemplatesEmpty: '還沒有部件範本。部件卡片的「詳細」裡可以收進範本。',
  templateAdd: '加入',
  templateAdded: '已加入部件',

  /* ---------- 場景 ---------- */
  scenesTitle: '場景',
  createArea: '建立場景',
  createCollapse: '收起',
  createExpand: '展開',
  quickName: '場景名稱',
  quickFg: '前景',
  quickFgEmpty: '之後再選',
  quickCreate: '建立',
  symbols: '名稱符號',
  fromMaterialsScene: '從素材挑選建立',
  bulkCreate: '貼上建立多個場景',
  sceneTemplates: '場景範本',
  sceneCreated: '已建立場景',
  sceneList: '場景一覽',
  multiMode: (on: boolean) => (on ? '批次選取模式：開' : '批次選取模式'),
  multiModeOn: '批次選取模式：點一下就加入或取消勾選',
  multiModeOff: '批次選取模式已關閉',
  checkAll: '全部勾選',
  checkNone: (n: number) => `取消勾選（${n}）`,
  sceneRename: '批次改名',
  moveUp: '上移',
  moveDown: '下移',
  moveTop: '移到最前',
  moveBottom: '移到最後',
  needChecked: '請先勾選場景',
  noScenes: '還沒有場景。',
  pickScene: '從左邊的一覽選一個場景。',
  sceneMarks: { tachie: '有登場立繪', effect: '有演出', cutin: '有切入' },
  sceneCopy: '複製',
  sceneUp: '上移',
  sceneDown: '下移',
  sceneDelete: '刪除',
  sceneBookmark: '記下本場景設定',
  sceneBookmarkOn: '取消記下的設定',
  sceneForeground: '前景',
  sceneMemo: '備忘（不會輸出）',
  sceneAdvanced: '詳細設定',
  sceneText: '切換時文字',
  sceneTextHint: '切換到這個場景時送到聊天的文字。',
  sceneFinal: '最終切換文字',
  sceneFinalNone: '無',
  sceneFieldSize: '前景尺寸（格）',
  sceneAutoCrop: '前景自動裁切（關閉時拉伸填滿）',
  sceneGrid: '顯示格線',
  sceneBackground: '背景',
  sceneBgModes: {
    room: '沿用房間背景',
    foreground: '與前景相同',
    image: '個別素材',
    none: '沒有背景',
  },
  sceneBgImage: '背景圖',
  syncRoom: '同步房間設計',
  syncThis: '這個場景',
  syncChecked: (n: number) => `勾選的場景（${n}）`,
  syncAll: '所有場景',
  syncConfirm: (n: number) =>
    `要把 ${n} 個場景的前景尺寸、自動裁切、格線改成房間設計，並清除共用部件的差異嗎？`,
  syncDone: (n: number) => `已同步 ${n} 個場景`,
  syncHint:
    '前景尺寸改成目前盤面、自動裁切開、格線關，並清除共用部件的差異；前景圖片、立繪、演出、切入不變。',
  secTachie: '立繪',
  secEffect: '演出',
  secCutin: '切入',
  secParts: '共用部件',
  secHelp: {
    tachie: '勾選角色就會登場並自動等距排列；名稱可以開啟立繪的共用設定。',
    effect: '只在這個場景出現的圖或字。全畫面會自動配合盤面大小。',
    cutin: '一個場景最多一個切入；切換時文字會自動加上「@切入名稱」。',
    parts: '這個場景和共用標記的差異（換圖、移位、改大小、隱藏）。',
  },
  count: (n: number) => `${n} 項`,
  tachieEmpty: '立繪庫是空的，先到「立繪庫」登錄立繪。',
  tachieFace: '差分',
  tachieMain: '主立繪',
  tachieSwapLeft: '和左邊的立繪對調位置',
  tachieSwapRight: '和右邊的立繪對調位置',
  tachieSize: '大小',
  tachieLayout: '等距排列',
  tachieGapShort: '間隔',
  effectAdd: '加入',
  effectNew: '新建',
  effectAdded: '已加入演出',
  effectImageEmpty: '無圖',
  effectMode: '出現方式',
  effectModes: { full: '全畫面', free: '調整大小' },
  effectCover: '等比蓋滿（取消時拉伸）',
  effectContain: '這是舊資料的「完整放入」模式。',
  effectOptions: '選項',
  effectName: '演出名稱',
  effectText: '盤面文字',
  effectFade: '動態圖',
  effectToPreset: '收進演出預設',
  effectPresetMatch: (n: string) => `★ ${n}`,
  effectCopy: '複製',
  effectDelete: '刪除',
  presetDup: (n: string) => `已經有叫「${n}」的演出預設了。要覆蓋嗎？`,
  presetSaved: '已收進演出預設',
  cutinChoice: '切入',
  cutinNew: '新建',
  cutinAssigned: '已指定切入',
  cutinName: '名稱',
  cutinToTemplate: '收進切入範本',
  cutinUnassign: '移除',
  cutinCount: (n: number) => (n ? '1 項' : '0 項'),
  overridesShowAll: (n: number) => `顯示全部（${n}）`,
  overridesShowDiff: '只顯示有差異的',
  overridesNoMarkers: '還沒有共用標記。',
  overridesNoDiff: '這個場景沒有差異，全部和共用相同。',
  overridesPanelNote: '螢幕面板不分場景（CCFOLIA 的スクリーンパネル），這裡不列。',
  overrideState: {
    same: '與共用相同',
    hidden: '隱藏',
    image: '圖片',
    position: '位置',
    size: '大小',
    z: '堆疊順序',
    changed: '變更',
  },
  overrideImage: '這個場景的圖',
  overrideEdit: '變更',
  overrideReset: '回到預設',
  overrideResetDone: '已回到共用設定',
  overrideHide: '本場景隱藏',
  overrideBlank: (v: number) => `共用：${v}`,
  clipTitle: '記下的設定',
  clipFrom: (n: string) => `來源：${n}`,
  clipNoFg: '沒有前景',
  clipTargets: (n: number, cur: string) =>
    n ? `貼上到勾選的 ${n} 個場景` : `貼上到目前的場景「${cur}」`,
  clipNoTarget: '請先選一個場景',
  clipNotes: '名稱不在貼上的範圍；再按一次書籤可以取消。',
  clipAll: '全部貼上',
  clipKinds: {
    tachie: (n: number) => `立繪（${n} 項）`,
    effect: (n: number) => `演出（${n} 項）`,
    cutin: (n: number) => `切入（${n} 項）`,
    overrides: '共用部件差異',
    text: '文字與備忘',
    image: '前景與背景',
  },
  clipClose: '不再記住',
  clipSaved: (n: string) => `已記下「${n}」的設定`,
  clipPasted: (n: number) => `已貼上到 ${n} 個場景`,
  clipNone: '還沒有記下任何場景的設定',
  bulkTitle: '貼上建立多個場景',
  bulkLead:
    '一行一個場景：「場景名稱, 切換時文字, 前景素材名稱」（Tab 或逗號分隔）。第一行是表頭時會略過。',
  bulkGo: '建立',
  bulkFile: '讀取 CSV／TSV／TXT',
  bulkDone: (n: number) => `已建立 ${n} 個場景`,
  bulkNone: '沒有可以建立的場景（場景名稱是空白）',
  bulkFileFailed: (e: string) => `讀取失敗：${e}`,
  templatesTitle: '場景範本',
  templatesLead:
    '範本包含：前景、背景、前景尺寸、裁切與格線、切換時文字、共用部件差異、立繪與演出、切入。名稱與備忘不包含。範本存在專案裡。',
  templateRegister: '把目前場景登錄為範本',
  templateName: '範本名稱',
  templateNew: '以範本新建場景',
  templateApply: '套用到目前場景',
  templateApplyKeep: '套用（保留目前前景）',
  templateDelete: '刪除',
  templatesEmpty: '還沒有場景範本。',
  templateRegistered: '已登錄範本',
  templateApplied: '已套用範本',
  templateCreated: '已用範本建立場景',
  needScene: '請先選一個場景',
  multiTitle: {
    scene: '從素材挑選建立場景',
    tachie: '從素材挑選登錄立繪',
    marker: '從素材挑選建立共用標記',
    panel: '從素材挑選建立螢幕面板',
    cutin: '從素材挑選建立切入',
  },
  multiLead: '依點選的順序建立；Shift＋點可以把上一個到這一個之間全部加入。',
  multiOrder: (n: number) => `第 ${n} 個`,
  multiAll: '全選',
  multiNone: '取消',
  multiOthers: (t: string) => `「${t}」以外的素材也列出`,
  multiGo: (n: number, what: string) => `用 ${n} 個做${what}`,
  multiWhat: {
    scene: '場景',
    tachie: '立繪',
    marker: '共用標記',
    panel: '螢幕面板',
    cutin: '切入',
  },
  multiEmpty: '沒有符合的素材。',
  multiNoMaterials: '還沒有素材',
  multiNoneSelected: '請先選取素材',
  sceneRenameTitle: '場景批次改名',
  sceneRenameTarget: (n: number, checked: boolean) =>
    checked ? `對象：勾選的 ${n} 個場景` : `對象：全部 ${n} 個場景`,
  renameLead: '一行一個名稱，依序對應右邊的清單；空行或沒有改的不變。',
  renameGo: '套用',
  renameDone: (n: number) => `已改名 ${n} 個`,
  materialRenameTitle: '素材批次改名',
  materialRenameTarget: (n: number, sel: boolean) =>
    sel ? `對象：選取的 ${n} 張` : `對象：目前列出的 ${n} 張`,

  /* ---------- 預覽 ---------- */
  previewScene: '場景',
  previewRoom: '房間本身（不套場景）',
  previewModes: { fit: '貼合盤面', far: '拉遠一點', farther: '拉更遠' },
  previewHeights: { small: '小', normal: '標準', large: '大' },
  previewHeight: '預覽高度',
  previewGuides: (on: boolean) => `參考線 ${on ? 'ON' : 'OFF'}`,
  previewPanHint: '按住空白鍵或中鍵拖曳平移',
  previewScope: '只動這個場景',
  previewScopeHint: '取消時拖曳共用標記會改所有場景的位置。',
  previewFar: '拉遠時也看得到盤面外；參考線框內才是實際範圍。',
  previewNoParts: '還沒有部件；房間設計可以加螢幕面板或共用標記。',
  previewDragInfo: (x: number, y: number, scope: string) => `位置 ${x}, ${y}（${scope}）`,
  previewSizeInfo: (w: number, h: number, scope: string) => `大小 ${w}×${h}（${scope}）`,
  previewScopeScene: '只限本場景',
  previewScopeAll: '所有場景',
  layersTitle: '圖層',
  layerHide: '預覽暫時隱藏',
  layerLock: '本場景的預覽裡鎖定',
  layerTrueHide: '此場景徹底隱藏',
  layerPanelNote: '螢幕面板不分場景，只影響預覽',
  layerZ: '堆疊順序',
  layerZPrompt: '新的堆疊順序（可負數）',
  layerCutin: '切入（固定在中央）',
  layerFg: '前景（0）',
  tachiePreviewNote: '立繪庫全部排在同一條基準線上；上下拖曳改腳底抬升，拖右下角改高度。',
  tachiePreviewShowAll: '全部顯示',

  /* ---------- 右側素材 ---------- */
  mediaTarget: (n: string) => `目前場景：${n}`,
  mediaNoTarget: '選了場景才能直接設成前景。',
  mediaAsFg: '當前景',
  mediaAsTachie: '當立繪',
  mediaFgDone: '已設成目前場景的前景',
  mediaTachieDone: '已登錄到立繪庫',
  mediaEmpty: '還沒有素材，把圖片拖進畫面就會加入。',
  mediaDragHint: '縮圖可以拖到選圖欄或虛線的建立區。',

  /* ---------- 立繪庫 ---------- */
  tachieTitle: '立繪庫',
  tachieLead: '登錄角色的立繪與表情差分；在場景裡勾選才會登場。',
  tachieAdd: '新增',
  tachieFromMaterials: '從素材挑選登錄',
  tachieAll: '全部',
  tachieBulk: '批次設定',
  tachieBulkLead: '只改主立繪與單獨設定的差分；長寬比不變，差分跟著主立繪。',
  tachieBulkFields: { height: '高度', dy: '腳底抬升', z: '堆疊順序' },
  tachieBulkApply: '全部套用',
  tachieBulkEmpty: '請輸入數值',
  tachieBulkNaN: '請輸入數字',
  tachieBulkDone: (n: number) => `已改 ${n} 張`,
  tachieImage: '圖片',
  tachieOriginal: (n: string) => `原始檔名：${n}`,
  tachieCharacter: '角色名稱',
  tachieExpression: '表情名稱',
  tachieCopy: '複製',
  tachieMakeFace: '做表情差分',
  tachieFaceMade: '已做出表情差分；它的大小與位置跟著主立繪',
  tachieDelete: '刪除',
  tachieFaceOf: (n: string) => `表情差分（主立繪：${n}）`,
  tachieSolo: '此差分單獨設定',
  tachieSoloOff: (h: number, dy: number, z: number) =>
    `大小與腳底沿用主立繪：高 ${h}、抬升 ${dy}、堆疊順序 ${z}`,
  tachieHeight: '大小（高，格）',
  tachieDy: '腳底抬升（格）',
  tachieZ: '堆疊順序',
  tachieReadout: (w: number, h: number, iw: number, ih: number, y: number) =>
    iw
      ? `在 CCFOLIA 的大小 ${w}×${h} 格（原圖 ${iw}×${ih} px，比例不變）・垂直位置 ${y}`
      : `在 CCFOLIA 的大小 ${w}×${h} 格・垂直位置 ${y}`,
  tachieNone: '還沒有立繪。',

  /* ---------- 切入 ---------- */
  cutinsTitle: '切入',
  cutinsLead:
    '只做名稱與圖（聲音到 CCFOLIA 再加）。場景指定切入後，切換時文字會自動加上「@名稱」。',
  cutinAdd: '新增',
  cutinFromMaterials: '從素材挑選建立',
  cutinHint: (n: string) => `場景指定後會以「@${n}」放進切換時文字`,
  cutinCopy: '複製',
  cutinDelete: '刪除',
  cutinSelect: '選取並存成範本',
  cutinSelected: (n: number) => `已選 ${n} 個`,
  cutinSelectAll: '全選',
  cutinSelectNone: '取消',
  cutinSaveSelected: '選取的收進範本',
  cutinSelectEnd: '結束',
  cutinSavedN: (n: number) => `已收進 ${n} 個切入範本`,
  cutinDupConfirm: (names: string) => `有重複的名稱：${names}。要覆蓋同名的範本嗎？`,
  cutinTemplates: (n: number) => `切入範本（${n}）`,
  cutinTemplateName: '名稱',
  cutinSeparator: '分隔名稱',
  cutinSeparatorAdd: '加入分隔',
  cutinSeparatorEmpty: '請輸入分隔名稱',
  cutinTemplateUse: '使用',
  cutinTemplateUsed: '已加入切入',
  cutinTemplateRenameDup: (n: string) => `已經有叫「${n}」的範本了，還是要改成這個名稱嗎？`,
  cutinNone: '還沒有切入。',
  dragHandle: '拖曳排序',

  /* ---------- 劇本文字 ---------- */
  storyTitle: '劇本文字',
  storyLead: '整理劇本的段落（只存在工具與專案檔，不會輸出到 ZIP）。',
  storyModes: { single: '一筆', bulk: '批次' },
  storyTitleField: '標題',
  storyBody: '正文',
  storyAddOne: '登錄',
  storyToTemplate: '存成範本',
  storyAdded: '已登錄',
  storyBulkText: '整段文字',
  storyInsertSep: '插入分隔線',
  storyInsertTitle: '插入標題記號 #',
  storySplitSettings: '分割設定',
  storySplitSummary: (d: string, blank: boolean) =>
    `分隔：${d || '（無）'}${blank ? '・空白行也分割' : ''}`,
  storyDelimiter: '分隔字串',
  storySplitBlank: '空白行也當分隔',
  storyBulkCount: (n: number) => `共 ${n} 筆`,
  storyBulkPreview: '標題預覽',
  storyBulkGo: '批次登錄',
  storyBulkNone: '沒有可以登錄的段落',
  storyBulkDone: (n: number) => `已登錄 ${n} 筆`,
  storyTemplates: (n: number) => `範本（${n}）`,
  storyTemplateUse: '使用',
  storyTemplateDelete: '刪除',
  storyTemplateSaved: '已存成範本',
  storyList: (n: number) => `一覽（${n}）`,
  storyEmpty: '還沒有劇本文字。',
  storySelected: (n: number) => `已選 ${n} 筆`,
  storyDelete: '刪除',

  /* ---------- 棋子 ---------- */
  piecesTitle: '棋子',
  piecesLead: '棋子匯入後放在盤面外待命，聊天面板一起輸出。',
  kpTitle: 'KP 設定',
  kpSystem: '系統',
  kpCheck: '判定指令',
  kpOwnSkills: 'KP 自己的技能',
  kpSkillName: '技能名',
  kpSkillValue: '技能值',
  kpAddSkill: '加入技能',
  kpPcs: 'PC 名單',
  kpPcName: 'PC 名稱',
  kpAddPc: '加入 PC',
  kpTemplates: 'KP 範本',
  kpTplFields: { main: '通用骰子與進行', scene: '場景與切入', memo: '備忘' },
  kpTplNote: '每個系統各自保存一份。',
  kpShared: '共用 KP 範本',
  kpSharedLoad: '讀取',
  kpSharedSave: '存到共用',
  kpSharedDelete: '刪除',
  kpSharedNone: '（沒有共用範本）',
  kpSharedPick: '請先選一個共用範本',
  kpSharedName: '共用 KP 範本的名稱',
  kpSharedDefault: (sys: string) => `${sys} 範本`,
  kpSharedDup: (n: string) => `同一個系統已經有「${n}」了。要覆蓋嗎？`,
  kpSharedSaved: '已存到共用 KP 範本',
  kpSharedLoaded: '已讀取共用 KP 範本',
  kpSharedDeleted: '已刪除共用 KP 範本',
  kpGenerate: '產生 KP 用棋子',
  kpGenerated: '已更新 KP 用棋子的聊天面板',
  addEnemy: '加入敵方 NPC',
  addAlly: '加入友方 NPC',
  addNormal: '加入一般棋子',
  pieceKinds: { kp: 'KP 棋子', enemy: '敵方', ally: '友方', normal: '一般' },
  pieceName: '名稱',
  pieceIcon: '圖示',
  pieceHp: 'HP',
  pieceMp: 'MP',
  pieceToTemplate: '收進棋子範本',
  pieceKpNoTemplate: 'KP 用棋子不能收進範本',
  pieceDelete: '刪除',
  pieceFaces: (n: number) => `表情差分（${n}）`,
  pieceFaceName: '差分名稱',
  pieceFaceAdd: '加入差分',
  pieceArmor: '裝甲',
  pieceDodge: { coc: '迴避', emo: '迴避骰子數' },
  pieceNoDodge: '沒有迴避',
  pieceSkills: '技能',
  pieceSkillValue: { coc: '技能值', emo: '骰子數' },
  pieceDamage: '傷害',
  pieceCommands: '聊天面板',
  pieceMemo: '備忘',
  piecesNone: '還沒有棋子。',
  pieceTemplatesTitle: '棋子範本（跨專案）',
  pieceTemplatesEmpty: '棋子卡片上可以收進範本。',
  pieceTemplateDetail: '詳細',
  pieceTemplateUse: '加入',
  pieceTemplateDelete: '刪除',
  pieceTemplateSaved: '已收進棋子範本',
  pieceTemplateUsed: '已加入棋子',
  pieceTemplateSummary: (kind: string, parts: string[]) => [kind, ...parts].join('・'),

  /* ---------- 儲存與說明 ---------- */
  saveTitle: '儲存與匯出',
  saveDownload: '儲存（下載專案檔）',
  newRoom: '開新房間',
  newRoomConfirm: '要開新的房間嗎？目前的內容與素材會清空（跨專案的設定與範本不受影響）。',
  newRoomDone: '已開新的房間',
  helpTitle: '說明',
  saving: '儲存中…',
  saved: (size: string) => `已儲存（${size}）`,
  saveFailed: (e: string) => `儲存失敗：${e}`,
  opened: '已讀取專案',
  openFailed: (e: string) => `讀不了這個檔案：${e}`,
  openConfirm: '讀取專案會取代目前的內容（可以復原）。要繼續嗎？',

  /* ---------- 工具設定 ---------- */
  settingsTitle: '工具設定',
  settingsLead: '這裡的設定對同一個瀏覽器裡的每個專案都有效。',
  settingsCats: {
    display: '顯示與操作',
    create: '建立與素材',
    templates: '範本與預設',
    save: '儲存與匯出',
  },
  themeNote: '亮色／暗色在頁首右上角切換。',
  shortcutsTitle: '快捷鍵',
  shortcutsLead: '在輸入欄裡打字時，只有儲存與另存新檔的快捷鍵有效。',
  shortcutRecord: '錄製按鍵',
  shortcutRecording: '請按下新的按鍵組合…',
  shortcutClear: '解除',
  shortcutNone: '未設定',
  shortcutReset: '回到預設值',
  shortcutDup: (n: string) => `這個按鍵已經給「${n}」用了`,
  shortcutSet: (k: string) => `已設定為 ${k}`,
  shortcutGroups: { basic: '基本', view: '畫面', pages: '移到頁面', parts: '部件（房間設計頁）' },
  defaultsZTitle: '新物件的預設堆疊順序',
  defaultsSizeTitle: '新物件的預設大小（格）',
  defaultsNote: '既有的物件不變；本專案有自訂值時以本專案為準。',
  panelAuto: '0＝自動（比盤面窄三格）',
  symbolsTitle: '場景名稱符號',
  symbolsHint: '以空白、逗號或頓號分隔。',
  sitesTitle: '找圖網站',
  sitesHint: '網址裡的「{關鍵字}」會換成搜尋的字；沒有記號時接在最後。',
  siteName: '網站名稱',
  siteUrl: '搜尋網址',
  siteAdd: '新增網站',
  siteReset: '恢復預設清單',
  siteResetConfirm: '要把找圖網站恢復成預設清單嗎？',
  presetsTitle: '演出預設',
  presetsLead: '場景演出的下拉清單就是這份清單。圖片本體存在瀏覽器裡。',
  presetName: '名稱',
  presetImage: '圖片',
  presetKind: '種類',
  presetFit: '填滿方式',
  presetFits: { stretch: '拉伸', cover: '蓋滿', contain: '完整放入' },
  presetRegister: '登錄',
  presetDefaultName: '演出預設',
  presetSeparator: '分隔名稱',
  presetSeparatorAdd: '加入分隔',
  presetDeleteConfirm: (n: string) => `要刪除演出預設「${n}」嗎？`,
  presetsEmpty: '還沒有演出預設。',
  manageTitle: '共用範本管理',
  manageExport: '匯出範本',
  manageImport: '讀取範本檔',
  manageImported: (n: number) => `已加入 ${n} 個範本`,
  manageImportFailed: '讀不了這個範本檔',
  manageNote: '部件、棋子、演出預設與切入範本會在瀏覽器保存圖片本體；匯出的範本檔不含圖片。',
  manageKinds: {
    scene: '場景範本',
    marker: '共用標記',
    panel: '螢幕面板',
    piece: '棋子',
    cutin: '切入',
  },
  manageEdit: '編輯',
  manageUse: '使用',
  manageDelete: '刪除',
  autosavesTitle: '自動儲存',
  autosavesLead:
    '專案有變更時每 10 分鐘在瀏覽器存一份（最多 5 份）。自動儲存裡沒有圖片資料，圖片不在這個瀏覽器時要重新放圖。',
  autosaveRestore: (t: string) => `${t} 還原`,
  autosaveConfirm: '要還原這份自動儲存嗎？還原前的狀態可以用「復原」回來。',
  autosaveRestored: '已還原自動儲存',
  autosavesNone: '還沒有自動儲存。',
  saveTargetTitle: '覆蓋儲存的目標',
  saveTargetSupported: '「儲存」會寫回同一個檔案（第一次會問存放位置）。',
  saveTargetChoose: '改選存檔位置',
  saveTargetUnsupported: '這個瀏覽器不能寫回檔案，每次儲存都會下載新檔。',
  roomOutTitle: '輸出到房間設定',
  bgmCrossfade: 'BGM 交叉淡化',
  legacyDice: '舊式骰子（不用 3D 骰子）',
  roomOutNote: '這兩項存在專案裡。',
  noimageTitle: '空白演出格',
  noimageOn: '匯出時在每個場景放空白的全畫面格',
  noimageCount: '張數',
  noimageZ: '堆疊順序',
  noimageNote: '匯入後把演出圖放進這些格就好；工具畫面上不會顯示。',
  guideSettings: '前景參考線',

  /* ---------- 匯出 ---------- */
  exportNothing: '沒有場景也沒有素材，沒有東西可以匯出',
  exportSteps: { prepare: '確認並建立', assemble: '組裝資料', check: '檢查內容' },
  exportBroken: '有圖片找不到資料，先修復再匯出',
  exportAborted: (p: string) => `已中止：${p}`,
  exportDone: (scenes: number, images: number, pieces: number, size: string) =>
    `完成：場景 ${scenes} 個、圖片 ${images} 張、棋子 ${pieces} 個（約 ${size}）`,
  exportFailed: (e: string) => `匯出失敗：${e}`,
  problems: {
    folder: 'ZIP 裡有資料夾',
    'no-token': '缺少 .token',
    'no-data': '缺少 __data.json',
    'bad-json': '__data.json 不是正確的 JSON',
    'missing-image': '資料裡列出的圖片不在 ZIP 裡',
    'orphan-image': 'ZIP 裡有資料沒列出的圖片',
    'hash-mismatch': '圖片的檔名和內容不符',
    'dangling-ref': '引用的圖片不在 ZIP 裡',
  } as Record<string, string>,
  brokenDialog: '修復找不到的圖片',
  brokenNone: '沒有找不到的圖片了。',
  brokenContinue: '繼續匯出',
  brokenCount: (n: number) => `有 ${n} 張圖片找不到資料`,
  brokenLead: '下面的圖片被引用了，但工具裡沒有它的資料（例如換了瀏覽器、清掉了網站資料）。',
  brokenReplace: '替代素材',
  brokenReplaceNone: '（不換）',
  brokenAuto: '自動復原',
  brokenAutoDone: (n: number) => `復原了 ${n} 張`,
  brokenApply: '套用替代素材',
  brokenApplied: (n: number) => `換掉了 ${n} 張`,
  brokenUpload: '補上原圖',
  brokenUploadFor: '要補哪一張',
  brokenUploaded: '已補上',
  brokenExclude: '只排除遺失的圖後匯出',
  brokenExcludeConfirm: '要把這些引用清空後匯出嗎？被排除的地方會變成沒有圖。',
  brokenExcludeNote: '被排除的地方會變成空白。',

  /* ---------- 快捷鍵名稱 ---------- */
  actions: {
    undo: '復原',
    redo: '重做',
    save: '覆蓋儲存',
    saveAs: '另存新檔',
    export: '匯出',
    toggleRight: '右側面板顯示切換',
    toggleBottom: '備忘／待辦欄展開切換',
    toggleTheme: '切換主題',
    prevScene: '上一個場景',
    nextScene: '下一個場景',
    quickScene: '跳到場景頁的快速建立',
    goMaterials: '素材',
    goScenes: '場景',
    goMarkers: '共用標記',
    goTachie: '立繪庫',
    goPanels: '螢幕面板',
    goCutins: '切入',
    goPieces: '棋子',
    goStory: '劇本',
    goRoom: '房間設定',
    goSettings: '工具設定',
    goSave: '儲存與說明頁',
    partOpen: '開啟選取部件的設定',
    partLock: '選取部件的鎖定切換',
    partVisible: '選取部件的顯示切換',
  } as Record<string, string>,
  partNeedOne: '請剛好選一個部件',
  partNeedSel: '請先在畫布上選取部件',
  partsLocked: (on: boolean) => (on ? '已鎖定選取的部件' : '已解除鎖定'),
  partsShown: (on: boolean) => (on ? '已顯示選取的部件' : '已隱藏選取的部件'),

  /* ---------- 說明 ---------- */
  usageIntro:
    '把自己的圖片整理成 CCFOLIA 可以直接匯入的房間 ZIP。全部在瀏覽器裡處理，不會上傳任何東西。',
  usageSteps: [
    '放入素材：把圖片拖進畫面，工具會依長寬比推測用途（前景、立繪、面板…）。',
    '房間設計：設定盤面格數、背景與前景，加入每個場景都會出現的共用部件，用拖曳擺位置。',
    '場景：從素材挑選建立（圖片會成為前景），再勾選登場的立繪、加入演出與切入。',
    '匯出房間 ZIP，在 CCFOLIA 開一個新房間，到房間設定用匯入功能讀入。',
  ],
  usageNotes: [
    'BGM 與音效不在這裡處理，匯入後到 CCFOLIA 設定；切入只做名稱與圖，場景指定切入後切換時文字會自動加上「@名稱」。',
    '儲存（Ctrl／⌘＋S）會寫回同一個專案檔（第一次會問存放位置；Chrome、Edge 才能寫回，其他瀏覽器每次下載）；Ctrl／⌘＋Shift＋S 另存新檔。專案檔裡有圖片、整體備忘與待辦。',
    '專案會自動存在這個瀏覽器，下次打開會還原；工具設定裡的「自動儲存」是每 10 分鐘一份的備份，裡面沒有圖片資料。',
    '右側「素材」的縮圖可以拖到任何選圖欄直接替換，拖到虛線的建立區就建立一個；把圖片檔丟到畫面任何地方會加入素材。',
    'Shift＋拖曳只能水平、垂直或 45°；在輸入欄裡 Ctrl／⌘＋Z 是文字的復原。',
    '棋子匯入後在盤面外待命，要用時再拖進盤面；聊天面板一起輸出。空白演出格可以在匯入後放演出圖。',
    '這是非官方工具；CCFOLIA 改版時可能需要更新。',
  ],
} as const;
