/** 角色分析圖產生器的介面文字 */
import type { AxisKey, ChartKind, LabelKey, LineStyle, Marker } from './model';
import type { CompareMode } from './store';

export const S = {
  /* 圖表 */
  chart: '圖表',
  charts: { quadrant: '四象限', relation: '關係圖' } satisfies Record<ChartKind, string>,
  chartAria: {
    quadrant: '性格四象限',
    relation: '角色關係圖',
  } satisfies Record<ChartKind, string>,

  /* 角色 */
  sectionCharacters: '角色',
  charactersHint: '兩張圖共用同一份角色清單。',
  addTitle: '新增角色',
  name: '名字',
  namePlaceholder: '例如 艾琳',
  color: '顏色',
  image: '圖片（選填）',
  imageField: '圖片',
  imageDropLabel: '角色圖片',
  imageChoose: '選擇圖片',
  imageChosen: (name: string) => `圖片：${name}`,
  imageClear: '不用圖片',
  addButton: '加入角色',
  addHintQuadrant: '加入後放在目前這一頁的中央；在名字欄按 Enter 也可以加入。',
  addHintRelation: '加入後會出現在關係圖上；在名字欄按 Enter 也可以加入。',
  needName: '請輸入名字。',
  batchLabel: '一次加入多張圖片',
  batchAria: '從圖片加入角色',
  batchDrop: '把角色圖片拖到這裡',
  batchHint: '可以多選；每張圖片一個角色，名字取自檔名。拖到視窗任何地方也可以。',
  batchButton: '選擇圖片',
  windowDrop: '放開即可加入角色',
  windowDropHint: '每張圖片一個角色，名字取自檔名',
  notImage: (names: string) => `「${names}」不是圖片檔。`,
  decodeError: (names: string) => `無法讀取「${names}」，檔案可能已損壞。`,
  imageNotSaved: '瀏覽器空間不足或無法存檔：圖片這次可以用，但重新整理之後就不見了。',
  added: (name: string) => `已加入「${name}」。`,
  addedMany: (n: number) => `已加入 ${n} 個角色。`,
  limitReached: (n: number) => `角色最多 ${n} 個。`,
  listLabel: '角色清單',
  listEmpty: '還沒有角色。在上面輸入名字加入，或一次加入多張圖片。',
  listHint: '拖曳左邊的把手調整順序（四象限：後面的畫在上面；關係圖：繞圈的順序）。',
  count: (n: number) => `${n} 個`,
  noName: '（沒有名字）',
  onPage: '在這一頁',
  notOnPage: '不在這一頁',
  place: '放到這一頁',
  placed: (name: string) => `已把「${name}」放到這一頁的中央。`,
  inMap: '放進關係圖',
  mapOrder: (n: number) => `#${n}`,
  remove: '刪除',
  clearCharacters: '刪除所有角色',
  clearTitle: '刪除所有角色？',
  clearDesc: '兩張圖上的角色、位置與連線都會刪掉（頁面、線的種類與標題留著；可以復原）。',
  clearConfirm: '全部刪除',

  /* 選取的角色 */
  sectionSelected: '選取的角色',
  marker: '四象限的標記',
  markers: { dot: '圓點', image: '圖片' } satisfies Record<Marker, string>,
  markerHint: '沒有圖片時一律畫圓點；圖片寬 50 px。',
  changeImage: '換圖片',
  addImage: '加上圖片',
  removeImage: '拿掉圖片',
  imageMissing: '圖片讀不到了（可能已從這個瀏覽器清除），請重新選擇。',
  inMapHint: '拿出關係圖時，這個人的連線會一起刪掉（可以復原）。',
  unplace: '從這一頁拿掉',
  deleteCharacter: '刪除角色',
  selectedHint: '方向鍵移動 1 px（Shift 10 px），Delete 從這一頁拿掉。',

  /* 四象限：頁 */
  sectionPage: '這一頁',
  axis: { title: '標題', top: '上', bottom: '下', left: '左', right: '右' } satisfies Record<
    LabelKey,
    string
  >,
  axisLabel: (k: AxisKey) =>
    ({ top: '上方的軸名', bottom: '下方的軸名', left: '左方的軸名', right: '右方的軸名' })[k],
  pageHint: '也可以在圖上的標題或軸名按兩下直接修改。',
  pageBar: '頁面',
  prevPage: '上一頁',
  nextPage: '下一頁',
  pageOf: (i: number, n: number) => `第 ${i}／${n} 頁`,
  addPage: '新增一頁',
  deletePage: '刪除這一頁',
  pageAdded: '已新增一頁。',
  pageDeleted: '已刪除這一頁。',
  lastPage: '至少要留一頁。',
  pageLimit: (n: number) => `最多 ${n} 頁。`,
  deletePageTitle: '刪除這一頁？',
  deletePageDesc: '這一頁的標題、軸名與角色的位置會一起刪掉（角色本身留著；可以復原）。',
  deletePageConfirm: '刪除',

  /* 契合度 */
  sectionScore: '契合度',
  compare: '比較',
  compares: { pair: '兩個角色', group: '全體平均' } satisfies Record<CompareMode, string>,
  pickA: '第一個角色',
  pickB: '第二個角色',
  pickPlaceholder: '選擇角色',
  pickTwo: '請選兩個角色。',
  pickDifferent: '請選兩個不同的角色。',
  needTwo: '至少要有兩個角色。',
  colPage: '頁面',
  colScore: '契合度',
  colAverage: '平均契合度',
  average: '平均',
  groupAverage: '全體平均',
  groupNote: '所有角色兩兩組合的平均。',
  scoreNote:
    '兩個角色位置相同時是 100%，離得很遠時會低於 0%；每一頁分開計算，不在那一頁的角色不算。',
  untitled: '（沒有標題）',

  /* 座標碼 */
  sectionShare: '座標碼',
  shareLabel: '這一頁的座標碼',
  shareHint: '只有這一頁的角色名字、顏色與位置（沒有圖片），方便貼給別人或貼到另一頁。',
  sharePlaceholder: '按「複製座標碼」產生，或把別人的座標碼貼在這裡再按「加入座標」。',
  copyShare: '複製座標碼',
  applyShare: '加入座標',
  shareCopied: '已複製這一頁的座標碼。',
  shareCopyFailed: '瀏覽器不讓網頁複製，請自己選取文字複製。',
  shareEmpty: '請先貼上座標碼。',
  shareBad: '座標碼的格式不對。',
  shareResult: (added: number, updated: number, skipped: number) => {
    const parts: string[] = [];
    if (added) parts.push(`加入 ${added} 個角色`);
    if (updated) parts.push(`更新 ${updated} 個角色的位置`);
    if (skipped) parts.push(`${skipped} 個因為角色數已滿沒有加入`);
    return parts.length ? `已${parts.join('、')}。` : '沒有任何變更。';
  },

  /* 關係圖 */
  sectionRelation: '關係圖',
  relationTitle: '標題',
  relationTitleHint: '也可以在圖上的標題按兩下直接修改。',
  showNames: '顯示名字',
  sectionLegends: '線的種類',
  legendsLabel: '線的種類（點一下改用這種線連線）',
  legendsHint: '連線時用目前選取的那一種；拖曳把手調整圖例的順序。',
  legendName: '名稱',
  legendColor: '顏色',
  legendStyle: '樣式',
  styles: { solid: '實線', dash: '虛線', arrow: '箭頭' } satisfies Record<LineStyle, string>,
  styleHint: '箭頭畫在後點的那個人那一端。',
  addLegend: '新增一種線',
  legendLimit: (n: number) => `線的種類最多 ${n} 種。`,
  removeLegend: '刪除這種線',
  legendInUse: (n: number) => `${n} 條`,
  lastLegend: '至少要留一種線。',
  noLabel: '（沒有名稱）',
  activeLegend: '目前的線',
  sectionLinks: '連線',
  linksLabel: '連線清單',
  linksEmpty: '還沒有連線。在關係圖上依序點兩個人，就會用目前的線連起來。',
  linkName: (a: string, b: string, arrow: boolean) => `${a} ${arrow ? '→' : '—'} ${b}`,
  linkLegend: '線的種類',
  reverse: '反轉箭頭',
  removeLink: '刪除連線',
  randomLinks: '隨機連線',
  randomHint: '隨機加上「人數 − 1」條還沒有的線，線的種類也隨機。',
  randomNeedTwo: '至少要有兩個人在關係圖上。',
  randomDone: (n: number) => (n ? `已隨機加上 ${n} 條線。` : '已經沒有可以加的線了。'),
  clearLinks: '刪除所有連線',
  clearLinksTitle: '刪除所有連線？',
  clearLinksDesc: '關係圖上的線全部刪掉（可以復原）。',
  clearLinksConfirm: '全部刪除',
  canvasLegend: '圖例',

  /* 預覽 */
  previewLabel: (kind: ChartKind) => (kind === 'quadrant' ? '四象限預覽' : '關係圖預覽'),
  quadLayer: '四象限：拖曳角色調整位置',
  relationLayer: '關係圖：依序點兩個人連線',
  nodeLabel: (name: string) => name || '（沒有名字）',
  hintQuadrant: '拖曳角色調整位置；在標題或軸名上按兩下可以直接修改。',
  hintQuadrantEmpty: '在「角色」加入角色，就會出現在這一頁的中央。',
  hintRelation: (legend: string) =>
    `依序點兩個人，用「${legend}」連起來；同一對再連一次會刪掉那條線。`,
  hintRelationFrom: (name: string) => `已選「${name}」，再點另一個人連線（點同一個人取消）。`,
  hintRelationEmpty: '在「角色」加入角色（勾「放進關係圖」），就會排成一圈。',
  relationEmpty: '還沒有人在關係圖上',
  editLabel: (k: LabelKey) => `修改${k === 'title' ? '標題' : `${S.axis[k]}方的軸名`}`,
  imagesMissing: '有些角色的圖片讀不到了（可能已從這個瀏覽器清除），請重新選擇圖片。',

  /* 匯出 */
  exportTitle: '匯出',
  downloadPng: '下載 PNG',
  scale: '大小',
  scaleAria: (s: number) => `${s} 倍`,
  exportSize: (w: number, h: number) => `${w} × ${h} px`,
  exportNote: '輸出就是預覽上的樣子（不含選取標示）。',
  downloadDone: (name: string) => `已下載 ${name}`,
  downloadFailed: '無法產生圖片，請再試一次。',
  fileQuadrant: '角色四象限',
  fileRelation: '角色關係圖',

  /* 頁首 */
  undo: '復原',
  redo: '重做',
  resetTitle: '重設？',
  resetDesc: '角色、頁面、線的種類與連線都會回到剛打開的樣子（可以復原）。',
  openConfirmTitle: '開啟專案檔？',
  openConfirmDesc: '目前的角色與兩張圖會被專案檔的內容取代（可以復原）。',
  openConfirmLabel: '開啟',
  projectOpened: '已開啟專案檔。',
  projectBad: '這個專案檔的內容無法使用。',
  projectMissingImage: '專案檔裡少了角色的圖片，或圖片無法讀取。',
  saveFailed: '自動儲存失敗（瀏覽器空間不足或被封鎖）',

  /* 快捷鍵 */
  groupEdit: '編輯',
  groupQuadrant: '四象限',
  groupRelation: '關係圖',
  shortcutNudge: '移動選取的角色 1 px',
  shortcutNudgeBig: '移動選取的角色 10 px',
  shortcutUnplace: '把選取的角色從這一頁拿掉',
  shortcutEscape: '取消選取',
  shortcutCancelLink: '取消點了第一個人的連線',

  /* 使用方式 */
  usage: [
    '在「角色」輸入名字加入角色（可以加上圖片），或一次加入多張圖片（每張一個角色，名字取自檔名）。兩張圖共用同一份角色清單。',
    '四象限：把角色拖到想要的位置；標題與四個軸名在「這一頁」修改，或在圖上按兩下直接改。可以有好幾頁，每一頁的位置分開記。',
    '不在這一頁的角色，在清單上按「放到這一頁」就會出現在中央；「契合度」依兩個角色在每一頁的距離算出分數。',
    '「座標碼」可以把這一頁的名字、顏色與位置複製給別人，或把別人的座標碼加進這一頁。',
    '關係圖：在「線的種類」選好要用的線，再在圖上依序點兩個人連線；同一對再連一次會刪掉那條線。箭頭畫在後點的那個人那一端。',
    '按「下載 PNG」存成圖片。內容會自動儲存在這個瀏覽器，也可以從「專案」選單存成專案檔。',
  ],
};
