/**
 * CCFOLIA 日誌轉換器的介面文字與成品內建字樣（用詞照 DESIGN.md 第 5 節）。
 * 成品字樣（OUT）是規格 F92 的「新版自訂字樣」：系統、通知、閒聊摺疊的標題、插圖的替代文字、預設標題、分割頁碼。
 */
import type { OutputLabels } from './render';
import type {
  ChatMode,
  DialogueLayout,
  NarrationMode,
  OutputStyle,
  QualityPreset,
  SeparatorType,
  SplitMethod,
  SubNarratorStyle,
  TabStyle,
} from './settings';

export const OUT: OutputLabels = {
  lang: 'zh-Hant-TW',
  defaultTitle: '跑團日誌',
  system: '系統',
  notice: '通知',
  chatSummary: (n) => `閒聊訊息（${n} 則）`,
  chatFold: '閒聊訊息',
  chatFoldCount: (n) => `閒聊訊息 ${n} 則`,
  illustrationAlt: '插圖',
  page: (part, total) => `第 ${part} 頁，共 ${total} 頁`,
};

const n = (v: number) => v.toLocaleString('zh-TW');

export const S = {
  /* ---------- 載入 ---------- */
  load: {
    title: '日誌檔',
    drop: '把 CCFOLIA 匯出的日誌檔（.html）拖到這裡',
    button: '選擇日誌檔',
    hint: '可以一次選多個新格式的分頁檔',
    analyzing: '分析中……',
    analyzeFailed: '分析失敗：這個檔案裡讀不到任何訊息。請確認是 CCFOLIA 匯出的日誌檔。',
    readFailed: (name: string) => `讀不到「${name}」。`,
    loadedTitle: (count: number) => `已載入 ${count} 個檔案`,
    fileRow: (count: number, tabs: string) => `${n(count)} 則 · ${tabs}`,
    fileUnused: '未採用（已有訊息較多的全分頁檔）',
    fileCovered: '已包含在全分頁檔裡',
    removeFile: (name: string) => `從清單移除「${name}」`,
    addFiles: '加入檔案',
    noLog: '選好日誌檔後，這裡會出現詳細設定。',
    legacyBadge: '舊格式',
    v2Badge: '新格式',
    summary: (count: number, speakers: number, tabs: number) =>
      `共 ${n(count)} 則訊息、${speakers} 位發言者、${tabs} 個分頁`,
  },
  notices: {
    legacyOne: (first: string, rest: number) =>
      `舊格式一次只能轉換一個檔案，所以只用了「${first}」。其餘 ${rest} 個請分次轉換。`,
    mixed: (excluded: number) =>
      `有 ${excluded} 個檔案格式不同，已經排除。新、舊格式的檔案不能一起處理。`,
    multiAll: (count: number) => `含有全部分頁的檔案有 ${count} 個，只使用了訊息最多的那一個。`,
    addMismatch: '要加入的檔案不是新格式的日誌，所以沒有加入。',
    addDuplicate: '這些檔案已經載入過，所以沒有加入。',
    added: (count: number) => `已加入 ${count} 個檔案。`,
    skipped: (count: number) => `已略過 ${count} 個重複的檔案。`,
    excluded: (count: number) => `已排除 ${count} 個格式不同的檔案。`,
    allRemoved: '已移除所有檔案，請重新選擇日誌檔。',
  },
  /* ---------- 輸出樣式 ---------- */
  style: {
    label: '輸出樣式',
    hint: '換樣式後要再按一次「開始轉換」。',
    options: {
      novel: '小說',
      timeline: '時間軸',
      ccfolia: 'CCFOLIA 風格',
    } satisfies Record<OutputStyle, string>,
    descriptions: {
      novel: '台詞與敘述連成散文段落，適合當讀物保存。',
      timeline: '左側一條直線串起頭像，依序排列每一則。',
      ccfolia: '接近 CCFOLIA 聊天欄的一列一則。',
    } satisfies Record<OutputStyle, string>,
  },
  tabs: {
    label: '詳細設定',
    basic: '基本',
    appearance: '外觀',
    illustration: '插圖',
    advanced: '進階',
  },
  /* ---------- 基本 ---------- */
  basic: {
    titleSection: '標題',
    title: '標題',
    subtitle: '副標題',
    summary: '摘要',
    titleHint: '舊格式會從檔名帶入；空白時從檔名或房間名稱決定。',
    summaryPlaceholder: '可以不填',
    narratorSection: '旁白',
    narrator: '旁白角色',
    narratorDefault: 'GM（預設）',
    narratorHint: '這位發言者的發言會當成敘述呈現。',
    narrationMode: '旁白的呈現（CCFOLIA 風格）',
    narrationModes: {
      highlight: '換底色',
      block: '獨立區塊',
      plain: '同對話',
    } satisfies Record<NarrationMode, string>,
    narrationModeHint: {
      highlight: '名稱和頭像照常顯示，整列換成旁白的底色。',
      block: '不顯示名稱和頭像，做成橫跨整列的色塊；連續的旁白合成一塊。',
      plain: '和一般對話一樣，只有名稱用旁白角色的名稱顏色。',
    } satisfies Record<NarrationMode, string>,
    narrationCenter: '區塊內的文字置中',
    narrationCenterHint: '適合短的演出句子；長的描寫靠左比較好讀。',
    chatTab: '閒聊分頁',
    chatTabNone: '不指定',
    chatTabHint: '這個分頁裡的訊息都當成閒聊。',
    emptySpeaker: '（沒有名稱）',
  },
  sub: {
    title: '副旁白',
    description: '另外指定要當成旁白呈現的發言者，各自選一種樣式。',
    pick: '選擇發言者',
    pickLabel: '要加入的發言者',
    add: '新增',
    empty: '還沒有副旁白。',
    remove: (name: string) => `移除副旁白「${name}」`,
    styleLabel: (name: string) => `「${name}」的樣式`,
    colorLabel: (name: string) => `「${name}」的文字`,
    styles: {
      'italic-narration': '旁白（斜體）',
      narration: '旁白（一般）',
      'italic-dialogue': '對話（斜體）',
      'colored-narration': '旁白（指定顏色）',
    } satisfies Record<SubNarratorStyle, string>,
  },
  /* ---------- 外觀 ---------- */
  avatar: {
    title: '頭像圖片',
    onlyFor: '時間軸與 CCFOLIA 風格才有頭像。',
    resize: '縮放圖片',
    resizeHint: '關閉時用原圖，檔案可能變得很大。',
    keepExternal: '直接引用網址',
    keepExternalHint: '輸入網址時不下載，成品直接引用原網址（離線時看不到）。',
    quality: '圖片品質',
    qualityOptions: {
      low: '最小（每張約 3 KB）',
      medium: '標準（每張約 10 KB，建議）',
      high: '較高畫質（每張約 25 KB）',
      original: '原圖',
      custom: '自訂',
    } satisfies Record<QualityPreset, string>,
    custom: '自訂品質',
    customSmall: '往左檔案小',
    customLarge: '往右畫質好',
    customEstimate: (est: string) => `每張${est}`,
    perMessage: '逐則頭像',
    perMessageHint:
      '開啟時每一則用日誌裡它自己的頭像（表情差分）；關閉時每位發言者只用一張，檔案比較小。',
    total: '頭像總容量',
    source: (name: string) => `「${name}」的頭像來源`,
    sourceFile: '選檔',
    sourceUrl: '網址',
    pickFile: '選擇圖片',
    urlLabel: (name: string) => `「${name}」的頭像網址`,
    urlPlaceholder: 'https://example.com/face.png',
    clear: (name: string) => `清除「${name}」的頭像`,
    fromLog: '日誌裡的頭像',
    none: '沒有頭像',
    processing: (i: number, total: number) => `正在重新處理圖片……（${i}／${total}）`,
    processed: (count: number) => `圖片重新處理完成（${count} 張）`,
    readFailed: (name: string, why: string) => `「${name}」的頭像讀不了：${why}`,
    urlFailed: (name: string) =>
      `下載不到「${name}」的頭像。對方的網站可能不允許跨網域讀取；可以開啟「直接引用網址」，或改用選檔。`,
  },
  colors: {
    title: '名稱顏色',
    description: '每位發言者名稱的顏色。新格式會先帶入 CCFOLIA 記錄的顏色。',
    label: (name: string) => `「${name}」名稱`,
  },
  layout: {
    title: '字型與版面',
    novelTypography: '小說排版微調',
    novelTypographyHint: '旁白段落第一行內縮一字，字距與詞距稍微調整。',
    fontUrl: '自訂字型網址',
    fontUrlPlaceholder: 'https://fonts.googleapis.com/css2?family=…',
    fontUrlHint:
      '可以填網址、以 @import 開頭的寫法，或整段 @font-face。空白時用思源宋體／思源黑體。',
    fontFamily: '自訂字型名稱',
    fontFamilyPlaceholder: '例：Noto Serif TC',
    fontFamilyHint: '加不加引號都可以。',
    fontHelpTitle: '怎麼取得 Google Fonts 的字型',
    fontHelp: [
      '到 fonts.google.com 搜尋想用的字型（例如 Noto Serif TC、LXGW WenKai TC）。',
      '按「Get font」→「Get embed code」，在網頁用的程式碼裡找到 https://fonts.googleapis.com/css2?family=… 這段網址。',
      '把網址貼到「自訂字型網址」，字型名稱（例如 Noto Serif TC）填到「自訂字型名稱」。',
      '成品要連得到 Google Fonts 才看得到這個字型；離線時會改用電腦裡的字型。',
    ],
    fontSize: '字級',
    lineHeight: '行距',
    pageWidth: '頁面寬度',
  },
  /* ---------- 插圖 ---------- */
  ill: {
    title: '插圖',
    description: '在指定的訊息之後插入圖片。訊息序號在預覽裡每則的右上角。',
    showNumbers: '預覽顯示訊息序號',
    showNumbersHint: '只在預覽顯示，下載的檔案不會有。',
    add: '新增插圖',
    empty: '還沒有插圖。',
    itemTitle: (i: number) => `插圖 ${i}`,
    position: '插在第幾則之後',
    positionPlaceholder: '例：48',
    size: '大小',
    sizes: { small: '小（400 px）', medium: '中（600 px）', large: '大（800 px）', full: '滿版' },
    align: '對齊',
    aligns: { left: '靠左', center: '置中', right: '靠右' },
    source: '來源',
    sourceFile: '選檔',
    sourceUrl: '網址',
    pickFile: '選擇圖片',
    url: '圖片網址',
    urlPlaceholder: 'https://example.com/map.png',
    warnFile: '分割檔案時，留意圖片的大小。',
    warnUrl: '網址插圖不會嵌入成品，連結要一直有效才看得到。',
    urlError: '無法載入這個網址的圖片',
    remove: (i: number) => `移除插圖 ${i}`,
    readFailed: (why: string) => `圖片讀不了：${why}`,
  },
  /* ---------- 進階 ---------- */
  adv: {
    contentTitle: '內容',
    merge: '合併同人連續對話',
    mergeHint: '同一位發言者在同一個分頁連續說的話合成一則，每則一行。',
    longNameWrap: '名稱過長時換行',
    longNameWrapHint: '名稱超過 10 個字時可以換行，名稱欄不會被撐寬。',
    layout: '台詞版面（時間軸）',
    layouts: { grid: '欄位對齊', inline: '接續' } satisfies Record<DialogueLayout, string>,
    layoutHint: '欄位對齊：名稱在固定寬度的欄、台詞從同一條線開始；接續：名稱後面緊接台詞。',
    separator: '分隔符號',
    separators: { space: '空格', custom: '自訂' } satisfies Record<SeparatorType, string>,
    customSeparator: '自訂分隔字',
    customSeparatorHint: '最多 3 個字元；空白時用「:」。',
    chatMode: '閒聊的呈現',
    chatModes: { collapse: '摺疊', show: '全部顯示', hide: '完全隱藏' } satisfies Record<
      ChatMode,
      string
    >,
    showChatCount: '顯示閒聊數量',
    showChatCountHint: '摺疊時在標題顯示則數。',
    system: '系統訊息（擲骰）',
    systemModes: { show: '顯示', hide: '隱藏' },
    channelTitle: '分頁名稱',
    channelDescription:
      '新格式的分頁以代碼記錄（main、自訂分頁是一串英數）。改成好認的名稱；名稱只用在選單與 CCFOLIA 風格的分頁標籤。',
    channelLabel: (code: string) => `分頁 ${code} 的名稱`,
    channelCount: (count: number) => `${n(count)} 則`,
    tabsTitle: '分頁',
    visibleTabs: '輸出的分頁',
    visibleTabsHint: '沒勾的分頁，裡面的訊息（含系統訊息與閒聊）都不輸出。',
    tabStyle: '分頁標示方式（CCFOLIA 風格）',
    tabStyleLabel: (tab: string) => `分頁「${tab}」的標示方式`,
    tabStyles: { none: '不標示', label: '標出分頁', notice: '通知框' } satisfies Record<
      TabStyle,
      string
    >,
    colorTitle: '配色',
    preset: '配色預設',
    custom: '自訂',
    presetHint: '選一組預設時 9 個顏色一起換；改任何一色會變成「自訂」。',
    systemColors: '系統訊息',
    narrationColors: '旁白（時間軸、CCFOLIA 風格）',
    pageColors: '頁面',
    colorNames: {
      systemBg: '背景',
      systemBorder: '邊框',
      systemText: '文字',
      narrationBg: '背景',
      narrationText: '文字',
      pageBg: '頁面背景',
      containerBg: '容器',
      text: '文字',
      accent: '強調色',
    },
    colorLabel: (group: string, name: string) => `${group}：${name}`,
    tabColors: '分頁配色',
    tabColorsHint: '每個分頁各自的文字與背景顏色。',
    tabText: (tab: string) => `分頁「${tab}」的文字`,
    tabBg: (tab: string) => `分頁「${tab}」的背景`,
    transparent: '透明',
    clearBg: '改回透明',
    splitTitle: '檔案分割',
    split: '分割方式',
    splitMethods: {
      none: '不分割',
      count: '依則數',
      size: '依大小',
      files: '固定檔數',
    } satisfies Record<SplitMethod, string>,
    splitCount: '每檔則數',
    splitSize: '每檔大小',
    splitFiles: '檔數',
    splitWarn: (kb: number) => `目前頭像共 ${n(kb)} KB；每檔大小不要設得比這個小。`,
    blogTitle: '部落格貼文版',
    blogMode: '一併產生部落格貼文版',
    blogHint:
      '轉成可以貼進部落格文章的 HTML 片段（沒有 html、head、body），樣式只作用在成品範圍內。有些部落格版型可能讓外觀走樣。',
    settingsTitle: '設定檔',
    settingsHint: '設定會自動記在瀏覽器裡。也可以從頁首的「專案」選單存成檔案、開啟或重設。',
  },
  /* ---------- 轉換、預覽、下載 ---------- */
  result: {
    convert: '開始轉換',
    selectFirst: '請先選擇日誌檔。',
    reading: '正在讀取並分析日誌……',
    analyzed: (count: number) => `共分析 ${n(count)} 則，轉換中……`,
    done: '轉換完成。',
    doneSplit: (parts: number) => `轉換完成，已分成 ${parts} 個檔案。`,
    failed: (why: string) => `轉換失敗：${why}`,
    cancelled: '已取消轉換。',
    stale: '設定改過了；要套用到預覽與下載，請再按一次「開始轉換」。',
    previewTitle: '預覽',
    previewEmpty: '選好日誌檔、按「開始轉換」後，預覽會出現在這裡。',
    previewFrame: '轉換結果預覽',
    rangeStart: '起始編號',
    rangeCount: '則數',
    rangeAll: '全部',
    rangeApply: '檢視',
    rangeInfo: (start: number, last: number, total: number) =>
      `顯示第 ${n(start)}～${n(last)} 則 · 共 ${n(total)} 則`,
    rangeInfoAll: (total: number) => `顯示全部 ${n(total)} 則`,
    downloads: '下載',
    downloadHtml: '下載 HTML',
    downloadBlog: '下載部落格貼文版',
    downloadZip: '全部下載（ZIP）',
    downloadBlogZip: '部落格貼文版・全部（ZIP）',
    zipping: '打包中……',
    downloadPart: (i: number) => `下載第 ${i} 檔`,
    downloadBlogPart: (i: number) => `第 ${i} 檔（部落格貼文版）`,
    zipFailed: '打包 ZIP 時發生錯誤。',
    bigImagesTitle: '有圖片比每檔大小還大',
    bigImages: (limit: number, list: string) =>
      `下列圖片本身就超過每檔大小（${n(limit)} KB）：\n${list}\n\n這樣分割可能不如預期。建議開啟「縮放圖片」、加大每檔大小，或換成較小的圖片。要繼續轉換嗎？`,
    bigImageAvatar: (name: string, kb: number) => `・「${name}」的頭像：約 ${n(kb)} KB`,
    bigImageIll: (i: number, pos: number | null, kb: number) =>
      `・插圖 ${i}（第 ${pos ?? '—'} 則之後）：約 ${n(kb)} KB`,
    continue: '繼續轉換',
  },
  project: {
    saved: (name: string) => `已匯出設定：${name}`,
    opened: (name: string) => `已匯入設定：${name}`,
    openError: (msg: string) => `無法匯入設定：${msg}`,
    resetTitle: '重設所有設定？',
    resetDescription:
      '記在瀏覽器裡的設定會全部清除並重新載入頁面，目前載入的日誌、頭像與插圖也會消失。',
    resetConfirm: '重設並重新載入',
    resetMenu: '重設所有設定…',
  },
};

/** 使用說明（F94） */
export const USAGE = {
  intro:
    '把 CCFOLIA 匯出的聊天日誌（HTML）轉成方便保存、分享或貼到部落格的網頁。全部在瀏覽器裡處理，不會上傳。',
  steps: [
    '在 CCFOLIA 房間選單的「ログ出力」下載日誌檔。新格式（含頭像與時間）每個分頁一個檔，可以全部一起選。',
    '選擇輸出樣式：小說、時間軸或 CCFOLIA 風格。',
    '在下方四個分頁調整設定，按「開始轉換」，右邊（手機在上方）會出現預覽與下載按鈕。',
  ],
  styles: [
    '小說：台詞與敘述連成散文段落，旁白角色的發言就是敘述。',
    '時間軸：左側一條直線串起頭像，依序排列；連續的旁白合成一段。',
    'CCFOLIA 風格：接近 CCFOLIA 聊天欄的一列一則，可以標出分頁或把分頁做成通知框。',
  ],
  tabs: [
    '基本：標題、旁白角色與旁白的呈現、閒聊分頁、副旁白。',
    '外觀：頭像圖片與品質、名稱顏色、字型、字級、行距、頁面寬度。',
    '插圖：在指定的訊息之後插入圖片。',
    '進階：合併同人連續對話、台詞版面、閒聊與系統訊息、分頁、配色、檔案分割、部落格貼文版。',
  ],
  tips: [
    '日誌很長時，預覽只畫出其中一段；在預覽下方改起始編號與則數，或選「全部」。下載的檔案一定包含全部。',
    '預覽裡每則右上角的「#編號」是訊息序號，插圖用它指定位置；下載的檔案不會有編號。',
    '檔案太大時可以在「進階 → 檔案分割」分成幾個檔，另外有全部打包的 ZIP。',
    '要直接貼進部落格文章時，開啟「進階 → 部落格貼文版」；有些部落格版型可能讓外觀走樣。',
    '設定會自動記在瀏覽器裡；日誌、頭像與插圖不會記住。',
    '建議用最新版的桌面瀏覽器（Chrome、Edge、Firefox）。',
  ],
};
