/**
 * 打字機動畫產生器的介面文字（台灣繁體中文，用詞照 DESIGN.md 第 5 節）。
 */
import type { FadeKind, HAlign, KaraokeShow, Mode, ShapeKind, VAlign } from './settings';

export const S = {
  modes: {
    typing: '打字',
    glitch: '故障',
    credits: '片尾名單',
    karaoke: '卡拉 OK',
  } satisfies Record<Mode, string>,
  modesAria: '模式',

  sections: {
    text: '文字',
    lyrics: '歌詞',
    style: '字型與樣式',
    layout: '排版',
    color: '顏色',
    animation: '動畫',
    timing: '時間',
    glitch: '亂碼',
    shape: '圖形',
    sound: '音效',
    scan: '掃描',
    show: '顯示哪些句子',
    output: '輸出',
    silence: '靜音音檔',
    canvas: '畫布',
  },

  text: {
    label: '文字',
    typingHint: '換行會保留，太長的行不會自動換行。每一格多出現一個字（空白、換行也算一格）。',
    glitchHint: '每個字先閃過幾格亂碼才變成正確的字；半形空白與換行不閃。',
    creditsHint: '空一行可以把名單分成幾段（分段匯出時每段一個檔案）。',
    lyricsLabel: '歌詞',
    lyricsHint:
      '一行一句；行尾寫「| 秒數」可以指定這一句變色所需的秒數（例：「月色落在窗邊 | 2.5」），沒寫的句子自動分配剩下的時間。只有空白的行不唱。',
  },

  font: {
    label: '字型',
    custom: '自訂（電腦已安裝的字型）',
    customName: '自訂字型名稱',
    customHint: '輸入電腦已安裝的字型名稱；留空時用瀏覽器的無襯線字型。',
    size: '字級',
    scaleX: '水平縮放',
    tracking: '字距',
    leading: '行距',
    leadingHint: '行與行（直書是欄與欄）的間距＝字級 × 倍數。',
    bold: '粗體',
    italic: '斜體',
    underline: '底線',
    strike: '刪除線',
  },

  layout: {
    direction: '書寫方向',
    horizontal: '橫書',
    vertical: '直書',
    verticalHint: '直書時欄由右往左、字由上往下；英數轉 90°，句讀移到右上。',
    align: '水平對齊',
    valign: '垂直對齊',
    shapeOff: '圖形模式下書寫方向、對齊、行距沒有作用。',
  },
  aligns: { left: '靠左', center: '置中', right: '靠右' } satisfies Record<HAlign, string>,
  valigns: { top: '靠上', middle: '置中', bottom: '靠下' } satisfies Record<VAlign, string>,

  color: {
    bgOn: '使用背景色',
    bgHint: '開啟時每一格先塗滿背景色，輸出沒有透明；關閉時是透明背景。',
    bg: '背景色',
    fill: '文字填色',
    stroke: '外框色',
    strokeWidth: '外框粗細',
    strokeHint: '0＝不畫外框。',
    shadow: '陰影色',
    shadowBlur: '陰影模糊',
    shadowX: '陰影 X 偏移',
    shadowY: '陰影 Y 偏移',
    copy: '複製',
    copied: '已複製',
    copyLabel: (name: string) => `複製${name}色碼`,
    copyFailed: '無法複製到剪貼簿',
    copyFailedHint: (hex: string) => `請手動複製色碼：${hex}`,
  },

  anim: {
    fps: '每秒格數（FPS）',
    fpsHint: '也就是打字速度：每一格 1000 ÷ FPS 毫秒。',
    glitchFpsHint: '亂碼閃爍的速度：每一格 1000 ÷ FPS 毫秒。',
    creditsFpsHint: '捲動的取樣：每一格 1000 ÷ FPS 毫秒。',
    karaokeFpsHint: '掃描的取樣：每一格 1000 ÷ FPS 毫秒。',
    hold: '最後停留時間',
    holdHint: '最後一格（停留格）顯示多久。',
    direction: '出現方向',
    forward: '正向',
    reverse: '反向',
    directionHint: '反向時從末尾的字開始往前出現，每個字仍在它最終的位置。',
    fade: '淡出方式',
    fadeMs: '淡出長度',
    fadeHint: '淡出格數＝淡出長度 × FPS ÷ 1000（四捨五入，至少 1）。',
  },
  fades: {
    none: '不淡出',
    whole: '整體一起淡出',
    each: '一字接一字淡出',
  } satisfies Record<FadeKind, string>,

  shape: {
    kind: '圖形模式',
    size: '圖形大小',
    sizeHint: '圓的半徑、正方形邊長的一半、正三角形的外接圓半徑。',
    rotate: '每格旋轉角度',
    rotateHint: '整個圖形每格以畫布中心轉這麼多度（正數順時針）。不為 0 時停留期間也會繼續轉。',
  },
  shapes: {
    none: '不使用',
    circle: '圓',
    square: '方',
    triangle: '三角',
  } satisfies Record<ShapeKind, string>,

  sound: {
    drop: '把音效檔拖到這裡',
    pick: '選擇音效檔',
    dropHint: 'MP3、WAV 等瀏覽器能播放的格式；每打一格放一次。',
    decoding: (name: string) => `解碼中：${name}`,
    loaded: (name: string, sec: number, ch: number, rate: number) =>
      `已載入：${name}（${sec.toFixed(2)} 秒、${ch} 聲道、${rate} Hz）`,
    mode: '音效的放法',
    each: '每格都播',
    skip: '不疊音',
    modeHint: '不疊音：上一聲還沒播完就跳過這一格，結尾 0.2 秒淡出。',
    make: '合成音效',
    makeHint: '依目前的打字時間軸合成 WAV，可以先試聽再下載。',
    needClip: '請先載入音效檔。',
    player: '試聽',
    download: '下載音效 WAV',
    made: '已合成音效',
  },

  glitch: {
    charsets: '亂碼字元類別',
    charsetsHint: '全部不勾時當成只勾拉丁字母與符號。',
    latin: '拉丁字母與符號',
    kana: '日文假名',
    hangul: '韓文（字母與音節）',
    shapes: '框線與幾何圖形',
    intensity: '亂碼格數（強度）',
    intensityHint: '每個字變成正確的字之前閃過幾格亂碼；0＝沒有亂碼。',
    together: '同時亂碼、依序還原',
    togetherHint: '一開始所有字都是亂碼，再由前往後一個一個還原。',
  },

  credits: {
    duration: '總長',
    split: '匯出方式',
    single: '整段一個檔案',
    segments: '以空白行分成多個檔案',
    splitHint: '預覽一律顯示整段文字與總長；分段時各段的長度按字數比例分配，各自從下往上捲完。',
    segmentInfo: (n: number) => `目前分成 ${n} 段`,
    silenceExtra: '靜音音檔延長',
    silenceHint: '產生與動畫等長（再加上延長秒數）的靜音 WAV，方便在剪輯軟體裡對齊。',
    makeSilence: '產生靜音 WAV',
    silenceDone: (n: number) => `已下載 ${n} 個靜音 WAV`,
    silenceNone: '沒有可產生的靜音音檔（長度是 0）。',
  },

  karaoke: {
    duration: '總時間',
    intro: '前奏等待',
    introHint: '第一句開始掃描前的時間。',
    alloc: '未標記句子的時間分配',
    allocChars: '按字數',
    allocEqual: '每句等長',
    palette: '配色預設',
    paletteNames: {
      classic: '金黃與桃紅',
      ocean: '海洋',
      sakura: '櫻花',
      forest: '森林',
    } as Record<string, string>,
    beforeFill: '唱前填色',
    beforeStroke: '唱前外框色',
    afterFill: '唱後填色',
    afterStroke: '唱後外框色',
    direction: '掃描方向',
    ltr: '由左往右',
    rtl: '由右往左',
    softness: '交界柔化',
    softnessHint: '唱過與沒唱過的交界做成這麼寬的漸變；0＝硬邊。',
    glowOn: '掃描發光',
    glowColor: '發光色',
    glowWidth: '發光帶寬',
    show: '顯示方式',
    rows: '同時出現的行數',
    swapFade: '輪替淡化',
    swapFadeHint: '要離開的句子唱完後淡出，接手的句子再淡入（先出後進）。',
  },
  shows: {
    all: '全部一直顯示',
    reveal: '唱到才出現並保留',
    current: '只顯示正在唱的一句',
    rotate: '固定 n 行、逐句輪替',
    page: '固定 n 行、整頁更換',
  } satisfies Record<KaraokeShow, string>,

  canvas: {
    width: '寬',
    height: '高',
    fit: '依文字裁切畫布',
    fitHint: '把畫布改成剛好容納文字再加一點留白（不改對齊設定）。',
    fitDone: (w: number, h: number) => `畫布已改成 ${w} × ${h}`,
  },

  noText: '沒有文字可用',
  noTextHint: '請先輸入文字。',
  emptyNotice: '還沒有文字：預覽只顯示背景，也不能匯出。',
  loadingFonts: '字型載入中…',
  frameCounter: (i: number, n: number) => `${i}／${n} 格`,
  tooManyFrames: (n: number, max: number) =>
    `影格數 ${n} 超過上限 ${max}：請縮短時長或降低每秒格數。`,

  export: {
    fixedFpsHint: '每秒格數是動畫的內容設定（在左邊的設定裡調整），匯出時不另選。',
    quantizeHint: '減到最多 256 色（含半透明），檔案小很多。只影響 APNG。',
    webpLossless: 'WebP 無損',
    webpQuality: 'WebP 品質',
    webpQualityHint: '無損開啟時不使用品質設定。',
    zipName: (ts: number) => `credit_分段_${ts}`,
    segments: '分段',
    segmentsValue: (n: number) => `以空白行分成 ${n} 段`,
    colors: '色數',
    lossless: (n: number) => `無損（${n} 色）`,
    colorCount: (n: number) => `${n} 色`,
  },

  project: {
    fileName: '打字機動畫',
  },

  usage: [
    '在上方選模式：打字（字一個一個出現）、故障（先閃亂碼再變成正確的字）、片尾名單（由下往上捲）、卡拉 OK（歌詞依時間變色）。四個模式的設定各自獨立。',
    '在「文字」輸入內容；預覽會從頭播放最新的結果。每秒格數（FPS）就是打字、閃爍、捲動的速度。',
    '畫布太大時可以按「依文字裁切畫布」，改成剛好容納文字的大小。',
    '在預覽下方的「匯出」選 APNG、GIF 或 WebP，按「匯出」後再下載。片尾名單可以以空白行分段，每段一個檔案。',
    '打字模式可以上傳一個音效檔，合成與打字節奏對應的音效 WAV；片尾名單可以產生同長度的靜音 WAV。',
    '設定會自動存在這個瀏覽器裡；右上角的專案選單可以存成專案檔、開啟或全部重設。',
  ],
  about: [
    '所有處理都在你的瀏覽器裡完成，文字與音效檔不會上傳到任何地方。',
    '可選的網路字型皆來自 Google Fonts，授權依各字型（SIL Open Font License 等）。',
  ],
};
