/**
 * 介面文字（繁體中文；用詞照 DESIGN.md 第 5 節）。物件的預設名稱（3.6）也在這裡。
 */
import type { MapGridType } from '@/core/grid';

const n = (v: number) => String(v);

export const S = {
  toolName: '地圖編輯器',
  docTitle: (name: string) => `${name}｜地圖編輯器｜TRPG Toolkit`,

  /* ---------- 網格種類 ---------- */
  gridTypes: {
    square: '方格',
    'hex-flat': '六角格・平頂',
    'hex-flat-fit': '六角格・平頂・對齊網格',
    'hex-pointy': '六角格・尖頂',
    'hex-pointy-fit': '六角格・尖頂・對齊網格',
  } satisfies Record<MapGridType, string>,

  /* ---------- 地圖一覽 ---------- */
  list: {
    title: '我的地圖',
    newMap: '新增地圖',
    importJson: '讀取 JSON',
    empty: '還沒有儲存的地圖',
    updated: (d: string) => `更新：${d}`,
    open: (name: string) => `開啟「${name}」`,
    duplicate: '複製',
    rename: '重新命名',
    exportJson: '匯出 JSON',
    delete: '刪除',
    more: (name: string) => `「${name}」的操作`,
    copyName: (name: string) => `${name}（副本）`,
    deleteTitle: '刪除地圖',
    deleteConfirm: (name: string) => `要刪除「${name}」嗎？刪除後無法復原。`,
    invalidFile: '檔案格式無效',
    importName: (d: string) => `匯入 ${d}`,
    importError: (msg: string) => `讀取錯誤：${msg}`,
    imported: (name: string) => `已讀取「${name}」`,
    defaultName: (d: string) => `地圖 ${d}`,
    migrated: (count: number) => `已從舊版搬入 ${n(count)} 張地圖`,
    notFound: '找不到這張地圖',
    memoryOnly:
      '這個瀏覽器不能使用 IndexedDB（例如私密瀏覽），地圖只存在這一頁，重新整理後就會消失。請記得匯出 JSON。',
    dropHint: '也可以把地圖的 JSON 檔拖進這裡',
    renameTitle: '重新命名',
    nameLabel: '地圖名稱',
    nameRequired: '請輸入地圖名稱',
    loading: '讀取中…',
    thumbAlt: (name: string) => `「${name}」的縮圖`,
    noThumb: '沒有縮圖',
  },

  /* ---------- 新增地圖 ---------- */
  newMap: {
    title: '新增地圖',
    kind: '網格種類',
    kinds: { square: '方格', hex: '六角格' },
    kindHints: { square: '正方形的格子', hex: '六角形的格子' },
    orientation: '六角格的方向',
    orientations: { flat: '平頂', pointy: '尖頂' },
    orientationHints: { flat: '上下是平邊', pointy: '上下是頂點' },
    fit: '對齊網格（CCFOLIA 用）',
    fitHint: '稍微變形六角格，讓它對齊正方形的網格',
    name: '地圖名稱',
    create: '建立並開啟',
    fixedNote: '網格種類建立後不能改；格子大小固定 72 px。',
  },

  /* ---------- 編輯列 ---------- */
  editor: {
    backToList: '地圖一覽',
    renameMap: '重新命名地圖',
    saveNow: '立即儲存',
    undo: '復原',
    redo: '重做',
    exportImage: '匯出圖片',
    loading: '讀取地圖中…',
    loadFailed: '讀取地圖失敗',
  },
  save: {
    saved: '已儲存',
    dirty: '未儲存',
    saving: '儲存中…',
    error: '儲存失敗',
  },

  /* ---------- 工具 ---------- */
  tools: {
    select: '選取',
    cell: '格子',
    rect: '矩形',
    ellipse: '橢圓',
    line: '直線',
    path: '折線',
    polygon: '多邊形',
    curve: '曲線',
    'curve-closed': '封閉曲線',
    ground: '地面',
    wall: '牆壁',
    room: '房間',
    decor: '裝飾',
    freehand: '手繪',
    text: '文字',
    image: '圖片',
  },
  toolGroups: { basic: '基本圖形', map: '地圖', common: '共通' },
  toolbar: '工具',

  /* ---------- 物件的名稱（3.6） ---------- */
  prefix: { ground: '地面_', wall: '牆_', room: '房間_', decor: '裝飾_' },
  layer: {
    cell: '格子',
    groundCell: '地面_格子',
    group: '群組',
    ungrouped: '解散',
    layer: '圖層',
    object: '物件',
    copyOf: (name: string) => `${name} 副本`,
    boolRoom: (op: string) => `${op}_房間`,
  },
  bool: { union: '聯集', intersection: '交集', difference: '差集', xor: '互斥' },
  boolHints: {
    union: '聯集：合成一個',
    intersection: '交集：只留重疊的部分',
    difference: '差集：第一個減掉其餘',
    xor: '互斥：去掉重疊的部分',
  },

  /* ---------- 復原的操作名稱 ---------- */
  hist: {
    undo: (name: string) => `復原：${name}`,
    redo: (name: string) => `重做：${name}`,
    add: (name: string) => `新增 ${name}`,
    modify: (name: string) => `變更 ${name}`,
    delete: (name: string) => `刪除 ${name}`,
    deleteN: (count: number) => `刪除 ${n(count)} 個物件`,
    duplicate: '複製',
    duplicateN: (count: number) => `複製 ${n(count)} 個`,
    paint: (name: string) => `${name}填色`,
    fillCells: (count: number) => `填滿（${n(count)} 格）`,
    fillColor: '變更填色',
    strokeColor: '變更描邊顏色',
    textDelete: '刪除文字',
    textEdit: '編輯文字',
    eraser: '橡皮擦',
    freehandAdd: '新增手繪',
    group: '群組',
    ungroup: '解散群組',
    bool: (op: string) => `布林運算：${op}`,
    boolRoom: (op: string) => `房間布林運算：${op}`,
    front: '移到最上層',
    back: '移到最下層',
    lock: '鎖定',
    unlock: '解除鎖定',
    unlockLayer: (name: string) => `解除鎖定 ${name}`,
    show: '顯示',
    hide: '隱藏',
    showLayer: (name: string) => `顯示 ${name}`,
    hideLayer: (name: string) => `隱藏 ${name}`,
    rename: (from: string, to: string) => `重新命名：${from} → ${to}`,
    reorder: '調整圖層順序',
    moveX: (name: string) => `變更 ${name} 的 X`,
    moveY: (name: string) => `變更 ${name} 的 Y`,
    selPattern: (kind: string) => `變更${kind}的圖樣`,
    selScale: (kind: string) => `變更${kind}的縮放`,
    selOffsetX: (kind: string) => `變更${kind}的偏移 X`,
    selOffsetY: (kind: string) => `變更${kind}的偏移 Y`,
    selRotation: (kind: string) => `變更${kind}的旋轉`,
    shadow: '變更陰影',
    textLook: '變更文字顏色與描邊',
    textStyle: '變更文字樣式',
    font: '變更字型',
    fontSize: '變更文字大小',
    strokeWidth: '變更線寬',
    lineStyle: '變更線型',
    cornerRadius: '變更圓角',
    opacity: '變更不透明度',
    blend: '變更混合模式',
    lineJoin: '變更轉角',
    lineCap: '變更線端',
    rotate: '旋轉',
  },

  /* ---------- 狀態列的暫時訊息 ---------- */
  status: {
    selectTwo: '請選取 2 個以上',
    cannotGroup: '格子／手繪圖層無法群組',
    selectGroup: '請選取群組',
    cannotUngroup: '格子／手繪圖層無法解散',
    selectTwoBool: '請選取 2 個以上可以做布林運算的圖形',
    sameKind: '請只選取同一類（一般圖形／地面／牆壁／房間）的圖形',
    notEnoughShapes: '可以轉換的圖形不夠',
    notEnoughRooms: '可以轉換的房間不夠',
    boolFailed: '布林運算失敗',
    emptyResult: '結果是空的',
    cellLayerEmpty: '格子圖層是空的',
    outOfCellLayer: '超出格子圖層的範圍',
    fillLimit: (max: number) => `超過填滿上限（${n(max)} 格）`,
    selectDecor: '請選擇裝飾',
    imageFailed: '讀取圖片失敗',
  },

  /* ---------- 狀態列 ---------- */
  statusBar: {
    cell: '游標所在的格',
    zoom: '縮放',
    cellSize: (px: number) => `${n(px)} px`,
    cellSizeLabel: '格子大小',
    zoomIn: '放大',
    zoomOut: '縮小',
    resetView: '重設檢視',
    lastAction: '最後的操作',
  },

  /* ---------- 面板 ---------- */
  panel: {
    tabs: { props: '屬性', layers: '圖層', settings: '地圖設定' },
    label: '面板',
  },

  sel: {
    none: '請選取物件',
    name: '名稱',
    width: '寬',
    height: '高',
    rotation: '旋轉',
    count: (count: number) => `已選取 ${n(count)} 個物件`,
    kinds: { ground: '地面', wall: '牆壁', 'room-ground': '房間地面', 'room-wall': '房間牆壁' },
    fillOf: (kind: string) => `${kind}的填色`,
    strokeOf: (kind: string) => `${kind}的輪廓`,
    style: '填色與描邊',
  },

  style: {
    title: '填色與描邊',
    fill: '填色',
    stroke: '描邊',
    strokeWidth: '線寬',
    strokeStyle: '線型',
    styles: {
      solid: '實線',
      dashed: '虛線',
      dotted: '點線',
      dashdot: '點劃線',
      longdash: '長虛線',
    },
    lineJoin: '轉角',
    joins: { miter: '尖角', round: '圓角', bevel: '斜角' },
    lineCap: '線端',
    caps: { butt: '平頭', round: '圓頭', square: '方頭' },
    cornerRadius: '圓角',
    ellipseMode: '畫法',
    ellipseModes: { bbox: '外框', center: '中心→半徑' },
    ellipseHints: { bbox: '以 2 點為外框畫內切橢圓', center: '從中心拉半徑畫正圓' },
    wallThickness: '牆壁厚度',
  },

  shadow: {
    title: '陰影',
    enabled: '加上陰影',
    enabledFor: {
      simple: '加上陰影（一般圖形）',
      ground: '加上陰影（地面）',
      wall: '加上陰影（牆壁）',
      decor: '加上陰影（裝飾）',
    },
    color: '顏色',
    blur: '模糊',
    offsetX: '偏移 X',
    offsetY: '偏移 Y',
    note: '只套用在之後新增的物件；已經畫好的請選取後在「屬性」改。',
  },

  cell: {
    mode: '模式',
    modes: { pen: '畫筆', eraser: '橡皮擦', fill: '填滿' },
    addLayer: '新增格子圖層',
    fillColor: '填色',
    hint: '點或拖曳經過的格子塗上顏色；同一種顏色會合成一塊。',
  },

  ground: {
    subtool: '形狀',
    tools: {
      cell: '格子',
      rect: '矩形',
      ellipse: '橢圓',
      polygon: '多邊形',
      'curve-closed': '封閉曲線',
    },
    addLayer: '新增地面的格子圖層',
  },
  wall: {
    subtool: '形狀',
    tools: {
      rect: '矩形',
      ellipse: '橢圓',
      line: '直線',
      path: '折線',
      polygon: '多邊形',
      curve: '曲線',
      'curve-closed': '封閉曲線',
    },
  },
  room: {
    subtool: '形狀',
    tools: {
      rect: '矩形',
      ellipse: '橢圓',
      polygon: '多邊形',
      'curve-closed': '封閉曲線',
      path: '折線（自動封閉）',
      curve: '曲線（自動封閉）',
    },
    ground: '地面',
    wall: '牆壁',
  },

  pattern: {
    title: '圖樣',
    groundTitle: '地面的圖樣',
    wallTitle: '牆壁的圖樣',
    genres: { all: '全部', user: '自訂' },
    solid: '單色',
    solidColor: '單色的顏色',
    add: '新增自訂圖樣',
    emptyHint: '沒有內建圖樣。請按「＋」上傳自己的圖片來當圖樣。',
    remove: (name: string) => `刪除圖樣「${name}」`,
    removeTitle: '刪除自訂圖樣',
    removeConfirm: (name: string) => `要刪除圖樣「${name}」嗎？已經畫好的物件不受影響。`,
    defaultName: '圖樣',
    detail: '圖樣細節',
    offsetX: '偏移 X',
    offsetY: '偏移 Y',
    rotation: '旋轉',
    scale: '縮放',
    loadFailed: '讀取圖樣失敗',
  },

  decor: {
    title: '裝飾',
    genres: { all: '全部', user: '自訂', 'jp-symbol': '地圖符號', icon: '圖示' },
    add: '新增自訂裝飾',
    remove: (name: string) => `從清單移除「${name}」`,
    removeTitle: '移除自訂裝飾',
    removeConfirm: (name: string) => `要從清單移除裝飾「${name}」嗎？已經放好的不受影響。`,
    defaultName: '裝飾',
    size: '大小',
    rotation: '旋轉',
    flip: '翻轉',
    flipX: '水平',
    flipY: '垂直',
    recolor: '改色（只有 SVG）',
    fill: '填色',
    stroke: '描邊',
    original: '原色',
    resetColor: '回到原色',
    loadFailed: '讀取裝飾失敗',
    hint: '選好之後在畫布上點一下放置；R／Shift＋R 旋轉。',
  },

  freehand: {
    brush: '筆刷',
    brushes: { pencil: '畫筆', spray: '噴槍', eraser: '橡皮擦' },
    color: '顏色',
    width: '線寬',
    smoothing: '平滑化',
    smoothingHint: '距離小於這個值的點捨去（0＝不平滑）',
    addLayer: '新增手繪圖層',
    shiftHint: '按住 Shift 畫直線。',
  },

  text: {
    font: '字型',
    size: '大小',
    style: '樣式',
    bold: '粗體',
    italic: '斜體',
    underline: '底線',
    linethrough: '刪除線',
    fill: '文字的顏色',
    stroke: '描邊',
    strokeWidth: '描邊的粗細',
    hint: '點空白處開始輸入，點已有的文字可以編輯；Enter 換行，點畫布的其他地方結束。',
    fontGroups: {
      tc: '繁體中文',
      gothic: '日文黑體',
      mincho: '日文明體',
      round: '日文圓體／流行',
      hand: '日文楷書／手寫',
      deco: '日文裝飾',
      fantasy: '西文奇幻',
      horror: '西文恐怖／科幻',
      mono: '西文等寬／現代',
    },
  },

  image: {
    pick: '選擇圖片',
    hint: '圖片以原尺寸放在原點（左上角對齊）；也可以把圖片拖進畫布。',
  },

  layers: {
    title: '圖層',
    list: '圖層清單',
    add: '新增圖層',
    group: '群組',
    ungroup: '解散群組',
    groupToggle: '群組／解散群組',
    delete: '刪除',
    empty: '還沒有物件',
    show: (name: string) => `顯示「${name}」`,
    hide: (name: string) => `隱藏「${name}」`,
    locked: '已鎖定（點一下解除）',
    rename: '重新命名',
    renameField: (name: string) => `「${name}」的新名稱`,
    opacity: '不透明度',
    blend: '混合模式',
    drag: '拖曳調整順序',
    kinds: {
      cell: '格子圖層',
      freehand: '手繪圖層',
      group: '群組',
      text: '文字',
      image: '圖片',
      decor: '裝飾',
      room: '房間',
      shape: '圖形',
    },
  },

  blend: {
    groups: { basic: '基本', light: '明暗', diff: '差異與色彩' },
    modes: {
      'source-over': '正常',
      'source-atop': '覆蓋於上',
      'destination-out': '挖空',
      'source-in': '交集',
      xor: 'XOR',
      multiply: '色彩增值',
      screen: '濾色',
      overlay: '覆蓋',
      darken: '變暗',
      lighten: '變亮',
      'color-dodge': '加亮顏色',
      'color-burn': '加深顏色',
      'hard-light': '實光',
      'soft-light': '柔光',
      difference: '差異化',
      exclusion: '排除',
      hue: '色相',
      saturation: '飽和度',
      color: '顏色',
      luminosity: '明度',
    } as Record<string, string>,
  },

  actions: {
    bar: '選取物件的操作',
    boolBar: '布林運算',
    group: '群組',
    ungroup: '解散群組',
    duplicate: '複製',
    visibility: '顯示／隱藏',
    hide: '隱藏',
    show: '顯示',
    lock: '鎖定',
    unlock: '解除鎖定',
    front: '移到最上層',
    back: '移到最下層',
    delete: '刪除',
    rename: '重新命名',
    menu: '物件',
  },

  finish: {
    cancel: '取消',
    ok: '確定',
    bar: '作圖',
  },

  settings: {
    grid: '網格',
    gridVisible: '顯示網格',
    gridColor: '顏色',
    gridWidth: '粗細',
    gridStyle: '線型',
    gridStyles: { solid: '實線', dashed: '虛線', dotted: '點線' },
    snap: '吸附',
    snapEnabled: '啟用吸附',
    snapShift: '按住 Shift 時暫時停用',
    snapIntersection: '交點（格點）',
    snapCenter: '格子中心',
    snapMidpoint: '邊的中點',
    save: '儲存',
    autoSave: '自動儲存',
    autoSaveHint: '所有地圖共用。關閉時要按「立即儲存」或 Ctrl＋S。',
    info: '這張地圖',
    gridType: '網格種類',
    cellSize: '格子大小',
  },

  exportDialog: {
    title: '匯出圖片',
    pickBanner: '在畫布上點兩下（或拖曳）框出要匯出的範圍。',
    cancel: '取消',
    format: '格式',
    formats: { png: 'PNG', jpeg: 'JPEG', svg: 'SVG' },
    bg: '背景',
    bgs: { transparent: '透明', white: '白色' },
    jpegNoAlpha: 'JPEG 不能透明，背景固定白色。',
    grid: '含網格',
    gridOffNote: '地圖設定的「顯示網格」關著，所以不會畫網格。',
    svgGridNote: 'SVG 不含網格。',
    cellRes: '每格解析度',
    pxPerCell: 'px／格',
    info: (w: string, h: string, iw: number, ih: number) =>
      `${w} × ${h} 格（內部：${n(iw)} × ${n(ih)} px）`,
    size: (w: number, h: number) => `輸出尺寸：${n(w)} × ${n(h)} px`,
    preview: '預覽',
    download: '下載',
    reselect: '重新選範圍',
    tooLarge: '輸出尺寸太大，請降低每格解析度或縮小範圍。',
    tools: '也可以做疊在這張地圖上的素材（在新分頁開啟）：',
    gridTool: (kind: string) => `製作座標網格（${kind}）`,
    rulerTool: (kind: string) => `製作量尺（${kind}）`,
    kinds: { square: '方格', hex: '六角格' },
    failed: '匯出失敗',
  },

  upload: {
    tooLarge: (mb: number) => `檔案太大（上限 ${n(mb)} MB）`,
    accept: 'PNG、JPEG、WebP、GIF、SVG，每個最大 4 MB',
  },

  context: {
    label: '物件的操作',
  },

  /* ---------- 快捷鍵 ---------- */
  keys: {
    groups: { tools: '工具', edit: '編輯', view: '檢視', text: '文字' },
    tool: (name: string) => name,
    closedCurve: '封閉曲線',
    undo: '復原',
    redo: '重做',
    save: '立即儲存',
    group: '群組',
    ungroup: '解散群組',
    delete: '刪除選取的物件',
    finish: '完成作圖（折線、多邊形、曲線）',
    cancel: '取消作圖、離開匯出範圍',
    rotate: '旋轉到下一個角度（有選取時、裝飾工具）',
    rotateBack: '旋轉到上一個角度',
    nudge: '移動選取的物件 1 px',
    nudgeBig: '移動選取的物件 10 px',
    bold: '粗體',
    italic: '斜體',
    underline: '底線',
    pan: '按住拖曳：平移畫面',
    panAlt: 'Alt＋拖曳、滑鼠中鍵拖曳也可以平移',
    wheel: '滾輪：以游標為中心縮放',
    shift: '按住：暫時不吸附；手繪時畫直線',
  },

  /* ---------- 使用方式 ---------- */
  usage: {
    intro:
      '只要有瀏覽器就能畫 TRPG 的戰鬥地圖與平面圖：沿著方格或六角格拉出地面、牆壁、房間，放上家具、門、樹與地圖符號，再匯出成 PNG、JPEG 或 SVG 帶進 CCFOLIA 等線上團工具。地圖會自動存在這個瀏覽器裡，隨時可以接著畫。',
    steps: [
      '在一覽按「新增地圖」，選方格或六角格（六角格可以選平頂、尖頂，以及對齊 CCFOLIA 的正方形網格）。',
      '用「地面」「牆壁」「房間」沿著格子畫出建築；房間會一次產生地面與外牆。地面、牆壁可以用單色或自己上傳的圖樣。',
      '「裝飾」放上家具、門、樹、地圖符號（SVG 的可以改色）；也可以用一般圖形、格子填色、手繪、文字與圖片。',
      '用「選取」移動、縮放、旋轉；選取框上方的按鈕可以複製、鎖定、調整上下層、群組，或對多個圖形做聯集、交集等布林運算。',
      '按「匯出圖片」，在畫布上框出範圍，選格式、背景、網格與每格的解析度後下載。',
    ],
    notes: [
      '作圖時會吸附到格點、格子中心與邊的中點（按住 Shift 暫時不吸附），並顯示尺寸的格數。',
      '滾輪縮放；按住空白鍵或 Alt 拖曳、滑鼠中鍵拖曳可以平移；觸控時兩指平移與縮放。',
      '一覽的「匯出 JSON」可以備份地圖、搬到別的瀏覽器；「讀取 JSON」也能讀舊版（違法建築的 TRPG 實驗室）匯出的檔案。',
      '同一個網站上舊版地圖編輯器存在瀏覽器裡的地圖，第一次開啟時會自動搬進來（舊版的資料不變）。',
    ],
  },
} as const;
