/** 文字演出產生器的介面文字 */
export const S = {
  modeDesc: { title: '畫面中央的大字', long: '開場白、預告、旁白', caption: '地點、時間字幕' },
  tabs: { mode: '模式', text: '文字', style: '樣式', deco: '裝飾', time: '時間與尺寸' },
  phase: {
    intro: '登場',
    hold: '停留',
    outro: '退場',
    scroll: '捲動',
    before: '開始前空白',
    done: '完成狀態',
    after: '結束後空白',
    between: '換頁空白',
  },
  template: {
    title: '範本',
    note: '每個範本是一組完整的設定，只是起點，套用後可以自由修改。切換範本時會保留畫面尺寸與退場開關。',
    reset: '重設為範本預設',
    resetConfirm: '把目前模式的所有設定（含文字）恢復成範本原樣？',
  },
  intro: {
    title: '登場效果',
    blockNote: '整塊效果：整段文字一起動。',
    glyphNote: '逐字效果：每個字依序錯開。時長比字間隔長很多時，看起來會是一道連續的波。',
  },
  sub: {
    title: '副文字登場',
    offsetHint: '主文字登場結束後幾秒開始（負值＝提早）',
    blockSame: '主文字是整塊效果：副文字跟主文字黏在一起動。',
    normal: '副文字在「主文字登場結束＋時差」開始，不會早於文字開始。',
  },
  flow: {
    title: '顯示流程',
    punctHint: '句號、問號、刪節號之後；逗號、頓號停一半',
    bigHint: '畫面短邊的百分比',
    scrollNote: '捲動模式沒有停留與退場，整段從畫面外捲進來再捲出去。',
    charTitle: '每個字怎麼出現',
  },
  paging: { title: '換頁', note: '每一頁各自完成登場、停留、退場，再接下一頁。' },
  hold: { title: '停留中效果', none: '登場完成後保持不動。' },
  outro: { title: '退場效果', backspaceNote: '退格刪除一律從最後一個字往前刪。' },
  glitch: { title: '雜訊顏色' },
  text: {
    longPaging: '空一行＝換頁（翻頁時前一頁會先退場）。修改過的文字會依範本分別記住。',
    longOne: '整段當作一頁。修改過的文字會依範本分別記住。',
    caption: '字幕模式的文字所有範本共用。',
    title: '修改過的文字會依範本分別記住。',
    placeholder: '輸入要做成動畫的文字',
    subPlaceholder: '例如英文標語、時間',
    verticalNote: '直書時，，。、 移到字格右上（或置中）；「」（）…— 等符號轉 90°；！？ 保持直立。',
    wrapNote:
      '換行時套用禁則：，。、；：！？」』）等不放在行首，「『（ 等不放在行尾；英文單字不從中間斷開。',
    wrapCharsHint: '0＝不依字數換行。半形英數約算半個字。',
  },
  style: {
    kits: '文字風格（一鍵套用）',
    fontNote:
      '中文字型沒有的韓文字會自動改用風格相近的 Noto Sans KR／Noto Serif KR；西文字型遇到中文字會自動改用思源黑體或思源宋體。網路字型只在選到時才下載，而且只下載用到的字。',
    subSameColor: '目前跟主文字使用相同的塗色。',
    fillOpacityHint: '0% 加上外框就是空心字',
  },
  deco: {
    notes: {
      none: '不加裝飾。',
      band: '橫貫畫面的半透明色帶，上下邊緣柔化。會先開場，文字晚一點出現。',
      tape: '文字上下各一條黃黑斜紋膠帶，斜紋會流動、閃爍。會先開場。',
      roundBox: '包住全部文字的圓角底框。會跟著整塊效果一起縮放。',
      frame: '只框住主文字、左右延伸的長框；外框線從左上角順時針一筆畫完。會先開場。',
      rails: '文字上下各一條橫線，從中央往兩端伸長。',
      underline: '主文字下方一條橫線（有副文字在下方時畫在兩者正中間）。',
      dashes: '主文字左右各一條短線。',
      sideBar: '文字左側一條直線（直書時改成上方橫線）。',
      corners: '四個角的 L 形角線，像取景框。',
    } as Record<string, string>,
    scrollNote: '捲動模式不使用裝飾。',
    bgNote: '整張背景會畫進輸出的檔案裡（預覽底色則不會）。',
  },
  time: {
    size: '畫面尺寸',
    timing: '時間',
  },
  export: {
    noText: '請先輸入文字，再匯出。',
    loadingFonts: '載入字型',
    seqTitle: '文字演出產生器　連番 PNG',
    loopOnceHint: '播放一次會停在最後一格：開著退場時最後一格是全透明，關掉退場時停在完成狀態。',
    quantizeHint:
      '256 色：實際用到的顏色在 256 色以內時完全無損；超過時才減色（保留半透明邊緣）。全彩檔案約大 3 倍。',
    sizeWarning: '建議改用 256 色、降低 fps、縮小畫面尺寸，或拿掉停留效果。',
    pngNote: 'PNG：暫停中存目前那一格；正在播放或那一格是空的時候，存完成狀態。',
    nameLabel: '檔名（留空＝自動命名）',
    autoName: '自動命名',
  },
  hints: {
    empty: '還沒有文字：請在「文字」分頁輸入內容。',
    holdSize: '已選停留效果：每一格畫面都不同，檔案會變大。',
    breathe: '「呼吸發光」需要先開啟光暈。',
    breatheAction: '開啟光暈',
    loopNoOutro: '退場關閉又設成無限循環：播完會直接從頭開始。',
    loopNoOutroAction: '改成播放一次',
  },
  gallery: {
    open: '效果一覽',
    note: '用目前的文字示範每種效果。點一下就套用。',
    titles: {
      intro: '登場效果一覽',
      outro: '退場效果一覽',
      hold: '停留中效果一覽',
      char: '每個字的出現方式',
      flow: '長文顯示流程一覽',
    } as Record<string, string>,
    block: '整塊',
    glyph: '逐字',
  },
  loadingFonts: '字型載入中…',
} as const;
