/**
 * CoC 7 版調查員角色卡的介面文字與角色卡上印出來的標籤（台灣繁中，用詞照 DESIGN.md 第 5 節）。
 * 技能名稱與初始值沿用舊版 trpg-lab（MIT）的繁中翻譯。
 */

/** 預設技能的名稱（鍵與 model.ts 的 SKILL_CATALOG 相同） */
export const SKILL_NAMES: Readonly<Record<string, string>> = Object.freeze({
  intimidate: '恐嚇',
  fastTalk: '話術',
  medicine: '醫學',
  driveAuto: '汽車駕駛',
  firstAid: '急救',
  occult: '神秘學',
  stealth: '潛行',
  dodge: '閃避',
  science: '科學',
  locksmith: '鎖匠',
  appraise: '估價',
  mechRepair: '機械維修',
  listen: '聆聽',
  fightingBrawl: '格鬥（鬥毆）',
  cthulhuMythos: '克蘇魯神話',
  artCraft: '藝術／手藝',
  accounting: '會計',
  archaeology: '考古學',
  computerUse: '電腦使用',
  survival: '生存',
  naturalWorld: '博物學',
  firearmsHandgun: '射擊（手槍）',
  firearmsRifle: '射擊（步槍／霰彈槍）',
  heavyMachinery: '操作重型機械',
  creditRating: '信用評級',
  psychology: '心理學',
  anthropology: '人類學',
  swim: '游泳',
  psychoanalysis: '精神分析',
  persuade: '說服',
  pilot: '駕駛',
  jump: '跳躍',
  track: '追蹤',
  sleightOfHand: '妙手',
  elecRepair: '電氣維修',
  electronics: '電子學',
  throw: '投擲',
  climb: '攀爬',
  libraryUse: '圖書館使用',
  navigate: '導航',
  disguise: '喬裝',
  law: '法律',
  otherLanguage: '外語',
  ownLanguage: '母語',
  charm: '魅惑',
  spotHidden: '偵查',
  history: '歷史',
});

/** 角色卡（印出來的紙面）上的文字 */
export const SHEET = {
  title: '調查員角色卡',
  info: {
    name: '姓名',
    player: '玩家',
    occupation: '職業',
    age: '年齡',
    sex: '性別',
    residence: '居住地',
    birthplace: '出生地',
  },
  characteristics: '屬性',
  idea: '靈感',
  know: '知識',
  mov: '移動力',
  portrait: '頭像',
  hp: '生命值',
  majorWound: '重傷',
  dying: '瀕死',
  unconscious: '昏迷',
  max: '最大值',
  san: '理智',
  temporary: '臨時瘋狂',
  indefinite: '不定期瘋狂',
  start: '初始',
  insane: '永久瘋狂',
  luck: '幸運',
  luckOut: '運氣耗盡',
  mp: '魔法值',
  skills: '技能',
  weapons: '武器',
  weapon: {
    name: '武器',
    regular: '一般',
    hard: '困難',
    extreme: '極限',
    damage: '傷害',
    range: '射程',
    attacks: '攻擊次數',
    ammo: '裝彈數',
    malfunction: '故障',
  },
  combat: '戰鬥',
  db: '傷害加值',
  build: '體格',
  dodge: '閃避',
  backstory: '背景故事',
  story: {
    description: '外貌描述',
    ideology: '思想／信念',
    people: '重要之人',
    locations: '意義非凡之地',
    possessions: '寶貴之物',
    traits: '特質',
    injuries: '傷口、疤痕',
    phobias: '恐懼症、躁狂症',
    tomes: '魔法書、咒文、神器',
    encounters: '遭遇過的超自然存在',
  },
  gear: '裝備與隨身物品',
  assets: '現金與資產',
  spending: '消費水準',
  cash: '現金',
  assetsLabel: '資產',
  memo: '備註',
  customTitle: '自訂',
  /** 技能的初始值寫法：15 →「15%」、DEX 的一半 →「DEX×½」、EDU →「EDU%」 */
  /** 會被截掉的欄位在提醒裡的名稱 */
  lineOf: (label: string, n: number) => `${label} 第 ${n} 行`,
  weaponRow: (n: number) => `武器第 ${n} 列`,
  baseDexHalf: 'DEX×½',
  baseEdu: 'EDU%',
} as const;

/** 新角色卡的預設內容（第一把武器「徒手」、自訂欄的標題） */
export const DEFAULTS = {
  unarmed: '徒手',
  unarmedDamage: '1D3 + DB',
  unarmedAttacks: '1',
  dash: '─',
  customTitle: '自訂',
} as const;

/** 屬性的中文名稱（表單用） */
export const STAT_NAMES: Readonly<Record<string, string>> = Object.freeze({
  STR: '力量',
  DEX: '敏捷',
  INT: '智力',
  CON: '體質',
  APP: '外貌',
  POW: '意志',
  SIZ: '體型',
  EDU: '教育',
});

export const S = {
  undo: '復原',
  redo: '重做',
  keysGroup: '編輯',
  outputGroup: '輸出',
  usage: [
    '左邊的表單填好，右邊就是可以直接列印的 A4 角色卡（兩頁）；所有欄位都會自動儲存在這個瀏覽器裡。',
    '屬性、技能、武器填了「一般」值就會自動算出困難（½）與極限（⅕）。生命值、魔法值、理智、移動力、傷害加值、體格與技能值可以留白讓工具依規則自動算，也可以直接填數字取代。',
    '技能可以分配職業與興趣點數（技能值＝初始＋職業＋興趣＋成長），上方會顯示已用的點數；也可以直接填技能值。技能表最多印 60 列、武器最多印 7 列。',
    '「角色卡」清單可以新增、複製、重新命名、刪除與切換多張角色卡；要留一份快照時先複製一張。',
    '頭像：選擇圖片後裁切成角色卡上的頭像框比例；圖片存在這個瀏覽器裡，存成專案檔時會一起打包。',
    '「列印／存成 PDF」只印角色卡（在列印對話框選「另存為 PDF」即可存檔）；也可以匯出 PNG，或複製 CCFOLIA 角色資料貼進房間。',
    '舊版角色卡（實驗室版）存在這個瀏覽器裡的角色卡與自動儲存的內容，第一次開啟時會自動搬過來。',
  ],
  list: {
    title: '角色卡',
    aria: '角色卡清單',
    add: '新增角色卡',
    addShort: '新增',
    rename: '角色卡名稱',
    duplicate: (name: string) => `複製「${name}」`,
    duplicateShort: '複製',
    newTitle: '新角色卡',
    copySuffix: '（複本）',
    unnamed: '未命名的角色卡',
    meta: (name: string, occupation: string) =>
      [name || '（姓名未填）', occupation].filter(Boolean).join('・'),
    removeTitle: (name: string) => `刪除角色卡「${name}」？`,
    removeDescription: '刪除後可以用復原（Ctrl＋Z）找回來。',
    current: (name: string) => `編輯中：${name}`,
  },
  tabs: {
    aria: '角色卡的欄位',
    info: '基本資料',
    stats: '屬性與狀態',
    skills: '技能',
    combat: '戰鬥',
    story: '背景與物品',
  },
  info: {
    section: '基本資料',
    portrait: '頭像',
    portraitHint: '選擇圖片後裁切成頭像框的比例（寬 13：高 16）。',
    choose: '選擇圖片',
    drop: '把圖片拖到這裡，或',
    recrop: '調整裁切',
    remove: '移除頭像',
    cropTitle: '裁切頭像',
    cropApply: '套用',
    readFailed: '這張圖片無法讀取。',
    notSaved: '瀏覽器的空間不足（或無法使用），頭像只在這次開啟時有效；要留下來請存成專案檔。',
    custom: '自訂欄',
    customTitle: '標題',
    customText: '內容',
    customHint: '每行一項，印 8 行。',
    agePlaceholder: '例：42',
  },
  stats: {
    characteristics: '屬性',
    characteristicsHint: '填 ×5 之後的值（例：STR 50）。',
    statLabel: (key: string, name: string) => `${key} ${name}`,
    halfFifth: (hard: number | null, extreme: number | null) =>
      hard === null ? '困難 —／極限 —' : `困難 ${hard}／極限 ${extreme}`,
    luck: '幸運',
    luckHint: '3D6×5 擲出的值。',
    mov: '移動力',
    auto: (v: string) => `空白＝自動：${v}`,
    autoNone: '空白＝自動（屬性還沒填）',
    resetAuto: '改回自動',
    movFormula: 'DEX、STR 與 SIZ 比較，40 歲起依年齡減少',
    hp: '生命值',
    hpFormula: '(CON＋SIZ)÷10',
    mp: '魔法值',
    mpFormula: 'POW÷5',
    san: '理智',
    sanStart: '初始理智',
    sanStartFormula: '＝POW',
    sanMax: '理智上限',
    sanMaxFormula: '99－克蘇魯神話',
    max: '最大值',
    current: '目前',
    hpMax: '生命值上限',
    hpNow: '目前的生命值',
    mpMax: '魔法值上限',
    mpNow: '目前的魔法值',
    sanNow: '目前的理智',
    currentHint: '印在軌道上（圈起來）。',
    luckNow: '目前的幸運',
    status: '狀態',
    majorWound: '重傷',
    dying: '瀕死',
    unconscious: '昏迷',
    temporary: '臨時瘋狂',
    indefinite: '不定期瘋狂',
  },
  skills: {
    section: '技能',
    budget: '技能點數',
    occupation: '職業技能點數',
    interest: '興趣技能點數',
    occupationFormula: 'EDU×4',
    interestFormula: 'INT×2',
    budgetHint: '依職業不同時可以直接填總點數。',
    used: (used: number, total: number | null) =>
      total === null ? `已用 ${used}` : `已用 ${used}／${total}`,
    over: (n: number) => `超過 ${n} 點`,
    filter: '搜尋技能',
    filterPlaceholder: '技能名稱或專長',
    filterEmpty: '沒有符合的技能。',
    aria: '技能表',
    columns: {
      check: '✓',
      checkLabel: '成長勾選',
      name: '技能',
      base: '初始',
      occupation: '職業',
      interest: '興趣',
      growth: '成長',
      total: '技能值',
      thresholds: '困難／極限',
      thresholdsShort: '½／⅕',
    },
    name: '技能名稱',
    specialty: '專長',
    specialtyPlaceholder: '專長',
    customPlaceholder: '（空白列）',
    baseFormula: (label: string, value: number | null) =>
      value === null ? label : `${label}＝${value}`,
    add: '新增技能',
    insert: (name: string) => `在「${name}」下面插入一列`,
    remove: (name: string) => `刪除「${name}」`,
    drag: (name: string) => `拖曳「${name}」調整順序（Alt＋↑／↓）`,
    noCheck: '這個技能沒有成長勾選',
    rowLabel: (index: number) => `第 ${index} 列`,
    autoTotal: (v: number | null) => (v === null ? '—' : String(v)),
    printLimit: (n: number) => `技能有 ${n} 列；角色卡只印得下 60 列，第 61 列以後不會印出來。`,
    manual: '手動',
  },
  combat: {
    weapons: '武器',
    weaponsAria: '武器清單',
    add: '新增武器',
    name: '武器名稱',
    skill: '使用的技能',
    skillManual: '（直接填技能值）',
    value: '技能值',
    damage: '傷害',
    range: '射程',
    attacks: '攻擊次數',
    ammo: '裝彈數',
    malfunction: '故障',
    up: (name: string) => `把「${name}」往上移`,
    down: (name: string) => `把「${name}」往下移`,
    empty: '還沒有武器。',
    unnamedWeapon: '未命名的武器',
    printLimit: (n: number) => `武器有 ${n} 列；角色卡只印得下 7 列，第 8 列以後不會印出來。`,
    combat: '戰鬥',
    db: '傷害加值（DB）',
    dbFormula: '依 STR＋SIZ 查表',
    build: '體格',
    dodge: '閃避',
    dodgeHint: (v: string) => `跟著技能「閃避」：${v}`,
  },
  story: {
    backstory: '背景故事',
    gear: '裝備與隨身物品',
    gearHint: '每行一項，印 20 行（左右兩欄各 10 行）。',
    assets: '現金與資產',
    spending: '消費水準',
    cash: '現金',
    assetsLabel: '資產',
    otherAssets: '其他',
    otherAssetsHint: '每行一項，印 7 行。',
    gearLimit: (n: number) =>
      `裝備與隨身物品有 ${n} 行；角色卡只印得下 20 行，第 21 行以後不會印出來。`,
    otherAssetsLimit: (n: number) =>
      `現金與資產的「其他」有 ${n} 行；角色卡只印得下 7 行，第 8 行以後不會印出來。`,
    memo: '備註',
    memoHint: '印 20 行（左右兩欄各 10 行）。',
    lines: (n: number) => `印 ${n} 行。`,
  },
  preview: {
    region: '角色卡預覽',
    zoomOut: '縮小',
    zoomIn: '放大',
    fit: '配合寬度',
    zoom: '顯示比例',
    overflow: (fields: string) => `這些欄位的文字太多，印出來會被截掉：${fields}。`,
    page: (n: number) => `第 ${n} 頁`,
  },
  output: {
    section: '輸出',
    print: '列印／存成 PDF',
    printHint: '只印角色卡兩頁（A4、無邊界）；在列印對話框選「另存為 PDF」就能存成 PDF。',
    printKey: '列印',
    png: '匯出 PNG',
    pngPages: 'PNG 的頁面',
    page1: '第 1 頁',
    page2: '第 2 頁',
    both: '兩頁接成一張',
    pngHint: '字型用電腦上的字型（與畫面上的預覽相同）。',
    ccfolia: '複製 CCFOLIA 角色資料',
    ccfoliaHint:
      '能力值、生命值等狀態與擲骰指令；在 CCFOLIA 的房間按 Ctrl＋V 貼上就會新增這個角色。',
    copied: '已複製到剪貼簿',
    copiedHint: '在 CCFOLIA 的房間畫面按 Ctrl＋V 貼上。',
    copyFailed: '無法寫入剪貼簿',
    copyFailedHint: '瀏覽器不允許網頁寫入剪貼簿；請改用其他瀏覽器，或允許剪貼簿的權限後再試一次。',
    printFailed: '無法列印',
    exportFailed: '匯出失敗',
  },
  project: {
    fileName: 'CoC 角色卡',
    resetLabel: '全部重來',
    resetTitle: '刪除所有角色卡、重新開始？',
    resetDescription: '所有角色卡與頭像都會刪除，只留一張新的角色卡（可以復原）。',
    invalid: '專案檔的內容無法使用。',
    missingImages: (n: number) => `專案檔裡有 ${n} 張頭像找不到，這些角色卡的頭像會是空白。`,
  },
  migrate: {
    autosaveTitle: '自動儲存的角色卡',
    blankRow: '空白列',
    label: (text: string, field: string) =>
      `欄位名稱「${text}」（${field}欄改過的名稱；新版的欄位名稱是固定的）`,
    notNumber: (what: string, raw: string) => `${what}「${raw}」（不是數字）`,
    partial: (what: string, raw: string, v: number) => `${what}「${raw}」（只取 ${v}）`,
    skillValue: (label: string) => `技能「${label}」的技能值`,
    weaponValue: (name: string) => `武器「${name}」的技能值`,
    dodge: (combat: number, skill: number | null) =>
      `戰鬥欄的閃避「${combat}」（和技能「閃避」的 ${skill ?? '空白'} 不同；新版的戰鬥欄跟著技能）`,
    portrait: '頭像（圖片的格式讀不出來）',
    title: (n: number) => `已從舊版角色卡搬來 ${n} 張`,
    names: (names: string) => `搬來的角色卡：${names}。舊版的資料沒有刪除。`,
    autosave: '自動儲存的內容',
    unparsed: (items: string) => `下列內容無法轉換，已略過：${items}`,
    dismiss: '知道了',
  },
  png: {
    fileSuffix: '角色卡',
    page: (p: string) => `第${p}頁`,
    saved: (name: string) => `已匯出 ${name}`,
    size: (w: number, h: number) => `${w} × ${h} px`,
    scale: 'PNG 的解析度',
    scale1: '標準（96 dpi）',
    scale2: '高（192 dpi）',
    scale3: '列印用（288 dpi）',
  },
  ccfolia: {
    sanRoll: '理智檢定',
    luckRoll: '幸運',
    idea: '靈感',
    know: '知識',
    damage: (name: string) => `${name}（傷害）`,
    weapon: '武器',
    build: '體格',
    mov: 'MOV',
    luck: '幸運',
    unnamed: '無名氏',
  },
} as const;
