/**
 * 前景框產生器的介面文字（台灣繁體中文）。範本、差分、裝飾的名稱與說明依 id 查。
 */

const kb = (n: number): string =>
  n >= 1048576 ? `${(n / 1048576).toFixed(1)} MB` : `${Math.max(1, Math.round(n / 1024))} KB`;

export const S = {
  tabsAria: '設定分類',
  tabs: {
    frame: '框',
    deco: '裝飾',
    layers: '圖層',
    variants: '差分',
    project: '專案',
  },

  usage: [
    '「框」分頁決定窗的形狀、邊距、顏色、線條與陰影；「裝飾」分頁沿著框加上藤蔓、鎖鏈、角飾等裝飾。選一個設計範本再按「套用」，可以一次換掉整套外觀（圖層與差分不受影響）。',
    '「圖層」分頁放自己的圖片與文字。在預覽上可以直接拖曳圖層與差分標籤，按住 Shift 只沿水平或垂直移動；預覽有焦點時方向鍵移動 1 單位（Shift＋方向鍵 10 單位），Delete 刪除選取的圖層。',
    '想依時間帶、天氣、季節做出好幾張時，到「差分」分頁打開「製作差分」：每個差分可以有自己的配色、窗的覆蓋色與窗內效果（雨、雪、霧…），並一次匯出成 ZIP。',
    '預覽的範例風景、背景圖、格線與選取框只出現在預覽裡，匯出的 PNG 只有框本身，窗的部分是透明的。',
    '設定、圖片與預覽背景會自動存在這個瀏覽器；上傳的字型存在共用的字型庫。要換電腦或備份時，用頁首的「專案」選單存成專案檔。',
  ],
  ccfoliaTitle: '在 CCFOLIA 裡怎麼用',
  ccfolia: (cell: number) => [
    '在盤面的前景上按兩下（或從右鍵選單）設定前景圖片，選這個工具匯出的 PNG。',
    `前景的寬、高以格數設定（1 格＝${cell} px），請填「輸出尺寸」下方提示的格數。比例和圖片不一致時，沒開自動裁切會把圖拉伸變形，開了則會裁掉邊緣。`,
    '窗是透明的，房間背景會從窗露出來。',
    '建議每個差分各建一個「場景」：場景會一起記住前景、背景、標記面板與 BGM，切換場景就能瞬間換框。',
  ],
  unofficial: '本工具與 CCFOLIA 官方無關。',

  /* ---------- 框 ---------- */
  design: {
    section: '設計範本',
    label: '範本',
    apply: '套用',
    note: '套用會換掉窗的形狀、邊距、顏色、線條、陰影、角飾、裝飾與差分標籤的樣式；圖層、差分清單、輸出尺寸與檔名維持不變。可以按復原取消。',
  },
  designs: {
    simple: { name: '簡約', desc: '圓角加細線，什麼團都合用的基本款。' },
    mansion: { name: '古典洋館', desc: '內凹的角配雙線與唐草角飾，適合探索與哥德風。' },
    forest: { name: '森林遺跡', desc: '長了青苔的石框纏著藤蔓與小花，適合奇幻與廢墟探索。' },
    horror: { name: '恐怖', desc: '暗沉的框配上滴落的液體與蜘蛛網，適合克蘇魯與怪談。' },
    steampunk: { name: '蒸汽龐克', desc: '黃銅色的框、齒輪與鎖鏈，適合機械都市與冒險。' },
    winter: { name: '雪國', desc: '白框上積雪、垂下冰柱，適合冬天與雪山。' },
    sakura: { name: '春櫻', desc: '淡粉色的框與櫻花枝，適合校園與春天的日常。' },
    cinema: { name: '電影黑邊', desc: '只在上下留黑帶，適合開場與重視演出的場面。' },
    novel: { name: '視覺小說', desc: '下方留出大片文字區，可以放立繪或台詞。' },
    cyber: { name: '科幻霓虹', desc: '斜切的角、霓虹線條與電路，適合科幻與現代異能。' },
    wa: { name: '和風', desc: '缺角的造型加上和紙質感，適合和風奇譚與時代劇。' },
  } as Record<string, { name: string; desc: string }>,

  size: {
    section: '輸出尺寸',
    label: '尺寸',
    custom: '自訂',
    width: '寬',
    height: '高',
    customHint: '64～4096 px；按 Enter 或離開欄位時套用。',
    presetNote: {
      '1920x1080': '16:9',
      '1280x720': '16:9，較輕',
      '1152x648': '16:9，與 48 × 27 格等倍',
      '1440x1080': '4:3',
      '960x720': '4:3，與 40 × 30 格等倍',
      '1080x1080': '正方形',
    } as Record<string, string>,
    cells: (w: number, h: number) =>
      `在 CCFOLIA 設定前景時，寬填 ${w} 格、高填 ${h} 格（1 格＝24 px）。`,
    approx: '比例無法剛好整除，這是接近值。',
  },

  opening: {
    section: '窗',
    shape: '形狀',
    rect: '矩形',
    ellipse: '橢圓',
    quick: '邊距快速設定',
    layouts: {
      thin: '細',
      normal: '標準',
      thick: '粗',
      cinema: '上下帶狀',
      novel: '下方留寬',
      side: '左右留寬',
    } as Record<string, string>,
    link: '四邊共用',
    all: '框的粗細',
    t: '上邊距',
    b: '下邊距',
    l: '左邊距',
    r: '右邊距',
    info: (w: number, h: number, cw: string, ch: string, px: string, py: string) =>
      `窗 ${w} × ${h} px，相當於盤面的寬 ${cw} × 高 ${ch} 格，左上角在第 ${px}, ${py} 格的位置。`,
    corners: '窗的四角',
    linkCorners: '四角共用',
    cornerShape: (name: string) => `${name}的形狀`,
    cornerSize: (name: string) => `${name}的大小`,
    cornerAll: '四角',
    cornerNames: ['左上角', '右上角', '右下角', '左下角'],
    cornerTypes: {
      square: '直角',
      round: '圓角',
      chamfer: '斜切',
      scoop: '內凹',
      notch: '缺角',
    } as Record<string, string>,
    outerRadius: '外側圓角',
    outerHint: '畫布四個角的圓角，圓角外透明。',
  },

  colors: {
    section: '顏色與填色',
    frame1: '框色 1',
    frame2: '框色 2',
    accent: '強調色',
    text: '文字色',
    editingVariant: (name: string) =>
      `正在改差分「${name}」自己的顏色。要改回整體配色，到「差分」分頁取消「這個差分用自己的顏色」。`,
    editingGlobal: '這是整體配色。想讓某個差分換色，到「差分」分頁勾選「這個差分用自己的顏色」。',
    fill: '填色方式',
    fills: {
      linear: '線性漸層',
      radial: '放射漸層',
      solid: '單色',
      none: '不填色',
    } as Record<string, string>,
    fillHint: {
      linear: '框色 1 漸變到框色 2。',
      radial: '中央框色 1，往四角漸變成框色 2。',
      solid: '只用框色 1。',
      none: '框完全透明，只靠線條、角飾、裝飾與圖層。',
    } as Record<string, string>,
    angle: '漸層方向',
    angleHint: '0° 由下往上、90° 由左往右、180° 由上往下（與 CSS 相同）。',
    opacity: '框的不透明度',
    grain: '顆粒感',
    grainHint: '加了顆粒的 PNG 會變大不少。',
  },

  colorRef: {
    accent: '強調色',
    text: '文字色',
    frame1: '框色 1',
    frame2: '框色 2',
    custom: '自訂顏色',
    none: '不換色',
    customAria: (label: string) => `${label}（自訂顏色）`,
  },

  lines: {
    section: '線條與陰影',
    inner: '窗的邊線',
    innerWidth: '邊線粗細',
    innerGap: '離窗的距離',
    double: '雙線',
    innerColor: '邊線顏色',
    outer: '畫面的邊線',
    outerWidth: '邊線粗細',
    outerGap: '離畫布邊的距離',
    outerColor: '邊線顏色',
    shadow: '窗的陰影',
    shadowSize: '模糊',
    shadowOpacity: '濃度',
    shadowColor: '陰影顏色',
    shadowHint: '從框往窗內投下的陰影，只出現在窗裡。',
  },

  /* ---------- 裝飾 ---------- */
  ornament: {
    section: '角飾',
    hint: '窗的四個角各放一個線稿圖案，朝向窗內。',
    type: '角飾',
    types: {
      none: '無',
      bracket: '折角線',
      diamond: '菱形',
      star: '星芒',
      flourish: '唐草',
      dots: '圓點',
    } as Record<string, string>,
    size: '大小',
    gap: '距離窗角',
    gapHint: '正值往框外移、負值往窗內移。',
    width: '線條粗細',
    color: '角飾顏色',
  },
  deco: {
    section: '沿框裝飾',
    addHint: '按一下新增；同一種可以加很多個。',
    addLabel: (name: string) => `新增${name}`,
    list: '裝飾（上面的在前面）',
    empty:
      '還沒有裝飾。用上面的按鈕新增，或到「框」分頁套用有裝飾的範本（森林遺跡、恐怖、蒸汽龐克…）。',
    show: (name: string) => `顯示${name}`,
    forward: (name: string) => `${name}往前`,
    backward: (name: string) => `${name}往後`,
    selected: '選取中的裝飾',
    placement: '配置',
    placements: {
      all: '窗的四周',
      top: '上',
      bottom: '下',
      topbottom: '上下',
      sides: '左右',
      corners: '四個角',
      topcorners: '上方兩角',
      bottomcorners: '下方兩角',
    } as Record<string, string>,
    size: '大小（倍率）',
    density: '密度',
    coverage: '延伸量',
    coverageHint: '從角往邊的中間長多少；100% 是整條邊都有。',
    offset: '離窗距離',
    offsetHint: '正值往框外、負值往窗內。',
    clip: '不溢出到窗內',
    showIn: '顯示的差分',
    reseed: '重新產生圖樣',
    duplicate: '複製',
    remove: '刪除',
  },
  decoTypes: {
    ivy: {
      name: '藤蔓',
      desc: '藤蔓沿著窗邊攀爬；延伸量低時只從角落長出一點。',
      c1: '莖',
      c2: '葉',
    },
    flowers: {
      name: '小花',
      desc: '散落的小花；疊在藤蔓上就成了開花的藤。',
      c1: '花瓣',
      c2: '花心',
    },
    thorns: { name: '荊棘', desc: '帶刺的枝條互相纏繞。', c1: '枝', c2: '花苞' },
    sakura: {
      name: '櫻花枝',
      desc: '櫻花枝從角落伸出來；延伸量決定枝條長度。',
      c1: '枝',
      c2: '花',
    },
    grass: { name: '草叢', desc: '邊緣長滿草。', c1: '草 1', c2: '草 2' },
    stars: { name: '星塵', desc: '框上散落小星星。', c1: '星星 1', c2: '星星 2' },
    cobweb: {
      name: '蜘蛛網',
      desc: '角落結了蜘蛛網；密度高時網更密，還會垂下蜘蛛。',
      c1: '蛛絲',
      c2: '蜘蛛',
    },
    chain: { name: '鎖鏈', desc: '鎖鏈沿著框垂掛；密度決定垂掛的段數。', c1: '亮部', c2: '暗部' },
    gears: { name: '齒輪', desc: '角落的齒輪互相咬合；密度越高齒輪越多。', c1: '齒輪', c2: '軸心' },
    circuit: { name: '電路', desc: '像電路板的線路與端點沿著框延伸。', c1: '線路', c2: '端點' },
    snowcap: { name: '積雪冰柱', desc: '邊上積雪，上緣垂下冰柱。', c1: '雪', c2: '陰影' },
    drips: { name: '滴落', desc: '液體往下滴；紅色像血，綠色像毒液。', c1: '液體', c2: '光澤' },
  } as Record<string, { name: string; desc: string; c1: string; c2: string }>,

  /* ---------- 圖層 ---------- */
  layer: {
    section: '新增',
    addImage: '新增圖片',
    addText: '新增文字',
    addHint:
      'PNG、JPEG、WebP 等；也可以把檔案拖進頁面，或按 Ctrl＋V 貼上。用別人發布的素材時，請遵守其使用條款。',
    list: '圖層（上面的在前面）',
    empty: '還沒有圖層。',
    show: (name: string) => `顯示${name}`,
    forward: (name: string) => `${name}往前`,
    backward: (name: string) => `${name}往後`,
    badgeText: '文',
    badgeImage: '圖',
    badgeBack: '後',
    selected: '選取中的圖層',
    name: '名稱',
    fit: '擺放方式',
    fits: { free: '自由擺放', stretch: '拉伸鋪滿', cover: '等比鋪滿', tile: '平鋪' } as Record<
      string,
      string
    >,
    recolor: '圖片換色',
    text: '文字內容',
    textHint: '開了差分時，{差分} 會換成差分的名稱、{英文} 換成英文標示；沒開差分時兩者都是空白。',
    font: '字型',
    fontSize: '文字大小',
    bold: '粗體',
    vertical: '直書',
    align: '對齊',
    aligns: { left: '靠左', center: '置中', right: '靠右' } as Record<string, string>,
    spacing: '字距',
    color: '文字顏色',
    stroke: '外框粗細',
    strokeColor: '外框顏色',
    shadow: '陰影',
    x: '水平位置',
    y: '垂直位置',
    rotation: '旋轉',
    scale: '大小',
    flip: '左右翻轉',
    opacity: '不透明度',
    blend: '混合模式',
    blends: {
      'source-over': '一般',
      multiply: '色彩增值',
      screen: '濾色',
      overlay: '覆蓋',
      'soft-light': '柔光',
      lighter: '加亮',
    } as Record<string, string>,
    order: '疊放位置',
    orders: { front: '最前面', back: '框的下層' } as Record<string, string>,
    orderHint: '框的下層：壓在填色上，但在線條、角飾、裝飾與差分標籤底下。',
    clip: '繪製範圍',
    clips: { none: '不限', frame: '限框上', window: '限窗內' } as Record<string, string>,
    showIn: '顯示的差分',
    duplicate: '複製',
    remove: '刪除',
    copySuffix: ' 的複本',
    defaultImageName: '圖片',
    defaultTextName: '文字',
    defaultText: '第一章　霧中的燈塔',
  },

  /* ---------- 差分 ---------- */
  variant: {
    section: '差分',
    enable: '製作差分',
    enableHint:
      '同一個框依時間帶、天氣等條件做出好幾張，各自換色、加窗內效果與標籤，一次匯出成 ZIP。',
    kind: '差分種類',
    kindHint: '換種類會整批換掉下面的清單（可以復原）。',
    list: '差分清單',
    listHint: '點一列切換預覽與編輯的對象；取消勾選的差分不匯出。',
    exportOn: (name: string) => `匯出${name}`,
    notExported: '不匯出',
    up: (name: string) => `${name}上移`,
    down: (name: string) => `${name}下移`,
    remove: (name: string) => `刪除${name}`,
    add: '新增差分',
    editing: (name: string) => `「${name}」的設定`,
    name: '顯示名稱',
    sub: '英文標示',
    icon: '圖示',
    iconPick: '選擇圖示圖片',
    iconPicked: '已選擇圖片',
    useColors: '這個差分用自己的顏色',
    tint: '窗的覆蓋色',
    tintAmount: '覆蓋強度',
    effect: '窗內效果',
    effectAmount: '效果強度',
    effectHint: '覆蓋色與效果只畫在窗裡，例如夜晚讓窗外暗一點、雨天像隔著雨看。',
    copyColors: '把這組顏色套用到所有差分',
    noName: '（未命名）',
    defaultName: '組合',
    newName: (n: number) => `組合 ${n}`,
    newSub: (n: number) => `PATTERN ${n}`,
    switchAria: '切換差分',
    thumbsAria: '差分縮圖',
  },
  variantKinds: {
    time: {
      name: '時間帶',
      desc: '早晨、白天、傍晚、夜晚：用框的配色與窗的覆蓋色表現時間推移，顏色自動推導。',
    },
    weather: { name: '天氣', desc: '晴、陰、雨、雪、霧、雷雨：窗上疊雨、雪、霧的效果。' },
    season: { name: '季節', desc: '春夏秋冬各自的配色，配上花瓣、落葉、飄雪等效果。' },
    scene: { name: '場面氛圍', desc: '日常、探索、戰鬥、危機、回想：用窗內效果切換氣氛。' },
    sanity: { name: '理智狀態', desc: '清醒、動搖、瘋狂：用暗角與故障雜訊表現精神狀態。' },
    chapter: { name: '章節', desc: '序章、第一章…：顏色共用，只換標籤。' },
    custom: { name: '自由', desc: '名稱與數量都自由，依喜歡的條件做差分。' },
  } as Record<string, { name: string; desc: string }>,
  variantNames: {
    morning: '早晨',
    day: '白天',
    evening: '傍晚',
    night: '夜晚',
    sunny: '晴天',
    cloudy: '陰天',
    rain: '雨',
    snow: '雪',
    fog: '霧',
    storm: '雷雨',
    spring: '春',
    summer: '夏',
    autumn: '秋',
    winter: '冬',
    daily: '日常',
    explore: '探索',
    battle: '戰鬥',
    crisis: '危機',
    memory: '回想',
    sane: '清醒',
    shaken: '動搖',
    madness: '瘋狂',
    prologue: '序章',
    ch1: '第一章',
    ch2: '第二章',
    ch3: '第三章',
    epilogue: '終章',
    p1: '組合 1',
    p2: '組合 2',
  } as Record<string, string>,
  effects: {
    none: '無',
    rain: '雨',
    storm: '雷雨',
    snow: '雪',
    fog: '霧',
    petals: '花瓣',
    leaves: '落葉',
    sparkle: '星光閃爍',
    dust: '浮塵',
    vignette: '暗角',
    alert: '警報',
    glitch: '故障雜訊',
    scanlines: '掃描線',
    sepia: '懷舊褐色',
  } as Record<string, string>,
  icons: {
    none: '無',
    sunrise: '日出',
    sun: '太陽',
    sunset: '夕陽',
    moon: '月亮',
    star: '星星',
    cloud: '雲',
    rain: '雨',
    snow: '雪',
    fog: '霧',
    bolt: '閃電',
    flower: '花',
    leaf: '葉',
    heart: '愛心',
    search: '放大鏡',
    swords: '劍',
    alert: '警告',
    eye: '眼睛',
    skull: '骷髏',
    clock: '時鐘',
    book: '書',
    custom: '自訂圖片',
  } as Record<string, string>,
  label: {
    section: '差分標籤',
    style: '標籤樣式',
    styles: {
      badge: '徽章',
      tabs: '並排',
      dial: '軌道',
      label: '純文字款',
      none: '不顯示',
    } as Record<string, string>,
    styleHint: {
      badge: '膠囊底加圖示、名稱與英文標示。',
      tabs: '所有要匯出的差分排成一條，目前的反白。',
      dial: '差分排在半圓軌道上，適合時間帶。',
      label: '名稱兩側加裝飾線。',
      none: '',
    } as Record<string, string>,
    pos: '標籤位置',
    positions: {
      tl: '左上',
      tc: '上',
      tr: '右上',
      bl: '左下',
      bc: '下',
      br: '右下',
    } as Record<string, string>,
    free: '目前是拖曳後的自由位置；按任一按鈕回到固定位置。',
    dragHint: '也可以在預覽上直接拖曳標籤。',
    scale: '標籤大小',
    bgAlpha: '背景濃度',
    showSub: '顯示英文標示',
    font: '標籤字型',
  },

  /* ---------- 專案 ---------- */
  project: {
    fontsSection: '上傳的字型',
    fontsHint:
      'TTF、OTF、WOFF、WOFF2，可以多選或拖進頁面。字型存在這個瀏覽器的共用字型庫，所有字型選單都可以選。',
    addFont: '上傳字型',
    fontsEmpty: '還沒有上傳字型。',
    removeFont: (name: string) => `移除字型「${name}」`,
    bgSection: '預覽背景圖片',
    bgHint: '放上打算當房間背景的圖，比較好確認效果。背景圖只出現在預覽，不會畫進輸出的 PNG。',
    bgPick: '選擇圖片',
    bgRemove: '移除',
    bgNone: '沒有背景圖。',
    bgHas: '已設定背景圖。',
    resetLabel: '全部重來…',
    resetTitle: '全部重來？',
    resetDescription:
      '設定、圖層、差分、圖片與預覽背景都會回到剛開啟時的狀態，也會清空復原紀錄。上傳的字型存在共用字型庫，不會被刪除。',
    resetConfirm: '全部重來',
    invalid: '這不是前景框產生器的專案檔。',
    newer: '這個專案檔是用較新的版本存的，請更新頁面後再開啟。',
    unreadable: '無法讀取這個檔案。',
  },

  /* ---------- 字型 ---------- */
  fonts: {
    presets: {
      'Yu Gothic UI': {
        label: '黑體類',
        note: 'Yu Gothic UI、Yu Gothic、Hiragino Kaku Gothic ProN、Meiryo',
      },
      'Yu Mincho': {
        label: '明體類',
        note: 'Yu Mincho、Hiragino Mincho ProN、BIZ UDPMincho、MS PMincho',
      },
      'UD Digi Kyokasho NK-R': {
        label: '教科書體',
        note: 'UD Digi Kyokasho NK-R（沒有時用 Yu Mincho）',
      },
      Georgia: { label: '西文襯線', note: 'Georgia、Times New Roman' },
      'Segoe UI': { label: '西文無襯線', note: 'Segoe UI、Helvetica Neue、Arial' },
      'Microsoft JhengHei': { label: '繁中黑體', note: '微軟正黑體、PingFang TC、Heiti TC' },
      PMingLiU: { label: '繁中明體', note: '新細明體、Songti TC' },
      'DFKai-SB': { label: '繁中楷書', note: '標楷體、BiauKai、Kaiti TC' },
    } as Record<string, { label: string; note: string }>,
    localNote:
      '電腦上沒有這套字型時改用黑體類。電腦字型不會從網路下載，在別台電腦上看到的可能不同。',
    previewText: '霧中的燈塔 Chapter 1',
  },

  /* ---------- 預覽 ---------- */
  preview: {
    aria: '預覽（可以拖曳圖層與差分標籤）',
    bg: '預覽背景',
    bgs: {
      scenery: '範例風景',
      checker: '棋盤格',
      dark: '深色',
      light: '白色',
      image: '圖片',
    } as Record<string, string>,
    grid: '格線',
    undo: '復原',
    redo: '重做',
  },

  /* ---------- 匯出 ---------- */
  export: {
    fileName: '檔名',
    defaultBase: '前景框',
    png: '匯出 PNG',
    pngVariant: '只匯出目前差分（PNG）',
    zip: '所有差分匯出成 ZIP',
  },

  /* ---------- 狀態列 ---------- */
  status: {
    ready: '準備完成。先在「框」分頁挑範本或調整窗的形狀。',
    restored: '已還原上次的編輯內容。',
    noAutosave: '這個瀏覽器無法自動存檔，請用頁首的「專案」選單存成專案檔保留內容。',
    designApplied: (name: string) => `已套用範本「${name}」。`,
    added: (name: string) => `已新增「${name}」。`,
    removed: (name: string) => `已刪除「${name}」（可以復原）。`,
    layerRemoved: '已刪除圖層（可以復原）。',
    imagesAdded: (n: number) => `已新增 ${n} 張圖片。`,
    imageFailed: (name: string) => `無法讀取「${name}」（例如沒有寫寬高的 SVG），已略過。`,
    imageNotSaved: '瀏覽器無法儲存圖片，重新整理後圖片會消失；請用專案檔儲存。',
    projectImagesNotSaved: '專案檔裡的圖片存不進這個瀏覽器，重新整理後會消失（要再開一次專案檔）。',
    fontsLoaded: (n: number) => `已載入 ${n} 個字型，所有字型選單都可以選。`,
    fontFailed: (name: string) => `「${name}」不是可用的字型檔。`,
    fontRemoved: (name: string) => `已移除字型「${name}」。`,
    variantAdded: '已依目前的差分新增一個差分。',
    needOneExported: '至少要有一個要匯出的差分。',
    needOneVariant: '至少要留一個差分；不需要差分時請關閉「製作差分」。',
    kindChanged: (name: string) => `已把差分種類換成「${name}」。`,
    colorsCopied: (name: string) => `已把「${name}」的顏色套用到所有差分。`,
    exporting: '匯出中…',
    saved: (name: string, bytes: number) => `已儲存 ${name}（${kb(bytes)}）。`,
    savedZip: (n: number, name: string, bytes: number) =>
      `已把 ${n} 張打包成 ${name}（${kb(bytes)}）。`,
    exportFailed: (msg: string) => `匯出失敗：${msg}`,
    projectSaved: (name: string) => `已儲存專案檔 ${name}。`,
    projectOpened: (name: string) => `已開啟「${name}」。`,
    reset: '已回到剛開啟時的狀態。',
    bgImageSet: '已設定預覽背景圖片。',
    bgImageRemoved: '已移除預覽背景圖片。',
  },
  bytes: kb,
};
