/**
 * 介面文字（台灣繁體中文，用詞照 DESIGN.md 第 5 節）。畫面上的示範文字在 model.ts（DEFAULT_TEXT）、
 * 科技風左上角的字樣在 render.ts（HUD_LABEL）。
 */
import type {
  BackgroundId,
  DecoId,
  FontId,
  LayoutId,
  LyricPosition,
  MoodId,
  RangeMode,
  VizId,
} from './model';

export const S = {
  usage: [
    '在「曲目」放進封面圖片與音樂（也可以直接把檔案拖到畫面上）；沒有封面時用示範封面。',
    '填好標題與歌手，在「設計」「動態」挑版面、背景、字型、邊框與視覺化。',
    '要顯示歌詞時到「歌詞」打開，貼上 LRC／SRT／VTT，或放音樂邊聽邊按「打點」記下每一行的時間。',
    '預覽下方的「儲存 PNG」存成 1920 × 1080 的圖；「匯出」分頁把整首（或一段）存成影片。',
  ],
  about:
    '適合做跑團的 BGM、角色主題曲的「正在播放」畫面。檔案只在瀏覽器裡處理，不會上傳；設定、封面與音樂會自動儲存在這個瀏覽器。',
  tabsAria: '設定分類',
  tabs: { track: '曲目', design: '設計', motion: '動態', lyrics: '歌詞', export: '匯出' },

  undo: '復原',
  redo: '重做',

  files: {
    section: '封面與音樂',
    cover: '封面',
    coverDrop: '把封面圖片拖到這裡',
    coverHint: '建議正方形；不是正方形時取中央',
    coverPick: '選擇圖片',
    coverReplace: '換一張',
    coverRemove: '移除封面',
    demoName: '示範封面（星空下的二十面骰）',
    coverMissing: '找不到上次的封面，請重新選擇。',
    coverLoading: '讀取中…',
    audio: '音樂（可以不放）',
    audioDrop: '把音樂檔拖到這裡',
    audioHint: 'MP3、WAV、M4A、OGG、FLAC 等瀏覽器能播放的格式',
    audioPick: '選擇音樂',
    audioRemove: '移除音樂',
    audioNone: '沒有音樂：畫面用下面「動態」分頁的曲長與進度，影片是一段循環',
    audioLoading: '讀取音樂中…',
    audioMissing: '找不到上次的音樂，請重新選擇。',
    audioInfo: (name: string, duration: string) => `${name}・${duration}`,
    privacy: '檔案只在瀏覽器裡處理，不會上傳到任何伺服器。',
  },

  info: {
    section: '曲目資訊',
    title: '標題',
    artist: '歌手',
    subtitle: '副標',
    subtitleHint: '一句曲目說明或喜歡的歌詞；空白時不顯示。',
    subtitlePlaceholder: '可以不填',
    artistPlaceholder: '歌手或作曲者',
  },

  design: {
    layoutSection: '版面',
    layout: '版面',
    layouts: { split: '左右', center: '中央', vinyl: '黑膠' } satisfies Record<LayoutId, string>,
    background: '背景',
    backgrounds: { blur: '封面模糊', gradient: '漸層', solid: '單色' } satisfies Record<
      BackgroundId,
      string
    >,
    mood: '明暗',
    moods: { auto: '自動', dark: '深色', light: '淺色' } satisfies Record<MoodId, string>,
    moodHint: '自動：依封面的亮度決定。',
    font: '字型',
    fontAria: '字型',
    fonts: {
      sans: { label: '黑體', description: '思源黑體' },
      serif: { label: '明體', description: '思源宋體' },
      latin: { label: '英文無襯線', description: 'Inter＋思源黑體' },
      pixel: { label: '像素體', description: 'DotGothic16' },
      hand: { label: '手寫體', description: '芫荽' },
      mono: { label: '等寬', description: 'Roboto Mono' },
    } satisfies Record<FontId, { label: string; description: string }>,
    fontSample: '永夜 Aa 12',
    fontFailed: '字型載入失敗（離線或被擋），暫時用電腦內建的字型顯示；連上網路後會自動換回來。',
    fontHint: '英文、像素、手寫、等寬字型沒有的中文字用思源黑體顯示。',
    radius: '封面圓角',
    accentSection: '重點色',
    accentAuto: '從封面自動抽色',
    accent: '重點色',
    accentAutoHint: '目前抽出來的顏色；關掉自動後可以自己改。',
    decoSection: '邊框裝飾',
    deco: '邊框',
    decos: { none: '無', line: '線條', cyber: '科技風' } satisfies Record<DecoId, string>,
    hud: '角落文字',
    hudText: '左下角文字',
    hudTextHint: '預設跟著影片的 FPS；改了之後就不再跟著。',
    scanlines: '掃描線',
  },

  motion: {
    vizSection: '視覺化',
    viz: '聲音視覺化',
    vizs: { bars: '長條', wave: '波形', peaks: '整首波形', none: '關閉' } satisfies Record<
      VizId,
      string
    >,
    vizHint: '沒有音樂時是示意的動畫；整首波形會依進度上色。',
    progress: '進度條與時間',
    effectsSection: '動態效果',
    float: '封面漂浮',
    floatHint: '封面上下漂、背景緩緩移動、黑膠轉動、科技風的掃描光。',
    react: '隨節拍的封面動態',
    reactHint: '播放與匯出時，封面跟著低音微微放大。',
    reactNoAudio: '放進音樂後才有作用。',
    grain: '底片顆粒',
    fakeSection: '沒有音樂時',
    fakeDuration: '曲長',
    fakeDurationHint: '分:秒，例如 4:05。',
    fakePosition: '進度位置',
    fakeAudioLoaded: '已經放了音樂：曲長與進度依音樂。',
  },

  lyrics: {
    section: '歌詞',
    enabled: '隨時間顯示歌詞',
    file: '歌詞檔',
    fileDrop: '把歌詞檔拖到這裡',
    fileHint: '.lrc、.srt、.vtt、.txt',
    filePick: '選擇歌詞檔',
    text: '歌詞',
    textPlaceholder:
      '[00:12.50] 第一句歌詞\n[00:12.50] [-] 翻譯寫在原文下一行，前面加 [-]\n[00:18.20] 第二句\n\n也可以只貼歌詞，放音樂後邊聽邊按「打點」。',
    textHint: '［分:秒.百分秒］後面寫歌詞，到了那個時間就出現。',
    stats: (lines: number, translated: number, untimed: number) =>
      `讀到 ${lines} 句歌詞${translated ? `・翻譯 ${translated} 句` : ''}${untimed ? `・沒有時間的 ${untimed} 行不會顯示` : ''}。`,
    noTimed: '還沒有寫上時間的行。放了音樂的話，可以邊播放邊按「打點」。',
    empty: '還沒有歌詞。',
    stamp: '打點',
    stampHint: '播放中在游標所在的行（或下一個還沒有時間的行）記下現在的時間，游標移到下一行。',
    stampNeedsAudio: '放進音樂後才能打點。',
    stampEmpty: '請先貼上歌詞，一行一句。',
    stampDone: '每一行都有時間了。要重新打點，先點要改的那一行再按。',
    position: '位置',
    positions: { bottom: '畫面下方', stack: '曲目資訊下方' } satisfies Record<
      LyricPosition,
      string
    >,
    positionCenter: '中央版面固定在曲目資訊下方。',
    size: '大小',
    showNext: '預告下一句',
    offset: '時間偏移',
    offsetHint: '正值＝晚一點出現，負值＝早一點出現。',
    loaded: (name: string) => `已讀入歌詞檔：${name}`,
    loadedNoTime: (name: string) => `已讀入 ${name}，但沒有找到寫上時間的行。`,
    loadFailed: '這個歌詞檔無法讀取，請改用 .lrc、.srt、.vtt 或 .txt。',
    big5: '以 Big5 編碼讀取。',
  },

  preview: {
    aria: '播放畫面預覽（1920 × 1080）',
    png: '儲存 PNG',
    pngHint: '存成 1920 × 1080 的圖（目前這一格）。',
    dropHint: '也可以把封面、音樂、歌詞檔直接拖到這個頁面上。',
    dropLabel: '放開即可加入',
    dropDetail: '圖片→封面、音樂→音樂、.lrc／.srt／.vtt→歌詞',
    removeAudio: '移除音樂',
    loopNote: (sec: number) => `沒有音樂：預覽 ${sec} 秒的循環（與匯出的影片相同）。`,
  },

  exp: {
    title: '影片',
    lead: '把播放畫面存成 1920 × 1080 的影片。',
    loopLength: '循環長度',
    loopHint: '沒有音樂時的影片長度；結尾會接回開頭。',
    range: '範圍',
    ranges: { all: '整首', part: '指定區間' } satisfies Record<RangeMode, string>,
    start: '開始',
    end: '結束',
    clockHint: '分:秒',
    rangeTooShort: '區間太短：結束要比開始晚 1 秒以上。',
    fps: 'FPS',
    mute: '錄影時喇叭靜音',
    muteHint: '只在即時錄影時有作用（錄影時音樂會實際播放）。',
    formatLabel: {
      mp4Aac: 'MP4',
      movPcm: 'MOV',
      mp4Vp9: 'MP4',
      realtimeMp4: 'MP4（即時錄影）',
      realtimeWebm: 'WebM（即時錄影）',
      none: '影片',
    },
    formatNote: {
      mp4Aac: '逐格編碼的 MP4（H.264＋AAC），每一格都會進檔案，比實際播放快。',
      mp4H264: '逐格編碼的 MP4（H.264），每一格都會進檔案。',
      movPcm:
        '逐格編碼的 MOV（H.264＋不壓縮的 PCM 聲音）：這個瀏覽器沒有 AAC 編碼器，聲音改存成無損的 PCM，檔案較大。',
      mp4Vp9:
        '逐格編碼的 MP4（VP9＋Opus）：這個瀏覽器沒有 H.264 編碼器。Chrome、Edge、Firefox、VLC 播放得了；QuickTime 等舊的播放器可能不支援。',
      realtime:
        '這個瀏覽器不能逐格編碼，改用即時錄影：音樂會實際播放，花的時間和影片一樣長；錄影時請不要切換分頁或縮小視窗。錄出來的檔案可能沒有寫上總長。',
      unsupported: '這個瀏覽器不支援匯出影片，請改用最新版的 Chrome、Edge 或 Firefox。',
    },
    checking: '檢查瀏覽器能用的影片格式中…',
    phaseAudio: '處理聲音中',
    phaseFrames: (done: number, total: number) => `畫面 ${done}／${total} 格`,
    recording: (sec: number, total: number) => `錄影中 ${sec.toFixed(1)}／${total.toFixed(1)} 秒`,
    details: {
      length: '長度',
      fps: 'FPS',
      codec: '編碼',
    },
    failed: '影片產生失敗：',
    tooLarge: '影片超過 1 GB，請縮短區間或改用 30 FPS。',
    encoderFailed: '影片編碼失敗，請改用 30 FPS 再試一次。',
    recordFailed: '無法開始錄影，請改用 30 FPS 再試一次。',
    hiddenWarning: '切換分頁或縮小視窗可能讓錄影中斷，請保持畫面開著。',
  },

  toast: {
    coverLoaded: '已換上封面，配色依封面重新設定。',
    coverRemoved: '已換回示範封面。',
    notImage: (name: string) => `「${name}」無法當成封面，請改用 JPG、PNG、WebP 圖片。`,
    audioLoaded: '已放進音樂，可以按播放試聽。',
    audioRemoved: '已移除音樂。',
    audioFailed: (name: string) => `「${name}」無法播放，請改用 MP3、WAV、M4A 等音訊檔。`,
    notSupported: (name: string) => `「${name}」不是圖片、音樂或歌詞檔。`,
    notPersisted: '瀏覽器空間不足，這個檔案無法自動儲存（重新整理後要再放一次）。',
    png: (name: string) => `已儲存 ${name}`,
    pngFailed: 'PNG 產生失敗，請再試一次。',
    exported: (name: string) => `影片已完成：${name}`,
    cancelled: '已取消匯出。',
    busy: '匯出中，請等匯出完成或取消後再操作。',
  },

  project: {
    resetTitle: '全部重來？',
    resetText: '設定、封面、音樂與歌詞都會清掉，回到示範內容。可以按復原救回設定。',
    invalid: '這不是播放畫面產生器的專案檔。',
    newer: '這個專案檔來自比較新的版本，請重新整理頁面後再開。',
    missing: (n: number) => `專案檔裡少了 ${n} 個檔案（封面或音樂），已略過。`,
  },

  keys: {
    group: '播放畫面',
    play: '播放／暫停',
    playAnywhere: '播放／暫停（輸入框裡也可用）',
    stamp: '打點（歌詞欄裡也可用）',
    undo: '復原',
    redo: '重做',
  },
};
