/**
 * 介面文字（原作未授權：全部自己寫）。
 */
import type { RenderText } from './render';

export const S = {
  usage: [
    '在「角色」分頁放進角色圖片（可以一次選很多張），或先用內建角色試試看。',
    '在「畫面樣式」調整版面、背景、標題與選取前後的效果；也可以開「大主格」放大顯示選到的角色。',
    '在「選擇演出」設定幾位玩家、各自要選誰；直接在預覽上點一個角色，就會指定成目前那位玩家的目標。',
    '在「匯出」存成 APNG、WebP、GIF、MP4、AVI，或做成可以自己選的互動 HTML。',
  ],
  about:
    '所有圖片與設定都只在這個瀏覽器裡處理，不會上傳。設定與角色會自動保存；要搬到別台電腦請存成專案檔。',

  tabsAria: '編輯步驟',
  tabs: {
    characters: { n: '01', label: '角色', sub: '新增與替換圖片' },
    appearance: { n: '02', label: '畫面樣式', sub: '背景・排列・樣式' },
    motion: { n: '03', label: '選擇演出', sub: '玩家・移動路徑' },
    export: { n: '04', label: '匯出', sub: '動態圖片・HTML' },
  },
  next: (label: string) => `下一步：${label}`,

  /* ---------- 專案 ---------- */
  project: {
    legacy: '匯入舊版的專案檔（.json）…',
    legacyOk: '已匯入舊版的專案檔',
    legacyBad: '這不是舊版選角畫面產生器的專案檔。',
    opened: '已開啟專案檔',
    newer: '這個專案檔是較新版本做的，請更新頁面後再開啟。',
    invalid: '專案檔的內容不正確。',
    missing: (n: number) => `有 ${n} 張圖片在專案檔裡找不到，已略過那些角色。`,
    resetTitle: '全部重設？',
    resetText: '所有設定回到預設值，角色換回內建角色。上傳的圖片會從清單移除。',
    notPersisted: '瀏覽器空間不足或無法保存，圖片在重新整理後會不見；請記得存成專案檔。',
  },
  undo: '復原',
  redo: '重做',

  /* ---------- 角色 ---------- */
  chars: {
    heading: '角色圖片',
    lead: '先用內建角色試試看，也可以放進自己的圖片。清單的順序就是畫面上的順序。',
    count: (n: number) => `${n} 人`,
    dropLabel: '新增角色圖片',
    dropButton: '選擇圖片',
    dropHint: 'PNG、JPG、WebP、GIF、SVG、AVIF；可以一次選很多張，也可以拖放或貼上',
    listAria: '角色清單',
    empty: '還沒有任何角色。從上面新增圖片，或還原成內建角色。',
    position: (i: number, demo: boolean) =>
      `${String(i + 1).padStart(2, '0')}・${demo ? '內建角色' : '自己的圖片'}`,
    nameAria: (i: number) => `第 ${i + 1} 個角色的名稱`,
    defaultName: (n: number) => `角色 ${n}`,
    copySuffix: ' 複本',
    replace: '替換圖片',
    replaceAria: (name: string) => `替換「${name}」的圖片`,
    up: '往前移',
    down: '往後移',
    duplicate: '複製角色',
    remove: '刪除角色',
    actionAria: (action: string, name: string) => `${action}：${name}`,
    tune: '位置與縮放',
    tuneHint: '只影響小清單的格子；大格用的是原圖（或下面設定的大格範圍）。',
    scale: '縮放',
    offsetX: '水平位置',
    offsetY: '垂直位置',
    rangeX: '水平移動範圍（±%）',
    rangeY: '垂直移動範圍（±%）',
    cropList: '設定小清單縮圖',
    cropListState: (custom: boolean) => (custom ? '清單用自訂的範圍' : '清單用整張原圖'),
    cropMain: '設定大格顯示範圍',
    cropMainState: (custom: boolean) => (custom ? '大格用自訂的範圍' : '大格用整張原圖'),
    assigned: '選它的玩家',
    manage: '還原內建角色・全部刪除',
    restore: '還原成內建角色',
    restoreTitle: '還原成內建角色？',
    restoreText: '角色清單換成 8 個內建角色，玩家的起始游標與路徑也會重設。',
    clear: '全部刪除',
    clearTitle: '刪除全部角色？',
    clearText: '玩家的目標與路徑也會一併重設。',
    missing: '找不到這張圖片（瀏覽器的資料可能被清除了），請替換圖片。',
  },
  toast: {
    added: (n: number) => `已新增 ${n} 張圖片`,
    noImage: '沒有可用的圖片',
    noImageHint: '請選擇 PNG、JPG、WebP、GIF、SVG 或 AVIF 圖片。',
    readFailed: (name: string) => `「${name}」讀不到，已略過`,
    replaced: (name: string) => `已替換「${name}」的圖片`,
    replacedHint: '縮放與位置回到預設值。',
    replaceFailed: '圖片載入失敗，維持原本的圖片',
    demo: '已換成內建角色',
    bg: '已套用背景圖片',
    bgFailed: '背景圖片載入失敗',
    crop: (label: string) => `已套用${label}的範圍`,
    cropAll: (label: string) => `已把同一塊範圍套用到所有角色的${label}`,
    route: (name: string) => `已把 ${name} 目前的自動路徑固定下來`,
    needCharacters: '請先新增角色圖片',
    exported: (label: string) => `${label} 已完成，可以下載了`,
    cancelled: '已取消匯出',
    png: '已儲存目前畫面的 PNG',
    htmlCopied: '已複製 HTML 程式碼',
    popup: '彈出視窗被擋掉了',
    popupHint: '請在瀏覽器允許這個網站開啟彈出視窗。',
  },

  /* ---------- 畫面構成 ---------- */
  comp: {
    title: '畫面構成',
    badgeGrid: '格狀',
    badgeMain: '主格＋清單',
    mode: '選角框形式',
    modeGrid: '角色格狀排列',
    modeMain: '大主格＋小清單',
    presetsAria: '主格版型',
    portrait: '主格在上・清單在下',
    portraitSub: '直式 960 × 1280',
    landscape: '主格在左・清單在右',
    landscapeSub: '橫式 1280 × 720',
    fillOne: '確定選擇後大格就填上那個角色，下一位確定時換成新的角色。',
    fillMany: (n: number) =>
      `由左到右、由上到下依序填滿 ${n} 個大格，超過格數就從第一格重新填；用不到的格子留白。`,
    slots: '大格的數量與排列',
    slotsAria: '大格快速排列',
    slotPresets: { one: '1 格', row2: '橫向 2 格', col2: '直向 2 格', grid4: '2 × 2' },
    count: '大格數量',
    columns: '欄',
    rows: '列（自動）',
    slotsHint: '最多 12 格；指定欄數後列數自動算出來。',
    slotGap: '大格之間的間距',
    position: '大格區域的位置',
    positions: { top: '清單上方', left: '清單左邊', right: '清單右邊' },
    reveal: '顯示時機',
    reveals: { confirm: '確定選擇的當下', hover: '游標移過去就先顯示' },
    tune: '大小・圖片・名稱',
    size: '大格所佔比重',
    gap: '主格與清單的間距',
    fit: '大格的圖片縮放',
    fits: { contain: '完整顯示', cover: '填滿格子' },
    fitHint: '大格用原圖（或角色的大格範圍），不套用小清單的縮放與位置。',
    showName: '在大格顯示玩家與角色名稱',
    effects: '大格也套用選取效果',
    effectsHint: '一起套用色調、放大、光暈、外框與確定時的閃光。',
    placeholder: '還沒選擇時的提示文字',
    placeholderHint: '留空就不顯示文字。',
  },

  /* ---------- 尺寸與排列 ---------- */
  layout: {
    title: '畫面尺寸與角色排列',
    width: '寬',
    height: '高',
    presetsAria: '畫布版型',
    presets: {
      '16:9': '16:9',
      '1:1': '1:1',
      blog: '部落格',
      hd: 'HD',
      p8: '直式・2 欄 4 列',
      p5: '直式・1 欄 5 列',
    } as Record<string, string>,
    presetTitle: (w: number, h: number, grid?: readonly [number, number]) =>
      grid ? `${w} × ${h}・${grid[0] * grid[1]} 格` : `${w} × ${h}`,
    area: '角色擺放的區域（px）',
    areaMain: '主格與清單的整體區域（px）',
    columns: '欄',
    rowsMin: '最少列數',
    rows: '列數',
    gap: '間距',
    autoGap: '依畫面比例與格數自動調整間距',
    autoRows: '角色變多時自動加列',
    capacity: (c: number, r: number, k: number) =>
      `${c} 欄 ${r} 列只放得下清單前 ${k} 個角色；其他角色仍留在清單裡。想全部顯示請打開「自動加列」。`,
    radius: '方格圓角',
    fit: '圖片縮放',
    fits: { cover: '填滿', contain: '完整顯示' },
    border: '預設外框',
    guides: '顯示編輯用的參考線（不會匯出）',
  },

  /* ---------- 背景 ---------- */
  bg: {
    title: '背景',
    type: '背景方式',
    types: { gradient: '漸層', solid: '單色', image: '背景圖片', transparent: '透明' },
    colorA: '顏色 A',
    colorB: '顏色 B',
    color: '顏色',
    angle: '漸層角度',
    pick: '選擇背景圖片',
    replace: '更換背景圖片',
    clear: '移除背景圖片',
    dim: '背景圖片的暗度',
    vignette: '暗角',
    pattern: '遊戲畫面感的細紋',
    transparentHint: '透明背景存成 APNG、WebP、GIF 時保留透明；MP4、AVI 的透明處是黑色。',
  },

  /* ---------- 標題、名牌、字型 ---------- */
  text: {
    title: '標題與名牌',
    font: '畫面字型',
    fontHint: '畫面上所有文字都用這個字型；上傳的字型會一起存進專案檔與互動 HTML。',
    fontSample: '角色選擇 ABC 123',
    showTitle: '顯示上方標題',
    main: '主標題',
    sub: '副標題',
    size: '標題大小',
    align: '對齊',
    aligns: { left: '靠左', center: '置中', right: '靠右' },
    showLabels: '顯示角色名牌',
    labelHeight: '名牌高度',
    labelSize: '文字大小',
  },

  /* ---------- 選取效果 ---------- */
  fx: {
    title: '選取前後的效果',
    idle: '未選取',
    mode: '濾鏡',
    modes: { normal: '正常', grayscale: '黑白', sepia: '深褐' },
    amount: '濾鏡強度',
    brightness: '亮度',
    saturation: '彩度',
    overlay: '暗色遮罩',
    active: '選取時',
    tintMode: '色調方式',
    tintModes: { none: '只還原成原色', fixed: '固定色調', player: '玩家色調' },
    tint: '固定顏色',
    tintAlpha: '色調強度',
    scale: '放大',
    glow: '光暈',
    border: '選取外框',
    borderStyle: '外框樣式',
    borderStyles: { solid: '單線', corners: '四個角', dashed: '虛線', double: '雙線' },
    borderHint: '套用到小清單與已填入的大格；線的粗細與圓角沿用上面的設定。',
    presetsAria: '效果的預設組合',
    presets: { gray: '黑白→原色', sepia: '深褐→原色', playerTint: '黑白→玩家色' },
  },

  /* ---------- 玩家 ---------- */
  players: {
    title: '玩家設定',
    badgeSeq: (n: number) => `依序 ${n} 人`,
    badgeOne: (name: string) => `只有 ${name}`,
    mode: '選擇方式',
    modes: { sequence: '全部依序選擇', single: '只讓某一號選擇' },
    single: '要選擇的玩家編號',
    singleUnit: '號',
    quickAria: '玩家編號快速選擇',
    quickTitle: (n: number, name: string) => `${n} 號・${name}`,
    singleHint: '可以指定 1～99 號；那一號的顯示名稱在下面改。',
    count: '依序選擇的人數',
    countUnit: '人',
    rule: '選擇規則',
    rules: { unique: '不可重複', duplicate: '允許重複' },
    seqHelp: (first: string) =>
      `從 ${first} 開始依序選擇。挑好目標角色後，細部的移動可以在各玩家的「游標路徑」裡調整。`,
    oneHelp: (name: string) => `只播放 ${name} 的目標與路徑；其他玩家的設定會保留。`,
    gridNote: '欄、列與間距套用到小清單；大格的比重在「畫面構成」調整。',
    issue: (k: number, n: number) =>
      `畫面上只有 ${k} 個角色，選擇的人數卻是 ${n} 人。多顯示幾個角色，或改成允許重複，才能播放與匯出。`,
    allowDuplicate: '改成允許重複',
    nameHelp: '最多 99 人；顯示名稱最多 24 字，空白時顯示 1P、2P 這樣的編號。',
    listAria: '玩家',
    label: (n: number) => `${n} 號的顯示名稱`,
    labelPlaceholder: (n: number) => `${n}P（預設）`,
    pick: (name: string) => `指定 ${name} 的目標`,
    color: (name: string) => `${name} 的顏色`,
    target: '目標',
    targetAria: (name: string) => `${name} 的目標角色`,
    noCharacter: '沒有角色',
    route: '游標路徑',
    routeAuto: '自動',
    routeCustom: '自行指定',
    start: '起始游標',
    startAria: (name: string) => `${name} 的起始游標`,
    random: '隨機（自動）',
    pathMode: '路徑方式',
    pathModeAria: (name: string) => `${name} 的路徑方式`,
    pathModes: { random: '自動（預設）', custom: '自行指定' },
    summary: '播放路徑',
    addFirst: '請先新增角色。',
    capture: '固定目前的自動路徑',
    addWaypoint: '＋ 中繼點',
    waypoint: (n: number) => `中繼 ${n}`,
    waypointAria: (name: string, n: number) => `${name} 的中繼點 ${n}`,
    waypointUp: '中繼點往前',
    waypointDown: '中繼點往後',
    waypointRemove: '刪除中繼點',
    emptyCustom: '沒有中繼點：游標從起點直接移到目標。',
    emptyAuto:
      '依「自動經過的格數」產生路徑。按「固定目前的自動路徑」就會存成自己的路徑，可以再細調。',
  },

  /* ---------- 時間 ---------- */
  time: {
    title: '播放時間與速度',
    initialHold: '開場等待',
    search: '游標移動',
    confirm: '確定演出',
    endHold: '結尾停留',
    hops: '自動經過的格數',
    hopsUnit: '次',
    loop: '無限循環',
    loopHint: '預覽一直重播；動畫檔無限循環（關掉時只播一次）。',
  },

  /* ---------- 匯出 ---------- */
  exp: {
    title: '匯出動畫與影片',
    lead: '選好格式按匯出；完成後在下面的結果下載。',
    formats: {
      apng: { label: 'APNG', description: '全彩、半透明都保留，無損；CCFOLIA 可以直接用。' },
      webp: { label: 'WebP', description: '檔案小、畫質高；Safari 無法匯出。' },
      gif: {
        label: 'GIF',
        description: '相容性最好；最多 256 色、依場景配色並抖色，最多 50 FPS，半透明表現有限。',
      },
      mp4: { label: 'MP4', description: '影片（H.264）；透明的地方是黑色。' },
      avi: {
        label: 'AVI',
        description: '影片（MJPEG）；所有瀏覽器都能做，檔案較大；透明的地方是黑色。',
      },
    },
    mp4Unsupported: '這個瀏覽器不支援 MP4（H.264）編碼，請改用 Chrome、Edge，或改存成 AVI。',
    webpQuality: 'WebP 品質',
    webpQualityHint: '100 為無損。',
    counts: (image: number, video: number, fps: number) =>
      `圖片 ${image} 格／影片 ${video} 格（${fps} FPS）`,
    notes: ['MP4 與 AVI 依 FPS 逐格存下所有影格。', '想用原始解析度輸出，尺寸請選 100%。'],
    budget: '處理量太大（寬 × 高 × 影格數），請縮小尺寸、降低 FPS 或縮短時間。',
    bigTitle: '要處理的畫面很多',
    bigText: (mp: number) => `大約要處理 ${mp} 百萬像素，瀏覽器的記憶體用量可能很大。要繼續嗎？`,
    bigConfirm: '繼續匯出',
    progressFrames: (label: string, i: number, n: number) => `${label} 影格 ${i}／${n}`,
    details: { size: '畫布', time: '總長', frames: '影格' },
    resume: '想之後再繼續編輯，請在頁首的專案選單「存成專案檔」：圖片與設定會一起存下來。',
    htmlTitle: '可以自己選的互動 HTML',
    htmlLead: '做成一段可以用滑鼠、鍵盤、觸控選角色的 HTML，貼到部落格或網站上。',
    htmlButton: 'HTML 程式碼',
    htmlTry: '在新視窗試用',
  },

  /* ---------- 互動 HTML 對話框 ---------- */
  html: {
    title: '互動 HTML',
    lead: '圖片都以 data URL 內嵌，是一段獨立的程式碼。',
    note: '可以貼進部落格文章的 HTML 模式。如果部落格會把 <script> 拿掉，請把「獨立 HTML」放到自己的空間，再用 iframe 嵌入。',
    code: 'HTML 程式碼',
    copy: '複製程式碼',
    download: '儲存獨立 HTML',
    open: '開新視窗試用',
    size: (kb: string) => `約 ${kb}`,
    generating: '正在產生 HTML…',
  },
  widget: {
    aria: '角色選擇',
    help: '方向鍵移動・Enter 選擇・也可以用滑鼠或觸控',
    reset: '重來',
    selecting: (name: string) => `${name} 選擇中`,
    complete: '選擇完成',
    completeOne: (name: string) => `${name} 選擇完成`,
  },

  /* ---------- 預覽 ---------- */
  preview: {
    aria: '選角畫面預覽',
    targets: '指定目標',
    targetsAria: '要指定目標的玩家',
    hintPick: (name: string) => `點一下要當成 ${name} 目標的角色。`,
    hintMain: (name: string) => `點一下角色就指定成 ${name} 的目標，並直接在大格看到結果。`,
    hintEmpty: '請先在「角色」分頁新增圖片。',
    timeline: (mode: string) => `開始 → ${mode} → 完成`,
    modeSeq: '玩家依序選擇',
    modeOne: (name: string) => `只有 ${name} 選擇`,
    png: '儲存目前畫面為 PNG',
    tryIt: '自己試著選選看',
    live: '改過的設定會立刻反映在預覽上。',
    goExport: '匯出',
    segments: { hold: '開場', end: '結尾' },
  },
  guides: {
    characters: {
      title: '想換成自己的圖片？',
      text: '按角色清單裡的「替換圖片」就行了，名稱與玩家的設定都會留著。',
    },
    appearance: {
      title: '調成喜歡的氣氛',
      text: '試試不同的背景與排列，比較選取前後的效果。參考線不會出現在匯出的檔案裡。',
    },
    motion: {
      title: '也可以直接點預覽',
      text: '在預覽上點一個角色，就會指定成目前那位玩家的目標；打開「游標路徑」還能改移動的順序。',
    },
    export: {
      title: '依用途選格式',
      text: '影片用 MP4 或 AVI，動態圖片用 APNG、WebP 或 GIF；HTML 會做出可以自己選的畫面。',
    },
  },

  keys: {
    group: '選角畫面',
    play: '播放／暫停',
    undo: '復原',
    redo: '重做',
  },

  crop: {
    titleMain: (name: string) => `大格的顯示範圍：${name}`,
    titleList: (name: string) => `小清單縮圖的範圍：${name}`,
    free: '自由',
    fitMain: '配合大格的比例',
    fitList: '配合格子的比例',
    applyOne: '套用到這個角色',
    applyAll: '套用到所有角色',
    preview: '預覽',
    previewHint: (target: string) => `依目前${target}的比例與縮放方式顯示。`,
    listNote: '套用到清單後，縮放與位置會回到 1 倍與置中。',
    labelMain: '大格',
    labelList: '清單縮圖',
  },
} as const;

/** 畫面上的固定字樣（規格 5. D4） */
export const RENDER_TEXT: RenderText = {
  complete: '選擇完成',
  locking: '確定中…',
  ready: '準備',
  selecting: '選擇中…',
  guide: '格子區域（不會匯出）',
};
