/** 讀取動畫產生器的介面文字（台灣繁體中文；用詞照 DESIGN.md 第 5 節） */
import type {
  BarStyle,
  BuiltinCharacter,
  FollowPlacement,
  ImageOrder,
  LoaderType,
  LoopStyle,
  MotionKind,
  ProgressMode,
  RowPattern,
  RowShape,
  VanishMode,
} from './settings';

const n2 = (v: number) => v.toFixed(2);

export const S = {
  usage: [
    '先選一個內建角色，或把角色的動畫檔（APNG、GIF、動態 WebP）或一組連續圖拖進「角色」分頁。',
    '在「讀取動畫」分頁選進度條、循環動畫或換圖列，調整樣式、顏色與時間；進度條還有開場淡入與結尾消失演出。',
    '在預覽上直接拖曳角色、讀取動畫、進度數字與文字，靠近畫布中線或其他元素時會自動對齊；選取後也能用方向鍵微調。',
    '在右側（手機在下方）的匯出區選 APNG、WebP 或 GIF 匯出，放進 CCFOLIA 等線上跑團平台當讀取畫面。',
    '設定會自動儲存；上傳的圖片與字型存在這個瀏覽器裡，所有處理都在本機完成，不會上傳。',
  ],
  tabs: { character: '角色', loader: '讀取動畫', text: '文字', canvas: '畫布' },
  tabsAria: '設定分類',

  status: {
    start: '選一個內建角色，或上傳角色圖片開始製作。',
    idle: '所有處理都在你的瀏覽器裡完成，圖片與字型不會上傳。',
    characterLoaded: (n: number) => `已載入角色（${n} 格）。`,
    characterCleared: '已改回內建角色。',
    rowLoaded: (which: string, n: number) => `已載入${which} ${n} 張。`,
    rowCleared: (which: string) => `已移除全部${which}。`,
    fontApplied: (name: string) => `上下兩段文字都已改用字型「${name}」。`,
    projectSaved: (assets: boolean, name: string) =>
      `已存成專案檔（${assets ? '含素材' : '只含設定'}）：${name}`,
    projectLoaded: (name: string) => `已開啟專案檔：${name}`,
    projectReset: '已重設成預設值。',
    exported: (format: string, size: string) => `已存成 ${format}（${size}）。`,
    exportCancelled: '已取消匯出。',
    keysReset: '已恢復預設的 4 個節點。',
    percentReset: '已把進度數字的位置歸零。',
    shapesAll: (shape: string) => `已把所有位置的底形改成「${shape}」。`,
    seamless: (cycles: number, seconds: string, extended: boolean) =>
      `已對齊為 ${cycles} 圈、${seconds} 秒${extended ? '（不足一圈，已延長）' : ''}，預覽從頭播放。`,
    loadWhileExporting: '匯出中無法開啟專案檔，請等匯出結束。',
    staleLoad: '載入途中有其他編輯，這次載入已取消。',
    notPersisted: '瀏覽器空間不足，這次上傳的圖片只在目前開著的頁面有效，重新整理後會消失。',
    skipped: (n: number) => `（略過 ${n} 個不是圖片的檔案）`,
    decodeFailed: (msg: string) => `${msg} 已改回內建角色。`,
    restoreFailed: '找不到之前上傳的圖片（瀏覽器的資料可能已被清除），已改用內建角色與底形。',
    tooHeavy: '處理量超過上限（寬 × 高 × 影格數 > 2 億 2 千萬），請縮小畫布、降低 FPS 或縮短長度。',
  },
  busy: {
    image: '載入圖片中…',
    font: '載入字型中…',
    project: '開啟專案檔中…',
  },
  capabilities: {
    aria: '這個瀏覽器的支援度',
    input: '動畫輸入',
    apng: 'APNG 匯出',
    webp: 'WebP 匯出',
    gif: 'GIF 匯出',
    ok: '支援',
    limited: '不支援',
  },

  character: {
    sectionImage: '角色圖片',
    dropLabel: '把動畫檔或多張圖片拖到這裡',
    dropButton: '選擇圖片',
    dropHint: 'APNG、GIF、動態 WebP 會拆成影格；一次選多張當成連續圖（依檔名排序）。',
    builtinInfo: (name: string) => `目前是內建角色「${name}」`,
    builtinHint: '上傳圖片後會換成你的角色。',
    uploadInfo: (n: number, w: number, h: number) => `${n} 格 · ${w}×${h}`,
    builtin: '內建角色',
    clear: '改回內建角色',
    builtins: {
      cat: '貓咪',
      dice: '骰子寶寶',
      mushroom: '蘑菇',
      penguin: '企鵝',
      cocoa: '熱可可',
    } satisfies Record<BuiltinCharacter, string>,
    sectionLook: '位置與外觀',
    x: '位置 X',
    y: '位置 Y',
    size: '大小',
    sizeHint: '角色的高度＝畫布高的百分比，寬度依圖的比例。',
    rotation: '旋轉',
    opacity: '不透明度',
    dragHint: '也可以在預覽上直接拖曳角色。',
    sectionMotion: '附加動作',
    motion: '動作',
    motions: {
      none: '無',
      float: '漂浮',
      bounce: '彈跳',
      sway: '左右擺',
      squish: '軟壓',
      step: '踏步',
      wiggle: '擺頭',
    } satisfies Record<MotionKind, string>,
    motionAmount: '動作幅度',
    motionSpeed: '動作速度',
    motionSpeedHint: '一個週期＝1 ÷ 速度 秒；0 時不動。',
    sectionFrames: '影格播放',
    fileTiming: '照檔案的影格時間',
    fileTimingHint: '動畫檔依檔案裡每格的時間播放；關掉時改用下面的 FPS。',
    speed: '播放速度',
    fps: '連續圖 FPS',
    fpsHint: '連續圖（或不照檔案時間時）每秒播幾格。',
    sectionShadow: '陰影',
    shadow: '角色陰影',
    shadowColor: '陰影顏色',
    shadowBlur: '暈染',
    shadowY: 'Y 偏移',
    sectionFollow: '跟著進度條',
    follow: '跟著進度條移動',
    followHint: '角色的水平中心跟著填滿的前緣走，並畫在進度條上面。',
    placement: '跟隨的位置',
    placements: {
      above: '條上方',
      center: '條中線',
      below: '條下方',
    } satisfies Record<FollowPlacement, string>,
    gap: '間距',
    gapHint: '在條中線時無效。',
    followX: '前後微調',
    followY: '上下微調',
    followOffsetHint: '跟隨時在預覽上拖曳角色，改的是這兩個值。',
    followSnap: '逐格跟隨',
    followSnapHint: '分段類的樣式時，角色只停在已填滿的格的右端，一格一格跳。',
    followInside: '限制在畫布內',
    followFlip: '鏡像',
  },

  loader: {
    sectionType: '讀取動畫',
    type: '種類',
    types: {
      bar: '進度條',
      loop: '循環動畫',
      row: '換圖列',
      none: '隱藏',
    } satisfies Record<LoaderType, string>,
    x: '位置 X',
    y: '位置 Y',
    glow: '光暈',
    glowColor: '光暈顏色',
    glowBlur: '光暈暈染',
    seed: '亂數種子',
    reseed: '換一組',
    seedHint: '影響不規則進度、隨機順序與結尾動作的粒子。同一個種子每次結果相同。',
  },

  bar: {
    sectionStyle: '條的樣式',
    style: '樣式',
    styles: {
      rounded: '圓角長條',
      segmented: '分段膠囊',
      pixel: '像素格',
      hearts: '愛心列',
      bubbles: '泡泡列',
    } satisfies Record<BarStyle, string>,
    styleDescriptions: {
      rounded: '兩端全圓，平順填滿',
      segmented: '一段一段的圓角膠囊',
      pixel: '直角的像素方格',
      hearts: '愛心一顆顆長出來',
      bubbles: '泡泡一顆顆長出來',
    } satisfies Record<BarStyle, string>,
    width: '寬度',
    height: '高度',
    segments: '格數',
    segmentsHint: '分段類的四種樣式用；也用在逐格跟隨。',
    sectionProgress: '進度方式',
    mode: '進度方式',
    modes: {
      linear: '等速',
      smoothstep: '平滑',
      cubicIn: '漸快',
      cubicOut: '漸慢',
      cubicInOut: '慢快慢',
      steps10: '階梯',
      bounceOut: '彈跳',
      irregular: '不規則',
      keyframes: '自訂時間表',
    } satisfies Record<ProgressMode, string>,
    modeDescriptions: {
      linear: '同樣的速度跑完',
      smoothstep: '兩端慢、中間快',
      cubicIn: '越來越快',
      cubicOut: '越來越慢',
      cubicInOut: '更明顯的慢快慢',
      steps10: '每 10% 跳一階',
      bounceOut: '衝到底後回彈',
      irregular: '忽快忽慢、不倒退',
      keyframes: '自己排第幾秒到幾 %',
    } satisfies Record<ProgressMode, string>,
    start: '起點',
    end: '終點',
    rangeHint: '終點比起點小時會自動對調。',
    keys: '節點表',
    keysAria: '自訂時間表',
    keysLabels: { time: '秒數', value: '進度', curve: '進入此節點的曲線' },
    sectionFill: '顏色',
    fill: '填滿方式',
    fills: { solid: '單色', gradient: '漸層' },
    fillColor: '填滿色',
    stops: '漸層色標',
    stopsCount: (n: number, max: number) => `顏色 ${n}／${max}`,
    stopColor: (i: number) => `第 ${i} 個色標的顏色`,
    stopPos: (i: number) => `第 ${i} 個色標的位置`,
    stopRemove: (i: number) => `刪除第 ${i} 個色標`,
    stopAdd: '新增色標',
    angle: '漸層角度',
    angleHint: '0°＝由左到右、90°＝由上到下、180°＝由右到左。',
    colorBlur: '顏色暈染',
    colorBlurHint: '在填滿下方加一層模糊的同色副本，讓漸層色往外暈開。',
    flow: '漸層流動',
    flowSpeed: '流動速度',
    flowSpeedUnit: '次／秒',
    flowDirection: '方向',
    flowDirections: { forward: '正向', reverse: '反向' },
    trackColor: '空條色',
    borderColor: '邊框色',
    borderWidth: '邊框粗細',
    shimmer: '白色流光',
    shimmerHint: '只有圓角長條：一道白色柔光跟著進度移動。',
    sectionPercent: '進度數字',
    percent: '顯示進度數字',
    percentX: '數字位置 X',
    percentY: '數字位置 Y',
    percentReset: '數字位置歸零',
    percentHint: '也可以在預覽上直接拖曳數字。',
    sectionTiming: '開場與結尾',
    fadeIn: '開場淡入',
    fadeInDuration: '淡入秒數',
    fadeInHint: '淡入期間畫面停在第 0 秒，淡入完才起跑。',
    previewFadeIn: '預覽開場',
    hold: '100% 停留時間',
    vanish: '結尾動作',
    vanishes: {
      none: '無',
      fade: '平順淡出',
      sparkle: '星光閃爍',
      noise: '雜訊條紋',
      shatter: '碎片飛散',
      dissolve: '方塊消融',
      pop: '彈一下後縮小',
      float: '往上飄走',
      close: '往中央收起',
      spin: '旋轉縮小',
      burst: '閃光爆開',
    } satisfies Record<VanishMode, string>,
    vanishHint: '結尾期間整個畫面（不透明時連背景）一起消失，最後一格全空。',
    vanishDuration: '結尾長度',
    intensity: '演出強度',
    intensityHint: '放大粒子數量、位移、旋轉圈數等幅度；平順淡出不受影響。',
    previewVanish: '預覽結尾',
  },

  loop: {
    sectionShape: '循環動畫',
    style: '組成圖形',
    styles: {
      dots: '圓點',
      bubbles: '泡泡',
      stars: '星星',
      petals: '花瓣',
      squares: '方塊',
      hearts: '愛心',
      ring: '圓弧',
    } satisfies Record<LoopStyle, string>,
    count: '元素數量',
    radius: '半徑',
    size: '圖形大小',
    speed: '旋轉速度',
    speedHint: '每秒轉幾圈。',
    direction: '旋轉方向',
    directions: { cw: '順時針', ccw: '逆時針' },
    trail: '殘影',
    pulse: '大小脈動',
    baseColor: '基本色',
    accentColor: '強調色',
    fit: '對齊整圈長度',
    fitHint: '把長度改成完整轉完的圈數，匯出時首尾無縫。',
  },

  row: {
    sectionStart: '起始',
    startMode: '起始內容',
    startModes: { shape: '底形', images: '圖片' },
    startImages: '起始圖片',
    targetImages: '目標圖片',
    dropLabel: '把圖片拖到這裡',
    dropButton: '選擇圖片',
    dropHint: 'PNG、JPG、WebP、AVIF、BMP，可多選；再選一次會整組換掉。',
    setInfo: (n: number) => `${n} 張 · 按檔名自然順序排列`,
    setEmpty: '還沒有圖片',
    startEmptyHint: '沒有圖片的格用底形。',
    targetEmptyHint: '沒有圖片時用填滿色的同形圖案代替。',
    removeAll: '移除全部',
    startOrder: '起始圖的分配',
    targetOrder: '目標圖的分配',
    orders: {
      sequential: '依序重複',
      alternating: '來回往返',
      random: '亂數',
    } satisfies Record<ImageOrder, string>,
    startFit: '起始圖的縮放',
    targetFit: '目標圖的縮放',
    fits: { contain: '完整顯示', cover: '填滿' },
    fitHint: '填滿時以該格的底形為外形裁切。',
    sectionTarget: '目標',
    sectionPlay: '變換方式',
    mode: '播放型態',
    modes: { progress: '進度型', loop: '循環型' },
    modeHint: '進度型換完後停住；循環型換完再依同樣的順序變回，可無縫循環。',
    pattern: '奇偶交錯',
    patterns: {
      'all-base': '全部從起始',
      'odd-base': '奇數格起始',
      'odd-image': '奇數格目標',
    } satisfies Record<RowPattern, string>,
    patternHint: '交錯時另一半的格從目標開始，輪到時換回起始。',
    order: '變換順序',
    changeOrders: {
      sequential: '從左到右',
      alternating: '兩端交替',
      random: '亂數',
    } satisfies Record<ImageOrder, string>,
    repeats: '隨機重複次數',
    repeatsHint: '整段時間平分成幾輪，每輪重新洗牌。',
    sectionLayout: '排列',
    count: '格數',
    length: '整列長度',
    size: '大小',
    sizeHint: '格子太多放不下時自動縮小。',
    sectionColor: '顏色與邊框',
    baseColor: '底形色',
    targetColor: '目標替代色',
    sectionShapes: '各位置的底形',
    shapesCount: (n: number) => `${n} 個位置`,
    shapesCountImages: (n: number) => `${n} 個位置（也是填滿圖片時的裁切形狀）`,
    shapeAt: (i: number) => `第 ${i} 格`,
    shapes: {
      circle: '圓',
      square: '方',
      diamond: '菱形',
      triangle: '三角',
      star: '星',
      heart: '愛心',
      hexagon: '六角形',
    } satisfies Record<RowShape, string>,
    applyAllShape: '要套用的底形',
    applyAll: '全部套用',
  },

  text: {
    sectionFont: '本機字型',
    fontUpload: '上傳字型檔',
    fontUploadHint: 'TTF、OTF、WOFF、WOFF2；上下兩段文字都會改用它。',
    fontApplied: (name: string) => `${name}（已套用）`,
    top: '上方文字',
    bottom: '下方文字',
    enabled: '顯示',
    text: '文字',
    font: '字型',
    x: '位置 X',
    y: '位置 Y',
    size: '大小',
    weight: '粗細',
    spacing: '字距',
    spacingHint: '一行太長（超過畫布寬的 92%）時整行水平壓縮。',
    rotation: '旋轉',
    color: '文字色',
    strokeColor: '外框色',
    strokeWidth: '外框粗細',
    previewText: '冒險準備中 Aa',
  },

  canvas: {
    sectionSize: '畫布尺寸',
    preset: '常用尺寸',
    presets: (w: number, h: number) =>
      `${w} × ${h}${w === h ? '（1:1）' : w * 9 === h * 16 ? '（16:9）' : ''}`,
    custom: '自訂',
    width: '寬',
    height: '高',
    sectionBackground: '背景',
    transparent: '透明背景',
    transparentHint: '預覽以棋盤格表示透明。',
    background: '背景色',
    backgroundHint: '只在不透明時用到；結尾動作會連背景一起消失。',
    sectionSnap: '拖曳對齊',
    snapCanvas: '吸附畫布',
    snapCanvasHint: '對齊畫布的左、中、右與上、中、下。',
    snapItems: '吸附其他元素',
    snapItemsHint: '對齊其他元素的邊與中心。',
  },

  preview: {
    stage: '預覽',
    size: (w: number, h: number) => `${w} × ${h}px`,
    framePng: '目前影格 PNG',
    editor: '預覽上的元素',
    elements: {
      character: '角色',
      loader: '讀取動畫',
      percent: '進度數字',
      top: '上方文字',
      bottom: '下方文字',
    },
  },

  export: {
    lengthLabels: {
      bar: '到達 100% 的時間',
      loop: '一輪的長度',
      rowLoop: '一輪的長度',
      rowProgress: '全部換完的時間',
      none: '整段長度',
    },
    lengthReadonly: (s: string) => `${s} 秒（＝最後節點的時間）`,
    breakdownBar: (fade: number, reach: number, hold: number, end: number, total: number) =>
      `${fade > 0 ? `淡入 ${n2(fade)} ＋ ` : ''}到達 100% ${n2(reach)} ＋ 停留 ${n2(hold)} ＋ 結尾 ${n2(end)} ＝ ${n2(total)} 秒`,
    breakdownLoop: (seconds: string, rotations: string, seamless: boolean) =>
      `總長 ${seconds} 秒 · 轉 ${rotations} 圈${seamless ? ' · 無縫' : ''}`,
    breakdownRow: (count: number, action: string, total: number) =>
      `${count} 格 · ${action} · 全長 ${n2(total)} 秒`,
    rowActions: {
      loop: (rounds: number) => `來回 ${rounds} 次 · 無縫`,
      random: (rounds: number) => `隨機 ${rounds} 輪後停在換好的狀態`,
      alternating: '交錯排列收尾',
      progress: '停在換好的狀態',
    },
    breakdownNone: (total: number) => `總長 ${n2(total)} 秒`,
    fpsHint: '每秒格數；GIF 每格至少 20 ms。',
    quality: 'WebP 品質',
    qualityHint: '1＝無損；越低檔案越小。',
    gifThreshold: 'GIF 透明判定',
    gifThresholdHint: '不透明度小於等於這個值的像素變成透明。',
    fileName: '檔名',
    fileNameHint: (stem: string) => `會存成「${stem}」＋副檔名。`,
    includeAssets: '專案檔含素材',
    includeAssetsHint: '存專案時一併存入上傳的角色圖、兩組換圖用的圖片與上傳字型。',
    loopHint: '「播放次數」三種格式一致。',
  },

  project: {
    resetTitle: '開新專案？',
    resetDescription:
      '所有設定回到預設，並拿掉上傳的角色圖、換圖用的圖片與上傳字型（可以用「復原」找回設定）。',
    resetLabel: '新專案…',
    resetConfirm: '開新專案',
    newer: '這個專案檔是較新版本的工具做的，無法開啟。',
    invalid: '專案檔的內容無法使用。',
    missingImage: '專案檔裡缺少用到的圖片。',
  },
  undo: '復原（Ctrl＋Z）',
  redo: '重做（Ctrl＋Shift＋Z）',
};
