/** 刮刮卡產生器的介面文字（繁中；用詞照 DESIGN.md 第 5 節） */
import type { BgFit, ContentKind, CoverShape, ImageStyle } from './model';

export const S = {
  /* 預設內容（自己寫的範例） */
  defaultCoverText: '刮刮看！',
  defaultSentences: [
    '大成功！幸運值 +10',
    '什麼都沒有……',
    '獲得：生鏽的鑰匙',
    'SAN 值檢定（0/1）',
    '再抽一次！',
  ],
  noResult: '沒有結果',
  noImages: '還沒有圖片。',

  /* 卡片（預覽與互動 HTML 共用） */
  cardLabel: '刮刮卡',
  coverLabel: '刮刮卡的塗層：用滑鼠或手指刮開',
  recover: '再蓋一次',
  revealNow: '直接刮開',

  /* 區塊 */
  sectionCard: '卡片',
  sectionDraw: '抽獎',
  sectionContent: '內容',
  sectionImages: '圖片',
  sectionCover: '塗層',
  sectionBackground: '背景與刮開區（進階）',
  sectionTitle: '標題（進階）',

  expert: '進階設定',
  expertHint:
    '打開後可以改底色、背景圖、刮開區、標題、句子顏色與塗層形狀；關閉時用簡單的樣子（整張都是刮開區、白底）。',
  width: '寬',
  height: '高',
  px: 'px',

  fixedSeed: '自己指定種子',
  fixedSeedHint: '打開時「抽新的一張」不換種子；同一個種子、同樣的設定一定抽出同一張。',
  seed: '種子',
  currentSeed: (n: number) => `目前的種子：${n}`,
  shuffleSeed: '換一個種子',

  kind: '內容種類',
  kinds: {
    icons: '隨機圖示',
    sentence: '隨機句子',
    'image-icon': '圖片（小圖）',
    'image-full': '圖片（蓋滿）',
  } satisfies Record<ContentKind, string>,
  kindHints: {
    icons: '從 8 個圖示裡抽，可以重複。',
    sentence: '從句子清單抽一句。',
    'image-icon': '從圖片清單抽，排成一排小圖，可以重複。',
    'image-full': '從圖片清單抽一張，蓋滿整個刮開區。',
  } satisfies Record<ContentKind, string>,
  count: '數量',
  countHint: '超過 5 個時圖示會變小。',
  sentences: '句子清單',
  sentencesHint: (n: number) => `一行一句，空白行不算。共 ${n} 句。`,
  sentenceSize: '句子字級',
  sentenceColor: '句子顏色',
  imageSize: '圖片大小',
  imageStyle: '圖片樣式',
  imageStyles: {
    rounded: '圓角方形（有陰影）',
    circle: '圓形（有陰影）',
    square: '方形',
    'circle-flat': '圓形',
    contain: '完整顯示',
  } satisfies Record<ImageStyle, string>,
  trim: '去掉透明留白',
  trimHint: '把每張圖四周透明的部分裁掉再排；網址的圖讀不到像素時照原圖。',

  imagesTitle: (n: number) => (n ? `圖片清單（共 ${n} 張）` : '圖片清單'),
  imagesEmpty: '還沒有圖片',
  imagesDrop: '把圖片拖到這裡',
  imagesChoose: '選擇圖片',
  imagesDropHint: '可以多選，最多 30 張。',
  imagesListLabel: '圖片清單',
  urlLabel: '圖片網址',
  urlPlaceholder: 'https://…',
  urlAdd: '加入',
  urlInvalid: '請輸入 http 或 https 開頭的圖片網址。',
  urlFull: '圖片已經有 30 張，先刪掉一些。',
  urlTag: '網址',
  removeImage: (name: string) => `刪除「${name}」`,

  coverText: '塗層文字',
  coverColor: '塗層顏色',
  brush: '筆刷大小',
  coverShape: '塗層形狀',
  coverShapes: {
    zone: '整個刮開區',
    circle: '每個各自一個圓',
    rect: '每個各自一個方形',
  } satisfies Record<CoverShape, string>,
  coverShapeHint: '「每個各自」只在內容是圖示或小圖片時作用。',

  bgColor: '底色',
  bgImage: '背景圖',
  bgDrop: '把背景圖拖到這裡',
  bgChange: '換一張背景圖',
  bgChoose: '選擇圖片',
  bgRemove: '拿掉圖片',
  bgMissing: '背景圖讀不到了（可能被瀏覽器清掉），請重新選一張。',
  bgFit: '背景圖填法',
  bgFits: { cover: '蓋滿', contain: '完整顯示' } satisfies Record<BgFit, string>,
  zone: '刮開區',
  zoneX: 'X',
  zoneY: 'Y',
  zoneW: '寬',
  zoneH: '高',
  zoneHint: '刮開區超出卡片的部分不算；整個在卡片外面時用整張卡。',

  titleText: '標題文字',
  titlePlaceholder: '例：酒館的抽獎券',
  titleHint: '標題放在刮開區裡、塗層底下：塗層蓋住整個刮開區時，要刮開才看得到。',
  titleColor: '標題顏色',
  titleSize: '標題字級',
  titlePos: '標題位置',

  /* 預覽 */
  previewLead: '用滑鼠或手指刮開塗層，看看抽到什麼。',
  drawCount: (n: number) => `這次開頁抽了 ${n} 張`,
  newTicket: '抽新的一張',
  revealed: '已經刮開了。',
  stageLabel: '刮刮卡預覽',
  exportHtml: '互動 HTML…',
  shareLink: '分享連結…',
  outputTitle: '輸出',
  outputHint: '輸出的是目前這一張（同樣的結果）。',
  shareUploaded: '上傳的圖片放不進連結：改用網址加入圖片，或用互動 HTML。',
  shareTooLong: '內容太長，放不進連結：請縮短文字或改用互動 HTML。',
  imagesLoading: '圖片讀取中…',
  imageMissing: (n: number) => `有 ${n} 張圖片讀不到了（可能被瀏覽器清掉），請刪掉後重新加入。`,

  /* 互動 HTML */
  html: {
    title: '互動 HTML',
    lead: '把目前這一張刮刮卡做成可以刮的網頁程式碼。',
    note: '貼進部落格或網站的 HTML 模式就能刮；網站會拿掉 <script> 時，下載獨立 HTML 放到網路空間，再用 iframe 嵌入。只會出現目前這一張的結果。',
    placeholders: '上傳的圖片改成待填的網址',
    placeholdersHint:
      '程式碼裡上傳的圖片（與裁過的圖、背景圖）換成「請換成第N張圖片的網址」：把圖片另外上傳到網站後，自己換成圖片的網址。網址加入的圖不必換。',
    code: '程式碼',
    size: (s: string) => `大小 ${s}`,
    copy: '複製程式碼',
    copied: '已複製 HTML 程式碼',
    download: '下載 HTML',
    open: '開新視窗試刮',
    generating: '產生中…',
    failed: '無法產生互動 HTML。',
    placeholderImage: (n: number) => `請換成第${n}張圖片的網址`,
    placeholderBg: '請換成背景圖片的網址',
    docTitle: '刮刮卡',
    commentStart: '刮刮卡產生器：互動 HTML 開始',
    commentEnd: '刮刮卡產生器：互動 HTML 結束',
  },

  /* 分享連結 */
  share: {
    title: '分享連結',
    lead: '開這個連結的人只會看到這張刮刮卡，可以直接刮開。',
    note: '結果就是目前這一張；連結裡含有結果，懂的人解得開，別拿來放重要的祕密。',
    link: '連結',
    copy: '複製連結',
    copied: '已複製分享連結',
    open: '開新視窗試刮',
    count: (n: number) => `${n} 字`,
  },

  /* 分享連結的畫面 */
  player: {
    lead: '用滑鼠或手指刮開塗層，看看抽到什麼。',
    make: '自己做一張刮刮卡',
    broken: '分享連結的內容讀不出來。',
    brokenHint: '連結可能不完整，已經打開編輯畫面。',
  },

  /* 通知 */
  popupBlocked: '瀏覽器擋下了新視窗',
  popupBlockedHint: '請允許這個網站開新視窗後再試一次。',
  imagesAdded: (n: number) => `已加入 ${n} 張圖片。`,
  notImage: (names: string) => `不是圖片：${names}。`,
  decodeError: (names: string) => `讀不了：${names}。`,
  imagesOver: (n: number) => `圖片最多 30 張，有 ${n} 張沒有加入。`,
  imageNotSaved: '瀏覽器空間不足或無法存檔，圖片這次可以用，但重新整理後就不見了。',
  bgSet: '已換上背景圖。',
  saveFailed: '自動儲存失敗（瀏覽器空間不足或被封鎖），重新整理後會回到上次存到的內容。',

  /* 專案檔 */
  openConfirmTitle: '開啟專案檔？',
  openConfirmDesc: '目前的刮刮卡會被取代（可以復原）。',
  openConfirmLabel: '開啟',
  projectOpened: '已開啟專案檔',
  projectBad: '專案檔的內容無法使用。',
  projectMissingImage: '專案檔缺少用到的圖片，沒有開啟。',
  legacyDone: '已讀入原作的設定檔。',
  legacyFailed: (n: number) => `有 ${n} 張圖片讀不了。`,
  legacyDropped: (n: number) => `圖片最多 30 張，有 ${n} 張沒有讀入。`,
  resetTitle: '重設刮刮卡？',
  resetDesc: '回到預設的設定，圖片清單會清空（可以復原）。',

  /* 快捷鍵、說明 */
  undo: '復原',
  redo: '重做',
  groupEdit: '編輯',
  groupCard: '刮刮卡',
  shortcutPaste: '貼上圖片（加進圖片清單）',
  usage: [
    '「內容」選要藏在塗層底下的東西：隨機圖示、隨機句子，或圖片（小圖排成一排，或一張蓋滿）。',
    '在右邊的卡片上用滑鼠或手指刮開塗層試試看；刮掉大部分時會自動清掉並噴出彩帶。',
    '「抽新的一張」換一個結果；要固定結果時打開「自己指定種子」，同一個種子一定是同一張。',
    '打開「進階設定」可以換底色、背景圖、調整刮開區、加標題，或讓塗層只蓋住每個結果。',
    '「互動 HTML…」把目前這一張做成可以刮的網頁程式碼（貼進部落格的 HTML 模式，或下載成網頁檔）；「分享連結…」複製一個連結，開連結的人只看到這張卡、可以直接刮。',
    '內容自動存在這個瀏覽器；要換電腦或備份時用「專案」存成專案檔。原作存的設定檔（.json）也可以用「開啟專案檔…」讀進來。',
  ],
};
